### ISSUE TITLE
register gives  "Unexpected error, "

### ISSUE THREAD

**Issue by wimkok** [stx-labs/stacks.js#100]
I am getting the following error:
$ blockstack register wimkok.id
Enter wallet password:
Unlocked wallet.
{
    "error": "Unexpected error, ",
    "help": "Try getting latest version of CLI with \"sudo pip install blockstack --upgrade\""
}

The upgrade gives only "Requirement already up-to-date:"
Killing the services is not helping.

There is money on my balance.

**Comment by jcnelson** [comment]
Hi @wimkok, we just merged 0.14.0 to master, and it fixes a lot of bugs like this.  If you want to try again, could you do so with `BLOCKSTACK_DEBUG=1 blockstack register wimkok.id` and paste the debug trace here?  Thanks!

**Comment by jcnelson** [comment]
Looks like this issue is dead.  Please re-open in the blockstack-core repo if the problem persists.  Thanks!
