### ISSUE TITLE
Accept pubkeyHash in makeUnsignedSTXTokenTransfer

### ISSUE THREAD

**Issue by rllola** [stx-labs/stacks.js#1003]
**Is your feature request related to a problem? Please describe.**
I am encountering the issue where I am trying to forge an unsigned transaction for which I don't know the public key.

**Describe the solution you'd like**
Let use the public key hash in `makeUnsignedSTXTokenTransfer` instead of a public key.

**Describe alternatives you've considered**
No alternative.

**Additional context**
We are trying to build a simple transfer tx for which we only have the addresses. As it is possible to revert an address to its public key hash it is not possible to unhash it to recover the public key. A shortcut would be neat.

**Comment by agraebe** [comment]
sounds like @rllola could help us out with a PR. thanks 🙏🏼

**Comment by rllola** [comment]
I have a question regarding the need of the pubkey encoding 
see https://github.com/blockstack/stacks.js/blob/master/packages/transactions/src/authorization.ts#L172

Is this required ?

If I am passing a hash I don't know if the pub key is compressed or not (which seems to be what is refered here looking at this part of the code https://github.com/blockstack/stacks.js/blob/master/packages/transactions/src/authorization.ts#L195)

If this is required then I don't think I am going to be able to complete this PR. A second opinion would be really much appreciated.

**Comment by agraebe** [comment]
@zone117x to provide input please :)

**Comment by zone117x** [comment]
The `keyEncoding` flag is required, see:
https://github.com/blockstack/stacks.js/blob/14e06827bdc0bf379a1553d22f2e4eb132e11641/packages/transactions/src/authorization.ts#L255
This is also described in the transaction encoding SIP here: https://github.com/stacksgov/sips/blob/main/sips/sip-005/sip-005-blocks-and-transactions.md#transaction-authorization

You may have to do something like require that the usage only supports one encoding mode.

**Comment by rllola** [comment]
I can't enforce that the hash has been done using only uncompressed or compressed key. I am afraid we are in front of a wall here.

**Comment by zone117x** [comment]
@rllola can you give some context on the goal of this PR? You could create a function that returns a non-standard serialized tx without the `keyEncoding` byte (for example setting it to zero). Then, you'd need to create the corresponding signing function that sets the correct `keyEncoding`.

**Comment by agraebe** [comment]
pinging @rllola to get input :)

**Comment by rllola** [comment]
Yeah the issue mentioned about compressed and uncompressed key makes it not possible to to support public key hash. I think this can be closed.
