### ISSUE TITLE
npm install @stacks/cli failing

### ISSUE THREAD

**Issue by pseudozach** [stx-labs/stacks.js#1006]
**Describe the bug**

stacks-cli install is failing because npm doesn't have the ^1.4 versions that seems to be required now.

> gitpod /workspace/clarity-js-sdk $ npm install @stacks/cli -g
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @stacks/stacking@^1.4.0-alpha.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@stacks/cli'
npm ERR! notarget

**Comment by SverreOye** [comment]
I had the same issue, but was able to work around it due to help from @psq on Discord. 

Same error as above when running `npm i -g @stacks/cli`.

Running `npm i -g @stacks/cli@1.3.5` installs successfully. The problem appears to be that @stacks/stacking version 1.4.0 does not exist or cannot be found.

**Comment by ttruga** [comment]
This also happens to me, using node 12
````
pcastro@DarkOveja ~ % npm i -g @stacks/cli@1.3.5
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 127
npm ERR! path /Users/pcastro/.nvm/versions/node/v12.19.0/lib/node_modules/@stacks/cli/node_modules/@stacks/blockchain-api-client
npm ERR! command failed
npm ERR! command sh -c npx shx find lib/index.js || npm run build
npm ERR! > @stacks/blockchain-api-client@0.34.2 build
npm ERR! > rimraf ./lib && npm run generate-openapi && npm run build:node && npm run build:browser
npm ERR! sh: shx: command not found
npm ERR! sh: rimraf: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pcastro/.npm/_logs/2021-04-19T22_03_19_271Z-debug.log
````

**Comment by theo-learner** [comment]
I found the same error. using node 14

`Error: Cannot find module '/home/bhlee/share/tutorial/manage_accounts/node_modules/@stacks/cli/lib/index.js'. Please verify that the package.json has a valid "main" entry`

**Comment by reedrosenbluth** [comment]
I believe I just fixed this! Please reopen if you are still experiencing this issue.
