### ISSUE TITLE
[New package suggestion] `@stacks/key-derivation`

### ISSUE THREAD

**Issue by kyranjamie** [stx-labs/stacks.js#1023]
In both wallets we use Argon2 to stretch passwords and use the resulting in the hash we use as the encryption key for software wallets. Currently this code is duplicated in each repo.

Any objections to creating a new package that houses this logic, or would this functionality not be considered directly related to stacks thus not to welcome in `stacks.js`?

**Comment by agraebe** [comment]
@zone117x @reedrosenbluth could you please provide input?

**Comment by zone117x** [comment]
Kinda seems like it doesn't belong in this repo, but I have no strong feelings either way.

**Comment by kyranjamie** [comment]
Happy not to proceed. If we want this package we can set up a UserX package elsewhere.
