### ISSUE TITLE
[BNS] Incorrect optional argument encoding.

### ISSUE THREAD

**Issue by Exulansis** [stx-labs/stacks.js#1026]
**Describe the bug**
The functions `buildTransferNameTx` and `buildRenewNameTx` incorrectly encode some of the contract call arguments. Optional arguments are either included or omitted (as can be seen [here](https://github.com/blockstack/stacks.js/blob/master/packages/bns/src/index.ts#L683)), which results in the created transactions being rejected (either not enough arguments, or a `TypeError` is thrown because the optional arguments are of the wrong type).

**What version of Blockstack.js are you using?**
2.0.0-beta.0

**To Reproduce**
Build a transaction by calling one of the aforementioned `buildTransferNameTx` or `buildRenewNameTx` functions (with or without passing the optional arguments), and broadcast the resulting transaction. This will result in an error.

**Additional context**
While debugging the issue, I've updated the relevant functions to encode the arguments correctly. The required changes can be seen in [this commit](https://github.com/Exulansis/stacks.js/commit/8a70ea8ac4c7b294a2f4220af12502743c1d3853). I have tested the fixes locally against a mocknet instance, and they seem to address the problem. I have not updated the tests.

**Comment by ahsan-javaid** [comment]
I have started working on this issue. Assigning it to myself.
