### ISSUE TITLE
[BNS] Missing STX burn / NFT spend post conditions.

### ISSUE THREAD

**Issue by Exulansis** [stx-labs/stacks.js#1027]
**Describe the bug**
When a user preorders a new BNS `namespace` or `name`, they must burn a specific amount of STX (depending on the `name` / `namespace` price). In order for the funds to be correctly spent, and the transaction to succeed, an [appropriate post-condition](https://github.com/stacksgov/sips/blob/main/sips/sip-005/sip-005-blocks-and-transactions.md#transaction-post-conditions) needs to be included in the transaction.

The post-condition needs to be created as part of the appropriate function call (i.e. [`buildNamespacePreorderTx`](https://github.com/blockstack/stacks.js/blob/master/packages/bns/src/index.ts#L288), [`buildNamePreorderTx`](https://github.com/blockstack/stacks.js/blob/7b6ceb33c835804822e19ad124e162d1b3cd3879/packages/bns/src/index.ts#L504)) and passed further to the [`makeBnsContractCall`](https://github.com/blockstack/stacks.js/blob/master/packages/bns/src/index.ts#L299), and eventually the [`makeUnsignedContractCall`](https://github.com/blockstack/stacks.js/blob/7b6ceb33c835804822e19ad124e162d1b3cd3879/packages/bns/src/index.ts#L85) functions.

**What version of Blockstack.js are you using?**
 2.0.0-beta.0

**To Reproduce**
Build a transaction by calling one of the aforementioned functions, and broadcast the resulting transaction. This will result in the transaction being aborted and reverted because of the (lack of) post-conditions.

**Additional context**

While debugging the issue, I've updated the relevant functions to encode the arguments correctly. The required changes can be seen [in this commit](https://github.com/Exulansis/stacks.js/commit/c7a2996c874d80a75de4bb0594d9edbc14914576). I have tested the fixes locally against a mocknet instance, and they seem to address the problem. I have not updated the tests.

It is important to point out that a **post-condition is required for transferring the name as well**. I have made an attempt to tackle this as well (as can be seen [here](https://github.com/Exulansis/stacks.js/commit/c7a2996c874d80a75de4bb0594d9edbc14914576#diff-be52d9579cd369a5e9dec98f1827bc27ac5899883cb293587e32dc0a4e5fa1c0R756)), **but the resulting transaction still fails, most likely because the post-conditions are incorrectly created (or not sufficient)**. (p.s. I have tried different configurations, with one, or two post-conditions, but with no luck)

I will continue digging on this topic a bit further, but in case anyone more familiar with post-conditions for non-fungible assets can point out my mistake, I'd be thankful!

**Comment by Exulansis** [comment]
I've since pushed an additional commit, which also addresses the post conditions needed during name transfer operations. I have tested the function against a mocknet instance, and it seems to address the issue. The required addition can be seen [here](https://github.com/Exulansis/stacks.js/blob/fix/arg-encoding/packages/bns/src/index.ts#L729).

**Comment by ahsan-javaid** [comment]
I have started working on this issue. Assigning it to myself.

**Comment by diwakergupta** [comment]
Closed by #1032
