### ISSUE TITLE
If 'data' is not in the DHT, CLI reports Unexpected Error

### ISSUE THREAD

**Issue by doodlemania2** [stx-labs/stacks.js#103]
{
   "error": "Unexpected error, 'data'",
   "help": "Try getting latest version of CLI with \"sudo pip install blockstack --upgrade\""
}

Reported when client is up to date, yet data has not yet made it to the DHT:
{
  "id": {
    "profile": {}, 
    "owner_address": "address", 
    "verifications": [], 
    "error": "Data not saved in DHT yet."
  }
}

cli should respond with error from resolver.

**Comment by muneeb-ali** [comment]
Thanks for reposting this! Yep, we need an error message for this.

**Comment by jcnelson** [comment]
DHT is now replaced with the Atlas network.
