### ISSUE TITLE
`broadcastRawTransaction` returns string error message on certain errors

### ISSUE THREAD

**Issue by aulneau** [stx-labs/stacks.js#1054]
I was trying to deploy a contract with an emoji in it, and saw that our extension was failing silently. We're using `broadcastRawTransaction` to send out our transactions, and in this case the response was a string value of `Failed to deserialize posted transaction: Invalid Stacks string: non-printable or non-ASCII string.`. Our code expected it to throw rather than return a string. For now I have https://github.com/blockstack/stacks-wallet-web/pull/1434 to address the issue, but the function should only return a string if it's a successful call.

**Comment by agraebe** [comment]
this seems to be fixed now. please reopen otherwise. thanks!
