### ISSUE TITLE
Improve multisig readme examples

### ISSUE THREAD

**Issue by reedrosenbluth** [stx-labs/stacks.js#1055]
- Make the multisig readme examples more clear.
- Make sure to point out that the order in which the TX is signed makes a difference.
- Mention that both private keys *and* public keys should be in the same format (compressed or uncompressed)

**Comment by Ramanand-Yadav** [comment]
hey can I contribute for this

**Comment by saralab** [comment]
Please feel to contribute and submit a PR

**Comment by scottsolowild** [comment]
Examples look [much better](https://github.com/hirosystems/stacks.js/tree/main/packages/transactions#supporting-multi-signature-transactions) now. Please reopen if you see ways to improve it.
