### ISSUE TITLE
[network] expose coreApiUrl

### ISSUE THREAD

**Issue by aulneau** [stx-labs/stacks.js#1065]
Hi there

I see that the `coreApiUrl` is no longer accessible on a given network instance, from this line https://github.com/blockstack/stacks.js/blob/master/packages/network/src/index.ts#L59

I don't see any alternative method to be able to read the api url for a given network instance. I think it's important to keep this functionality as many tools/clients rely on the ability to read what network url a StacksNetwork is using.

I think it's fine to make it so it's not set that way, but it is important to at least read it, maybe expose a `getCoreApiUrl` method on the class?

cc @reedrosenbluth @zone117x

**Comment by asimm241** [comment]
We are exposing `getCoreApiUrl` here https://github.com/blockstack/stacks.js/blob/f3cf94683b377619b9390fb400f445edf47f378a/packages/network/src/index.ts#L61
is that what you're talking about?

**Comment by zone117x** [comment]
The getter probably needs added to the `StacksNetwork` interface?
