### ISSUE TITLE
encrypted_master_private_key in Base58(Check) format

### ISSUE THREAD

**Issue by Gitju** [stx-labs/stacks.js#108]
Would be great if the `encrypted_master_private_key` in `wallet.json` could be in Base58 format. That makes manual backups easier to read if stored ofline.

**Comment by jcnelson** [comment]
In the mean time, here is a Python script that will decrypt the `wallet.json` file with your password.

```
#!/usr/bin/python

import blockstack_client
import sys
import json
from getpass import getpass

if len(sys.argv) != 2:
    print >> sys.stderr, "Usage: %s /path/to/wallet.json" % (sys.argv[0])
    sys.exit(1)

wallet_path = sys.argv[1]
password = getpass("Wallet password: ")

with open(wallet_path, "r") as f:
    wallet_data = f.read()

wallet_data = json.loads(wallet_data)

ret = blockstack_client.wallet.decrypt_wallet( wallet_data, password )
print json.dumps(ret, indent=4, sort_keys=True)

sys.exit(0)
```

**Comment by jcnelson** [comment]
In 0.14.0, we've added the `blockstack wallet` command that does exactly this--it prints out your keys in base58check format.  Please re-open this issue if you're still having trouble.  Thanks for reporting!
