### ISSUE TITLE
Domain names lost capacity to access remote json file from GAIA storage

### ISSUE THREAD

**Issue by paradigma-cl** [stx-labs/stacks.js#1086]
**Describe the bug**
In the legacy version for Storage (GAIA) it was possible to access a json file from a remote user using the username.  Now using domain names does not have the capacity to read the GAIA space.

**What version of Blockstack.js are you using?**
Latest
**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**

**To Reproduce**
1. Before in the legacy version
![imagen](https://user-images.githubusercontent.com/32182666/129808229-d7bca726-dd8b-476b-bf0a-a376afce90d6.png)
import { UserSession } from '@stacks/auth';
import { Storage } from '@stacks/storage'
….
this.state = {  userSession: new UserSession()}
….
const { userSession } = this.state
….
const storage = new Storage({ userSession });
const options = { username: userremote.id, decrypt: false, verify: false }
storage.getFile(file.json`, options)
          .then((fileContents) => {console.log(‘Good’)}
One specified the username in options and manage to get the file.

2. Now
![imagen](https://user-images.githubusercontent.com/32182666/129808476-cda1cf8f-bb00-4699-8893-f6a0115880b9.png)

import { UserSession } from '@stacks/auth';
import { Storage } from '@stacks/storage'
….
this.state = {  userSession: new UserSession()}
….
const { userSession } = this.state
….
const storage = new Storage({ userSession });
const options = { username: userremote.id.blockstack, decrypt: false, verify: false }
storage.getFile(file.json`, options)
          .catch((err) => {console.log(‘Bad)}

Using the new domain name the he username specified in options is not anymore in the zone file, goes as an error through the catch.
Now the name instead of username is located in a different place, retrievable by the stacks address associate to the name, so the storage cannot get the file.

**Expected behavior**
The storage should be able to get a file from a remote user.

**Comment by agraebe** [comment]
@ahsan-javaid could you take a look? thanks!

**Comment by ahsan-javaid** [comment]
Adding a working example here:
```
  import { UserSession, AppConfig } from '@stacks/auth';
  import { Storage } from '@stacks/storage';

  const appConfig = new AppConfig();
  const userSession = new UserSession({ appConfig });
  const storage = new Storage({ userSession });
  const options = {
    username: 'yukan.id',
    app: 'http://localhost:8080',
    decrypt: false,
  };
  const fileContent = await storage.getFile('test.json', options);
  console.log(fileContent);

```
The only difference is `app` parameter in the options which is missing in the snippet provided in the issue #1086. For example in the above code if you omit the app property then it will throw the same error `missing read url` similar to your case. 

#### Purpose of app parameter in the options ?
The app property specifies from which bucket address we are reading the file. 
1. When you call the `getFile` function with username first it will fetch the user profile
2. Attached below is the profile retrived in case of `jfontirroig.id.blockstack` as mentioned in the issue above
```
{
  '@type': 'Person',
  '@context': 'http://schema.org',
  apps: {
    'http://localhost:3000': 'https://gaia.blockstack.org/hub/15q7x8bRkhknKgunWBULBRLkbKGEQ12KSb/',
    'https://crosscheck.paradigma.global': 'https://gaia.blockstack.org/hub/15hBuet4cgSxP8kVtAqcFE8D4JQBh5HZpj/',
    'https://dappcrosscheck.paradigma.global': 'https://gaia.blockstack.org/hub/1DZ1fN2aJJ6PZuRzKYGRAXFM91vuK2L1pk/',
    'https://dapp.cryptocracy.io': 'https://gaia.blockstack.org/hub/1Gb3nx3VdT1LKCnvhfKdJKMBnNG46mygVT/',
    'http://localhost:8080': 'https://gaia.blockstack.org/hub/15xAmKUi5JqLeXkvHigH1pimeyF3GpEHdt/',
    'https://cheery.red': 'https://gaia.blockstack.org/hub/1Dyog8E9XRbmTBPx7LHgBao9eewbntAjFq/',
    'https://blackhole.run': 'https://gaia.blockstack.org/hub/1BC7wKYvytRsunQYLhsBx9Fn4VbStDBmTi/',
    'https://app-center.openintents.org': 'https://gaia.blockstack.org/hub/1Lrb9H2qypVrhzwC6VL6a8sRMjoDf2URZR/',
    'https://testnet-demo.blockstack.org': 'https://gaia.blockstack.org/hub/14RCJdNTpsUWqzLZXommHTDazG4HVoWruw/',
    'https://todos.blockstack.org': 'https://gaia.blockstack.org/hub/1DUtAds5eHVt5Mzn37re8khDMNf9doax9Z/',
    'https://explorer.stacks.co': 'https://gaia.blockstack.org/hub/1M3STGKQZTJWboLBrhQ2txDuQaQX9PCBqz/',
    'https://speed-spend.netlify.app': 'https://gaia.blockstack.org/hub/1JcEjdkiC5KJGS1A7JbrPZHWmXDatnc7Tz/',
    'https://xck.app': 'https://gaia.blockstack.org/hub/1KiLTFXph39g1TGBQNizCuSpVRMQ2KTjoR/'
  },
  api: {
    gaiaHubConfig: { url_prefix: 'https://gaia.blockstack.org/hub/' },
    gaiaHubUrl: 'https://hub.blockstack.org'
  },
  name: 'Josep Fontirroig',
  description: 'Ingeniero Informática',
  account: [
    {
      '@type': 'Account',
      placeholder: false,
      service: 'bitcoin',
      identifier: '19SHKGESMJipQGCrsidnfEHai66XQKnfVJ',
      proofType: 'http',
      proofUrl: ''
    },
    {
      '@type': 'Account',
      placeholder: false,
      service: 'facebook',
      identifier: 'jfontirroig',
      proofType: 'http',
      proofUrl: ''
    }
  ],
  appsMeta: {
    'https://testnet-demo.blockstack.org': {
      storage: 'https://gaia.blockstack.org/hub/14RCJdNTpsUWqzLZXommHTDazG4HVoWruw/',
      publicKey: '024d65108e72bbb2bc8940bfe6f58198bd38361a154911be648c57fbe8012ec3dc'
    },
    'https://todos.blockstack.org': {
      storage: 'https://gaia.blockstack.org/hub/1DUtAds5eHVt5Mzn37re8khDMNf9doax9Z/',
      publicKey: '0303d7576bccb8efafc9a57d71962a9bf7bba7077a8c554c9f73c9db8e57043853'
    },
    'http://localhost:3000': {
      storage: 'https://gaia.blockstack.org/hub/15q7x8bRkhknKgunWBULBRLkbKGEQ12KSb/',
      publicKey: '03e55447ad6c73d8bac0a373c1fdbc0d781ef3f8b315bfa090775a00343ebe2e13'
    },
    'https://crosscheck.paradigma.global': {
      storage: 'https://gaia.blockstack.org/hub/15hBuet4cgSxP8kVtAqcFE8D4JQBh5HZpj/',
      publicKey: '0272c6208c28519c27896f5bef2adb51d7bdd21725fabcc77b857187b49e2d05be'
    },
    'https://explorer.stacks.co': {
      storage: 'https://gaia.blockstack.org/hub/1M3STGKQZTJWboLBrhQ2txDuQaQX9PCBqz/',
      publicKey: '0344e985dafc364f1e0f23e73661ca59bba54c5aabd41f8f5933ee6f40488d3b06'
    },
    'https://speed-spend.netlify.app': {
      storage: 'https://gaia.blockstack.org/hub/1JcEjdkiC5KJGS1A7JbrPZHWmXDatnc7Tz/',
      publicKey: '02bfd2c50c172dfeb025f51c87bad28fac5df538d6260e270de714898e5d6c6ca4'
    },
    'https://xck.app': {
      storage: 'https://gaia.blockstack.org/hub/1KiLTFXph39g1TGBQNizCuSpVRMQ2KTjoR/',
      publicKey: '037402f55c3a0dc0f4793c8d541c405210dafb3cd9aa0a766ab17fb509f1228a71'
    }
  }
}
```
In the above profile json the `apps` section defines the bucket urls against each app for which we can retrieve a file. 
https://github.com/blockstack/stacks.js/blob/4a7258d5d56fbe886d90fce928e125b8b87200d7/packages/storage/src/storage.ts#L204
Below is the copy of above function that detects the bucket address.

```
 async getUserAppFileUrl(
    path: string,
    username: string,
    appOrigin: string,
    zoneFileLookupURL?: string
  ): Promise<string | undefined> {
    const profile = await lookupProfile({ username, zoneFileLookupURL });
    let bucketUrl: string | undefined;
    if (profile.hasOwnProperty('apps')) {
      if (profile.apps.hasOwnProperty(appOrigin)) {
        const url = profile.apps[appOrigin];
        const bucket = url.replace(/\/?(\?|#|$)/, '/$1');
        bucketUrl = `${bucket}${path}`;
      }
    }
    return bucketUrl;
  }
```

So if you omit the `app` property then bucketUrl will be undefined which is currently happing in this issue and `getFile` function will throw `missing read url` error.

To make `getFile` function work without `app` parameter option we may have to introduce a way to detect the bucket address.

cc: @zone117x @reedrosenbluth @kyranjamie  if you have any thoughts around this possibility.

**Comment by paradigma-cl** [comment]
> 
> 
> Adding a working example here:
> 
> ```
>   import { UserSession, AppConfig } from '@stacks/auth';
>   import { Storage } from '@stacks/storage';
> 
>   const appConfig = new AppConfig();
>   const userSession = new UserSession({ appConfig });
>   const storage = new Storage({ userSession });
>   const options = {
>     username: 'yukan.id',
>     app: 'http://localhost:8080',
>     decrypt: false,
>   };
>   const fileContent = await storage.getFile('test.json', options);
>   console.log(fileContent);
> ```
> 
> The only difference is `app` parameter in the options which is missing in the snippet provided in the issue #1086. For example in the above code if you omit the app property then it will throw the same error `missing read url` similar to your case.
> #### Purpose of app parameter in the options ?
> 
> The app property specifies from which bucket address we are reading the file.
> 
>     1. When you call the `getFile` function with username first it will fetch the user profile
> 
>     2. Attached below is the profile retrived in case of `jfontirroig.id.blockstack` as mentioned in the issue above
> 
> 
> ```
> {
>   '@type': 'Person',
>   '@context': 'http://schema.org',
>   apps: {
>     'http://localhost:3000': 'https://gaia.blockstack.org/hub/15q7x8bRkhknKgunWBULBRLkbKGEQ12KSb/',
>     'https://crosscheck.paradigma.global': 'https://gaia.blockstack.org/hub/15hBuet4cgSxP8kVtAqcFE8D4JQBh5HZpj/',
>     'https://dappcrosscheck.paradigma.global': 'https://gaia.blockstack.org/hub/1DZ1fN2aJJ6PZuRzKYGRAXFM91vuK2L1pk/',
>     'https://dapp.cryptocracy.io': 'https://gaia.blockstack.org/hub/1Gb3nx3VdT1LKCnvhfKdJKMBnNG46mygVT/',
>     'http://localhost:8080': 'https://gaia.blockstack.org/hub/15xAmKUi5JqLeXkvHigH1pimeyF3GpEHdt/',
>     'https://cheery.red': 'https://gaia.blockstack.org/hub/1Dyog8E9XRbmTBPx7LHgBao9eewbntAjFq/',
>     'https://blackhole.run': 'https://gaia.blockstack.org/hub/1BC7wKYvytRsunQYLhsBx9Fn4VbStDBmTi/',
>     'https://app-center.openintents.org': 'https://gaia.blockstack.org/hub/1Lrb9H2qypVrhzwC6VL6a8sRMjoDf2URZR/',
>     'https://testnet-demo.blockstack.org': 'https://gaia.blockstack.org/hub/14RCJdNTpsUWqzLZXommHTDazG4HVoWruw/',
>     'https://todos.blockstack.org': 'https://gaia.blockstack.org/hub/1DUtAds5eHVt5Mzn37re8khDMNf9doax9Z/',
>     'https://explorer.stacks.co': 'https://gaia.blockstack.org/hub/1M3STGKQZTJWboLBrhQ2txDuQaQX9PCBqz/',
>     'https://speed-spend.netlify.app': 'https://gaia.blockstack.org/hub/1JcEjdkiC5KJGS1A7JbrPZHWmXDatnc7Tz/',
>     'https://xck.app': 'https://gaia.blockstack.org/hub/1KiLTFXph39g1TGBQNizCuSpVRMQ2KTjoR/'
>   },
>   api: {
>     gaiaHubConfig: { url_prefix: 'https://gaia.blockstack.org/hub/' },
>     gaiaHubUrl: 'https://hub.blockstack.org'
>   },
>   name: 'Josep Fontirroig',
>   description: 'Ingeniero Informática',
>   account: [
>     {
>       '@type': 'Account',
>       placeholder: false,
>       service: 'bitcoin',
>       identifier: '19SHKGESMJipQGCrsidnfEHai66XQKnfVJ',
>       proofType: 'http',
>       proofUrl: ''
>     },
>     {
>       '@type': 'Account',
>       placeholder: false,
>       service: 'facebook',
>       identifier: 'jfontirroig',
>       proofType: 'http',
>       proofUrl: ''
>     }
>   ],
>   appsMeta: {
>     'https://testnet-demo.blockstack.org': {
>       storage: 'https://gaia.blockstack.org/hub/14RCJdNTpsUWqzLZXommHTDazG4HVoWruw/',
>       publicKey: '024d65108e72bbb2bc8940bfe6f58198bd38361a154911be648c57fbe8012ec3dc'
>     },
>     'https://todos.blockstack.org': {
>       storage: 'https://gaia.blockstack.org/hub/1DUtAds5eHVt5Mzn37re8khDMNf9doax9Z/',
>       publicKey: '0303d7576bccb8efafc9a57d71962a9bf7bba7077a8c554c9f73c9db8e57043853'
>     },
>     'http://localhost:3000': {
>       storage: 'https://gaia.blockstack.org/hub/15q7x8bRkhknKgunWBULBRLkbKGEQ12KSb/',
>       publicKey: '03e55447ad6c73d8bac0a373c1fdbc0d781ef3f8b315bfa090775a00343ebe2e13'
>     },
>     'https://crosscheck.paradigma.global': {
>       storage: 'https://gaia.blockstack.org/hub/15hBuet4cgSxP8kVtAqcFE8D4JQBh5HZpj/',
>       publicKey: '0272c6208c28519c27896f5bef2adb51d7bdd21725fabcc77b857187b49e2d05be'
>     },
>     'https://explorer.stacks.co': {
>       storage: 'https://gaia.blockstack.org/hub/1M3STGKQZTJWboLBrhQ2txDuQaQX9PCBqz/',
>       publicKey: '0344e985dafc364f1e0f23e73661ca59bba54c5aabd41f8f5933ee6f40488d3b06'
>     },
>     'https://speed-spend.netlify.app': {
>       storage: 'https://gaia.blockstack.org/hub/1JcEjdkiC5KJGS1A7JbrPZHWmXDatnc7Tz/',
>       publicKey: '02bfd2c50c172dfeb025f51c87bad28fac5df538d6260e270de714898e5d6c6ca4'
>     },
>     'https://xck.app': {
>       storage: 'https://gaia.blockstack.org/hub/1KiLTFXph39g1TGBQNizCuSpVRMQ2KTjoR/',
>       publicKey: '037402f55c3a0dc0f4793c8d541c405210dafb3cd9aa0a766ab17fb509f1228a71'
>     }
>   }
> }
> ```
> 
> In the above profile json the `apps` section defines the bucket urls against each app for which we can retrieve a file.
> 
> https://github.com/blockstack/stacks.js/blob/4a7258d5d56fbe886d90fce928e125b8b87200d7/packages/storage/src/storage.ts#L204
> 
> Below is the copy of above function that detects the bucket address.
> 
> ```
>  async getUserAppFileUrl(
>     path: string,
>     username: string,
>     appOrigin: string,
>     zoneFileLookupURL?: string
>   ): Promise<string | undefined> {
>     const profile = await lookupProfile({ username, zoneFileLookupURL });
>     let bucketUrl: string | undefined;
>     if (profile.hasOwnProperty('apps')) {
>       if (profile.apps.hasOwnProperty(appOrigin)) {
>         const url = profile.apps[appOrigin];
>         const bucket = url.replace(/\/?(\?|#|$)/, '/$1');
>         bucketUrl = `${bucket}${path}`;
>       }
>     }
>     return bucketUrl;
>   }
> ```
> 
> So if you omit the `app` property then bucketUrl will be undefined which is currently happing in this issue and `getFile` function will throw `missing read url` error.
> 
> To make `getFile` function work without `app` parameter option we may have to introduce a way to detect the bucket address.
> 
> cc: @zone117x @reedrosenbluth @kyranjamie if you have any thoughts around this possibility.

Thank you for the analysis.  The username here in the example is using the legacy names.  Now the names si stored in a different field called name, not username.  So from the GAIA a name like xck.app using the new naming system cannot be retrieved.

**Comment by paradigma-cl** [comment]
I wonder if this issue is being considered to be fixed.  
Essentially, we can only detect the bucket address when using the old domain name structure passed as a username.  
Using the new domain name with the parameter username (as name) does not detect the bucket.

**Comment by ahsan-javaid** [comment]
@zone117x @reedrosenbluth Any thoughts on how we can leverage the domain names that **paradigma-cl** is pointing out.

**Comment by paradigma-cl** [comment]
We have been analyzing how to solve the issue.  The way we understand BNS and GAIA, each domain name or namespace, or subdomain should have an associated field name or username since all of them can be used as a personal ID.  Also, there is a GAIA storage associated with it.  The domain name is the only one that has a list of subdomain names that are registered in the profile file. 
Just thinking aloud.
The legacy domain name (BNS) when it was in operation was registering the username in a field called username.  The actual domain name (BNS) is leaving the username blank, but probably neither registering in the field called name.  So depending on if we want to maintain the *.id.blockstack names we should have a kind of compatibility to see both.  Or if this one is deprecated, and the new BNS is the only one used, then it should be assured that each domain name, namespace, or subdomain is registered in this field name or username when created, and be capable to retrieve the storage bucket associated to it.
@ahsan-javaid @zone117x @reedrosenbluth

**Comment by ahsan-javaid** [comment]
Digging further into the issue and tryiing to find the actual fix. 
Fetch file steps docs: https://docs.stacks.co/build-apps/references/gaia#user-control-or-how-is-gaia-decentralized
When an application fetches a file data.txt for a given user alice.id, the lookup will follow these steps:
1. Fetch the zonefile for alice.id.
2. Read her profile URL from her zonefile.
3. Fetch Alice's profile.
4. Verify that the profile is signed by alice.id's key
5. Find the read-only url out of the profile's appsMeta section (e.g. https://example-app.gaia.alice.org).
6. Fetch the file from https://example-app.gaia.alice.org/data.txt

Mapping above steps to this issue.
username: jfontirroig.id.blockstack
1. Fetch the zone file for jfontirroig.id.blockstack (Worked)
2. Read profile url which is: https://gaia.blockstack.org/hub/1Gio2MiaN5ZPDnLMePhBRiWjAFrsRe5Qz9/profile.json (Worked)
3. Fetch profile (Worked)
4. Verify profile (skipped because verify: false)
5. Find read only url from appsMeta:
   See entry for https://xck.app in profile json from above url
6. Fetch file: https://gaia.blockstack.org/hub/1KiLTFXph39g1TGBQNizCuSpVRMQ2KTjoR/file.json
Code snippet:

```
import { UserSession, AppConfig } from '@stacks/auth';
import { Storage } from '@stacks/storage';

void(async () => {
  const appConfig = new AppConfig();
  const userSession = new UserSession({ appConfig });
  const storage = new Storage({ userSession });
  const options = {
    username: 'jfontirroig.id.blockstack',
    app: 'https://xck.app',
    decrypt: false,
    verify: false,
  };
  const fileContent = await storage.getFile('file.json', options);
  console.log(fileContent);
})();


```


Considering the above snippet i guess you are missing the app property in options which is required to retrieve the hub address. Try adding the valid `app` url in options should resolve this issue. It would be great if you can try it out and let me know if it works.

**Comment by paradigma-cl** [comment]
> 
> 
> Digging further into the issue and tryiing to find the actual fix.
> Fetch file steps docs: https://docs.stacks.co/build-apps/references/gaia#user-control-or-how-is-gaia-decentralized
> When an application fetches a file data.txt for a given user alice.id, the lookup will follow these steps:
> 
>     1. Fetch the zonefile for alice.id.
> 
>     2. Read her profile URL from her zonefile.
> 
>     3. Fetch Alice's profile.
> 
>     4. Verify that the profile is signed by alice.id's key
> 
>     5. Find the read-only url out of the profile's appsMeta section (e.g. https://example-app.gaia.alice.org).
> 
>     6. Fetch the file from https://example-app.gaia.alice.org/data.txt
> 
> 
> Mapping above steps to this issue.
> username: jfontirroig.id.blockstack
> 
>     1. Fetch the zone file for jfontirroig.id.blockstack (Worked)
> 
>     2. Read profile url which is: https://gaia.blockstack.org/hub/1Gio2MiaN5ZPDnLMePhBRiWjAFrsRe5Qz9/profile.json (Worked)
> 
>     3. Fetch profile (Worked)
> 
>     4. Verify profile (skipped because verify: false)
> 
>     5. Find read only url from appsMeta:
>        See entry for https://xck.app in profile json from above url
> 
>     6. Fetch file: https://gaia.blockstack.org/hub/1KiLTFXph39g1TGBQNizCuSpVRMQ2KTjoR/file.json
>        Code snippet:
> 
> 
> ```
> import { UserSession, AppConfig } from '@stacks/auth';
> import { Storage } from '@stacks/storage';
> 
> void(async () => {
>   const appConfig = new AppConfig();
>   const userSession = new UserSession({ appConfig });
>   const storage = new Storage({ userSession });
>   const options = {
>     username: 'jfontirroig.id.blockstack',
>     app: 'https://xck.app',
>     decrypt: false,
>     verify: false,
>   };
>   const fileContent = await storage.getFile('file.json', options);
>   console.log(fileContent);
> })();
> ```
> 
> Considering the above snippet i guess you are missing the app property in options which is required to retrieve the hub address. Try adding the valid `app` url in options should resolve this issue. It would be great if you can try it out and let me know if it works.

Thanks for following up the issue!  
Yes, it works for the user jfontirroig.id.blockstack as this subdomain name was created with the legacy BNS.  But if you use for ie the subdomain name: phillip.xck.app returns blank.

**Comment by paradigma-cl** [comment]
or the domain name xck.app

**Comment by paradigma-cl** [comment]
ahsan-javaid It does not work with the "new" BNS domains.

**Comment by ahsan-javaid** [comment]
Further looking into the issue using new domain name: `xck.app` as you provided.
Steps to getFile:
1. Fetch zonefile for `xck.app` 
URL: https://stacks-node-api.mainnet.stacks.co/v1/names/xck.app 
Response: Hit above url and it will gives zonefile for `xck.app`
2. Fetch profile 
URL: https://gaia.blockstack.org/hub/1NN4cyTXbZKM1cD3xD3w3gn2CAANvsx1r5/profile.json
Response: Hit above url and it returns the profile for `xck.app`
3. Get file bucket address from appsMeta of profile section of the above url
Response: https://gaia.blockstack.org/hub/1CGruqXaZhXhk9ANmmAd3ys3s5ySJUFpzo/
4. Get file: 
Will return file url: https://gaia.blockstack.org/hub/1CGruqXaZhXhk9ANmmAd3ys3s5ySJUFpzo/filename.txt

```
import { UserSession, AppConfig } from '@stacks/auth';
import { Storage } from '@stacks/storage';

void(async () => {
  const appConfig = new AppConfig();
  const userSession = new UserSession({ appConfig });
  const storage = new Storage({ userSession });
  const options = {
    username: 'xck.app',
    app: 'https://xck.app',
    decrypt: false,
    verify: false,
  };
  const fileContent = await storage.getFile('file.json', options);
  console.log(fileContent);
})();

```


**paradigma-cl** these steps does not produce the issue that you are referring using new domain name that you provided. It will be great if you can provide the exact `code-snippet` with correct values to reproduce the issue that will be great.

**Comment by zone117x** [comment]
@paradigma-cl any updates?

**Comment by paradigma-cl** [comment]
> 
> 
> Further looking into the issue using new domain name: `xck.app` as you provided.
> Steps to getFile:
> 
>     1. Fetch zonefile for `xck.app`
>        URL: https://stacks-node-api.mainnet.stacks.co/v1/names/xck.app
>        Response: Hit above url and it will gives zonefile for `xck.app`
> 
>     2. Fetch profile
>        URL: https://gaia.blockstack.org/hub/1NN4cyTXbZKM1cD3xD3w3gn2CAANvsx1r5/profile.json
>        Response: Hit above url and it returns the profile for `xck.app`
> 
>     3. Get file bucket address from appsMeta of profile section of the above url
>        Response: https://gaia.blockstack.org/hub/1CGruqXaZhXhk9ANmmAd3ys3s5ySJUFpzo/
> 
>     4. Get file:
>        Will return file url: https://gaia.blockstack.org/hub/1CGruqXaZhXhk9ANmmAd3ys3s5ySJUFpzo/filename.txt
> 
> 
> ```
> import { UserSession, AppConfig } from '@stacks/auth';
> import { Storage } from '@stacks/storage';
> 
> void(async () => {
>   const appConfig = new AppConfig();
>   const userSession = new UserSession({ appConfig });
>   const storage = new Storage({ userSession });
>   const options = {
>     username: 'xck.app',
>     app: 'https://xck.app',
>     decrypt: false,
>     verify: false,
>   };
>   const fileContent = await storage.getFile('file.json', options);
>   console.log(fileContent);
> })();
> ```
> 
> **paradigma-cl** these steps does not produce the issue that you are referring using new domain name that you provided. It will be great if you can provide the exact `code-snippet` with correct values to reproduce the issue that will be great.

The API steps to get the files work correctly.
The code snipet does not work well as it says that name does not exist.  We have detected that the Library code is pointing to the old Blockstack Name API and not the Stacks Name API.  So that is why is not getting the name.

We are digging a bit more in the library code to try to offer a way to try to solve the issue.

**Comment by paradigma-cl** [comment]
Using the following code snippet:

void(async () => {
  const appConfig = new AppConfig();
  const userSession = new UserSession({ appConfig });
  const storage = new Storage({ userSession });
  const options = {
    username: 'jfontirroig.xck.app',
    app: 'https://xck.app',
    decrypt: false,
    verify: false,
  };
  const fileContent = await storage.getFile('contractlist.json', options);
  console.log(fileContent);
})();


The console give us:

catch. Error: Name not found
    getNameInfo index.esm.js:67 

So we went to see getNameInfo at index.esm.js at the stacks@storage  library and it has the following code:

**this.bnsLookupUrl = 'https://core.blockstack.org'**;
_proto.getNameInfo = function getNameInfo(fullyQualifiedName) {
    var nameLookupURL = this.bnsLookupUrl + "/v1/names/" + fullyQualifiedName;
    return fetchPrivate(nameLookupURL).then(function (resp) {
      if (resp.status === 404) {
        throw new Error('Name not found');
      } else if (resp.status !== 200) {
        throw new Error("Bad response status: " + resp.status);
      } else {
        return resp.json();
      }
    }).then(function (nameInfo) {
      if (nameInfo.address) {
        return Object.assign({}, nameInfo, {
          address: nameInfo.address
        });
      } else {
        return nameInfo;
      }
    });
  };

 Obviously, the name won't be found as the **this.bnsLookupUrl = 'https://core.blockstack.org'** does not have that information anymore.   We tried to discover how to fix it in the library, but appeared deeper issues not so easy solve in short period of time. :-(

**Comment by ahsan-javaid** [comment]
@paradigma-cl 
As you know we discussed this issue in detail and i created the [pull request](https://github.com/blockstack/stacks.js/pull/1106) that fixes the issue as well. But after careful review with `splat` team we concluded that it's a user specific issue. 

The reason behind this is if you see the zonefile field at:
https://stacks-node-api.mainnet.stacks.co/v1/names/jfontirroig.xck.app

```
{
  "address": "SP31C1RGYVJVWNYWJNRVSZQA2XN9HDEA08FB0G03S",
  "blockchain": "stacks",
  "last_txid": "0x0b80143fae8a52f47c970c5cf935ae37cd13236887e2a470d8a6891091219986",
  "resolver": "",
  "status": "registered_subdomain",
  "zonefile": "https://gaia.blockstack.org/hub/1BhQxPY3N9ABXzkbr4U8J6gkvAdr9Acr8L/profile.json",
  "zonefile_hash": "fdccd9ca23ec81f8d5ef0057eb2f72fb"
}

```
The zonefile field in above json is not valid and its user's responsibility to specify a valid zonefile while registering the names. 
You may check the valid zonefile example here: https://stacks-node-api.mainnet.stacks.co/v1/names/yukan.id
Every domain or subdomain should follow a valid zonefile pattern. 

**But in case of `jfontirroig.xck.app` the zonfile field is only a profile url which is the root cause of this issue.** 

The reason for not merging the pr is we will end up adding user specific checks if we go in this direction. So because its a user specific issue i will suggest you to update the zonefile field with valid zonefile contents to resolve this specific issue. 
So closing the [PR](https://github.com/blockstack/stacks.js/pull/1106) by considering its not a stacks.js responsibility to manage zonefiles after discussion with `splat` team.

**Comment by paradigma-cl** [comment]
> 
> 
> @paradigma-cl As you know we discussed this issue in detail and i created the [pull request](https://github.com/blockstack/stacks.js/pull/1106) that fixes the issue as well. But after careful review with `splat` team we concluded that it's a user specific issue.
> 
> The reason behind this is if you see the zonefile field at: https://stacks-node-api.mainnet.stacks.co/v1/names/jfontirroig.xck.app
> 
> ```
> {
>   "address": "SP31C1RGYVJVWNYWJNRVSZQA2XN9HDEA08FB0G03S",
>   "blockchain": "stacks",
>   "last_txid": "0x0b80143fae8a52f47c970c5cf935ae37cd13236887e2a470d8a6891091219986",
>   "resolver": "",
>   "status": "registered_subdomain",
>   "zonefile": "https://gaia.blockstack.org/hub/1BhQxPY3N9ABXzkbr4U8J6gkvAdr9Acr8L/profile.json",
>   "zonefile_hash": "fdccd9ca23ec81f8d5ef0057eb2f72fb"
> }
> ```
> 
> The zonefile field in above json is not valid and its user's responsibility to specify a valid zonefile while registering the names. You may check the valid zonefile example here: https://stacks-node-api.mainnet.stacks.co/v1/names/yukan.id Every domain or subdomain should follow a valid zonefile pattern.
> 
> **But in case of `jfontirroig.xck.app` the zonfile field is only a profile url which is the root cause of this issue.**
> 
> The reason for not merging the pr is we will end up adding user specific checks if we go in this direction. So because its a user specific issue i will suggest you to update the zonefile field with valid zonefile contents to resolve this specific issue. So closing the [PR](https://github.com/blockstack/stacks.js/pull/1106) by considering its not a stacks.js responsibility to manage zonefiles after discussion with `splat` team.

@ahsan-javaid Thank you very much all for detecting the zone file issue.  We corrected it, but the issue is still there.

**Comment by ahsan-javaid** [comment]
@paradigma-cl 
The zone file for `jfontirroig.xck.app` is still not correct. Use below `script` to see the issues in zonefile.

```
// Steps to execute this file
// npm i axios
// npm i zone-file
// node below-file.js



const axios = require('axios');
const zonefile = require('zone-file');

const username = 'jfontirroig.xck.app';

void(async () => {
    const nameInfo = await axios.get(`https://stacks-node-api.mainnet.stacks.co/v1/names/${username}`)
    
    console.log('zone file content: ', nameInfo.data.zonefile)
    
    const zoneFileJson = zonefile.parseZoneFile(nameInfo.data.zonefile)

    console.log('parsed zone file', zoneFileJson);
})()

```

Above is simple js file you may execute to see the parsed zonefile. The parsed result does not contains profile url. Now replace the username variable  in the above `script` with value `yukan.id` and see the correct structure should look like. 

So zonefile still needs to be fixed.

**Comment by ahsan-javaid** [comment]
@paradigma-cl Let me know if you need further assistance, otherwise we can close this issue. 🙏

**Comment by ahsan-javaid** [comment]
Closing it after considering that it's not a stacks.js sdk issue as proved in previous conversation. Zonefile need to be fixed on user end. You may ask if further assistance required 🙏 any time 🙏. Closing the issue as no development required.
