### ISSUE TITLE
`@stacks/wallet-sdk` published without types

### ISSUE THREAD

**Issue by kyranjamie** [stx-labs/stacks.js#1088]
Rather, it's an outdated package that points the types to the incorrect file path. This looks fixed in `master` so the new package needs to be built/published

**Comment by kyranjamie** [comment]
Just ran into this again. Higher priority than p3. The latest stable version is unusable with TypeScript.

**Comment by reedrosenbluth** [comment]
@kyranjamie is this still true in `v3.0.0`?

**Comment by kyranjamie** [comment]
No, it isn't. See https://github.com/hirosystems/stacks-wallet-web/pull/2077

Thanks @reedrosenbluth
