### ISSUE TITLE
t.etags is undefined / m.etags is undefined

### ISSUE THREAD

**Issue by appsdevpk** [stx-labs/stacks.js#1093]
**Describe the bug**
when i try to put file (currently i am trying to save a json file) using storage.putFile with below options
contentType: 'application/json',
encrypt:false,
dangerouslyIgnoreEtag:true
i got 2 errors t.etags is undefined / m.etags is undefined in the browser

**What version of Blockstack.js are you using?**
19.2.5

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
Blockstack Browser

**Expected behavior**
file should be stored in user's Gaia storage

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. firefox]
 - Version [e.g. 91.0.1]

**Comment by zone117x** [comment]
How is your project being built, I don't think anyone else has ran into this issue

**Comment by agraebe** [comment]
@appsdevpk please provide more details so we can troubleshooting. closing this until we have more details.
