### ISSUE TITLE
BigInt type doesn't support on the old version browser

### ISSUE THREAD

**Issue by minhoyoo-iotrust** [stx-labs/stacks.js#1094]
**Describe the bug**

Currently, @stacks/common package uses "BigInt" type. But, the old version of browser doesn't support BigInt type. For example, in the Safari browser, BigInt type was supported from September 2020. 
It means if we use the stakcs.js package in the site, the site will not work on the old version browser.

Here is the referral link for better understanding the issue.
https://v8.dev/features/bigint#polyfilling-transpiling
https://babeljs.io/docs/en/babel-plugin-syntax-bigint 

**What version of Blockstack.js are you using?**
2.0.1

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
We found this issue during the D'CENT wallet integration. We are using stacks.js library in the webview of D'CENT mobile app.

**To Reproduce**
If you go to the site that use stacks.js library with old version of browser, you can see the error.
I'm not sure which site uses the stacks.js library.

**Expected behavior**
N/A

**Screenshots**
N/A

**Console log**
If applicable, add console log to help explain your problem.

Here is the console log we met during the test.
```
ReferenceError: Can't find variable: BigInt
Eval Code — intCV.js:3
eval
./node_modules/@stacks/transactions/dist/esm/clarity/types/intCV.js — app.js:1705
__webpack_require__ — app.js:895
fn — app.js:130
Eval Code — index.js:1
eval
./node_modules/@stacks/transactions/dist/esm/clarity/index.js — app.js:1657
__webpack_require__ — app.js:895
fn — app.js:130
Eval Code — utils.js:1
eval
./node_modules/@stacks/transactions/dist/esm/utils.js — app.js:1909
__webpack_require__ — app.js:895
fn — app.js:130
Eval Code — authorization.js:1
eval
./node_modules/@stacks/transactions/dist/esm/authorization.js — app.js:1597
__webpack_require__ — app.js:895
fn — app.js:130
Eval Code — transaction.js:1
eval
./node_modules/@stacks/transactions/dist/esm/transaction.js — app.js:1885
__webpack_require__ — app.js:895
fn — app.js:130
Eval Code
eval
./node_modules/@stacks/transactions/dist/esm/index.js — app.js:1825
__webpack_require__ — app.js:895
fn — app.js:130
Eval Code — chain-lib.js:2
eval
./node_modules/dcent-hybrid-common/src/lib/chain-lib.js — app.js:27397
__webpack_require__ — app.js:895
fn — app.js:130
Eval Code
eval
./node_modules/dcent-hybrid-common/src/utils/convert.js — app.js:28177
__webpack_require__ — app.js:895
fn — app.js:130
Eval Code
eval
./node_modules/dcent-hybrid-common/src/type/type-account.js — app.js:27829
__webpack_require__ — app.js:895
fn — app.js:130
Eval Code
eval
./src/model/model-account.js — app.js:42046
__webpack_require__ — app.js:895
fn — app.js:130
Eval Code — actions.js:11:98
eval
./src/store/actions.js — app.js:46291
__webpack_require__ — app.js:895
fn — app.js:130
Eval Code
eval
./src/store/store.js — app.js:46507
__webpack_require__ — app.js:895
fn — app.js:130
Eval Code
eval
./src/main.js — app.js:41374
__webpack_require__ — app.js:895
fn — app.js:130
(anonymous function) — app.js:46520
__webpack_require__ — app.js:895
(anonymous function) — app.js:1068
Global Code — app.js:1069
vue.esm.js:9121
```

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: iOS 12.2
 - Browser Safari
 - Version 12.1

**Additional context**
We've tried to use Babel & Polyfill to solve this issue, but it doesn't work.

**Comment by zone117x** [comment]
Have you tried https://www.npmjs.com/package/babel-plugin-transform-bigint ?

`BigInt` has over 90% support globally https://caniuse.com/bigint so I'm not sure if this lib should perform the polyfill itself.

**Comment by minhoyoo-iotrust** [comment]
@zone117x Thanks for your advises!

> Have you tried https://www.npmjs.com/package/babel-plugin-transform-bigint ?

We've tried this babel plugin, but it doesn't work properly. This plugin occured the side-effect that processes non-BigInt object as a BigInt object.

> `BigInt` has over 90% support globally https://caniuse.com/bigint so I'm not sure if this lib should perform the polyfill itself.

Yes, you're right. But many of our users use the old version of browser. That't the reason we need to fix this issue.

**Comment by zone117x** [comment]
> We've tried this babel plugin, but it doesn't work properly. This plugin occured the side-effect that processes non-BigInt object as a BigInt object.

Can you share a demo (preferably a repo) with the build setup you've tried so we can reproduce this behavior?

**Comment by minhoyoo-iotrust** [comment]
> > We've tried this babel plugin, but it doesn't work properly. This plugin occured the side-effect that processes non-BigInt object as a BigInt object.
> 
> Can you share a demo (preferably a repo) with the build setup you've tried so we can reproduce this behavior?

We did on our own repo, but I guess that you can reproduce this issue in https://github.com/blockstack/explorer repo to make a change to use the latest version of stacks library (Currently, the explore repo seems to use 2.0.0-beta stacks lib). If you can't reproduce the issue, please let me know. Thanks!

**Comment by zone117x** [comment]
This should be solvable using the correct babel config/polyfills, so I'm going to close this for now. Please let me know if you have a minimal repo to reproduce the issue and we could take a look.
