### ISSUE TITLE
Stacks CLI only supports limited subset of Clarity types for contract function calls

### ISSUE THREAD

**Issue by pgray-hiro** [stx-labs/stacks.js#1100]
While developing an example application for the Stacks docs, I wanted to demonstrate to a developer how to use the Stacks CLI to call a smart contract function on the local Clarinet DevNet. The function I was trying to call requires a `string-utf8` argument, which the Stacks CLI apparently does not support.

Talking with @zone117x, it appears that the Stacks CLI only supports `int`, `uint`, `bool`, `principal`, and `buffer`. Relevant source can be found [here](https://github.com/blockstack/stacks.js/blob/6d9ff4df00469bb1015e031bb04cc3423357de5b/packages/cli/src/utils.ts#L805-L840).

Ideally, the Stacks CLI should be updated to support all Clarity types. At the minimum, it would be nice to get string types supported immediately, and add other types in the future.

**Comment by agraebe** [comment]
This issue can be used to capture all missing types that were surfaced previously:
- https://github.com/blockstack/stacks.js/issues/931: strings
- https://github.com/blockstack/stacks.js/issues/1010: string-ascii
- https://github.com/blockstack/stacks.js/issues/900: optional

**Comment by agraebe** [comment]
@zone117x @reedrosenbluth - how much work would it be to add support for strings (ballpark/shirt-size)?

**Comment by zone117x** [comment]
small shirt size

**Comment by zone117x** [comment]
@ahsan-javaid is this something you can take a look at?
