### ISSUE TITLE
App with react-script throws TypeError: can't convert BigInt to number

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#1119]
**Describe the bug**
When running my app "pool registry" (https://github.com/friedger/stacks-pool-registry)  with the 2.0.1 in production, I get the error: 
`TypeError: can't convert BigInt to number`. The app is build using `react-script`

**What version of stack.js are you using?**
2.0.1

**To Reproduce**
1. clone the repo
2. yarn
3. yarn build
4. serve -s build

**Expected behavior**
localhost:5000/hodl should show

**Screenshots**
![Screenshot from 2021-10-18 18-11-42](https://user-images.githubusercontent.com/1449049/137768995-1175b3fc-7a1e-4c94-8822-d06a550ed125.png)

Maybe related to #1096 

**Additional Context**
https://github.com/facebook/create-react-app/issues/6907

**Comment by bigclown** [comment]
Hey i was trying to solve this exact thing.
Indeed the solution was along the lines of [this issue](https://github.com/blockstack/stacks.js/issues/1096) 

The thing is, you are going to lose the create-react-app support in both ways. if you eject and add the pollyfills or using react-app-rewired.

i've doing some test and using a [fresh New crapp](https://github.com/bigclown/cra-test-build-BigIntError/tree/main), with a connect button to login , haves the same error. But [under dev branch](https://github.com/bigclown/cra-test-build-BigIntError/tree/dev) used react-app-rewired and the pollyfills so serve -s build whould work correctly

Before trying this in your proyect read this aditional content See:
 [Important Comment about the pollyfills needed](https://github.com/blockstack/stacks.js/issues/1096#issuecomment-910418892)
[Medium article about how to integrate react-app-rewired](https://medium.com/swlh/javascript-es2020-in-react-project-9337cbe1e7db)
[react-app-rewired](https://github.com/timarney/react-app-rewired)

**Comment by dcsan** [comment]
Yeah i got exactly this problem and took a while to find it in the minified code.

So we can't build any production stacks apps since a month or so? uhhh... seriously?


```
import { IntegerType, intToBigInt } from '@stacks/common';
import { ClarityType } from '../clarityValue';

const MAX_U128 = BigInt(2) ** BigInt(128) - BigInt(1);
const MIN_U128 = BigInt(0);
const MAX_I128 = BigInt(2) ** BigInt(127) - BigInt(1);
const MIN_I128 = BigInt(-2) ** BigInt(127);

interface IntCV {
  readonly type: ClarityType.Int;
  readonly value: bigint;
}

const intCV = (value: IntegerType): IntCV => {
  const bigInt = intToBigInt(value, true);
  if (bigInt > MAX_I128) {
    throw new RangeError(
      `Cannot construct clarity integer from value greater than ${MAX_I128.toString()}`
    );
  } else if (bigInt < MIN_I128) {
    throw new RangeError(
      `Cannot construct clarity integer form value less than ${MIN_I128.toString()}`
    );
  }
  return { type: ClarityType.Int, value: bigInt };
};

interface UIntCV {
  readonly type: ClarityType.UInt;
  readonly value: bigint;
}

const uintCV = (value: IntegerType): UIntCV => {
  const bigInt = intToBigInt(value, false);
  if (bigInt < MIN_U128) {
    throw new RangeError('Cannot construct unsigned clarity integer from negative value');
  } else if (bigInt > MAX_U128) {
    throw new RangeError(
      `Cannot construct unsigned clarity integer greater than ${MAX_U128.toString()}`
    );
  }
  return { type: ClarityType.UInt, value: bigInt };
};

export { IntCV, UIntCV, intCV, uintCV };
```

**Comment by dcsan** [comment]
for anyone else still here, here's a current fix
https://github.com/blockstack/stacks.js/issues/1096#issuecomment-946350299
