### ISSUE TITLE
Bundle size of the stacks package is really huge

### ISSUE THREAD

**Issue by pradel** [stx-labs/stacks.js#1120]
**Is your feature request related to a problem? Please describe.**

I have a super simple next.js app, and the bundle size of the js files is in total `295 kB` gzipped. Without stacks.js dependencies, the size is around `65 kB`. So most of my bundle size is coming from the stacks dependencies as you can see in the following screenshot.

![Capture d’écran 2021-10-19 à 13 24 25](https://user-images.githubusercontent.com/5749437/137900584-912a2a55-5c64-47da-a052-f0140a0ff0e6.png)

**Describe the solution you'd like**

Using stacks.js libs shouldn't make my app slow to load for my users.

Opening the issue to start the discussion around improvements that can be made in stacks.js

**Comment by rafaelcr** [comment]
We are aware of this issue, we'll get back to you ASAP

**Comment by ahsan-javaid** [comment]
@zone117x As a starting point on this issue, to get rid of some of dependencies like bn.js and few others, is it allowed to use some source code from `micro-stacks` repo. I can see `micro-stacks` has `GNU GENERAL PUBLIC LICENSE` and stacks js is using `The MIT License (MIT)`. I am asking in terms of copyright issue / permissions to use `micro-stacks` code, will it be allowed or not.

**Comment by ahsan-javaid** [comment]
@zone117x Any thoughts on above question 🙏

**Comment by pradel** [comment]
Can you reopen the issue? I don't think this one is solved yet.

**Comment by pradel** [comment]
@reedrosenbluth

**Comment by janniks** [comment]
_Moving this to the relevant milestone and sub-issues_
https://github.com/hirosystems/stacks.js/milestone/56
