### ISSUE TITLE
Add url utilities for transaction api endpoints to network package

### ISSUE THREAD

**Issue by youfoundron** [stx-labs/stacks.js#1131]
**Is your feature request related to a problem? Please describe.**
I was frustrated when I wanted to look up a transaction by it's id via the hosted API and could not find the appropriate endpoint in the network package's url utilties.

**Describe the solution you'd like**
Add utility function(s) that produce the api route for looking up transactions.

**Describe alternatives you've considered**
Hard coding these endpoint strings into my own code.

**Comment by friedger** [comment]
@youfoundron Are these methods enough ? https://hirosystems.github.io/stacks-blockchain-api/client/index.html

**Comment by saralab** [comment]
This is out of scope for stacks.js, will not be pursuing this
