### ISSUE TITLE
Export `makeUnsignedContractDeploy` method

### ISSUE THREAD

**Issue by kyranjamie** [stx-labs/stacks.js#1140]
We have this already for STX token transfers and contract calls, but not contract deploys.

We'll need this method to support contract deploys on hardware wallets.

**Comment by agraebe** [comment]
@diwakergupta Kyran asked if the priority for this could be reviewed on splat. I figured it's best to surface to you directly?

**Comment by diwakergupta** [comment]
> @diwakergupta Kyran asked if the priority for this could be reviewed on splat. I figured it's best to surface to you directly?

Seems like a pretty small change? @ahsan-javaid can you take this on and then we can hopefully include it with the next release (cc/ @reedrosenbluth )

**Comment by ahsan-javaid** [comment]
Looks like its a duplicate issue if i am not wrong. Refer to the issue #1104
I already made [PR](https://github.com/blockstack/stacks.js/pull/1124) for that which matt approved. Reference: https://github.com/blockstack/stacks.js/pull/1124

**Comment by kyranjamie** [comment]
Oh great, completely missed this. Thanks @ahsan-javaid, will review.

**Comment by kyranjamie** [comment]
Closing in favour of #1124 1104
