### ISSUE TITLE
blockstack connect

### ISSUE THREAD

**Issue by dcsan** [stx-labs/stacks.js#1142]
I'm not sure if this is the right repo. confused trying to navigate all the different stacks/blockstack/hiro/nonfung systems packages that seem to do the same thing, but there's a connect package *somewhere* i've seen called 'connect'. 

Anyway it seems pinned to an ancient version of react which is now preventing other packages installing properly and getting stuck on peer deps.

```
npm ERR! While resolving: dcsan@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.31.1" from @blockstack/connect@2.12.7
npm ERR! node_modules/@blockstack/connect
npm ERR!   @blockstack/connect@"^2.12.7" from the root project
npm ERR!
```

**Comment by dcsan** [comment]
rjs 16 is from 2020, JS ecosystem thrash means this will probably stop working with a lot of stuff soon

https://github.com/facebook/react/releases/tag/v16.14.0

**Comment by friedger** [comment]
@dcsan The current version is hosted here: https://github.com/hirosystems/connect
The version of connect is 6.2.1: https://www.npmjs.com/package/@stacks/connect

This should also work with react 17: https://github.com/hirosystems/connect/blob/main/packages/connect-react/package.json#L61

**Comment by dcsan** [comment]
Thanks @friedger yes checking my package.json it seems a bit of a mess, due to confusion about what I need from `@blockstack` and else from `@stacks` ...

I'm not sure if there's a way to deprecate those old packages or somehow point to the updated ones. I heard there was some history of company name changes

I think i've built this project based on originally cloning one of the tutorials, but it's a Frankenstein of different things now as I tried to get stuff working.

So I'm assuming
>    "@stacks/connect": "^6.2.1",

replaces:
>    "@blockstack/connect": "^2.12.7",

and

>    "@blockstack/stacks-transactions": "^0.7.0",

is possibly replaced by:
https://github.com/blockstack/stacks.js/tree/master/packages/transactions
>    "@stacks/transactions": 

I'm not sure if
    "@stacks/connect": "^6.2.1",
    "@stacks/connect-react": "^13.0.0",

are both needed or one would require the other anyway...
anyway I'll try some pruning of this mess:

```
  "dependencies": {
    "@blockstack/connect": "^2.12.7",
    "@blockstack/stacks-transactions": "^0.7.0",
    "@blockstack/ui": "^2.12.14",
    "@micro-stacks/query": "^0.0.7",
    "@micro-stacks/react": "^0.0.7",
    "@stacks/connect": "^6.2.1",
    "@stacks/connect-react": "^13.0.0",
```

microstacks also looks really promising, but it's a whole alternate stack, eg jotai based rather than react-connect... so they probably don't work well together.

**Comment by friedger** [comment]
@dcsan Never use @ blockstack package!

You should either use @ stacks packages or @ microstacks packages. The deliver the same functionality.
