### ISSUE TITLE
Unable to login in to explorer.stacks.co with pre BNS 2 identities

### ISSUE THREAD

**Issue by mijoco-btc** [stx-labs/stacks.js#1148]
**Describe the bug**
The sandbox login in the explorer has recently stopped working for pre BNS migration addresses. 

Address: SP1R1061ZT6KPJXQ7PAXPFB6ZAZ6ZWW28GBQA1W0F
Username: radicle_art

Tested in Chrome and Firefox latest

Hiro Wallet v2.23.2 Firefox
Hiro Wallet v2.23.2 Chrome

Logging in with an address I created after the migration does work.

The call to 'https://core.blockstack.org/v1/names/radicle_art.id.blockstack' is throwing CORS errors.

**What version of Blockstack.js are you using?**
the version in explorer.stacks.co.

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**

**To Reproduce**
1. Go to https://explorer.stacks.co/sandbox/deploy?chain=mainnet
2. Click on Connect Stacks Wallet
3. Open inspector to '....'

**Expected behavior**

**Screenshots**

<img width="1376" alt="Screenshot 2021-12-09 at 08 41 26" src="https://user-images.githubusercontent.com/4384929/145363440-1e7e3467-0abd-4a9b-8f15-9405b49c58ea.png">

**Console log**
`deploy:1 Access to fetch at 'https://core.blockstack.org/v1/names/radicle_art.id.blockstack' from origin 'https://explorer.stacks.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
08:41:20.300 fetchUtil.esm.js:22 GET https://core.blockstack.org/v1/names/radicle_art.id.blockstack net::ERR_FAILED 301
(anonymous) @ fetchUtil.esm.js:22
f @ runtime.esm.js:66
(anonymous) @ runtime.esm.js:283
(anonymous) @ runtime.esm.js:119
i @ _rollupPluginBabelHelpers.js:3
a @ _rollupPluginBabelHelpers.js:25
(anonymous) @ _rollupPluginBabelHelpers.js:32
(anonymous) @ _rollupPluginBabelHelpers.js:21
a @ fetchUtil.esm.js:35
s @ fetchUtil.esm.js:6
(anonymous) @ verification.esm.js:102
f @ runtime.esm.js:66
(anonymous) @ runtime.esm.js:283
(anonymous) @ runtime.esm.js:119
v @ _rollupPluginBabelHelpers.js:3
s @ _rollupPluginBabelHelpers.js:25
(anonymous) @ _rollupPluginBabelHelpers.js:32
(anonymous) @ _rollupPluginBabelHelpers.js:21
Kt @ verification.esm.js:156
Ft @ verification.esm.js:54
(anonymous) @ verification.esm.js:310
f @ runtime.esm.js:66
(anonymous) @ runtime.esm.js:283
(anonymous) @ runtime.esm.js:119
v @ _rollupPluginBabelHelpers.js:3
s @ _rollupPluginBabelHelpers.js:25
(anonymous) @ _rollupPluginBabelHelpers.js:32
(anonymous) @ _rollupPluginBabelHelpers.js:21
Gt @ verification.esm.js:325
Wt @ verification.esm.js:299
(anonymous) @ userSession.esm.js:157
f @ runtime.esm.js:66
(anonymous) @ runtime.esm.js:283
(anonymous) @ runtime.esm.js:119
v @ _rollupPluginBabelHelpers.js:3
s @ _rollupPluginBabelHelpers.js:25
(anonymous) @ _rollupPluginBabelHelpers.js:32
(anonymous) @ _rollupPluginBabelHelpers.js:21
(anonymous) @ userSession.esm.js:314
(anonymous) @ auth.esm.js:78
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
i @ _rollupPluginBabelHelpers.js:3
a @ _rollupPluginBabelHelpers.js:25
Promise.then (async)
i @ _rollupPluginBabelHelpers.js:13
a @ _rollupPluginBabelHelpers.js:25
(anonymous) @ _rollupPluginBabelHelpers.js:32
(anonymous) @ _rollupPluginBabelHelpers.js:21
(anonymous) @ auth.esm.js:107
m @ ui.esm.js:7
(anonymous) @ use-connect.tsx:23
onClick @ index.esm.js:200
We @ react-dom.production.min.js:52
Ye @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
_r @ react-dom.production.min.js:100
Cr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Me @ react-dom.production.min.js:292
Xt @ react-dom.production.min.js:73
Show 15 more frames
08:41:20.302 auth.esm.js:95 [Connect] Error during auth request Error
    at t.<anonymous> (userSession.esm.js:167)
    at f (runtime.esm.js:66)
    at Generator._invoke (runtime.esm.js:283)
    at Generator.next (runtime.esm.js:119)
    at v (_rollupPluginBabelHelpers.js:3)
    at s (_rollupPluginBabelHelpers.js:25)
(anonymous) @ auth.esm.js:95
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
i @ _rollupPluginBabelHelpers.js:3
u @ _rollupPluginBabelHelpers.js:29
Promise.then (async)
i @ _rollupPluginBabelHelpers.js:13
a @ _rollupPluginBabelHelpers.js:25
Promise.then (async)
i @ _rollupPluginBabelHelpers.js:13
a @ _rollupPluginBabelHelpers.js:25
(anonymous) @ _rollupPluginBabelHelpers.js:32
(anonymous) @ _rollupPluginBabelHelpers.js:21
(anonymous) @ auth.esm.js:107
m @ ui.esm.js:7
(anonymous) @ use-connect.tsx:23
onClick @ index.esm.js:200
We @ react-dom.production.min.js:52
Ye @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
_r @ react-dom.production.min.js:100
Cr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Me @ react-dom.production.min.js:292
Xt @ react-dom.production.min.js:73
08:42:01.149 auth.esm.js:95 [Connect] Error during auth request cancel`
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ahsan-javaid** [comment]
The api call to old url `https://core.blockstack.org/v1/names/radicle_art.id.blockstack` from explorer gives 301 status code permanently moved to `https://stacks-node-api.stacks.co/v1/names/radicle_art.id.blockstack`

Looks like explorer is using older version of `auth` and eventually the `network` package which might be causing the issue.

https://github.com/hirosystems/explorer/blob/397eaaa3ca858e64dfd38af0d39e58b6176ab5fa/package.json#L35

Anyways, based on status code received in response name lookup url needs to updated at `https://stacks-node-api.stacks.co` instead of using old one.

Updating the `@stacks/auth` version in `explorer` may fix the issue because `network` package is using correct `bns` lookup url.

**Comment by diwakergupta** [comment]
> The api call to old url `https://core.blockstack.org/v1/names/radicle_art.id.blockstack` from explorer gives 301 status code permanently moved to `https://stacks-node-api.stacks.co/v1/names/radicle_art.id.blockstack`
> 
> Looks like explorer is using older version of `auth` and eventually the `network` package which might be causing the issue.
> 
> https://github.com/hirosystems/explorer/blob/397eaaa3ca858e64dfd38af0d39e58b6176ab5fa/package.json#L35
> 
> Anyways, based on status code received in response name lookup url needs to updated at `https://stacks-node-api.stacks.co` instead of using old one.
> 
> Updating the `@stacks/auth` version in `explorer` may fix the issue because `network` package is using correct `bns` lookup url.

cc/ @andresgalante -- is there an existing issue in the explorer for this?

Meanwhile @ahsan-javaid can you audit any usage of core.blockstack.org within stacks.js? That endpoint is deprecated and ideally we should just remove all usage of it (cc/ @saralab )

**Comment by mijoco-btc** [comment]
Hi when is likely to be released to https://explorer.stacks.co/sandbox/deploy ?

**Comment by andresgalante** [comment]
@radicleart would you mind creating an issue on the explorer repo to track that?

to answer your question, we have a code freeze until the first week of Jan, so it won't happen till then
