### ISSUE TITLE
Private key leaked in wallet sdk 3.1.0

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#1152]
**Describe the bug**
In the wallet sdk, the private key is used as a parameter in a call to the stacks node during name lookup.

**What version of Blockstack.js are you using?**
wallet sdk 3.1.0

see https://github.com/blockstack/stacks.js/pull/1151 in particular https://github.com/blockstack/stacks.js/pull/1151/commits/6bd5fd9bddf1b277a021a8b15cf82f5a336a9fa6 fixes it.

**Comment by kyranjamie** [comment]
Will make a separate PR just with this commit
