### ISSUE TITLE
https://browser.blockstack.org/auth is broken

### ISSUE THREAD

**Issue by sebyx07** [stx-labs/stacks.js#1157]
**Describe the bug**

Go to any app using blockstack authentication, ex: https://block-photos.com, try to login and it get's stuck. It's from CORS and changing the domain name
from https://core.blockstack.org/ to https://stacks-node-api.stacks.co/

```js
auth:1 
        
       Access to fetch at 'https://core.blockstack.org/v1/names/sebyx07_pro.id.blockstack' from origin 'https://browser.blockstack.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Please fix the https://core.blockstack.org to return the appropriate headers. A lot of apps are broken because of this

**Comment by ahsan-javaid** [comment]
This is a duplicate issue. Refer to https://github.com/blockstack/stacks.js/issues/1148 for discussion & PR already merged and released from stacks.js side. 
Upgrade stacks.js sdk to latest version in your projects.

**Comment by saralab** [comment]
Closing this issue, duplicate.
