### ISSUE TITLE
Silent failure on deploy_contract with long contract name

### ISSUE THREAD

**Issue by mrkmcknz** [stx-labs/stacks.js#1159]
**Describe the bug**
I noticed that when deploying via the cli and a bash script that I would get a successful txid for a deploy_contract command but there is nothing in the mempool and the transaction is not found.

After trying a number of alternative methods I assume this can only be down to the contract name length, using a shorter name with the same arguments and contract deploys without issue.

**What version of Blockstack.js are you using?**
3.1.1

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
Blockstack CLI

**To Reproduce**
1. Attempt to deploy any contract with a long name (unsure what constitutes a long name)

**Expected behavior**
The contract should deploy or an error message letting the consumer know the length exceeds an upper limit.

**Screenshots**

**Console log**
```
{
  txid: '0x538c7f155b5a76bf869d0c18ccd31ed39deafcfc99282ffb60c1c32ca0a7798b',
  transaction: 'https://explorer.stacks.co/txid/0x538c7f155b5a76bf869d0c18ccd31ed39deafcfc99282ffb60c1c32ca0a7798b?chain=mainnet'
}
```

**Comment by ahsan-javaid** [comment]
Contract name should be between 1  - 128 in length. Checks are already in place. Calling contract deploy with contract name length more than 128 will return following error:
`Error: String length exceeds maximum bytes 128`

In your scenario transaction did not broadcast so that why it's not visible in `explorer` url.

**Comment by mrkmcknz** [comment]
@ahsan-javaid, I see.

Is there a reason why a transaction would fail to broadcast? I assumed that a transaction ID output only happens if it was successful?

**Comment by ahsan-javaid** [comment]
Yes it can still fail even if you get txid. Use [This code to deploy](https://github.com/blockstack/stacks.js/blob/fe831cf28d71de9410c81cfabe256fd511e9aa4d/packages/transactions/README.md?plain=1#L68-L88) the contract and print out the 
```
import { makeContractDeploy, broadcastTransaction, AnchorMode } from '@stacks/transactions';
import { StacksTestnet, StacksMainnet } from '@stacks/network';
import { readFileSync } from 'fs';
// for mainnet, use `StacksMainnet()`
const network = new StacksTestnet();
const txOptions = {
  contractName: 'contract_name',
  codeBody: readFileSync('/path/to/contract.clar').toString(),
  senderKey: 'b244296d5907de9864c0b0d51f98a13c52890be0404e83f273144cd5b9960eed01',
  network,
  anchorMode: AnchorMode.Any,
};
const transaction = await makeContractDeploy(txOptions);
const broadcastResponse = await broadcastTransaction(transaction, network);

console.log(broadcastResponse); // This will give you the error reason 
```
to see the actual error message with failure reason.

**Comment by saralab** [comment]
Closing this, not a bug, addressed by the comment above.
