### ISSUE TITLE
Utilise the `browser` field of the package.json to deliver pre-polyfilled browser modules

### ISSUE THREAD

**Issue by saralab** [stx-labs/stacks.js#1162]
Webpack 5 doesn't support auto-polyfill for node.js modules like stream and crypto that are used in stacks.js
In an attempt to enable the SDK work seamlessly with both node and browser, it will be great to deliver pre-polyfilled browser modules.

**Comment by janniks** [comment]
not sure if it's a viable option to add a pre-polyfilled `browser` bundle.

1️⃣ the size of some polyfills are huge. e.g. adding the `crypto` polyfill to the `@stacks/encryption` package brought the bundle size from `32.7kB`→`275.1kB` (unpacked: `203.6kB`→`999.4kB`)

2️⃣ the `browser` module reference will override `main` — even if we don't want polyfills (e.g. in next js). there is no `polyfill` module specifier, unfortunately

3️⃣ [the polyfill for `crypto`](https://bundlephobia.com/package/crypto-browserify@3.12.0) uses the packages `elliptic` and `bn.js`, which we are already trying to get rid of — defeating the purpose of these bundle size improvements

---

i would rather suggest focussing on replacing the parts that need to be polyfilled.

for now, we could add guides to explain polyfills in our documentation.

---

 🚧 i'll investigate some more — maybe we can use a crypto alternative that allows us to slim the bundles with prior tree-shaking.

**Comment by janniks** [comment]
if we want to tackle this, step-by-step, i would propose NOT polyfilling `crypto` — rather replace the used functions with their `noble` equivalent. then we can still polyfill `buffer`, `process`, etc. where needed (all a lot smaller than `crypto`)
