### ISSUE TITLE
Support or tutorial for install on windows type environment

### ISSUE THREAD

**Issue by aquaflamingo** [stx-labs/stacks.js#119]
Hello BS Team,

I was extremely excited when coming across blockstack.org but was disappointed when I couldn't find a tutorial for installing through a windows environment. 

Unfortunately, I'm not familiar with Linux/Ubuntu or VM environment either. I'm sure it's probably an eventual feature but I just thought I'd create an issue for the request.

**Comment by aagorelik** [comment]
Hi! pip is a part of python bundle for windows, so you could use pip to install blockstack?

**Comment by jcnelson** [comment]
This conversation has moved here: https://github.com/blockstack/blockstack-core/issues/324
