### ISSUE TITLE
Offload `bip*` dependency

### ISSUE THREAD

**Issue by janniks** [stx-labs/stacks.js#1198]
### sub-issues
- https://github.com/hirosystems/stacks.js/issues/1201
- https://github.com/hirosystems/stacks.js/issues/1202
- https://github.com/hirosystems/stacks.js/issues/1203

**Comment by zone117x** [comment]
Issue should be broken into 2 issues: one for `bip32` and one for `bip39`

**Comment by janniks** [comment]
Split into respective bips and packages. Ignoring `cli` package for now as it benefits the least from web friendly un-polyfilling changes (and executes its functions via the other packages typically).

The only question remaining is: do we still want to support (or deprecate) the `keychain` package — i.e. either make the same changes for the `keychain` package or remove it in favor of `wallet-sdk`
