### ISSUE TITLE
`UserSession` fields not populated after `loadUserData` function call

### ISSUE THREAD

**Issue by m-roll** [stx-labs/stacks.js#1199]
**Describe the bug**
After calling `userSession.loadUserData()` after the authentication flow, fields like `username` are not properly populated. I am using the [Todos app](https://docs.hiro.so/example-apps/to-dos) example. If you use the [live demo](https://todos-lovat.vercel.app/), you can see that the username field is blank. The username should show in the upper right corner in the live demo but is instead an empty string. I am seeing the same behavior in my own app.

In my wallet, I have a `.btc` domain that I would expect to be used as my "username". Is my thinking incorrect?

**What version of Stacks.js are you using?**
Using version 2.0.1 of `@stacks/auth`
**Is the bug present in the Stacks.js CLI, Gaia hub, Connect or Blockstack Browser?**
In the `stacks.js` frontend library
**To Reproduce**

1. Go to the Todos example (or any app using hiro connect/auth)
2. Follow the auth flow
3. Username is blank

**Expected behavior**
username should show the one selected from the authorization flow

**Desktop (please complete the following information):**

- Browsers tested: Chrome, Brave

**Comment by pradel** [comment]
@m-roll this one looks pretty similar to https://github.com/hirosystems/stacks.js/issues/1144

**Comment by janniks** [comment]
Closing issue, due to removal of usernames in the wallet auth response.
