### ISSUE TITLE
New commands for blockstore-cli

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#12]
Need:
- `blockstore-cli get_all_names [offset] [count]`
- `blockstore-cli get_names_in_namespace <namespace_id> [offset] [count]`
- `blockstore-cli get_consensus_at <block number>`

Add more as we think of them.

**Comment by muneeb-ali** [comment]
Awesome to see this here! I was literally just looking at an implementation for 

> blockstore-cli get_names_in_namespace <namespace_id>

I need it for the resolver. I believe the resolver can simply import blockstore client and talk to a local blockstored for this functionality. Leaning towards keeping the resolver very light and doing most heavy-lifting in blockstored (this was not the case with namecoin resolver, where we'd pull info out of namecoin first and then process it and add additional calls/features).

**Comment by jcnelson** [comment]
Added in 8cd21f7cddc1610a64a526341fc994266f208450
