### ISSUE TITLE
Minimum node version required should be documented

### ISSUE THREAD

**Issue by criadoperez** [stx-labs/stacks.js#1208]
**Describe the bug**
If you follow the documented steps [here](https://github.com/hirosystems/stacks.js#development-environment-setup) to run the tests, it fails.

Looks like stacks.js requires a minimum version of node that is higher than the one shipped on the most popular Linux servers. If this is the case, we should see which is the minimum version required and document it so the users can make a successful installation.  In this case, the users will have to manually install that specific version of node, because the default one shipped by their Linux distribution is not enough.

**What version of Stacks.js are you using?**
Latest. Cloning from repo.

**To Reproduce**

Fresh install of OS, installed dependencies and followed the steps [here](https://github.com/hirosystems/stacks.js#development-environment-setup).

**Expected behavior**
Tests to pass

**Console log**
Here are the console logs on all 3 systems (all with latest updates installed):
[npm-run-test-debian.log](https://github.com/hirosystems/stacks.js/files/8185224/npm-run-test-debian.log) - Debian 11 - ships with node v.12.22.5 - Result: Fails

[npm-run-test-kubuntu.log](https://github.com/hirosystems/stacks.js/files/8185227/npm-run-test-kubuntu.log) - Kubuntu 21.10 - ships with node v.12.22.5 - Result: Fails

[npm-run-test-manjaro.log](https://github.com/hirosystems/stacks.js/files/8185225/npm-run-test-manjaro.log) Manjaro - ships with node v.17.6.0 - Result: Passes with a few errors.

**Desktop (please complete the following information):**

- OS: Debian, Ubuntu / Kubuntu and Manjaro / Arch

**Comment by janniks** [comment]
Thanks for the notes and error logs 👍 Will address these concerns here: https://github.com/hirosystems/stacks.js/pull/1211
