### ISSUE TITLE
Enable users to transfer subdomains to wallet-key addresses that correspond to all data-key addresses

### ISSUE THREAD

**Issue by markmhendrickson** [stx-labs/stacks.js#1209]
The CLI should allow the user to run a command that:

1. Detects whether there are any subdomains registered with the user's key and owned by data-key-derived addresses
2. Prompts the user to confirm whether they want to migrate these subdomains to the corresponding wallet-key-derived addresses for their key by position
3. Alerts the user to any subdomains that can't be migrated to these wallet-key-derived addresses given collision with existing usernames owned by them
4. Initiates request to subdomain registrar using [new transfer endpoint](https://github.com/stacks-network/subdomain-registrar/issues/79) upon confirmation
5. Displays message indicating how long the user will have to wait until request is likely fulfilled
6. Displays confirmation that no subdomains are pending migration if user tries to execute command again

**Comment by markmhendrickson** [comment]
cc @janniks as a heads up that we're now looking to tackle this as a CLI enhancement instead of a web-wallet one. @asimm241 may have questions about Stacks.js as he dives in here

**Comment by markmhendrickson** [comment]
Once this CLI functionality is available, please assign this issue to @sjwhitely for creation of a corresponding FAQ.

**Comment by ahsan-javaid** [comment]
Update: 

- Below is the supposed implementation (cli part) based on given steps in this issue
- Questions asked in the below code and suppositions need further thought's to make the implementation concrete
- `@Asim` is working on registrar repo for migration api implementation that may be integrated once ready

https://github.com/hirosystems/stacks.js/blob/b57494a46fe83aa0512acf7d05e1a18581b34610/packages/cli/src/cli.ts#L324-L407

Any thoughts, most welcome 🙏

**Comment by asimm241** [comment]
@ahsan-javaid here are the changes required from my end. 

1 - @ahsan-javaid this endpoint `https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP31C1RGYVJVWNYWJNRVSZQA2XN9HDEA08FB0G03S ` would also return the name registered for that address. You need to filter the subdomains from the list and only migrate those. 
2- for the registrar migration call you would also need to provide a signature in the request. see the explanation here https://docs.stacks.co/build-apps/references/bns#subdomain-lifecycle

**Comment by pradel** [comment]
@ahsan-javaid from my understanding finding all the accounts owning an username is working differently. First thing is that an address can own only one subdomain so there is no need to loop over multiple items returned by the API (needs confirmation).
I think that the list of accounts is stored in a json file stored on Gaia https://github.com/hirosystems/stacks.js/blob/fe831cf28d71de9410c81cfabe256fd511e9aa4d/packages/wallet-sdk/src/models/wallet-config.ts#L56. So you could retrieve this file to be able to loop over the X accounts that are stored in this file (again, needs confirmation, maybe @kyranjamie)?
