### ISSUE TITLE
Give the ability to pass a new attribute 'appPrivarteKeyFromWalletSalt' to UserSession

### ISSUE THREAD

**Issue by beguene** [stx-labs/stacks.js#1212]
The appPrivateKey derivation is wrong in stacks-web-wallet version 3.2.0. see https://github.com/hirosystems/stacks-wallet-web/issues/2238 for more details.

We fixed the issue in the web wallet but we still need to pass the incorrectly derived appPrivateKey to dapps so they can migrate some of their user data that was encrypted using the incorrect appPrivateKey in version 3.2.0

One solution would be to pass this information to the UserSession so the dapp can access it.
only makeAuthResponse from account.ts in wallet-sdk and makeAuthResponse from message.ts in auth need to be modified.
The web wallet only use [makeAuthResponse](https://github.com/hirosystems/stacks-wallet-web/blob/v3.2.0/src/app/store/wallet/wallet.hooks.ts#L92) from wallet-sdk to pass information 

This should be a temporary fix and can later be removed when all daps have migrated.

**Comment by janniks** [comment]
Is this closable with PR #1213 ?

**Comment by beguene** [comment]
@janniks Yes
