### ISSUE TITLE
Link to Stacks Authenticator is broken

### ISSUE THREAD

**Issue by binovatyv** [stx-labs/stacks.js#1216]
**Describe the bug**
In  README.md of (https://github.com/hirosystems/stacks.js/tree/master/packages/auth

The link in the following line is broken. 
  "If you would like to implement a Stacks authenticator, check out the reference implementation of the [Stacks browser extension](https://github.com/blockstack/ux/tree/master/packages/app)[](https://github.com/hirosystems/stacks.js/tree/master/packages/auth#handling-an-authentication-response-payload)."

where can I find documentation for Stacks Authenticator 

**To Reproduce**

1. Go to 'https://github.com/hirosystems/stacks.js/tree/master/packages/auth'
2. Click on 'Stacks browser extension'
3. Link is broken
 
**Expected behavior**
Need Documentation

**Screenshots**

**Console log**
If applicable, add console log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by janniks** [comment]
Thanks for the report, we just fixed this 👍

**Comment by binovatyv** [comment]
Thank you for fixing @janniks , is there a way to authenticate besides web extension ? We like to authenticate from Node JS Server Code, not from front end app. Please share your thoughts when you get a chance.
