### ISSUE TITLE
makecontractcall fails if fee estimation is not possible - add fallback default fee

### ISSUE THREAD

**Issue by pseudozach** [stx-labs/stacks.js#1217]
Note sure if this is a feature request but to me it's a bug.

When you deploy a new contract the new fee estimation endpoint returns error with status code 400 and `No estimate available for the provided payload.` error
This causes `makeContractCall` fail with the same error if there's no explicit fee set.

Shouldn't it be possible to have a fallback default fee without externally managing this?

@stacks/transaction package version `3.1.0`

**Comment by janniks** [comment]
Hey 👋 thanks for reporting this! Could you provide us with some more information on the contract/payload that you are deploying?

**Comment by unclemantis** [comment]
Stumbled on this. Would have loved to find out if there was a solution!

+1 Following.
