### ISSUE TITLE
Add non-interactive password CLI option

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#122]
Add a CLI option for entering the password non-interactively.

**Comment by aagorelik** [comment]
Moreover, I would suggest to enable non-interactive mode for any cli commands. Like 'y' for register, for example

**Comment by jcnelson** [comment]
Can do :+1:

**Comment by jcnelson** [comment]
This has been added in 0.14.1 with the `-p/--password` and `-a/--api_password` options.
