### ISSUE TITLE
[@stacks/transactions] Unable to deserialized unsigned/halfsigned multisig transactions

### ISSUE THREAD

**Issue by alebusse** [stx-labs/stacks.js#1221]
**Describe the bug**
Unable to deserialize a transaction that doesnt have all signatures required

**What version of Stacks.js are you using?** 
Stacks.js 3.4.0
@stacks/transaction 3.3.0

**Is the bug present in the Stacks.js CLI, Gaia hub, Connect or Blockstack Browser?**
Stacks.js

**To Reproduce**
This is the code that might need the fix to allow unsigned/halfisigned txs
https://github.com/hirosystems/stacks.js/blob/master/packages/transactions/src/authorization.ts#L238

The unsigned tx was created using the version 2.0.1 of the stacks.js
Check this repo for reproduction
https://github.com/alebusse/stx-multisig-bug-test

**Comment by janniks** [comment]
Thanks, we're looking to fix this 👍
