### ISSUE TITLE
[BUG] serialized partially signed multi-sig transactions cannot be deserialized back

### ISSUE THREAD

**Issue by luizalbertocviana** [stx-labs/stacks.js#1228]
First of all, thank you for the effort put in this library which I use in a daily basis :)

I believe I have found a bug regarding the serialization/deserialization scheme for multi-sig transactions.

According to the following line

https://github.com/hirosystems/stacks.js/blob/bd8c847e4ac43f5f8e1fd803174a199f69d5a435/packages/transactions/src/authorization.ts#L238

it is not possible to deserialize a serialized partially signed multi-sig spending condition.
This implies that a partially signed multi-sig tx can be serialized, but it cannot be deserialized back.

I believe this breaks the following scenario:
- userA creates a multi-sig tx using its public key as well as userB's public key;
- userA signs the tx;
- userA serializes the partially signed multi-sig tx;
- userA sends the serialized tx to userB;
- userB deserializes the tx;
- userB signs the tx;
- as the tx is now a fully signed multi-sig tx, userB broadcasts it.

**Comment by janniks** [comment]
Thanks for the report! We'll look into this 👍🏻

**Comment by janniks** [comment]
@ahsan-javaid are you already working on this or can I have a look?

**Comment by ahsan-javaid** [comment]
I looked into it and the scenario is valid and reproducible.

```
import { deserializeTransaction } from "@stacks/transactions";

const serializedUnsignedTx =
    '80800000000401a5beef0a47958d870fb90f5bd79e556b5ec7f483000000000000000400000000000000c8000000030003264290976c5bf07b0a12635f8ad57a8edff8f6e73554b30e19f6d6783ca6f4b70002688809b7fb74fb60dab30f8d23e139b2796fe112cc12d7909bdd49d356a9269700022d2426a24c70f34a05763f94ec67ac084065b23a127cb591d68c61a7e6311b5900020302000000000005159558bd2cdf99842228d266671c3f34722e803847000000000000006430000000000000000000000000000000000000000000000000000000000000000000';

try {
    const result = deserializeTransaction(serializedUnsignedTx);
    console.dir(result);
} catch (e) {
    console.log(e)
}

```


https://github.com/hirosystems/stacks.js/blob/bd8c847e4ac43f5f8e1fd803174a199f69d5a435/packages/transactions/src/authorization.ts#L238

To fix this need to allow `numSigs <= signaturesRequired` 

But doing this breaks couple of test cases.  Not sure will it be acceptable changing these breaking test cases accordingly as they align with `stacks-blockchain` in implementation to not allow deserialization of partially signed multisig transaction.

Thinking on this further... or most welcome if you have different thought's.

**Comment by diwakergupta** [comment]
@luizalbertocviana in your example, are you calling `appendOrigin` with user B's pubkey before user B attempts to deserialize (see pattern at https://github.com/hirosystems/stacks.js/tree/master/packages/transactions#supporting-multi-signature-transactions)?

**Comment by luizalbertocviana** [comment]
> @luizalbertocviana in your example, are you calling `appendOrigin` with user B's pubkey before user B attempts to deserialize (see pattern at https://github.com/hirosystems/stacks.js/tree/master/packages/transactions#supporting-multi-signature-transactions)?

Hi @diwakergupta :)
Thanks for your attention.

Maybe I have not described my test scenario as clearly as I should.

Notice that when userA sends a serialized partially signed transaction to userB, userA is in fact sending the return of the `serialize` method from `StacksTransaction` class.
That method returns a `Buffer`, so userA sends to userB just binary data (via https, a file transfer, etc).
This way, the first thing userB must do in order to operate on the partially signed multi-sig transaction he has received from userA is deserialize it.
Notice there is no way userB would call `appendOrigin` method from `TransactionSigner` before deserialization, as userB only has received a `Buffer`.

**Comment by luizalbertocviana** [comment]
>... as they align with stacks-blockchain in implementation to not allow deserialization of partially signed multisig transaction.

Hi @ahsan-javaid :)
Thanks for your quick replies to my issue.

Is there an alternative approach for sending partially signed multi-sig transactions across network?

Please correct if I am wrong, but I believe this is a critical thing to the scenario I have described, otherwise some part (userA, userB or a third part) would need to handle both userA and userB secret keys in order to properly sign and broadcast their multi-sig transaction, and this does not seem to be a decentralized approach.

**Comment by ahsan-javaid** [comment]
Looks like there is an alternative way of bypassing this error with existing code base. Here are the steps:

1. UserA create the transaction with numSignatures value set to 1
2. UserA signs the transaction and send it to userB after serialization
3. UserB will be able to deserialize it as numSignatures is met now
4. UserB will set numSignatures = 2. just increment numSignatures++
5. UserB will sign the transaction and broadcast it
6. This approach can work for any number of users
Hack: The receiver will just need to increment numSignatures before signining.

Sample implementation: 

```
import {
  makeUnsignedSTXTokenTransfer,
  deserializeTransaction,
  pubKeyfromPrivKey,
  publicKeyToString,
  standardPrincipalCV,
  BufferReader,
  MultiSigSpendingCondition,
  AnchorMode, TransactionSigner, createStacksPrivateKey,
} from '@stacks/transactions';

void(async () => {

  // User-A machine
  const recipient = standardPrincipalCV('SP3FGQ8Z7JY9BWYZ5WM53E0M9NK7WHJF0691NZ159');
  const amount = 2500000;
  const fee = 0;
  const nonce = 0;
  const memo = 'test memo';

  const privKeyStrings = [
    '6d430bb91222408e7706c9001cfaeb91b08c2be6d5ac95779ab52c6b431950e001',
    '2a584d899fed1d24e26b524f202763c8ab30260167429f157f1c119f550fa6af01',
    'd5200dee706ee53ae98a03fba6cf4fdcc5084c30cfa9e1b3462dcdeaa3e0f1d201',
  ];

  const privKeys = privKeyStrings.map(createStacksPrivateKey);


  const pubKeys = privKeyStrings.map(pubKeyfromPrivKey);
  const pubKeyStrings = pubKeys.map(publicKeyToString);

  const transaction = await makeUnsignedSTXTokenTransfer({
    recipient,
    amount,
    fee,
    nonce,
    memo: memo,
    numSignatures: 1, // Initially set numSignatures = 1 on userA machine
    publicKeys: pubKeyStrings,
    anchorMode: AnchorMode.Any
  });

  // Now add the required signatures in the original transactions
  const signer = new TransactionSigner(transaction);
  signer.signOrigin(privKeys[0]);

  const serializedTx = signer.transaction.serialize();

  //////////////////////////////////////////////////////////////////
  // Now give serializedTx to user B via http or file transfer etc...


  // Now on UserB machine set signaturesRequired = 2

  const bufferReader = new BufferReader(serializedTx);

  // It will successfully deserialize as numSignature condition met
  const stacksTransactionOnUserBMachine = deserializeTransaction(bufferReader);

  const sp = stacksTransactionOnUserBMachine.auth.spendingCondition as MultiSigSpendingCondition;
  // Now userB has this transaction so before sign make signaturesRequired++;
  sp.signaturesRequired++;
  const signerB = new TransactionSigner(stacksTransactionOnUserBMachine);
  // Now user B can sign the transaction
  signerB.signOrigin(privKeys[1]);
  const serializedTxUserB = signerB.transaction.serialize();
  console.log(serializedTxUserB);

  // Give it userC and so on for any number of users
  const bufferReader2 = new BufferReader(serializedTxUserB);
  const stacksTransactionOnUserCMachine = deserializeTransaction(bufferReader2);
  // On User C Machine
  console.log(stacksTransactionOnUserCMachine)
})();

```

cc: @luizalbertocviana

**Comment by luizalbertocviana** [comment]
Hey @ahsan-javaid :)

Thank you so much for this reply.
I will check this on my side as soon as I can.

What are your thoughts on updating documentation?
I believe such a scenario would be much more valuable than the current one regarding multi-sig, in which a non signed tx is serialized, you know?

**Comment by luizalbertocviana** [comment]
Hey @ahsan-javaid 

Indeed your approach solves the serialization/deserialization issue.
However, I am afraid it creates a new one.

When I try to broadcast the fully signed multi-sig tx, that is, signed by both userA (with `signaturesRequired == 1`) and userB (after `signaturesRequired++`), it is rejected with the following response:

```
{
  error: 'transaction rejected',
  reason: 'SignatureValidation',
  reason_data: {
    message: 'Signer hash does not equal hash of public key(s): 0acc89b63de9494f481389a9f2910a3e360e3e4c != 0d2b11f6b356be4d18a5898c99a7c49ac0bd8b09'
  },
  txid: '901b3f0d5c6fc21054e1177f05c614a5c5a823340dbcc3eca793c1d7e453e59c'
}
```

Maybe it is worth mentioning I am creating a contract call transaction.

**Comment by janniks** [comment]
I was under the impression that any signing needs to "know"/include the final number of signaturesRequired, correct?

We probably need to remove the check in the serialization. I had a brief look at this w/ reed before and came to the same conclusion (without comparing to the rust implementation).
