### ISSUE TITLE
cli ascii ui design

### ISSUE THREAD

**Issue by guylepage3** [stx-labs/stacks.js#123]
Design new cli ascii ui

Items to design:
- blockstack ascii logo
- ascii install loader

**Comment by muneeb-ali** [comment]
Oh that'd be awesome! I've thought about it a couple of times as well.

**Comment by jcnelson** [comment]
@guylepage3 which color do you want?  I can make the ASCII logo show up in any of these colors:

https://en.wikipedia.org/wiki/File:Xterm_256color_chart.svg

**Comment by guylepage3** [comment]
@jcnelson very cool. so the color options we have are all web safe only?

**Comment by jcnelson** [comment]
The colors in the link are available on most UNIX command-line interfaces.  If you can give me the ASCII logo and tell me which color(s) to make it, I can write the code to print it out accordingly.

**Comment by guylepage3** [comment]
Sounds good. When's the next release? I would like to push it out with that.

Also, are we able to execute a cool installation loader animation? Something simple for now. For example how NPM, Grunt or Gulp loaders look?

**Comment by jcnelson** [comment]
Probably not a high priority, since we have Portal now...
