### ISSUE TITLE
Support length estimation in fee estimate interface

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#1233]
The transaction fee estimation API on the stacks-node supports an `estimated_len` argument to supply a length estimate for the finalized transaction. This is essential for providing accurate fee esimates: many transactions' costs, particularly STX transfers, are dominated by the byte length of the transaction authorization data (signature, fees, etc).

Providing accurate estimates for this requires knowing the number of post-conditions, whether the transaction will be sponsored, and the kind of signer.

[SIP-005](https://github.com/stacksgov/sips/blob/main/sips/sip-005/sip-005-blocks-and-transactions.md) provides details on the serialization of transactions, but getting accurate estimates will likely require taking a close look at the serialization code in either the stacks-blockchain implementation of transaction serialization and signing or the implementation in stacks.js itself. Essentially, this method will be given a _payload_, and then estimate the length of these transaction fields:

* A 1-byte version number, identifying whether or not the transaction is meant as a mainnet or testnet transaction.
* A 4-byte chain ID, identifying which Stacks chain this transaction is destined for.
* The transaction authorization structure:
      - The address of the origin account.
      - The signature(s) and signature threshold for the origin account.
      - The address of the sponsor account, if this is a sponsored transaction.
      - The signature(s) and signature threshold for the sponsor account, if given.
      - The fee to pay, denominated in microSTX.
* A 1-byte anchor mode
* A 1-byte post-condition mode
* The post condition structure
      - A 4-byte length, indicating the number of post-conditions.
      - The post-conditions

And then add that estimated length to the length of the given payload.

**Comment by janniks** [comment]
It looks like stacks.js already uses some estimation. Currently, the transaction is serialized as far as possible (including payload, authorization, post-conditions, etc.) and used for `estimated_len`. 

[See fee estimation in `makeUnsignedSTXTokenTransfer()` →](https://github.com/hirosystems/stacks.js/blob/2b6638d61183e6bcdcac64b91b5e6a7117e7a898/packages/transactions/src/builders.ts#L617-L621)

Is this a feature request for including the later resulting additional signature-length in the estimation? Or maybe for an supplementary exported fee estimation method for wallets or similar consumers?

**Comment by kantai** [comment]
> Is this a feature request for including the later resulting additional signature-length in the estimation? 

Yes, exactly-- the current estimate (I think) only includes the payload length.

**Comment by ahsan-javaid** [comment]
Looks like serialization implementation in `stacks.js` is exactly same as in `stacks-blockchain`. 
**Reference stacks-blockchain**: 

https://github.com/stacks-network/stacks-blockchain/blob/6c5349b0422c5c88db02d578720467c16b102ab2/src/chainstate/stacks/transaction.rs#L515-L525

**Reference stacks.js**: 

https://github.com/hirosystems/stacks.js/blob/d1685e1ed8da8f1bbd0a8ae9565b443d705d80a9/packages/transactions/src/transaction.ts#L238-L248

https://github.com/hirosystems/stacks.js/blob/d1685e1ed8da8f1bbd0a8ae9565b443d705d80a9/packages/transactions/src/builders.ts#L618

That means `estimatedLen` includes everything as mentioned in this issue including (version, chainId, auth, anchor_mode, post condition mode, post conditions and payload). Total 7 fields.

`Yes, exactly-- the current estimate (I think) only includes the payload length.`
Given these facts the above statement does not looks valid.  👆

Not sure what is missing in `estimatedLen` value that Aaron wants to handle in this issue. 🙏 if i missunderstood anything.

**Comment by janniks** [comment]
Yes, currently the byteLength used for `estimated_len` includes: version, chainId, authorization, anchorMode, postConditions, and payload.
We can look into "estimating" the change in size after signing and use the result for `estimated_len` instead.

**Comment by kantai** [comment]
Ah, I see -- then yes, the only thing necessary is adding the estimated length of the signature.

**Comment by ahsan-javaid** [comment]
On point: `We can look into "estimating" the change in size after signing and use the result for estimated_len instead.`

I tried to figure out the change in size after signing and the result is **there is no change in size after signing**. 
The reason is unsigned transaction uses `emptyMessageSignature` which allocate the space for signature. 
https://github.com/hirosystems/stacks.js/blob/ad300fb1564331aebe70e710dfd8039312d4a17d/packages/transactions/src/authorization.ts#L40-L45

The resulting byteLength will remain the same before or after signing.  That means the current estimation is correct. 

🙏 if i am wrong in judging the scenario.

**Comment by janniks** [comment]
Ah, good to know 😄
Do you know if this this is also true for multi-signature transactions?

**Comment by ahsan-javaid** [comment]
Yes true
