### ISSUE TITLE
Unable to access hub_info on Tor browser

### ISSUE THREAD

**Issue by stxapps** [stx-labs/stacks.js#1242]
**Describe the bug**
On Tor browser, user can't sign up or sign in to https://brace.to. We've received an error below.

`XHR GET https://hub.blockstack.org/hub_info 403 Forbidden`

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://hub.blockstack.org/hub_info. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**To Reproduce**

1. Using Tor browser, go to https://brace.to
2. Click on Get Started button -> Get your Secret Key -> I've saved it -> I've backed up my Secret Key
3. See the error

**Screenshots**
<img width="240" alt="Screen Shot 2022-04-27 at 10 29 50" src="https://user-images.githubusercontent.com/61498730/165434261-fb19495a-c8f4-46ca-ab51-6a4e4f2634ee.png">

<img width="240" alt="Screen Shot 2022-04-27 at 10 12 09" src="https://user-images.githubusercontent.com/61498730/165434669-212f7825-18db-4fd4-afa2-96c80928ef57.png">

<img width="240" alt="Screen Shot 2022-04-27 at 10 14 21" src="https://user-images.githubusercontent.com/61498730/165434712-56a7cbef-b8e9-42ea-ab22-775e1cb1829b.png">

**Additional context**
We believe it's about Cloudflare blocking Tor nodes because of too much requests/strange behaviors. We can access https://hub.blockstack.org/hub_info directly on any browser but on Tor browser, we get security check hCaptcha shown below.

<img width="240" alt="Screen Shot 2022-04-27 at 10 15 09" src="https://user-images.githubusercontent.com/61498730/165435207-8c7ca759-0a22-476d-b3d2-467cae7fac6e.png">

We've tried changing Tor nodes by click new circuit button without success.
Can you help? It would be great if our apps can be used on Tor browser. Thank you so much.

**Comment by janniks** [comment]
cc @CharlieC3

**Comment by CharlieC3** [comment]
@stxapps Can you test this again? CORS is already set for this path correctly, it's just being blocked by a firewall. I adjusted the firewall a bit and I no longer get an error.

**Comment by stxapps** [comment]
@CharlieC3 We've tried several times with several new circuit but it still doesn't work. We still can't sign up or sign in.

If we access https://hub.blockstack.org/hub_info directly on Tor browser, it's a bit different from before. There's no hChaptcha. There's a waiting page showing for a while before redirecting to normal hub info page.

Can you help? Thank you.

**Comment by CharlieC3** [comment]
@stxapps It seems no matter how I configure our firewalls, Cloudflare is still automatically blocking this traffic.
However, I noticed there's no `referer` header being passed in the HTTP request. If you're able to add a `referer` header, I might be able to test a different method of allowing traffic through.

![Screen Shot 2022-05-02 at 10 39 48 AM](https://user-images.githubusercontent.com/2747302/166253362-186f50db-f1c2-4c2e-9035-89ae71b2e254.png)

**Comment by stxapps** [comment]
@CharlieC3 Can origin be used instead? With the default value of [referrer-policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy), for cross-origin requests, referrer value is origin. It's weird there is no referrer in the header, seems like it think it goes from HTTPS to HTTP?

**Comment by stxapps** [comment]
Correction: there is no referrer because [stacks.js](https://github.com/hirosystems/stacks.js/blob/master/packages/common/src/fetchUtil.ts) explicitly excludes it.

**Comment by CharlieC3** [comment]
I created [this issue](https://github.com/hirosystems/stacks.js/issues/1244) to see if a referrer can be set in the stacks.js lib.

**Comment by stxapps** [comment]
@CharlieC3 We've managed to add a referer in the header. Can you try and let us know if it helps. Thank you.

<img width="240" alt="Screen Shot 2022-05-06 at 17 57 34" src="https://user-images.githubusercontent.com/61498730/167119181-c2e8f9e3-2a99-45c7-bfeb-431b671cfb13.png">

**Comment by janniks** [comment]
Can I ask how you did it?

**Comment by stxapps** [comment]
Made changes in node_modules 😅

**Comment by CharlieC3** [comment]
@stxapps Thanks for making the change, albeit not ideal right now, it seemed to help do the trick. After some testing, I was able to sign up 5 times in a row without hitting any errors.
Let me know if it's fixed on your end!

**Comment by stxapps** [comment]
We've tested and it works! We'll let our user know. Thank you so much.

**Comment by stxapps** [comment]
@CharlieC3 We've added a referer in the request header for [Justnote](https://justnote.cc) but it doesn't work (It works on Brace.to). Can you help?

<img width="240" alt="Screen Shot 2022-05-08 at 14 08 58" src="https://user-images.githubusercontent.com/61498730/167285810-6bc4dd3c-393e-4894-9467-71b099c0b9f2.png">

**Comment by CharlieC3** [comment]
@stxapps Updated. Are there any other sites which need access through Tor?

**Comment by janniks** [comment]
@stxapps we just released v4.0.1 of stacks.js which now allows changing the referrer policy and should set a compatible policy for you by default.

**Comment by stxapps** [comment]
@CharlieC3 No, we have only these two. Thanks a lot.
@janniks Thank you. We'll upgrade it.
