### ISSUE TITLE
[test] make sure tests are using mocked fetch

### ISSUE THREAD

**Issue by janniks** [stx-labs/stacks.js#1249]
_related to https://github.com/hirosystems/stacks.js/issues/1248_

some tests may not be using mocked fetch results, but actually making network requests.

change remaining non-mocked fetch tests to mocked results.

**Comment by ahsan-javaid** [comment]
There are no further tests that needs to be mocked. Fixed the tests in `wallet-sdk` that already got merged. 
So this issue is safe to be closed.
