### ISSUE TITLE
Switch Registration Confirmation from BTC to Satoshi

### ISSUE THREAD

**Issue by doodlemania2** [stx-labs/stacks.js#125]
Most all of the CLI shows values in Satoshis now, except when pre-registering (blockstack-cli/blockstack_client/actions.py), line 755 - value is in BTC.

**Comment by shea256** [comment]
Thanks for reporting this @doodlemania2 and thanks for the pointer to comment here @jcnelson.

I'd like to offer up two more discussion points related to this...

**Improvement suggestion:** @vsund suggested we have a configuration option where users can set their unit to one of the following:
- Bitcoins/BTC
- millibitcoins (10^-3 bitcoins)
- bits/microbitcoins (10^-6 bitcoins)
- satoshis (10^-8 bitcoins)

**Default units:** What should the default be? What is easiest for everyone to use?

**Comment by Skorpion7777** [comment]
@shea256 in my opinion the **most common and mainstream used unit (and also my preferred one) is BTC**. If you buy BTCs somewhere or store them in a wallet they are nearly everywhere displayed in BTC.
**Multi and microbitcoins aren't commonly used and everybody would be confused** - no option.
**Satoshis are okay**.... i mean you can understand it. Nobody thinks, that a xxx.id registration costs 12314.0 BTC or something like this. But if you want to use satoshis, please do not only upgrade the `register` command, also update `blockstack wallet` . It should be displayed in satoshis also. 
However, **I would like to see BTC as the default**.

**Comment by shea256** [comment]
Great points @Skorpion7777.

One more suggestion: the JSON output should have an indication of what the units are. This could be another field in the JSON.

**Comment by jcnelson** [comment]
This has been fixed in 0.14.0.  Please re-open if you're still having problems.  Thanks for reporting!
