### ISSUE TITLE
Recover stx address from signature

### ISSUE THREAD

**Issue by peopledrivemecrazy** [stx-labs/stacks.js#1267]
**Is your feature request related to a problem? Please describe.**

Great fix on [#2435](https://github.com/hirosystems/stacks-wallet-web/issues/2435) I am able to verify

**Describe the solution you'd like**
Recover address from signature and message

**Comment by pradel** [comment]
You can get the address from a signature like this:
```
  const publicKey = publicKeyFromSignature(
          hashMessage(message).toString("hex"),
          createMessageSignature(signature)
        );
const addr = getAddressFromPublicKey(publicKey);
```

**Comment by peopledrivemecrazy** [comment]
~~Okay, this works thanks! how can I obtain the testnet and mainnet addresses?~~
Actually, I figured this out! it is in `profile.stxAddress` object.
