### ISSUE TITLE
[4.1.0] Can't use @stacks/storage anymore, createFetchFn is not a function

### ISSUE THREAD

**Issue by pradel** [stx-labs/stacks.js#1268]
**Describe the bug**

While upgrading deps to 4.1.0, I can't use the @stacks/storage functions to read / write on gaia

**What version of Stacks.js are you using?**

4.1.0

**Is the bug present in the Stacks.js CLI, Gaia hub, Connect or Blockstack Browser?**

@stacks/storage

**To Reproduce**

1. Pull the branch https://github.com/sigle/sigle/pull/482 locally
2. pnpm install
3. pnpm run dev
5. Login and see the error in the console

**Expected behavior**

4.1.0 should work as 4.0.0

**Screenshots**

![Screenshot 2022-05-23 at 12 54 30](https://user-images.githubusercontent.com/5749437/169804794-0c6280b2-149f-41fc-8652-69868ee8fb75.png)

**Additional context**

Most likely related to https://github.com/hirosystems/stacks.js/pull/1255

**Comment by janniks** [comment]
Thanks for the report, I‘ll look into this immediately!

**Comment by janniks** [comment]
Could you check if this is fixed in `4.2.0-beta.3` ? @pradel 🙏

**Comment by pradel** [comment]
@janniks yeah it's working!

**Comment by janniks** [comment]
📦 fixed in `4.1.2`
