### ISSUE TITLE
Provide a command for exporting an identifier's key pair

### ISSUE THREAD

**Issue by csuwildcat** [stx-labs/stacks.js#127]
User Story:

As a user who has registered an identifier, I would like to export and secure my private key outside of the Blockstack CLI's Docker instance.

Proposed Solution:

Please create a CLI command for exporting an identifier's key pair so it can be moved to the host machine or another device.

**Comment by csuwildcat** [comment]
Hey @jcnelson (that's so Beatles!),

Any reason why you can't include that Python script as one rudimentary way to get the keys for a name?

**Comment by jcnelson** [comment]
Hi @csuwildcat,

Have you seen the `blockstack wallet` command in the latest version from PyPI?  It exports the private keys and addresses in an easy-to-read format.

**Comment by csuwildcat** [comment]
Wasn't aware, I'll check it out - is that currently built into the latest
Docker image Muneeb pushed out? If not, can you get him to spin a build?

**Comment by jcnelson** [comment]
I'm guessing this is working now.  Closing the issue in this repo.  Please re-open in the blockstack-core repo if the problem persists.  Thanks!
