### ISSUE TITLE
Missing pollyfill dependencies when upgrading to @stacks/connect

### ISSUE THREAD

**Issue by mijoco-btc** [stx-labs/stacks.js#1274]
**Describe the bug**
npm install @stacks/connect ^6.? and then running vue application results in 

These dependencies were not found:

* @stacks/common/dist/polyfill in ./node_modules/@stacks/auth/dist/polyfill/index.js, ./node_modules/@stacks/connect/node_modules/@stacks/network/dist/polyfill/index.js and 1 other
* @stacks/encryption/dist/polyfill in ./node_modules/@stacks/auth/dist/polyfill/index.js
* @stacks/network/dist/polyfill in ./node_modules/@stacks/auth/dist/polyfill/index.js, ./node_modules/@stacks/transactions/dist/polyfill/index.js

**What version of Stacks.js are you using?**
@stacks/connect ^6.8.1 - latest as of now

**Is the bug present in the Stacks.js CLI, Gaia hub, Connect or Blockstack Browser?**
Connect for sure

**To Reproduce**

vue-cli create new-app
npm install @stacks/connect

in the code
`import { AppConfig, UserSession, authenticate, showConnect } from '@stacks/connect'`

then npm run serve - NB haven't checked if its one of above individual imports.

**Expected behavior**

**Screenshots**

**Console log**
If applicable, add console log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I rolled back to "@stacks/connect": "^6.4.0", and it worked.

**Comment by janniks** [comment]
Thanks for the report 🙏
This should be fixed in the latest `connect` — can you try updating to the following?
```
    "@stacks/connect": "6.8.2",
    "@stacks/connect-react": "17.0.2",
```
