### ISSUE TITLE
add sip018 tests

### ISSUE THREAD

**Issue by janniks** [stx-labs/stacks.js#1281]
add tests with test vectors from sip018 https://github.com/MarvinJanssen/sips/blob/feat/signed-structured-data/sips/sip-018/sip-018-signed-structured-data.md

**Comment by beguene** [comment]
@janniks FYI I am working on updating our wallet with SIP018 https://github.com/hirosystems/stacks-wallet-web/issues/2460. As part of this I am currently adding some methods to stacks.js to handle encoding/decoding + signingStructuredData functions to stacks.js
I will put up a PR soon I can also add those tests vectors if you did not work on it yet.

**Comment by janniks** [comment]
perfect, thanks 🙏
