### ISSUE TITLE
Read only call don't work

### ISSUE THREAD

**Issue by ilyabukalov** [stx-labs/stacks.js#1293]
client version: @stacks/transactions": "4.0.0".
Clarinet devnet backend: 0.30.0

There is very simple code in the contract
```
(define-constant HEAP_INDICES
  (list
    u1
    u2  u3
    u4  u5  u6  u7
    u8  u9 u10 u11 u12 u13 u14 u15
   u16 u17 u18 u19 u20 u21 u22 u23 u24 u25 u26 u27 u28 u29 u30 u31))

(define-read-only (get-orders)
  (ok (map get-position HEAP_INDICES)))
(define-read-only (get-position (index uint))
  (default-to {price: u0, value: u0} (map-get? heap {index: index})))
```
In function  **get-orders**  I just need to extract and return simple list out of internal contract storage, this is the goal.
Whenever calling **get-orders** as read only function it throws the error:
```
Error: Unchecked(CostBalanceExceeded(ExecutionCost { write_length: 0, write_count: 0, read_length: 10021, read_count: 31, runtime: 11790000 }, ExecutionCost { write_length: 0, write_count: 0, read_length: 100000, read_count: 30, runtime: 1000000000 }))
```
When I do more experiments and change the function signature to public:
```
(define-public (get-orders)
  (ok (map get-position HEAP_INDICES)))
```
Then calling it as normal function through signing transaction I am finally able to see the return value upon transaction confirmation. 

**Expected behavior**
Not sure why it needs to execute transaction (paying for gas + consensus validation) if the actual states don't change. To rephrase: why and for what are there any gas requirements and checks - if the storage is finally unchanged? Could you please clarify on that? Or let me know please if I am doing anything wrong
Thank you :)

**Comment by ilyabukalov** [comment]
Thank you for the clarification in discord. I appreciate. The direction is clear now. Since the computation of 
```
(define-public (get-orders)
  (ok (map get-position HEAP_INDICES)))
```
is going to be beyond threshold for read only zero cost calls we have decided to make it a public transaction call since it is not avoidable anyway.
But I think there is still an issue related purely to unit testing through ```clarinet test```:
1. The transaction **get-orders** passes correctly without problems but the return value is impossible to parse since it is returned as the plain ```typeof string``` like ```[{price: u1, value: u10}, {price: u0, value: u0}...```,. It pretends to be a JSON but without correct quotation it is in fact broken non-parsable format. 
2. Executing both chain.callReadOnlyFn and (mineBlock & Tx.contractCall). They return the same
3. .expectOk().expectTuple() does not recognise this plain string as well. 
4. I think the issue is related to the nested objects because we use ```list [object, object, object ]``` structure instead of just only one object-map (tuple type).

It is the first ever time we have used ```list``` as return value in our codebase. That's why rising this question to be double sure whether we are on the correct direction. Could you please clarify what is the feature/bug in this our case?

**Comment by friedger** [comment]
In the function, you have a map call that returns a list, therfore, you need to check using `expectOk().expectList()` and then iterate through the resulting list.

**Comment by ilyabukalov** [comment]
Perfect. Thank you. The issue resolved! :)
