### ISSUE TITLE
Version mismatch, 1.5.2 != 1.7.0 while installing from pip

### ISSUE THREAD

**Issue by vsund** [stx-labs/stacks.js#130]
I tried to install blockstack from pip with `pip install blockstack --upgrade` which ended in an `AssertionError: version mismatch, 1.5.2 != 1.7.0`.

After installing `cffi` version 1.5.2 with `pip install cffi==1.5.2` the installation succeeded.

See full output (from all three commands) [here](https://github.com/blockstack/blockstack-cli/files/428482/output.txt).
Useful additional information about the system are [here](https://github.com/blockstack/blockstack-cli/files/428429/system.txt).

**Comment by jcnelson** [comment]
That's odd.  I'm glad you got it to work.  Is this still happening?  If so, please re-open the issue in the blockstack-core repo.  Thanks!
