### ISSUE TITLE
TODO example doesn't work

### ISSUE THREAD

**Issue by chrisbward** [stx-labs/stacks.js#1301]
Followed the tutorial on https://blog.blockstack.org/hello-blockstack-tutorial/

At no point is the supported NodeJs version mentioned in this repo, so went with v16.15.0;

```
➜  hello-blockstack yo blockstack
? ==========================================================================
We're constantly looking for ways to make yo better! 
May we anonymously report usage statistics to improve the tool over time? 
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== No

     _-----_     ╭──────────────────────────╮
    |       |    │      Welcome to the      │
    |--(o)--|    │      Blockstack app      │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What type of project scaffolding do you want to generate? (Use arrow keys to 
select and press ENTER) React
   create package.json
   create .gitignore
   create .env.development
   create cors/_headers
   create cors/_redirects
   create cors/firebase.json
   create src/styles/style.css
   create src/index.js
   create src/App.js
   create src/Profile.js
   create src/setupProxy.js
   create src/Signin.js
   create public/favicon.ico
   create public/index.html
   create public/manifest.json
   create README.md
   create public/white-logo.svg


I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.


npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: hello-blockstack@0.0.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.8.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.31.1" from @blockstack/connect@2.12.7
npm ERR! node_modules/@blockstack/connect
npm ERR!   @blockstack/connect@"^2.7.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-06-25T14_40_34_343Z-debug-0.log

```

**Comment by sabbyanandan** [comment]
Hi, @chrisbward! I'd be curious to know how you have discovered the blog. It appears you've bumped into an older blog and the demo described in the blog is something we don't maintain.

Either way, please check out the [Tutorials](https://docs.hiro.so/tutorials) and [Examples Apps](https://docs.hiro.so/example-apps) instead. We will also refresh this collateral very soon, but this should get you started for now.

**Comment by sabbyanandan** [comment]
@chrisbward: Some of the example apps have a transitive dependency collision/issue, and we are addressing them through https://github.com/hirosystems/docs/issues/119. 

Apologies for not giving you a smoother onboarding experience with the listed examples. This is a top priority for us, and we will address the gaps. Thank you for your patience.

I will keep this open until we have the app refreshed, so you can give it a go on your end.

**Comment by sabbyanandan** [comment]
@chrisbward: The tactical improvement, including the Node-specific instructions, are now applied to the [examples](https://docs.hiro.so/example-apps). Unfortunately, it took so long to get sorted out, given the dated examples and the related dependency chain. We will get better at these going forward. And more improvements to docs.hiro.so are on their way in Q3, as well.

If you have any other feedback, please comment on this issue.
