### ISSUE TITLE
Vanilla JavaScript hello world yeoman generator non-starter

### ISSUE THREAD

**Issue by chrisbward** [stx-labs/stacks.js#1302]
hello-blockstack-again yo blockstack

     _-----_     ╭──────────────────────────╮
    |       |    │      Welcome to the      │
    |--(o)--|    │      Blockstack app      │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What type of project scaffolding do you want to generate? (Use arrow keys to 
select and press ENTER) Plain JavaScript
   create package.json
   create .gitignore
   create webpack.config.js
   create netlify.toml
   create firebase.json
   create amplify.yml
   create dist/app.css
   create dist/bootstrap.min.css
   create dist/avatar-placeholder.png
   create dist/index.html
   create dist/robots.txt
   create dist/manifest.json
   create dist/favicon.ico
   create dist/white-logo.svg
   create src/index.js

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: hello-blockstack-webpack@0.0.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.13.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.31.1" from @blockstack/connect@2.12.7
npm ERR! node_modules/@blockstack/connect
npm ERR!   @blockstack/connect@"^2.4.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-06-25T15_07_35_118Z-debug-0.log

**Comment by sabbyanandan** [comment]
I wanted to share the same comment as https://github.com/hirosystems/stacks.js/issues/1301#issuecomment-1166309800.

**Comment by sabbyanandan** [comment]
Duplicates #1301.
