### ISSUE TITLE
verifyMessageSignature() Returning FALSE after successfulling signing message

### ISSUE THREAD

**Issue by dr-bizz** [stx-labs/stacks.js#1307]
**Describe the bug**
On our website, we require users to sign a message once logged in to get access to a certain area of our website. The signing works for almost all users, but one user is having issues.

To sign the message, we use openSignatureRequestPopup(), and onFinish, we use the verifyMessageSignature() to verify if the message was signed correctly. For most users, it returns TRUE when successfully signed, but for one user it's returning FALSE.

I've had a few calls with this user to debug, but I can't see anything wrong with what I'm doing, so I'm assuming something is going wrong with the verifyMessageSignature() function.
I pass in the message, publicKey & signature into the verifyMessageSignature() function. I've ensured that the message is the same when signing and verifying the message signature.
Here is the below code:
```
import { StacksMainnet } from '@stacks/network';
import { openSignatureRequestPopup } from '@stacks/connect'
import { verifyMessageSignature } from "@stacks/encryption";
let message = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.e30.UFUdF2nITPHwEj6Yc3SG_EQIxjRe70e3MiqmtPj5YAVdaKyHdJqUgCKv3HepZylbUDH-ZdYD8HnWfOhMhgGXXw"
const txOptions = {
    message,
    network: new StacksMainnet(),
    appDetails: {
      name: "Byzantion",
      icon: 'https://byzantion.xyz/logo-icon.svg'
    },
    onFinish: async (data) => {
      const verified = await verifyMessageSignature({ message, publicKey: data.publicKey, signature: data.signature });
      if (verified) {
        console.log("User validated",verified)
      } else {
        console.log("User isn't validated",verified)
      }
    },
  };
  await openSignatureRequestPopup(txOptions)
```

**What version of Stacks.js are you using?**
"@stacks/auth": "^4.2.2",
"@stacks/common": "^4.0.0",
"@stacks/connect": "^6.4.0",
"@stacks/encryption": "^4.0.0",
"@stacks/network": "^4.2.0",
"@stacks/storage": "^4.2.0",
"@stacks/transactions": "^4.2.0",
**Is the bug present in the Stacks.js CLI, Gaia hub, Connect or Blockstack Browser?**
Yes
**To Reproduce**
I can't replicate the error, only the user who has the issue is facing the problem. On my wallet and my colleagues, it signs and verifies the message correctly.

**Expected behavior**
As the user is signing with the correct wallet and the message that is being signed isn't changing, the verifyMessageSignature() function should return TRUE.

**Screenshots**

**Console log**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by janniks** [comment]
Hi 👋 Do you have the public key, message, and signature that fails to verify?

**Comment by dr-bizz** [comment]
**PublicKey:**
"037047e167a988d9075d5d5a090c161bdef83643b01fb974d24804dd229cd03d62"

**signature:** "c7e7e95e524255da65f816bfd635079007999f7de21aad1bac6922a969a1ee8b7f89ee9bbf0cc56d39973dd1d59a8f6147227290f0c8b286adc28dff93015f0b01"

**Message**
"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.e30.Mi_dV9VtSnHZ41aVIeQ8Nr2-q4X30Su_Z9fniwGNdjvKhd_CT6ttjtDmWftnUvclvj7EPZtgnZMBVYfys_2DFQ"

**Comment by janniks** [comment]
Hmm, very interesting — could you also provide the same information for a case that works?

**Comment by anilasdev** [comment]
It used to work 3 days ago, but stopped working now.

**Comment by pradel** [comment]
I am having the same issue, for an app that was previously working before it stopped working after the latest release of the wallet see https://discord.com/channels/621759717756370964/745197302255321108/993447956759973978

**Comment by kyranjamie** [comment]
It looks like we need to publish the latest `@stacks/encryption` that includes the `verifyMessageSignatureRsv` method. We should then update all docs/blog posts to use this method instead.

**Comment by dr-bizz** [comment]
> It looks like we need to publish the latest `@stacks/encryption` that includes the `verifyMessageSignatureRsv` method. We should then update all docs/blog posts to use this method instead.

I have tried the `verifyMessageSignatureRsv` method and it too returns FALSE.

**Comment by markmhendrickson** [comment]
> It looks like we need to publish the latest @stacks/encryption that includes the verifyMessageSignatureRsv method. 

@janniks is this something for you to take on here?

**Comment by janniks** [comment]
I'll be in the office soon to verify and will release main's latest changes.

**Comment by kyranjamie** [comment]
I was mistaken, the method is exported. See conversation here https://discord.com/channels/621759717756370964/745197302255321108/993802738800545792

**Comment by dr-bizz** [comment]
> I have tried the `verifyMessageSignatureRsv` method and it too returns FALSE.

Sorry, I was wrong. It is working. I'm verifying the signature on the front-end and back-end and I forgot to update the backend function to use the `verifyMessageSignatureRsv` method.

Thank you for the support!
