### ISSUE TITLE
Regression in @stacks/profile from 4.1.0 to 4.3.0 - Expected input type is Uint8Array (got object)

### ISSUE THREAD

**Issue by pradel** [stx-labs/stacks.js#1309]
**Describe the bug**

There is a regression in the @stacks/profile package when upgrading from 4.1.0 to 4.3.0.

I created a branch in the Sigle repo to demonstrate the error. Tests which are working fine on the main branch are now failing when the profile package is updated with the following error.

```
      [ERROR] resolveZoneFileToProfile: error fetching token file https://gaia.blockstack.org/hub/1NDUWuxbtFyfUyq3tNbgJKiHptVJWjNePa/profile.json: TypeError: Expected input type is Uint8Array (got object)

      at Function.error (../node_modules/.pnpm/@stacks+common@4.3.0/node_modules/@stacks/common/src/logger.ts:20:13)
      at ../node_modules/.pnpm/@stacks+profile@4.3.0/node_modules/@stacks/profile/src/profile.ts:377:18
```

Here is the branch https://github.com/sigle/sigle/pull/586.

**What version of Stacks.js are you using?**

@stacks/profile 4.3.0

**To Reproduce**

1. Clone the sigle repository https://github.com/sigle/sigle
3. Checkout the feature/stacks-profile-regression branch
4. Go to the sigle folder `cd sigle`
5. install deps `pnpm install`
6. run tests `pnpm tests`
7. See error

**Expected behavior**

The tests should pass

**Console log**

```
    console.error
      [ERROR] resolveZoneFileToProfile: error fetching token file https://gaia.blockstack.org/hub/1NDUWuxbtFyfUyq3tNbgJKiHptVJWjNePa/profile.json: TypeError: Expected input type is Uint8Array (got object)

      at Function.error (../node_modules/.pnpm/@stacks+common@4.3.0/node_modules/@stacks/common/src/logger.ts:20:13)
      at ../node_modules/.pnpm/@stacks+profile@4.3.0/node_modules/@stacks/profile/src/profile.ts:377:18
```

**Comment by janniks** [comment]
Thanks for the reproduction, going through it now!

**Comment by janniks** [comment]
Annoying one to track down — but it looks like this is a bug in `jsdom`. They have their own implementation of Uint8Array and it doesn't work for a check used in `@noble/...`

Related: https://github.com/facebook/jest/issues/9993 https://github.com/facebook/jest/issues/9983

Not sure how to best resolve this one 😕

[This is how we moved to `node` testenv and resolved resulting failures →](https://github.com/hirosystems/stacks-wallet-web/pull/2333/files#diff-b5aeea8016ea298afcfd850a4e64eeb73d5b66698e7439aebd82efde19c9554f)

**Comment by pradel** [comment]
Thanks for looking into it @janniks, curious what changed that caused the issue, tried many things and managed to make it work by adding 

```
/**
 * @jest-environment node
 */
```

at the beginning of the failing tests

**Comment by janniks** [comment]
The @noble dependency we switched to uses an `instanceof` check with Uint8Array. In jsdom that doesn't work correctly, because they implemented their own version of Uint8Array, which is more like a global object than an actual type.

**Comment by pradel** [comment]
Thanks!
