### ISSUE TITLE
Add initializer site for create-stacks

### ISSUE THREAD

**Issue by janniks** [stx-labs/stacks.js#1316]
- [x] Complete building https://github.com/hirosystems/docs/pull/107
- [x] Add analytics to framework & feature select
- [x] Where does this site go?
  - docs.hiro
  - ~separate site~
- [ ] Get sign-off design/marketing team

**Comment by janniks** [comment]
@sabbyanandan are there any changes planned for docs.hiro.so? Do we have a good location for the initializer site?

**Comment by janniks** [comment]
![Screen Shot 2022-08-24 at 16 02 17](https://user-images.githubusercontent.com/6362150/186438678-547af931-4690-4bb3-84c8-d88c976c26ae.png)

@eugeniadigon we're planning on introducing a new form to the docs.hiro site ([live demo](https://hiro-systems-docs-git-add-mvp-starter-form-blockstack.vercel.app/stacksjs-starters))
Do you have any thoughts on the design? Should we add an illustration / graphic elements? 🎨

**Comment by sabbyanandan** [comment]
> @sabbyanandan are there any changes planned for docs.hiro.so? Do we have a good location for the initializer site?

Hi, @janniks. I'd want us to host this more prominently on the Docs, and eventually when we redo the hiro.so site, we can link there also. We may have to style it to match the Docs theme, though. I am leaning towards idea-1, but happy to hear any other thoughts.

----

A few ideas: 

idea-1) Collapse all developer resources in a dropdown, and add a line-item for the starters.
![image](https://user-images.githubusercontent.com/1562654/186463149-512b3fa1-5c8c-4017-a715-d27dbd4fcf7b.png)

----

idea-2) Makes it more prominent, but also more chatty on the header. 
![image](https://user-images.githubusercontent.com/1562654/186463812-f77a8668-93ac-4310-a6db-864dea14c2b6.png)

**Comment by saralab** [comment]
@sabbyanandan  : 
Option 1 works better IMHO. Albeit I would place the Starter Templates at the top of that drop down. 

Option 2 ,+1 that it looks chatty and is also unclear what the "Starter Templates" are without the stacks.js prefix. My default thought was "Starter Templates for Smart Contracts"

**Comment by janniks** [comment]
✅ Went with ~Option 1: https://hiro-systems-docs-git-add-mvp-starter-form-blockstack.vercel.app/stacksjs-starters
