### ISSUE TITLE
Cannot materialize contract calls with fungible tokens other than STX

### ISSUE THREAD

**Issue by paradigma-cl** [stx-labs/stacks.js#1319]
**Describe the bug**
makeStandardFungiblePostCondition function always return postcondition error

**What version of Stacks.js are you using?**
Latest
**Is the bug present in the Stacks.js CLI, Gaia hub, Connect or Blockstack Browser?**
It is in the @Stacks/transactions

**To Reproduce**

 const fungibleAssetInfo = createAssetInfo(
        keys_recipient,
        crypto_token.toUpperCase()
      );

      options = {
        contractAddress: contract_address,
        contractName: contract_name,
        functionName: "transfer",
        network: serverStacksX2,
        postConditionMode: PostConditionMode.Allow,
        **standardFungiblePostCondition:** [
          makeStandardFungiblePostCondition(
             keys_sender,
             FungibleConditionCode.LessEqual,
             new BigNum(amountTotal),
             fungibleAssetInfo
          ),
        ],
        functionArgs,
        appDetails: {
          name: '',
          icon: ,
        },
        onFinish: data => {
 
        },
      };
    }
    await openContractCall(options)

When calling the contract using tokens and sip11 contracts, returns the following error:
This transaction did not succeed because the transaction was aborted during its execution.

**Expected behavior**
It should work in a similar way as the standardSTXPostCondition function

**Additional context**
We are trying to execute contracts that use different types of tokens additionally to STX to make their payments.

**Comment by janniks** [comment]
Could you provide more details on the smart contract (address, function name) you’re running? Or the txId of a transaction that failed?

**Comment by paradigma-cl** [comment]
Here are 2 examples:
https://explorer.stacks.co/txid/0xe213edbb91b5c09daa3959533dbdcbbdc4f231a4c8985cd1b77750353a4ac272?chain=mainnet

https://explorer.stacks.co/txid/0x32ef4188a347e37f12728f7b2b9248dd9d7552403dff690a90f422c2849c8eed?chain=mainnet

**Comment by janniks** [comment]
It seems the transaction is using an incorrect nonce:
```
Transaction rejected from mempool, {"error":"transaction rejected","reason":"BadNonce","reason_data":{"actual":36,"expected":38,"is_origin":true,"principal":"SP31C1RGYVJVWNYWJNRVSZQA2XN9HDEA08FB0G03S"},"txid":"e213edbb91b5c09daa3959533dbdcbbdc4f231a4c8985cd1b77750353a4ac272"} 
```

Also the `try! (ft-transfer?` can result in an err, which is returned in this case (insufficient funds). [→ ft-transfer?](https://docs.stacks.co/docs/write-smart-contracts/clarity-language/language-functions#ft-transfer)

We're working on getting better error messages in the explorer to make this easier to debug!

**Comment by paradigma-cl** [comment]
Now it is working, thank you very much!
