### ISSUE TITLE
Compatibility with web containers

### ISSUE THREAD

**Issue by kyranjamie** [stx-labs/stacks.js#1322]
Maybe an issue for https://github.com/hirosystems/stacks.js-starters ?

I've been trying to use [Stackblitz](https://stackblitz.com/) and [Codesandbox](https://codesandbox.io/) to make shareable demos, debug issues etc.

They're incredibly helpful, though for a couple reasons, they don't play that well with Stacks packages

- **Polyfilling `Buffer`**: The age old issue, but this is a barrier to getting some apps working. Requires extra config
- **Packaging issues**: [See example of how it runs into error thrown from `@nobel/hashes`](https://stackblitz.com/edit/typescript-zdwzjj?file=index.ts) attempting to pull from `index.js` which throws error

Some of these issues could lie with the apps themselves, so perhaps fixing isn't trivial. Though, if we could offer stacks.js ready containers, that'd be a huge dev productivity win imo.

**Comment by janniks** [comment]
Seems to be a noble-hashes feature that Stackblitz doesn't play well with
- https://github.com/stackblitz/core/issues/1987

**UPDATE**: Resolved on StackBlitz's end
