### ISSUE TITLE
Add Subnets Support for stacks.js

### ISSUE THREAD

**Issue by saralab** [stx-labs/stacks.js#1324]
- Handle new events, add network id for hyperchains, to reflect the changes on API. 
- Related Issue: https://github.com/hirosystems/stacks-blockchain-api/issues/1237

**Comment by janniks** [comment]
On hold, will revisit with API team once 2.1 is code-complete and new withdrawal endpoints exist.

**Comment by janniks** [comment]
Latest demos/tests w/ the wallet look good. Closing
