### ISSUE TITLE
Misleading post-condition behavior

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#1326]
Hi,

The post-condition codes for NFTs are misleading.  The blockchain's post-condition processor does not check whether or not an NFT is owned or not owned.  It checks whether or not a principal _sent_ or _did not send_ an NFT.  Post-conditions, in general, do not verify anything about the recipient of an asset; they only pertain the the sender of the asset.  If you want to verify conditions about asset recipients, you'll need to do so in Clarity.

I've had to correct at least ~~one~~ two developer blog posts and one security audit finding that left users vulnerable to NFT theft because they were incorrectly relying post-conditions to check the NFT recipient (and they both cite the use of the words `Owns` and `DoesNotOwn` to describe the expected behavior).

I think some kind of warning in the post-conditions section of the `transactions` package README is necessary to correct this misconception.  Perhaps it would also be prudent to change the variable names, but I don't know what the fall-out of that would be at this point in time.

EDIT: now it's two blog posts, and one security audit that got tripped

**Comment by janniks** [comment]
→ https://github.com/hirosystems/stacks.js/pull/1359
→ https://github.com/hirosystems/stacks.js/pull/1371
→ https://github.com/hirosystems/stacks.js/pull/1379
