### ISSUE TITLE
make_keychain uses wrong wif prefix for testnet

### ISSUE THREAD

**Issue by igorsyl** [stx-labs/stacks.js#1327]
**Describe the bug**

`make_keychain -t` generates a WIF key with an "L" prefix which corresponds to mainnet and not testnet.

Instead, a testnet WIF key should begin with a "c".

See https://en.bitcoin.it/wiki/List_of_address_prefixes

```
$ stx make_keychain -t
{
    "mnemonic": "poet crumble alpha soft boss gadget venture roast dance update awake unhappy skirt crunch gown cake deal surround supreme load crystal traffic maze crumble",
    "keyInfo": {
        "privateKey": "da210b07f0f00edd5dc4b0e862afc61a80f4be360f29a4e0a21dad5f80ccd83e01",
        "address": "ST1ED1MJ1QC18W53N710BBK1VBHK43Y2KMRHKEPA7",
        "btcAddress": "moyicrwHUVdc5Mg9roBiMH6GUaw4okhJPX",
        "wif": "L4Xj2A5CoGhdN32VW5nbwZeCP7dAAGUjxviycq3BLxxZTdjcLRBk",
        "index": 0
    }
}
```

**What version of Stacks.js are you using?**

```
$ npm list -g
+-- @stacks/cli@4.3.3
```

**Is the bug present in the Stacks.js CLI, Gaia hub, Connect or Blockstack Browser?**

Stacks.js CLI

**To Reproduce**

$ stx make_keychain -t

**Expected behavior**

Expect to generate a testnet WIF key with a "c" prefix.

**Screenshots**

**Console log**
If applicable, add console log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by janniks** [comment]
Good catch 🙏 Thanks for the report — we'll get right on that!

**Comment by igorsyl** [comment]
In addition, I was not able to import the generated testnet private key, WIF or mnemonic into testnet Electrum so the private key generation may have issues as well.
