### ISSUE TITLE
Incorrect prefix for message signing

### ISSUE THREAD

**Issue by kyranjamie** [stx-labs/stacks.js#1328]
We use the wrong phrasing for the message signing prefix:

https://github.com/hirosystems/stacks.js/blob/5ac9385069ce48bde452520d5168c84e31b5b961/packages/encryption/src/messageSignature.ts#L5-L7

Following the [Ethereum format](https://eips.ethereum.org/EIPS/eip-712#signatures-and-hashing-overview), already followed on the Ledger app, the message should be _Stacks Signed Message_, not _Stacks Message Signing_.

This is a change of length, too, so if I'm not mistaken about how the prefixing works, should be:

```
\x17Stacks Signed Message:\n
```

`"Stacks Signed Message:\n".length.toString(16) // 17`

Useful info on prefix here https://blog.ricmoo.com/verifying-messages-in-solidity-50a94f82b2ca

**Comment by friedger** [comment]
Do we have a SIP for that?

**Comment by janniks** [comment]
I don't believe there is a SIP for general message signing (with prefix for safety) yet. Only SIP-018 with a separate prefix (which might also cause problems with ledger).

_There are also more comments and information in the PR:_ https://github.com/hirosystems/stacks.js/pull/1329
