### ISSUE TITLE
consensus command without block height periodically returns null

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#133]
Running `blockstack consensus` without a block height results in a call to `getinfo` to retrieve the block height and then a call to `get_consensus_at` to retrieve the consensus hash. 

<img width="653" alt="screen shot 2016-08-29 at 9 27 25 pm" src="https://cloud.githubusercontent.com/assets/597182/18053225/ffb42bc6-6e30-11e6-9258-53091ac0a67b.png">

If the two RPC calls are handled by separate blockstack-core instances (behind a load balancer, etc), the node handling `getinfo` call will periodically return a block height higher than that of the second node causing `blockstack consensus` to return a `null` consensus.

<img width="261" alt="screen shot 2016-08-29 at 2 10 18 pm" src="https://cloud.githubusercontent.com/assets/597182/18053215/f33d7438-6e30-11e6-9160-453aca3ed791.png">

This problem can be avoided by using the consensus information already provided by the `getinfo` RPC command when the user hasn't specified a block height.

See slack discussion here: http://blockstack.slackarchive.io/cli/-/1471967685/1472477412/1472477412001183/

**Comment by jcnelson** [comment]
This is fixed in 0.14.0.  If you don't pass a block height, the consensus hash in `getinfo` is returned.
