### ISSUE TITLE
Calculate approx_expiration_date based on latest blockchain state

### ISSUE THREAD

**Issue by stiell** [stx-labs/stacks.js#136]
`approx_expiration_date` is currently based on a fixed point in the blockchain and extrapolated from there without taking into account the times of later blocks. It is now about 18 days late.

This error caused me to miss the expiration date of my name, as I had assumed that the algorithm had taken into account the latest block times when I checked it a month ago and gave the renewal "only" ten days of margin.

I would expect `approx_expiration_date` to be calculated as `t + 600 * (record['expire_block'] - h)`, where `t` is the current time (if blockchain info is up to date, otherwise the time of the latest known block) and `h` is the latest known block height. For a name that has expired I would expect the `approx_expiration_date` to show the time of the block where it expired.

**Comment by jcnelson** [comment]
Hi @stiell, 

> This error caused me to miss the expiration date of my name, as I had assumed that the algorithm had taken into account the latest block times when I checked it a month ago and gave the renewal "only" ten days of margin.

Your point is well-taken.  Fortunately, names in 0.13 do not begin to expire until block 433665.  The countdown for imported names starts from the `NAMESPACE_READY`, not the import date.

> I would expect approx_expiration_date to be calculated as t + 600 \* (record['expire_block'] - h), where t is the current time (if blockchain info is up to date, otherwise the time of the latest known block) and h is the latest known block height. For a name that has expired I would expect the approx_expiration_date to show the time of the block where it expired.

This is a much better strategy.  I will implement this for 0.14.

**Comment by jcnelson** [comment]
We went ahead and removed `approx_expiration_date` since the error bars on how "wrong" this date can be have varied too widely.  We're going to have the CLI and upcoming browser automatically renew names based on the block height.
