### ISSUE TITLE
BigInt not supported on Ledger Live app

### ISSUE THREAD

**Issue by emmanuelm41** [stx-labs/stacks.js#1360]
We are currently working on Stacks integration on Ledger Live. 

The library uses js native biting implementation to handle big numbers. Unfortunately, it is not supported on older react native versions. Ledger Live Mobile is planning to upgrade the react native version they use, but in the meanwhile, the BigInt support is done by using different libraries, like BigNumberJS. BigInt cannot be polyfilled globally, as it could affect other blockchain integrations. 

Is it possible to handle big number with BigNumber.js? Or do you think is any other way to handle this situation.

**Comment by markmhendrickson** [comment]
@janniks Do you suspect BigInt could be removed as a requirement from the transactions package, or might @emmanuelm41 be better off forking and removing himself for this particular contextual usage?

This is a blocking issue for the Ledger Live Mobile integration he's working on (and we're hoping to release sometime over the next 1-2 months). So it'd be great to get your input here as soon as possible. 🙏

**Comment by janniks** [comment]
We're trying to stick to BigInt currently, and most RN projects should be able to upgrade to a JS runtime with BigInt support.

That being said, it depends on the scope of the features. An old release of Stacks.js uses bn.js and might be able to work (<=`4.0.1`). Some features like message signing were added after this.

**Comment by markmhendrickson** [comment]
Thanks for the input! The problem seems to be that we're dependent Ledger (the company) to update their JS runtime and we don't have a way to secure the update from them.

@emmanuelm41 Might you want to check a previous version and see if it works for our purposes?

**Comment by emmanuelm41** [comment]
@janniks thanks for your answer. I will test that specific version. We are not signing the tx internally actually, as the signing process is happening on the ledger HD. We are using the lib to generate the boilerplate tx object, fetching the nonce and fees, and not much more. 

@markmhx let's try that version specifically. I will let you know!

**Comment by emmanuelm41** [comment]
@janniks I have fetched the v3.5.1 and it still uses BigInt for `getNonce` function for example. Is that possible?

**Comment by janniks** [comment]
Ah, I see we were using BigInt in some places before our larger switch away from BN.js.

~Could you try if `2.0.0` works for you? This is the earliest mention I can find in our CHANGELOG.~

**EDIT:** Nevermind, just checked — that already used BigInt 🙃

**Comment by janniks** [comment]
`1.3.5` doesn't use BigInt for getNonce. This might be the point in time that works. I will go over the changelog to see if there are important changes that are missed.

Otherwise we might need to think about creating a fork of the important things for ledger live. Do you have a list of features/methods which are required?

**Comment by emmanuelm41** [comment]
This is what we are using today:
```
import {
  txidFromData,
  getNonce,
  AnchorMode,
  UnsignedTokenTransferOptions,
  makeUnsignedSTXTokenTransfer,
  estimateTransfer,
  UnsignedTokenTransferOptions,
  createMessageSignature
} from "@stacks/transactions/dist";
```

We are using  @stacks/network too, but I don't see there is a 1.3.5 version for that package. I will test the app with 1.3.5 for transactions and 3.5.1 for network and let you know!

**Comment by janniks** [comment]
👍 @stacks/transactions@`1.3.5` uses @stacks/network@`1.2.2`, so those are compatible

**Comment by janniks** [comment]
Looking at `getNonce` and `estimateTransfer` is would also be possible to use the Stacks API directly (used by those methods already). And add some custom code. (Might save some code, and might allow a more up-to-date version of Stacks.js, although I could not find any features/bugs that would cause a problem)

- [`@stacks/blockchain-api-client`](https://hirosystems.github.io/stacks-blockchain-api/client/index.html)
- [Stacks API](https://docs.hiro.so/api)
- [Stacks API: `/v2/accounts/{address}`](https://docs.hiro.so/api#tag/Accounts/operation/get_account_info) `getNonce`
- [Stacks API: `/v2/fees/transfer`](https://docs.hiro.so/api#tag/Fees/operation/get_fee_transfer) pseudo-code: `estimateTransfer() = feeRateFromAPI * transaction.serialize.byteLength`

_Let me know where I can help_

**Comment by emmanuelm41** [comment]
> @stacks/transactions@`1.3.5` uses @stacks/network@`1.2.2`, so those are compatible

@janniks I think it works with these two packages. Let me confirm it, but it seems to work well...

**Comment by emmanuelm41** [comment]
@janniks it works... but now we have another issue... this lib uses BigInt internally too

```import { c32addressDecode } from "c32check";```

I use it to check if an address is valid or not. Do we have another way to do it?

```
export const validateAddress = (input: string): ValidateAddressResult => {
  try {
    const [version, data] = c32addressDecode(input);
    return { isValid: true, data: { version, data } };
  } catch (e) {
    return { isValid: false, error: e };
  }
};
```

**Comment by janniks** [comment]
Version `1.1.3` for c32check should work. @stacks/transactions@`1.3.5` uses `1.1.1`, but anything <`2.0.0` would not use bigint (I believe)

**Comment by emmanuelm41** [comment]
Yes, you are right. It works now. Thanks!

**Comment by emmanuelm41** [comment]
Ok, everything works now. I think I can close this issue. The moment they add support to BigInt on React Native, we can update to newer libs.
