### ISSUE TITLE
Trouble compiling @stacks/common in typescript

### ISSUE THREAD

**Issue by bilalanees98** [stx-labs/stacks.js#1362]
**Describe the bug**
'NodeJSBuffer' not being recognised as a type when compiling the package in TS

Error: 'NodeJSBuffer' refers to a value, but is being used as a type here. Did you mean 'typeof NodeJSBuffer'

**What version of Stacks.js are you using?**
@stacks/common version 4.3.5

**Is the bug present in the Stacks.js CLI, Gaia hub, Connect or Blockstack Browser?**
Bug is in Stacks.js common package

**To Reproduce**

1. npm install @stacks/common
2. tsc --build
3. See error

**Expected behavior**
The build should complete.

**Screenshots**
<img width="1129" alt="Screen Shot 2022-09-27 at 11 23 34 AM" src="https://user-images.githubusercontent.com/62988673/192701065-808818b6-aa36-4058-a27b-1f50d3551013.png">

**Desktop (please complete the following information):**

- tsc -v = 4.8.3
- node -v = v16.13.2

**Additional context**
I believe this might be arising from a poly filling fix.

**Comment by janniks** [comment]
Thx for the report 🙏 The `NodeJSBuffer` is now removed.
