### ISSUE TITLE
ValidationError

### ISSUE THREAD

**Issue by gitati16** [stx-labs/stacks.js#1368]
hi, about a year ago I made a script using Stacks.js for Node to manage Gaia Store files.
I recently updated the dependencies and while I use it I get the following error:

> 'Error when uploading to Gaia hub.\n' +
>     'If you believe this exception is caused by a bug in stacks.js,\n' +
>     '      please file a bug report: https://github.com/blockstack/stacks.js/issues\n' +
>     '\n' +
>     'Error Code: validation_errorStack Trace:\n' +
>     'Error\n' +
>     '    at getBlockstackErrorFromResponse (CLI/node_modules/@stacks/storage/dist/hub.js:141:16)\n' +
>     '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
>     '    at async uploadToGaiaHub (CLI/node_modules/@stacks/storage/dist/hub.js:29:15)\n' +
>     '    at async uploadFn (CLI/node_modules/@stacks/storage/dist/storage.js:329:39)\n' +
>     '    at async Storage.putFile (CLI/node_modules/@stacks/storage/dist/storage.js:338:20)\n' +
>     '    at async Promise.all (index 0)',
>   code: 'validation_error',
>   parameter: undefined,
>   hubError: {
>     statusCode: 401,
>     statusText: 'Unauthorized',
>     message: 'Expired association token: expire time of 1642958882.618 (secs since epoch)',
>     error: 'ValidationError'
>   },
>   name: 'ValidationError'
> }

I use @stacks/storage at the latest version now available
the operation does not seem to have been compromised except for the error that appears in the console while I use it

**Comment by janniks** [comment]
Can you share more of the script (especially parts using the breaking code). Hard to debug from only the logs. It could be some authentication issue _(the 401)_, but I'm assuming nothing changed on that end?

**Comment by janniks** [comment]
Closing as stale for now
