### ISSUE TITLE
Problem exporting onename username to cli

### ISSUE THREAD

**Issue by Skorpion7777** [stx-labs/stacks.js#137]
Hi,

I've already  mentioned it in the Slack Community:
When exporting a onename username to your blockstack cli owner adress you get - after the transfer is done- an error when looking up that username it says: `failed to load user profile`

Muneeb said that it's likely, that the profile data is still signed by the old owner adress.
Now that the export from  onename finally works I think many users will try it out in the next weeks, so it would make sense to fix it asap ;)

**Comment by jcnelson** [comment]
This is probably a manifestation of [this](https://github.com/blockstack/blockstack-core/issues/240) issue.  Still testing the fix, but will deploy as soon as I'm confident it works.  Thank you for reporting it here!

**Comment by jcnelson** [comment]
Closing this issue here; we're consolidating the conversation here: https://github.com/blockstack/blockstack-core/issues/278
