### ISSUE TITLE
Failure of name-transfer transactions in @stacks/bns

### ISSUE THREAD

**Issue by bilal-waheed** [stx-labs/stacks.js#1378]
**Describe the bug**
Name transfer transactions being rolled back by a supplied post-condition.
Postconditions in buildTransferNameTx function not being met.

**What version of Stacks.js are you using?**
@stacks/bns: ^5.0.1

**Is the bug present in the Stacks.js CLI, Gaia hub, Connect or Blockstack Browser?**
@stacks/bns package

**To Reproduce**

1. Build a "transfer name" transaction using buildTransferNameTx function.
2. Sign the transaction.
3. Broadcast the transaction.
4. Copy the txid from response and look it up in https://explorer.stacks.co/
5. Observe that the smart-contract function call is successful but post conditions are not satisfied.

**Expected behavior**
The transaction should be successful, given that the name being transferred is owned by the holder of the given private-key and the recipient does not own a name previously.

**Transaction IDs**

Network: Testnet

Failed:

1. 0x8e7df8f7dd23786e7274cc9d5ae3f92b924dcfac562ba43ba427a165aa14d2b5
2. 0xba526164f9a64fa1d92c1ea7425b24af6a595e9161b3eae5aa25e67baa359376
3. 0xac31d9ebabebc08ebeb2bad7a24dfefd6a889a0bd85dff87a19c2cfdd76b31a8

Successful:

1. 0x44b3797f556a382f0699178e94340fec8b1cd81f56ce501a8f19e86a507a94ad
2. 0x55477cded5d314976850e182bbd0dc92a5c0387c4411b204d419a9b2e7eb0526
3. 0xa3e38243d6765f14c5372c690e9876652015286bd3ac76254dd9d797b8dc7c55

**Desktop (please complete the following information):**

- OS: macOS
- Browser: firefox
- Version: 105.0.3

**Additional context**
The transaction is being rolled back because the postconditions created in buildTransferNameTx function have incorrect NonFungibleConditionCode codes. The code in postConditionSender should be "NonFungibleConditionCode.Sends" (16) and in postConditionReceiver it should be "NonFungibleConditionCode.DoesNotSend" (17). After these changes, the transaction goes through successfully.

Successful transactions shared above were broadcast after switching the condition codes in postconditions.

**Comment by friedger** [comment]
The postConditionReceiver can be removed altogether.

**Comment by janniks** [comment]
Definitely a mistake I made while refactoring... 🙃 Will deploy a bugfix now — Thanks for reporting!
