### ISSUE TITLE
Document struct of database objects

### ISSUE THREAD

**Issue by muneeb-ali** [stx-labs/stacks.js#139]
@muneeb-ali commented on [Thu Oct 08 2015](https://github.com/blockstack/blockstack-registrar/issues/14)

For using the registrar, the code currently assumes that incoming registrations are stored in a DB and the registrar reads from that DB to process registrations.

The structure of the DB objects is not properly documented yet.

**Comment by jcnelson** [comment]
This is now all internally-facing.
