### ISSUE TITLE
Storage API endpoint

### ISSUE THREAD

**Issue by muneeb-ali** [stx-labs/stacks.js#140]
@jcnelson commented on [Wed Apr 13 2016](https://github.com/blockstack/blockstack-registrar/issues/62)

Add an API endpoint that will allow a client to upload their zonefile and profile information.  The endpoint should verify that the zonefile's hash is already present in the blockchain, and that the profile is signed by the key indicated in the zonefile.  This effectively makes the registrar a storage provider for the client.

**Comment by jcnelson** [comment]
This has been added in 0.0.13.2 and 0.14.0.  Blockstack-CLI 0.14.0 has driver support for this enabled by default.
