### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by yknl** [stx-labs/stacks.js#1407]
**Describe the bug**
Transactions [README](https://github.com/hirosystems/stacks.js/blob/master/packages/transactions/README.md) is out of date.

The following code example does not work in latest version:
```
// to see the raw serialized tx
const serializedTx = transaction.serialize().toString('hex');
```

**Comment by sabbyanandan** [comment]
@yknl: Thank you for reporting. 

A suggestion, @janniks; If we don't have this covered already, perhaps adding the unit/integration-test coverage to evaluate critical paths such as this would be helpful.
