### ISSUE TITLE
generateNewAccount in wallet-sdk does not work as expected 

### ISSUE THREAD

**Issue by yknl** [stx-labs/stacks.js#1408]
**Describe the bug**

`generateNewAccount` in wallet-sdk does not work as expected

[README](https://github.com/hirosystems/stacks.js/blob/master/packages/wallet-sdk/README.md)

```
import { generateNewAccount } from '@stacks/wallet-sdk';

const account = generateNewAccount(wallet);
```

After running `generateNewAccount` on a `wallet`, no new accounts are added to the list of accounts in the `wallet`.

If the intention is to not mutate the original `wallet` object, then the return type is also confusingly a new `Wallet` object, not a new `Account`.

Suggest either changing the behaviour or clarify in the documentation.

**Comment by janniks** [comment]
Yes, I believe immutability was part of the original intention: [here is a working demo](https://stackblitz.com/edit/typescript-muadg1?file=index.ts)

Will update the documentation accordingly 🙏
