### ISSUE TITLE
Consider renaming `@stacks/auth`'s `makeAuthRequest` to `makeAuthRequestToken`

### ISSUE THREAD

**Issue by edu-stx** [stx-labs/stacks.js#1419]
**Is your feature request related to a problem? Please describe.**
The "problem" here is that "making an auth request" seems to indicate that some sort of network request or other operation is performed to authenticate the user. Yet it seems no such request is made with the `makeAuthRequest` method, which simply creates a token that can later be used in the actual request.

**Describe the solution you'd like**
Rename `makeAuthRequest` to `makeAuthRequestToken` or similar. Can be a backwards compatible change by keeping the old method and marking it as deprecated.

**Describe alternatives you've considered**
n/a

**Additional context**
This is for the `@stacks/auth` package methods below,

https://github.com/hirosystems/stacks.js/blob/70830f77419e647c78462171f63973aa5b3ddc4d/packages/auth/src/userSession.ts#L111

https://github.com/hirosystems/stacks.js/blob/70830f77419e647c78462171f63973aa5b3ddc4d/packages/auth/src/messages.ts#L61

**Comment by janniks** [comment]
Yes, good call — I agree!
