### ISSUE TITLE
Add `fee` option to all functions in @stacks/stacking

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#1430]
**Is your feature request related to a problem? Please describe.**
As a pool operator for some transactions, I want to use replace-by-fees. 

**Describe the solution you'd like**
 An option for the functions on the StackingClient would help.

**Describe alternatives you've considered**
Do not use StackingClient

**Comment by janniks** [comment]
+1 — will do!

**Comment by friedger** [comment]
@janniks also a nonce option would be needed, e.g. for revokeDelegateStx
