### ISSUE TITLE
Add 4,5,6, to AddressHashMode for 2.1

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#1431]
**Is your feature request related to a problem? Please describe.**
As pool admin, I would like to use a segwit address

**Additional context**

https://github.com/hirosystems/stacks.js/blob/25032e046b309bc61644830d9381ff1fe956a149/packages/transactions/src/constants.ts#L92 

The spec is here: https://github.com/stacksgov/sips/blob/a7f2e58ec90c12ee1296145562eec75029b89c48/sips/sip-015/sip-015-network-upgrade.md

**Comment by janniks** [comment]
We split the enums to separate Stacks and Bitcoin. Does using this enum work for you: https://github.com/hirosystems/stacks.js/blob/489fa29cfb4b26702b3ef308916ffb8d73d164f7/packages/stacking/src/constants.ts#L2-L17
