### ISSUE TITLE
[2.1 TESTNET BUG] calling stack-aggregation-commit fails

### ISSUE THREAD

**Issue by timstackblock** [stx-labs/stacks.js#1445]
## Describe the bug

When calling stack-aggregation-commit for the next cycle on the 2.1 testnet we get a failed transaction. 5,200,106.00 STX are ready for that cycle which should be enough for this to work. Can you please tell me why this is erroring.

<img width="1293" alt="Screen Shot 2023-02-02 at 9 09 49 AM" src="https://user-images.githubusercontent.com/49165468/216347255-0bd129ba-a91c-42e4-9379-62778b351828.png">

## Steps To Reproduce

I have delegated my STX to ST21815DY1QZWV6NAPCDE54BMHE10WK8HB2QXBNDT the first round  of stacking was successful but we are running into the following error and I am not sure why this is failing

https://2-1-api.testnet.hiro.so/extended/v1/tx/0x2c0fe342f09fd0447d702e2497ef9720669e1dd68f2cf37166a0dbea4d2f165c?unanchored=true

@friedger can you add some additional context.

**Comment by zone117x** [comment]
Is this issue intended for the API repo? The API does not construct txs (see stacks.js repo for that) and it only reports tx status received from the stacks-node (see stacks-blockchain repo for that).

**Comment by timstackblock** [comment]
thanks @zone117x moving it to stacks.js

**Comment by zone117x** [comment]
You might also want to include the method/scripts you used for constructing the tx.

**Comment by friedger** [comment]
The call was to `pox`, not `pox-2`

**Comment by friedger** [comment]
Is `(err none)` the expected behaviour?

**Comment by zone117x** [comment]
@janniks isn't the `2-1-api.testnet.hiro.so` testnet well into period 3, where `pox` (v1) is fully disabled?

**Comment by janniks** [comment]
`(err none)` I believe is expected when the blockchain is blocking the old contract (will try to find the blockchain issues/pr). Will investigate what's going on with perdiod detection.

**Comment by janniks** [comment]
[`(err none)`](https://github.com/stacks-network/stacks-blockchain/issues/3423#issuecomment-1341124244) is expected in [some](https://github.com/stacks-network/stacks-blockchain/issues/3328) [cases](https://github.com/stacks-network/stacks-blockchain/issues/3500) -- not great for debugging...

When in `Period 3`, `.pox` calls will fail (as we're in a `.pox-2` cycle)

How was the tx constructed (e.g. which @stacks/stacking version)? Using latest @stacks/stacking the best pox contract to use is determined automatically. And from a local test right now it seems to be working as intended.

**Comment by friedger** [comment]
The tx was created manually

**Comment by janniks** [comment]
Thx 🙏 Closing this for now
