### ISSUE TITLE
Support StackingClient for contract principals

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#1456]
### What version of Stacks.js are you using?

6.1.0

### Describe the bug
Some functions (like getStatus) fail for stackers that are contract principals due to calling standardPrincipalCV with a string that contains a dot.

#### How to reproduce
```js
const client = new StackingClient("SP2HNY1HNF5X25VC7GZ3Y48JC4762AYFHKS061BM0.stacking-contracts`) 
await client.getInfo();
```

#### Expected behavior
Same behavior as for standard principals

### Additional context
I used the stacking client for Friedger Pool. Recently, the city coin treasuries joined the pool.

**Comment by friedger** [comment]
This is blocking https://github.com/hirosystems/btcweb3/issues/29

**Comment by janniks** [comment]
Thanks for the bump, I’ll try to fix today.
