### ISSUE TITLE
Optional input value not correctly encoded

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#1465]
### What version of Stacks.js are you using?
    "@stacks/transactions": "4.1.0",

### Describe the bug

I am using encodeClarityValue with optional(uint) and value "" and receive u0

#### How to reproduce

Try explorer sandbox with pox-2 allow contract caller function.

#### Expected behavior

The result should be `none`

### Additional context
https://github.com/hirosystems/explorer/issues/956

**Comment by janniks** [comment]
Not sure what you're trying to do here. The `encodeClarityValue` is used for contract abi checking. Do you have an example that fails? (for the explorer issue, I believe it's a frontend bug)

This might be a test in the stacks.js codebase (RE discord)
```ts
import { encodeClarityValue } from '../src';

describe('encodeClarityValue', () => {
  test('does not supprt optional encoding', () => {
    expect(() =>
      encodeClarityValue({ optional: { 'string-utf8': { length: 5 } } }, '"foo"')
    ).toThrow();
  });
});
```

**Comment by sabbyanandan** [comment]
@friedger: Hi! I was reviewing this, and I wanted to ask if you are still having issues with it or we can close.

**Comment by friedger** [comment]
It is not an explorer bug. The fix to the explore was to implement encodeOptional. The fix should be part of stacks.js

```
export const encodeOptional = (optionalType: ClarityAbiType, value: NonTupleValueType) => {
  if (value) {
    return someCV(encodeClarityValue(optionalType, value.toString()));
  } else {
    return noneCV();
  }
};
```
See https://github.com/hirosystems/explorer/commit/d41f0cd2968b03adcd2fcd6277fbf164d1801dcf

**Comment by friedger** [comment]
If encodeClarityValue does not support optionals it should be clearly stated in the documentation.
