### ISSUE TITLE
Is the attachment in the broadcastRawTransaction method necessary?

### ISSUE THREAD

**Issue by 247521776** [stx-labs/stacks.js#1469]
![image](https://user-images.githubusercontent.com/13410975/228117068-548f3fc5-d0a9-441c-b751-28866bb3f0f9.png)
![image](https://user-images.githubusercontent.com/13410975/228117106-5bd54be9-2356-41f8-b196-45b06399a11d.png)

When broadcasting transactions, no attachment is given, will there be any hidden problems?

**Comment by friedger** [comment]
Attachements are not required. An attachment is additional data that can be shared off-chain via the atlas network.

BNS is using attachments to share the zone files of bns names.

**Comment by janniks** [comment]
Nope, no problems. `attachment` is optional. @friedger's comment covers it well 👍
