### ISSUE TITLE
Add support for more Transaction Types

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#1472]
### Problem

For transactions explorer has defined various types. These should be added to @stacks/transactions for better type safety.

### Solution

Export https://github.com/hirosystems/explorer/blob/main/src/common/types/tx.ts in transactions

### Additional context
This came up while trying to extract a component for a network switcher via query params
https://github.com/Trust-Machines/sbtc-bridge-web/issues/80#issuecomment-1498528786

**Comment by janniks** [comment]
Looking into it.. Which methods/types do you need specifically? Is it enough to import them from `@stacks/stacks-blockchain-api-types` ?

**Comment by scottsolowild** [comment]
Closing for now. Please reopen if still relevant @friedger.
