### ISSUE TITLE
CLI returns 404 error when requesting balance

### ISSUE THREAD

**Issue by timstackblock** [stx-labs/stacks.js#1481]
The CLI is failing after each command here are a few of the errors that are coming back

```
tw@Ts-MacBook-Pro ~ %  stx -t balance ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J
{ status: 404, error: 'Not Found' }

```

```
tw@Ts-MacBook-Pro ~ % stx -t send_tokens ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J 12345 999 3248 fd3609e8b9352facf360c950d362afe8f0f108b9041750f54b017efc479efeb001
Error: Failed to broadcast transaction: invalid json response body at http://testnet-master.blockstack.org:20443/v2/transactions reason: Unexpected end of JSON input
```

**Comment by diwakergupta** [comment]
@timstackblock this URL is no longer valid `http://testnet-master.blockstack.org:20443/v2/transactions`

@janniks looks like we need to update this constant:
`packages/cli/src/argparse.ts:const PUBLIC_TESTNET_HOST = 'testnet-master.blockstack.org';`

I also see a bunch of other blockstack.org URLs in the codebase that we should audit, and update to default to hiro.so URLs while we're at it now that the domain migration is done.

**Comment by janniks** [comment]
Yep, on it -- going through all blockstack urls in code and docs

**Comment by scottsolowild** [comment]
@janniks to merge & mark done.
