### ISSUE TITLE
Publish packages with `--provenance` flag

### ISSUE THREAD

**Issue by kyranjamie** [stx-labs/stacks.js#1486]
https://github.blog/2023-04-19-introducing-npm-package-provenance/

New NPM feature let's you verify the bundled package matches the source. Would be great to have this set up for stacks packages.

**Comment by janniks** [comment]
Would be cool to add, right now it's not possible with lerna 😞 https://github.com/lerna/lerna/issues/3657
May re-open later

**Comment by JamesHenry** [comment]
FYI https://github.com/lerna/lerna/issues/3657#issuecomment-1535284598
