### ISSUE TITLE
How to solve 'abort_by_post_condition'.

### ISSUE THREAD

**Issue by Jackwumingjie** [stx-labs/stacks.js#1506]
Use the stack.js to send the alex. the code:
`import {
    makeContractCall,
    broadcastTransaction,
    AnchorMode,
    FungibleConditionCode,
    makeStandardFungiblePostCondition,
    bufferCVFromString,
    createAssetInfo,
    uintCV,
    standardPrincipalCV,
    optionalCVOf,
    serializeLPList,
  } from '@stacks/transactions';
  import { StacksMainnet } from '@stacks/network';
  import { bytesToHex} from '@stacks/common';
  
  async function run(){
    // for mainnet, use `StacksMainnet()`
    const network = new StacksMainnet();
    
    // Add an optional post condition
    // See below for details on constructing post conditions
    const postConditionAddress = 'SPJ6SB99GTVXHJQR8TNS369CYERZ638P1H7RZP8D';
    const postConditionCode = FungibleConditionCode.Equal;
    const postConditionAmount = 10000000n;

    const assetAddress = 'SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9'
    const assetContractName = 'age000-governance-token'
    const assetName = 'alex';
    const fungibleAssetInfo = createAssetInfo(assetAddress, assetContractName, assetName);
    const standardFungiblePostCondition = makeStandardFungiblePostCondition(
        postConditionAddress,
        postConditionCode,
        postConditionAmount,
        fungibleAssetInfo
      );
    const contractAddress = assetAddress;
    const contractName = assetContractName

    const postConditions = [
        standardFungiblePostCondition

    ]
    const txOptions = {
        contractAddress: 'SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9',
        contractName: 'age000-governance-token',
        functionName: 'transfer',
        functionArgs: [uintCV(10000000n), standardPrincipalCV('SP74952XKEW5HSFZD8V292ADNMJ3T13WVEWP5X38'), standardPrincipalCV('SPJ6SB99GTVXHJQR8TNS369CYERZ638P1H7RZP8D'), optionalCVOf(bufferCVFromString('test'))],
        senderKey: 'xxxxxx',
        validateWithAbi: true,
        network,
        postConditions,
        anchorMode: AnchorMode.Any,
    };
    const transaction = await makeContractCall(txOptions);
    const serializedTx = transaction.serialize(); // Uint8Array
    const serializedTxHex = bytesToHex(serializedTx); // hex string
    console.log(serializeLPList(transaction.postConditions))

    const broadcastResponse = await broadcastTransaction(transaction, network);
    const txId = broadcastResponse.txid;
    console.log("-----------", txId)

}
run()`
I can get the transaction id '0x0c1b1f6ba7591925f58d05ccd6275e718701307fdfaa68855e87b5647401778d', but the explore show failed 'This transaction would have succeeded, but was rolled back by a supplied post-condition.' and the tx_status show 'abort_by_post_condition'. The transaction https://explorer.hiro.so/txid/0x231762a73a8e232cef71a2ddb74cfc1ba5dcdf2bf040316ced6fa5311115e294?chain=mainnet is that I send the alex from the exchange and it success. I compare the two transaction post_conditions, can't find any diffrerence.

**Comment by friedger** [comment]
The tx failed due to an error: err u4, not due to post conditions

**Comment by Jackwumingjie** [comment]
@friedger Can you tell me which step result the failed transaction ?  what is an "error: err u4"?

**Comment by friedger** [comment]
@Jackwumingjie the tx sender needs to be the token holder

(define-constant err-not-token-owner (err u4))

**Comment by Jackwumingjie** [comment]
@friedger I have modified it, but the new transaction failed(abort_by_post_condition):
`{'tx_id': '0x6fddc38e81c6f2749dee8f94428d840f6bc6c753901b61927e316fda9e590786',
 'nonce': 6,
 'fee_rate': '48518',
 'sender_address': 'SP74952XKEW5HSFZD8V292ADNMJ3T13WVEWP5X38',
 'sponsored': False,
 'post_condition_mode': 'deny',
 'post_conditions': [{'type': 'fungible',
   'condition_code': 'sent_equal_to',
   'amount': '10000000',
   'principal': {'type_id': 'principal_standard',
    'address': 'SPJ6SB99GTVXHJQR8TNS369CYERZ638P1H7RZP8D'},
   'asset': {'contract_name': 'age000-governance-token',
    'asset_name': 'alex',
    'contract_address': 'SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9'}}],
 'anchor_mode': 'any',
 'is_unanchored': False,
 'block_hash': '0x102ff7386a29eb088d401c3709a2b0eac077b02c7bbb0097b444b2d3ad011358',
 'parent_block_hash': '0x3b78b8d9748d1596f69aa555cef9dd0fd2be6a410931b8d28c4fe3fc9b4cac8b',
 'block_height': 108665,
 'burn_block_time': 1686272850,
 'burn_block_time_iso': '2023-06-09T01:07:30.000Z',
 'parent_burn_block_time': 1686271409,
 'parent_burn_block_time_iso': '2023-06-09T00:43:29.000Z',
 'canonical': True,
 'tx_index': 5,
 'tx_status': 'abort_by_post_condition',
 'tx_result': {'hex': '0x0703', 'repr': '(ok true)'},
 'microblock_hash': '0x',
 'microblock_sequence': 2147483647,
 'microblock_canonical': True,
 'event_count': 0,
 'events': [],
 'execution_cost_read_count': 5,
 'execution_cost_read_length': 7144,
 'execution_cost_runtime': 10474,
 'execution_cost_write_count': 2,
 'execution_cost_write_length': 1,
 'tx_type': 'contract_call',
 'contract_call': {'contract_id': 'SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.age000-governance-token',
  'function_name': 'transfer',
  'function_signature': '(define-public (transfer (amount uint) (sender principal) (recipient principal) (memo (optional (buff 34)))))',
  'function_args': [{'hex': '0x0100000000000000000000000000989680',
    'repr': 'u10000000',
    'name': 'amount',
    'type': 'uint'},
   {'hex': '0x05160e44945d9bb858e5ff6a3624894dad243d047cdb',
    'repr': "'SP74952XKEW5HSFZD8V292ADNMJ3T13WVEWP5X38",
    'name': 'sender',
    'type': 'principal'},
   {'hex': '0x0516246cad2986b7d8caf846ab91992cf3b1f30d160c',
    'repr': "'SPJ6SB99GTVXHJQR8TNS369CYERZ638P1H7RZP8D",
    'name': 'recipient',
    'type': 'principal'},
   {'hex': '0x0a020000000474657374',
    'repr': '(some 0x74657374)',
    'name': 'memo',
    'type': '(optional (buff 34))'}]}}`

**Comment by friedger** [comment]
The post condition must contain the sender SP74952XKEW5HSFZD8V292ADNMJ3T13WVEWP5X38

09.06.2023 03:25:27 吴明杰 ***@***.***>:
