### ISSUE TITLE
getSecondsUntilNextCycle does not use perpare phase

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#1514]
### What version of Stacks.js are you using?

6.5.4

### Describe the bug

getSecondsUntilNextCycle returns the seconds until the start of the reward phase, not of the prepare phase.
The prepare phase is important for stackers because stx locked after the prepare phase do not earn rewards during the upcoming reward phase.

#### How to reproduce
Check getSecondsUntilNextCycle() and compare to blocks_until_prepare_phase of e.g. https://api.hiro.so/v2/pox

#### Expected behavior

Return estimated seconds until start of next prepare phase 

### Additional context
Used in lockstacks.com/pool-admin

![image](https://github.com/hirosystems/stacks.js/assets/1449049/30fb7365-74a9-45df-b112-231397f7d366)

**Comment by janniks** [comment]
I would think this behavior is correct, but we could add a new method to get the value you want. e.g. `getSecondsUntilNextPreparePhase()` or similar.

The prepare phase or a cycle N is in the last blocks of the previous cycle N-1.

**Comment by friedger** [comment]
I'd say the current implementation on the stacking client is useless while technically correct.

**Comment by janniks** [comment]
Is the use-case to show how much time folks have left to stack/delegate -- or how much time they need to wait until they can do something?
I feel like these methods are trivial to add, so we can just add them all 🤷‍♂

**Comment by janniks** [comment]
Consensus: deprecate and switch to `Get Seconds Until Next Stacking Deadline` method for usability

**Comment by friedger** [comment]
GetSecondsUntilNextCycle is useful to show when the user's stx unlock.
