### ISSUE TITLE
uintcv stores wrong number

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#1515]
### What version of Stacks.js are you using?

6.5.4

### Describe the bug

`uintCV(10000000000000000000000000000000) => { type: 1, value: 9999999999999999635896294965248n }`

#### How to reproduce

run the above code

#### Expected behavior

uintCV should encode the big number correctly

### Additional context
Try to renew friedger.crashpunks on https://renewbns.com/

**Comment by friedger** [comment]
uintCV("10000000000000000000000000000000"),
uintCV(10000000000000000000000000000000n),
uintCV(10000000000000000000000000000000)

=> 

Object { type: 1, value: 10000000000000000000000000000000n }
Object { type: 1, value: 10000000000000000000000000000000n }
Object { type: 1, value: 9999999999999999635896294965248n }

**Comment by friedger** [comment]
There should be an error because the number is larger than Number.MAX_SAFE_INTEGER

**Comment by janniks** [comment]
Yep, this is just the `BigInt` constructor not working correctly with too large numbers. [example](https://stacksjs-playground.vercel.app/editor?id=multisig-transactions&code=aW1wb3J0IHsgdWludENWIH0gZnJvbSAnQHN0YWNrcy90cmFuc2FjdGlvbnMnCgpjb25zb2xlLmxvZygidWludENWOiIpCmNvbnNvbGUubG9nKHVpbnRDVigxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCkpCmNvbnNvbGUubG9nKHVpbnRDVigiMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiKSkKCmNvbnNvbGUubG9nKCJCaWdJbnQ6IikKY29uc29sZS5sb2coQmlnSW50KDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwKSkK&t=QmlnSW50IFByb2JsZW1z&d=VGhpcyBzbmlwcGV0IHNob3dzIHNvbWUgaXNzdWVzIHdpdGggQmlnSW50cyBpbiBKUy9UUw%3D%3D)

Will update to check bounds and throw error telling to use with string or hex construction
