### ISSUE TITLE
sBTC smart contract wrapper in stacks.js

### ISSUE THREAD

**Issue by scottsolowild** [stx-labs/stacks.js#1541]
- add a smart contract wrapper (similar to `@stacks/stacking`), which doesn't really add groundbreaking stacks.js functionality, but makes it easier for users to use the sbtc contract, without know a lot about stacks/stacks.js

Code interface TBD (potentially inspired by `StackingClient`)

**Comment by sabbyanandan** [comment]
@smcclellan: It would be helpful if you can also update the description with the context and/or other background.

**Comment by janniks** [comment]
Closing, not needed since these functions are only called by sbtc itself
