### ISSUE TITLE
sBTC Bridge package in stacks.js

### ISSUE THREAD

**Issue by scottsolowild** [stx-labs/stacks.js#1542]
- add relevant JS functionality being worked on in the Bridge API repos (sbtc-bridge-lib) to stacks.js directly
- coordinated by @setbern & @janniks

**Comment by janniks** [comment]
Requirements:
- serialize/deserialize btc transactions
- API interactions library (where is this hosted? do we provide infra that wrap on-chain state?)

Todo:
- [ ] Lookat brdige repos for insipration

**Comment by janniks** [comment]
Update w/ @setbern, unclear and subject to change:
- sbtc is skipping the alpha release (in favor of Nakamoto Flip)
- seems like Nakamoto and sbtc will be two separate forks
- sbtc development release on testnet: Nakamoto Flip, will likely not have signers

**Comment by setbern** [comment]
2 week goal
- Sudo code of sbtc wrapper
- Sudo code of sbtc bridge helper functions

**Comment by janniks** [comment]
Helpers worked well and will stay in the sbtc branch for now ✅
