### ISSUE TITLE
Can't deploy pox-3 contract on testnet, Failed to deserialize posted transaction: Invalid Stacks string: non-printable or non-ASCII string

### ISSUE THREAD

**Issue by llwinner** [stx-labs/stacks.js#1550]
I tried to depoly pox-3 contract on testnet, I copied the contract SP000000000000000000002Q6VF78.pox-3 and follow the example:
[https://github.com/hirosystems/stacks.js/tree/main/packages/transactions](url)
But when I run code I got an error: Failed to deserialize posted transaction: Invalid Stacks string: non-printable or non-ASCII string
I can deploy hello-stacks contract on testnet with the same code. I tried to deploy pox-2 contract and got the same error.
What should I do? 
Please help me, thanks!

**Comment by janniks** [comment]
Good question, I'll have to look into the exact contract code.

**Comment by janniks** [comment]
It turns out the `pox-3` contract isn't meant to be deployed as is. The blockchain is doing some more work and concatenation to make it run. What are you trying to achieve, maybe we can help? 😀

**Comment by llwinner** [comment]
@janniks Thanks for your reply. I want to test that contract on testnet, but just as you said,  the blockchain is doing some more work and concatenation to make it run. So I will debug my code on mainnet.

**Comment by friedger** [comment]
Have you considered using clarinet integrate? https://docs.hiro.so/clarinet/feature-guides/clarinet-integrate
