### ISSUE TITLE
How to use tuple and uint with none value in stacks.js transaction?

### ISSUE THREAD

**Issue by llwinner** [stx-labs/stacks.js#1555]
I want to call a contract function with stacks.js, and the functions args contain tuple and uint. I read the README file about how to call a contract, that example just use bufferCVFromString function, and the parameter is not empty. 
The contract function I want to call has 5 parameters,  some tuple or uint parameter's value can be none, but I don't know how to do with stacks.js.
Please help me, thanks!

**Comment by friedger** [comment]
You can use `nonceCV()` https://stacks.js.org/functions/_stacks_transactions.noneCV-1

There is also `someCV(...)` when using uints and tuples with parameters of type optional.

**Comment by llwinner** [comment]
@friedger Thanks for your reply. It helps me!
