### ISSUE TITLE
Stacks.js Overview page on Docs refactor

### ISSUE THREAD

**Issue by ryanwaits** [stx-labs/stacks.js#1556]
Reference: https://docs.hiro.so/stacks.js/overview

The top level overview page should be re-worked, I don't see a huge value add in listing out each package - ideally should have immediate code examples and an easy win. If we need links/references to the repo code we can do so more contextually.

**Comment by mefrem** [comment]
Agreed. Working on this now, will kick back to you after a first pass.

**Comment by janniks** [comment]
Trying some stuff out in the branch `update-docs`
