### ISSUE TITLE
How can I generate stx and btc addresses using @stacks/cli code, not  command line?

### ISSUE THREAD

**Issue by llwinner** [stx-labs/stacks.js#1576]
Hello everyone, I want to generate stx and btc addresses with stacks.js. I read the doc about @stacks/cli and generate two addresses with 
stx make_keychain > cli_keychain.json.
But when I trid to generate addresses with code  not command line, I cannot find an easy way to call function directly.
I tried to copy makeKeychain() method to my code and call it, but it needs to  import a lot of methods from other files, and methods need import other methods.  So are there any ways to generate btc and stx addresses with stacks.js easily? Please help me, thanks.

**Comment by friedger** [comment]
You can use stacks js wallet-sdk package.

**Comment by llwinner** [comment]
@friedger Thanks for your reply. I just read the doc of wallet-sdk if. I use wallet-sdk, how to generate btc address and btc private key, I do not find the methods to generate them, I want to generate addresses like @stacks/cli command line, contains wif:
![image](https://github.com/hirosystems/stacks.js/assets/28646992/316afcfb-c62b-4524-b002-0613e681f15a)

**Comment by friedger** [comment]
You can use wif package:

Here a helper function for mainnet and testnet:
``` 

function privateKeyToWIF(private_key_hex: string, mainnet: boolean) {
  console.log(private_key_hex, private_key_hex.length)
  return wif.encode(
    mainnet ? 0x80 : 0xef,
    Buffer.from(private_key_hex, "hex"),
    true
  );
}

```

**Comment by llwinner** [comment]
@friedger Thanks for your reply. Would you tell me where wif package is? private_key_hex is generated by generateSecretKey() method? if private_key_hex is generated by generateSecretKey() method it means the btc private key is generated from a stx private key, is that right? 
Please help me, thanks

**Comment by llwinner** [comment]
I found the solution. Thanks.
