### ISSUE TITLE
Cors issue when upgrading the stacks.js SDK to the latest version on Sigle

### ISSUE THREAD

**Issue by pradel** [stx-labs/stacks.js#1595]
### What version of Stacks.js are you using?

```
"@stacks/auth": "6.9.0",
    "@stacks/blockchain-api-client": "7.3.2",
    "@stacks/common": "6.8.1",
    "@stacks/connect": "7.4.1",
    "@stacks/connect-react": "22.2.1",
    "@stacks/encryption": "6.9.0",
    "@stacks/keychain": "4.3.8",
    "@stacks/network": "6.8.1",
    "@stacks/profile": "6.9.0",
    "@stacks/storage": "6.9.0",
    "@stacks/transactions": "6.9.0",
```

### Describe the bug

When upgrading the stacks.js dependencies on Sigle to their latest version, I can't access any item from Gaia without having a cors error. See the upgrade package pr https://github.com/sigle/sigle/pull/967/files.
![Screenshot 2023-11-07 at 18 26 59](https://github.com/hirosystems/stacks.js/assets/5749437/cab72f65-3037-45b6-adde-84a8c2843c69)

#### How to reproduce

- clone the sigle repository https://github.com/sigle/sigle
- run `pnpm install`
- run sigle from the **main** branch `pnpm dev` in `sigle` folder
- see that no issues when logging in and fetching the files from Gaia
- switch to https://github.com/sigle/sigle/pull/967 branch
- run `pnpm install`
- run sigle from the **pr** branch `pnpm dev` in `sigle` folder
- see that when a file is fetched you get a Cors error 

#### Expected behavior

The upgrade of the stacks.js SDK should not cause any issue.

**Comment by janniks** [comment]
Might be a change on the infrastructure and a lib switching url strings. But not sure yet.

I'm having trouble reproducing, any steps I'm missing (ENV? run server locally? etc.)

**Comment by janniks** [comment]
CC @hirosystems/devops what does our CORS look like for gaia.hiro.so?

_Nothing critical, I still need to reproduce._

**Comment by CharlieC3** [comment]
@janniks IIUC the original request should have worked, the Gaia CDN's CORS settings are pretty permissive as shown below:
```
bash-5.1$ curl -X OPTIONS https://gaia.hiro.so/hub/1GT81E4hd1s5cDyY2qhVUEvRUbkqBKWLte/stories.json -H 'Origin: http://localhost:3000' -H 'Access-Control-Request-Method: GET' -H 'Access-Control-Request-Headers: content-type' -I
HTTP/2 200
date: Tue, 07 Nov 2023 22:06:20 GMT
access-control-allow-credentials: true
access-control-allow-headers: content-type
access-control-allow-methods: GET
access-control-allow-origin: http://localhost:3000
access-control-max-age: 200

bash-5.1$ curl -X GET https://gaia.hiro.so/hub/1GT81E4hd1s5cDyY2qhVUEvRUbkqBKWLte/stories.json -H 'Origin: http://localhost:3000' -H 'Access-Control-Request-Method: GET' -H 'Access-Control-Request-Headers: content-type' -I
HTTP/2 200
date: Tue, 07 Nov 2023 22:08:18 GMT
access-control-allow-origin: *
access-control-expose-headers: ETag
```

**Comment by pradel** [comment]
> I'm having trouble reproducing, any steps I'm missing (ENV? run server locally? etc.)

Nothing else, the setup should work directly, I can try some things on my side if you have some ideas of things to test (request header etc)

**Comment by pradel** [comment]
Don't know if that's helpful but the vercel deployed version is throwing the cors error https://sigle-git-feature-upgrade-stacks-packages-2-sigle.vercel.app/

![Screenshot 2023-12-14 at 19 17 36](https://github.com/hirosystems/stacks.js/assets/5749437/901573e0-b081-46a6-842a-639c88caa089)

**Comment by janniks** [comment]
@blockstack-devops Could this be due to missing CORS on OPTIONS requests?

**Comment by CharlieC3** [comment]
@janniks Correct me if I'm wrong, but the OPTIONS request I made [in this comment](https://github.com/hirosystems/stacks.js/issues/1595#issuecomment-1800268503) shows CORS is working. Is there something else you're noticing that I'm missing?

**Comment by janniks** [comment]
~Is this `access-control-allow-origin` of `http://localhost:3000` (from your comment) maybe the problem for browsers?~
Likely not, that changes to whatever the Origin header was from the request

**Comment by CharlieC3** [comment]
Just confirming but that is correct. The value of the returned `access-control-allow-origin` header is dynamic based on the `origin` header in the original request. This happens for some proxies when the CORS policy is configured to allow any origin.
e.g.
```
bash-5.1$ curl -X OPTIONS https://gaia.hiro.so/hub/1GT81E4hd1s5cDyY2qhVUEvRUbkqBKWLte/stories.json -H 'Origin: http://my-cool-website:3000' -H 'Access-Control-Request-Method: GET' -H 'Access-Control-Request-Headers: content-type' -I
...
access-control-allow-origin: http://my-cool-website:3000
...
```

**Comment by janniks** [comment]
Debugging the [deployed preview](https://sigle-git-feature-upgrade-stacks-packages-2-sigle.vercel.app/login) I run into this case:

```sh
λ curl 'https://gaia.hiro.so/hub/1BmdyEbE1PzAdhSufJkUmBvyfgeqq3zTeE/settings.json' \
  -X 'OPTIONS' \
  -H 'access-control-request-headers: x-hiro-product' \
  -H 'access-control-request-method: GET' \            
  -H 'origin: https://sigle-git-feature-upgrade-stacks-packages-2-sigle.vercel.app' \
  -H 'referer: https://sigle-git-feature-upgrade-stacks-packages-2-sigle.vercel.app/' \
  --compressed -i

HTTP/2 403 
date: Mon, 18 Dec 2023 09:27:07 GMT
content-type: application/xml
content-length: 316
x-ms-request-id: a2bd92a0-c01e-0003-5294-318306000000
x-ms-version: 2015-02-21
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 83765e40e919c24f-VIE

<?xml version="1.0" encoding="utf-8"?><Error><Code>CorsPreflightFailure</Code><Message>CORS not enabled or no matching rule found for this request.
RequestId:a2bd92a0-c01e-0003-5294-318306000000
Time:2023-12-18T09:27:07.8290466Z</Message><MessageDetails>No CORS rules matches this request</MessageDetails></Error>%
```

This is a blob that doesn't exist, but the browser never makes it to the GET, because the prior OPTIONS call is a `403`. Is there maybe something misconfigured on Stacks.js, or should the response look different?

**Comment by CharlieC3** [comment]
@janniks Ah the `x-hiro-product` header wasn't allowed. I've updated the CORS rule to allow all hiro headers.

**Comment by janniks** [comment]
Thanks 🙏
CC @pradel does it work as expected now? @ https://sigle-git-feature-upgrade-stacks-packages-2-sigle.vercel.app/login

**Comment by pradel** [comment]
@janniks issue seems to be fixed 👍 

Thanks for finding the problem!
