### ISSUE TITLE
Add utility `postConditionToHex`

### ISSUE THREAD

**Issue by aryzing** [stx-labs/stacks.js#1633]
### Problem

In the wake of the increasingly adopted WebBTC standard, and from how the [Integration of WebBTC Request Standard for Stacks Wallets SIP](Integration of WebBTC Request Standard for Stacks Wallets) is evolving, it would be helpful to have hex conversion helpers for all values recommended by the SIP to be used as hex,

- [done] Clarity values (covered by `cvToHex`)
- Post Conditions
- Transactions

Although user can 2-step this process by first serializing to bytes and then converting to hex, having a helper would make for a nicer DX.

### Solution

Similar to the [`cvToHex`](https://github.com/hirosystems/stacks.js/blob/922e037a6d77141afe0b7d664117ab2955a9507f/packages/transactions/src/types.ts#L360) helper, it would be helpful to have `postConditionToHex()` and `txToHex()` helpers.

**Comment by janniks** [comment]
Good point, thanks! There might exist some helpers, but I'll add aliases or build out the missing functions.
