### ISSUE TITLE
new bufferCV bug

### ISSUE THREAD

**Issue by SatoshiNakam** [stx-labs/stacks.js#1664]
### What version of Stacks.js are you using?
latest

### Describe the bug
In bufferCV.ts, `buffer.length > 1_000_000` should be `buffer.length > 1_048_576`.

#### How to reproduce
Let buffer contains (1_000_000, 1_048_576) characters, bufferCV will trigger error.

#### Expected behavior
Pls fix it.

**Comment by janniks** [comment]
Thanks for the report 🙏
