### ISSUE TITLE
installing issue on macOs sierra

### ISSUE THREAD

**Issue by Eric-Glaenzer** [stx-labs/stacks.js#167]
creating build/lib
    creating build/lib/bitcoin
    copying bitcoin/__init__.py -> build/lib/bitcoin
    copying bitcoin/bci.py -> build/lib/bitcoin
    copying bitcoin/blocks.py -> build/lib/bitcoin
    copying bitcoin/composite.py -> build/lib/bitcoin
    copying bitcoin/deterministic.py -> build/lib/bitcoin
    copying bitcoin/main.py -> build/lib/bitcoin
    copying bitcoin/mnemonic.py -> build/lib/bitcoin
    copying bitcoin/py2specials.py -> build/lib/bitcoin
    copying bitcoin/py3specials.py -> build/lib/bitcoin
    copying bitcoin/ripemd.py -> build/lib/bitcoin
    copying bitcoin/stealth.py -> build/lib/bitcoin
    copying bitcoin/transaction.py -> build/lib/bitcoin
    running egg_info
    writing bitcoin.egg-info/PKG-INFO
    writing top-level names to bitcoin.egg-info/top_level.txt
    writing dependency_links to bitcoin.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'bitcoin.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'bitcoin.egg-info/SOURCES.txt'
    copying bitcoin/english.txt -> build/lib/bitcoin
    running build_scripts
    creating build/scripts-2.7
    copying and adjusting pybtctool -> build/scripts-2.7
    changing mode of build/scripts-2.7/pybtctool from 644 to 755
    running install_lib
    running install_data
    copying LICENSE -> /System/Library/Frameworks/Python.framework/Versions/2.7/
    error: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/LICENSE'

**Comment by muneeb-ali** [comment]
@Eric-Glaenzer Thanks for reporting this. We don't currently test on macOS Sierra and only test on OS X, Debian, and Ubuntu. I'm adding the label platform-testing to include Sierra in our tests as well.

**Comment by tthsn** [comment]
@eric-glaenzer: sudo is requred to install blockstack to system path, or virtualenv can be used to creat a clean and isolated environment.

**Comment by Eric-Glaenzer** [comment]
@tthsn Yes I know and I did. (multiple times in fact and the error is consistently the same)

**Comment by larrysalibra** [comment]
@Eric-Glaenzer I use blockstack-cli on macOS Sierra 10.12.1

These are the steps I took to install it:

```
brew install libffi openssl
virtualenv -p /usr/bin/python2.7 blockstack-cli-venv
source blockstack-cli-venv/bin/activate
pip install --upgrade pip
pip install --upgrade blockstack
```

Specifically, install fails for me if i don't `pip install --upgrade pip` and use the really old version Apple ships.

Do these work for you? Which steps are you taking?

**Comment by Eric-Glaenzer** [comment]
I was following the steps from Blockstack.org: `sudo pip install blockstack`... I am going to try your steps.. maybe the website should be updated?

**Comment by tthsn** [comment]
@Eric-Glaenzer I have a macOS Sierra desktop and my installation is smooth with virtualenv. 
Please make sure to use python provided by brew.

MyMacPro:~ me$ which python
/usr/local/bin/python

MyMacPro:~ me$ virtualenv bs_new
New python executable in /Users/me/bs_new/bin/python2.7
Also creating executable in /Users/me/bs_new/bin/python
Installing setuptools, pip, wheel...done.

MyMacPro:~ me$ bash -c 'source bs_new/bin/activate; pip install blockstack'
Collecting blockstack
Collecting mixpanel>=4.3.1 (from blockstack)
  Using cached mixpanel-4.3.1-py2.py3-none-any.whl
Collecting jsonschema>=2.5.1 (from blockstack)
  Using cached jsonschema-2.5.1-py2.py3-none-any.whl
Collecting basicrpc>=0.0.2 (from blockstack)
Collecting boto>=2.38.0 (from blockstack)
  Using cached boto-2.43.0-py2.py3-none-any.whl
Collecting blockstack-profiles>=0.14.0 (from blockstack)
Collecting pybitcoin>=0.9.9 (from blockstack)
Collecting protocoin>=0.2 (from blockstack)
Collecting pycrypto>=2.6.1 (from blockstack)
Collecting virtualchain>=0.14.0 (from blockstack)
Collecting simplejson>=3.8.2 (from blockstack)
Collecting defusedxml>=0.4.1 (from blockstack)
Collecting blockstack-zones>=0.14.0 (from blockstack)
Collecting keylib>=0.0.5 (from blockstack)
Collecting six>=1.9.0 (from mixpanel>=4.3.1->blockstack)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting functools32; python_version == "2.7" (from jsonschema>=2.5.1->blockstack)
Collecting cryptography>=1.2.3 (from blockstack-profiles>=0.14.0->blockstack)
  Using cached cryptography-1.6-cp27-cp27m-macosx_10_10_intel.whl
Collecting jsontokens>=0.0.2 (from blockstack-profiles>=0.14.0->blockstack)
Collecting bitcoin>=1.1.42 (from pybitcoin>=0.9.9->blockstack)
Collecting commontools==0.1.0 (from pybitcoin>=0.9.9->blockstack)
Collecting requests>=2.4.3 (from pybitcoin>=0.9.9->blockstack)
  Using cached requests-2.12.1-py2.py3-none-any.whl
Collecting utilitybelt>=0.2.6 (from pybitcoin>=0.9.9->blockstack)
Collecting python-bitcoinrpc==0.1 (from pybitcoin>=0.9.9->blockstack)
Collecting ecdsa>=0.13 (from pybitcoin>=0.9.9->blockstack)
  Using cached ecdsa-0.13-py2.py3-none-any.whl
Collecting keychain>=0.1.4 (from pybitcoin>=0.9.9->blockstack)
Collecting cffi>=1.4.1 (from cryptography>=1.2.3->blockstack-profiles>=0.14.0->blockstack)
  Using cached cffi-1.9.1-cp27-cp27m-macosx_10_10_intel.whl
Collecting pyasn1>=0.1.8 (from cryptography>=1.2.3->blockstack-profiles>=0.14.0->blockstack)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting idna>=2.0 (from cryptography>=1.2.3->blockstack-profiles>=0.14.0->blockstack)
  Using cached idna-2.1-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=1.2.3->blockstack-profiles>=0.14.0->blockstack)
  Using cached enum34-1.1.6-py2-none-any.whl
Requirement already satisfied: setuptools>=11.3 in ./bs_new/lib/python2.7/site-packages (from cryptography>=1.2.3->blockstack-profiles>=0.14.0->blockstack)
Collecting ipaddress (from cryptography>=1.2.3->blockstack-profiles>=0.14.0->blockstack)
  Using cached ipaddress-1.0.17-py2-none-any.whl
Collecting bitmerchant>=0.1.8 (from keychain>=0.1.4->pybitcoin>=0.9.9->blockstack)
  Using cached bitmerchant-0.1.8-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.2.3->blockstack-profiles>=0.14.0->blockstack)
Collecting base58>=0.2.1 (from bitmerchant>=0.1.8->keychain>=0.1.4->pybitcoin>=0.9.9->blockstack)
Collecting cachetools>=1.1.1 (from bitmerchant>=0.1.8->keychain>=0.1.4->pybitcoin>=0.9.9->blockstack)
  Using cached cachetools-2.0.0-py2.py3-none-any.whl
Installing collected packages: six, mixpanel, functools32, jsonschema, basicrpc, boto, blockstack-zones, ecdsa, utilitybelt, keylib, pycparser, cffi, pyasn1, idna, enum34, ipaddress, cryptography, requests, jsontokens, blockstack-profiles, bitcoin, commontools, python-bitcoinrpc, base58, cachetools, bitmerchant, keychain, pybitcoin, protocoin, pycrypto, simplejson, virtualchain, defusedxml, blockstack
Successfully installed base58-0.2.4 basicrpc-0.0.2 bitcoin-1.1.42 bitmerchant-0.1.8 blockstack-0.14.0.7 blockstack-profiles-0.14.0 blockstack-zones-0.14.0 boto-2.43.0 cachetools-2.0.0 cffi-1.9.1 commontools-0.1.0 cryptography-1.6 defusedxml-0.4.1 ecdsa-0.13 enum34-1.1.6 functools32-3.2.3.post2 idna-2.1 ipaddress-1.0.17 jsonschema-2.5.1 jsontokens-0.0.2 keychain-0.1.4.1 keylib-0.0.5 mixpanel-4.3.1 protocoin-0.2 pyasn1-0.1.9 pybitcoin-0.9.9 pycparser-2.17 pycrypto-2.6.1 python-bitcoinrpc-0.1 requests-2.12.1 simplejson-3.10.0 six-1.10.0 utilitybelt-0.2.6 virtualchain-0.14.0

**Comment by larrysalibra** [comment]
@Eric-Glaenzer Yes, we need to update the website. Very sorry about that. I've opened an issue about it-> https://github.com/blockstack/blockstack.org/issues/165

@muneeb-ali Are we only testing on old versions of macOS for a reason? 10.12 has been out for a while.

**Comment by Eric-Glaenzer** [comment]
@larrysalibra: Yes your steps worked. Thanks, I am up and running on my macos Sierra.

**Comment by luisivan** [comment]
I'm still stuck with `ImportError: No module named _sqlite3` when running `blockstack` after trying all the aforementioned steps. I'm on Sierra w/ Python 2.7 and pip 9.0.1

**Comment by khusikhusi** [comment]
@larrysalibra, your solution worked for me, thanks!!

**Comment by larrysalibra** [comment]
@danopp glad to hear so!

**Comment by muneeb-ali** [comment]
I can confirm that 

> pip install --upgrade pip

fixes the cryptography installation issue.
