### ISSUE TITLE
React Native: Environment does not have randomBytes function

### ISSUE THREAD

**Issue by gendev1** [stx-labs/stacks.js#1672]
### What version of Stacks.js are you using?
@stacks/wallet-sdk v 6.13.1

### Describe the bug
Been getting Environment does not have randomBytes function.
Tried on expo as well as react native projects
Did all pollyfills required for Buffer, TextEncoder, Crypto etc
Tried modifying the metro config file
Tried rn-nodeify and imported the shim file generated
Nothing seems to solve the issue

#### How to reproduce
1. Create a new react native project
2. Install @stacks/wallet-sdk
3. Call generateSecretKey()

**Comment by janniks** [comment]
Thanks for the report. I will create a React-Native example / guide tomorrow to find out what's missing 🙏

**Comment by janniks** [comment]
Hi -- I added a [Guide](https://docs.hiro.so/stacks.js/guides/react-native-guide) to our docs 🙏
