### ISSUE TITLE
`bigint` arguments

### ISSUE THREAD

**Issue by obycode** [stx-labs/stacks.js#1678]
### Problem

For all of the functions that take in values that represent Clarity `int`s and `uint`s, they should probably accept `bigint | number`, since these types can be larger than a `number` (128-bit vs 64-bit).

### Solution

Update the parameter types to be `bigint | number`.

**Comment by janniks** [comment]
🙏🏻 We typically have an IntegerType for this where was it missing?

**Comment by obycode** [comment]
Oh, nice. I see that now. I was getting an error from `signPoxSignature`. It looks like just the period and reward cycle were the problem. Maybe that's intentional though?

**Comment by janniks** [comment]
Yeah, those we left as `number` intentionally, but maybe there's a case they should be `bigint`.

**Comment by janniks** [comment]
I'll close for now, please reopen if you feel `bigint` would be better. Realistically it should never be reached/needed, so I hope `number` is more understandable to be a lower "number" in users' minds -- but who knows :)
