### ISSUE TITLE
more user-friendly flag for verbose output (e.g. --verbose or -v)

### ISSUE THREAD

**Issue by OACDesigns** [stx-labs/stacks.js#168]
using `--v` and/or `--verbose` would be a more intuitive and user friendly way to get debug output

**Comment by muneeb-ali** [comment]
@OACDesigns Thanks for suggestion! +1 that --v and --verbose is a better developer UX and we should probably use that instead of --debug or BLOCKSTACK_DEBUG=1.

**Comment by jcnelson** [comment]
It will be added in the next stable release :)

**Comment by jcnelson** [comment]
This has been merged as `-d/--debug`.
