### ISSUE TITLE
lookup command fails with version 2.12.1 of requests library

### ISSUE THREAD

**Issue by OACDesigns** [stx-labs/stacks.js#169]
on a clean installation (windows linux subsystem) lookups fail. Debug mode points to the `requests` library (2.12.1) being the cause.
Downgrading `requests` to 2.9.1 solves the issue

**Comment by muneeb-ali** [comment]
@OACDesigns thanks for reporting. I'm marking this as a bug. The short-term solution is to ensure requests version 2.9.1. In the long-run, we should look more into how the "requests" package is breaking the lookup call so that we can work with the latest versions as well.

**Comment by jcnelson** [comment]
I think we've fixed this since then.  If not, please re-open in the blockstack-core repo.
