### ISSUE TITLE
get_name_record results in an "AWS Access Key" error

### ISSUE THREAD

**Issue by shea256** [stx-labs/stacks.js#17]
Here's my full output:

``` python
(blockstore-cli)blockstore-client-$ blockstore-cli get_name_record werner.id
[ERROR] [s3:72] Could not create/fetch bucket blockstore-test
[ERROR] [s3:73] S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>a</AWSAccessKeyId><RequestId>D09232CA3DFD8CD3</RequestId><HostId>wus/t/TLPupb+GNpNLqQpA6ou5UJoh5H+NBnEGYyrxZjplO8ieS90OA8y8Dn8TBG</HostId></Error>
Traceback (most recent call last):
  File "/Users/ryan/.virtualenvs/blockstore-cli/lib/python2.7/site-packages/blockstore_client-0.0.3-py2.7.egg/blockstore_client/drivers/s3.py", line 70, in get_bucket
    bucket = conn.create_bucket(bucket_name)
  File "/Users/ryan/.virtualenvs/blockstore-cli/lib/python2.7/site-packages/boto-2.38.0-py2.7.egg/boto/s3/connection.py", line 621, in create_bucket
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>a</AWSAccessKeyId><RequestId>D09232CA3DFD8CD3</RequestId><HostId>wus/t/TLPupb+GNpNLqQpA6ou5UJoh5H+NBnEGYyrxZjplO8ieS90OA8y8Dn8TBG</HostId></Error>
[ERROR] [s3:123] Failed to get bucket 'blockstore-test'
[ERROR] [client:232] Failed to load user record '3dafd5f42798df3045cd2eb70a71cccf8500e6d4'
{
    "error": "User data could not be loaded from storage"
}
```

**Comment by muneeb-ali** [comment]
This is an error in your ini file. Here is my output

```
(blockstore-client)muneeb@amsterdam:bin$ ./blockstore-cli get_name_record werner.id
{
    "avatar": {
        "url": "https://s3.amazonaws.com/kd4/werner"
    },
    "bio": "CTO @ Amazon",
    "bitcoin": {},
    "cover": {
        "url": "https://s3.amazonaws.com/dx3/werner"
    },
    "facebook": {
        "proof": {
            "url": "https://facebook.com/wernervogels/posts/10155319612560235"
        },
        "username": "wernervogels"
    },
    "github": {
        "proof": {
            "url": "https://gist.github.com/wv/2427b5a69aec5524ca67"
        },
        "username": "wv"
    },
    "location": {
        "formatted": "Seattle, WA"
    },
    "name": {
        "formatted": "Werner Vogels"
    },
    "twitter": {
        "proof": {
            "url": "https://twitter.com/Werner/status/571698777297321985"
        },
        "username": "Werner"
    },
    "v": "0.2",
    "website": "http://smile.amazon.com"
}
```

You should not provide S3 as a storage backend (we don't support S3 as a storage provider yet). And should add the 'dht' our current default storage in ~/.blockstore-client/blockstore-client.ini file.

> storage=disk,dht

**Comment by shea256** [comment]
I didn't set anything up with S3. I just used the .ini file that @jcnelson sent me.

In terms of usability, I'd say new installations of blockstore via `pip install blockstore` should prompt the user to update their .ini file.

**Comment by muneeb-ali** [comment]
Yes, that's a known issue. We've discussed it before and is on the roadmap before putting out any final release. The .ini files will have reasonable defaults and the user will be prompted to update/change any of the default configuration.

**Comment by shea256** [comment]
:+1:

**Comment by shea256** [comment]
OK I'm still having the issue. Here's what I did:
1. I pip uninstalled and then pip installed blockstore in a new virtual environment
2. I blew away my .ini file and created a new one from scratch
3. I started blockstored up again and made sure the index was up to date

Then I tried the `get_name_record` command again and I got the same error.

@jcnelson @muneeb-ali Any thoughts on what may be going wrong?

Is the latest `blockstore-cli` command pointing to the newest version of the blockstore client, or do I need to do something special here?

**Comment by jcnelson** [comment]
@shea256 In your `blockstore-client.ini` file, you should have `storage=disk,dht,s3`.  The lookup will try to find the profile on disk, then on the DHT, then in S3.  If you're hitting S3 (and failing), then it means you're either not trying the DHT, or the DHT is down.

**Comment by muneeb-ali** [comment]
This has been resolved in latest version. Please checkout the latest version of the client and cli!
