### ISSUE TITLE
Don't set logging settings propagate to parent packages

### ISSUE THREAD

**Issue by shea256** [stx-labs/stacks.js#170]
Currently, the Blockstack client is setting logging settings.

Unfortunately, every package that imports this library then inherits these settings.

For example, if I have a web server that has logging set to DEBUG or INFO, it will be overridden by the less verbose levels of logging that the Blockstack client sets.

We should figure out a way to prevent these logging settings from propagating up to packages that import the Blockstack client.

**Comment by jcnelson** [comment]
Actually, this has proven extremely useful at diagnosing problems.
