### ISSUE TITLE
API key header name doesn't match documented header name

### ISSUE THREAD

**Issue by aryzing** [stx-labs/stacks.js#1713]
### What version of Stacks.js are you using?

Commit `2c57ea4e5abed76da903f5138c79c1d2eceb008b` (`v6.16.0-beta.3`)

### Describe the bug

The http header for the api key [defaults to](https://github.com/hirosystems/stacks.js/blob/2c57ea4e5abed76da903f5138c79c1d2eceb008b/packages/network/src/fetch.ts#L104) `x-api-key` yet the [docs](https://docs.hiro.so/guides/api-keys) use `x-hiro-api-key`

Is it a bug in the docs / code or are both allowed?

**Comment by janniks** [comment]
Thanks, now updated in https://github.com/hirosystems/docs/pull/699 -- both work, but we're airing on the side of the default non-hiro branded header
