### ISSUE TITLE
Problem installing blockstack on Debian jessie

### ISSUE THREAD

**Issue by borisreitman** [stx-labs/stacks.js#172]
I tried installing blockstack on Debian, and I got this error when running command 

```
sudo apt-get update && sudo apt-get install -y python-pip python-dev libssl-dev
```

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1260, in prepare_files
    )[0]
IndexError: list index out of range
```

My version of Debian is Jessie, which was upgraded to Jessie from original Wheezy. THe version of python I have is 2.7.9.

**Comment by borisreitman** [comment]
I have created a brand new Debian jessie machine, and was able to install blockstack. I did have a few issues, but I was able to resolve them by googling.

I used this Vagrant machine as the starting point: https://atlas.hashicorp.com/debian/boxes/jessie64
called debian/jessie64

**Comment by jcnelson** [comment]
I'm guessing this was an environment error.  Please re-open in the blockstack-core repo if the problem persists.
