### ISSUE TITLE
Reconsider hardcoding Hiro RPC API in the package

### ISSUE THREAD

**Issue by OxMarco** [stx-labs/stacks.js#1760]
Hardcoding RPC nodes like the code snippet below should be avoided
```
export const HIRO_MAINNET_URL = 'https://api.mainnet.hiro.so';
export const HIRO_TESTNET_URL = 'https://api.testnet.hiro.so';

```
instead, provide a mandatory RPC argument for the contract calls and offer a constant that the users can provide to explicitly use Hiro API.

**Comment by janniks** [comment]
It's very easy to make a call target arbitrary nodes/APIs using Stacks.js. However most of the developers expect to have defaults and prefer using even more simplified arguments like `'mainnet'` and `'testnet'`.

While we do want to encourage everyone to host their own nodes and point calls to custom nodes, more users are annoyed by the initial frustration, so we will likely always have defaults to make the first use of Stacks.js easier. But we're always open to considering better developer experience.

e.g. to use a custom node / network
```ts
broadcastTransaction({ transaction, client: {
  baseUrl: "https://my-custom-node.com"
}})
```

> All RPC calls accept a `client` argument to configure the target node/API. Or developers can add the `client` to their `network` object.
