### ISSUE TITLE
Compartmentalize name ownership

### ISSUE THREAD

**Issue by john-light** [stx-labs/stacks.js#177]
1. Add the ability to generate new addresses on the fly and specify what address should be used to register a name.  

2. Make sure the bitcoin change from one name op tx isn't sent to an address that's been used for another name, to ensure compartmentalization.  

One potential solution is to introduce the notion of "accounts", similar to the way the [Mycelium bitcoin wallet](https://github.com/mycelium-com/wallet#features) works. Each account is its own branch of the master HD wallet and is used to create a bunch of derivative addresses that are completely isolated from addresses generated by other accounts. This way change from one account never unintentionally spills over into other accounts.

**Comment by muneeb-ali** [comment]
@john-light we merged the CLI repo with [blockstack-core](http://github.com/blockstack/blockstack-core) and I moved this issue there. Closing this copy of the issue.
