### ISSUE TITLE
I've love to join this community!!!

### ISSUE THREAD

**Issue by bitman09** [stx-labs/stacks.js#1775]
I'm a blockchain developer with experience in Bitcoin.
I'm familiar with Bitcoin Ordinals and Runes.
Nowadays, I'm focusing to learn Stacks network and also research stacks.js library.
It is very interesting and I wanna become a member of this community.
Sorry for my message and hope you understand.
Thanks

**Comment by scottsolowild** [comment]
Hi @bitman310 -- welcome to the community! I recommend joining [the Discord](https://stacks.chat) and reading [our docs](https://docs.hiro.so/) to get started. Our [platform](https://platform.hiro.so/) may also be helpful for starting out.
