### ISSUE TITLE
Please can someone kindly comment where the doc for test lies. This is really becoming so frustrating writing testcases.

### ISSUE THREAD

**Issue by kengoon** [stx-labs/stacks.js#1778]
Stacks community really need to work on their doc, I'm not a fan of watching thousands of tutorial before writing a code. I prefer reading a well structured doc that explains things. Stacks has thousands of web pages for their api doc. this is frustrating and crazy
1. https://docs.hiro.so/stacks
2. https://book.clarity-lang.org/title-page.html
3. https://docs.stacks.co/reference/keywords#tx-sender
4. https://learn.stacks.org/course/clarity-camp

this is enough to make someone crazy and most of the content are outdated. Thank heavens, I love reading source codes (to an extent I could navigate my way).

Please someone should drop the link for test doc.

**Comment by friedger** [comment]
https://docs.hiro.so/stacks/clarinet-js-sdk/guides/unit-testing

**Comment by friedger** [comment]
`clarinet fuzz` and `clarinet format` is coming as well

**Comment by kengoon** [comment]
@friedger thanks
