### ISSUE TITLE
Any plans to rewrite these packages in other languages?

### ISSUE THREAD

**Issue by cmd-scholar** [stx-labs/stacks.js#1779]

**Comment by friedger** [comment]
There was an effort some time ago:

Rust: https://github.com/52/stacks.rs

Python: https://github.com/rohitverma007/stackspy

**Comment by cmd-scholar** [comment]
> There was an effort some time ago:
> 
> Rust: https://github.com/52/stacks.rs
> 
> Python: https://github.com/rohitverma007/stackspy

Ohh thanks, it would be nice if its being updated tho, I'm planning on rewriting it in Go with some friends
