### ISSUE TITLE
Funds not received or not showing in blockstack CLI

### ISSUE THREAD

**Issue by mceoin** [stx-labs/stacks.js#178]
I transferred funds to the address provided in my blockstack CLI five days ago. On the send side, it shows transaction is complete. In Blockstack CLI I do not see funds received.

This is the second time I have sent funds to my blockstack address, the first time was successful.
cc. @jcnelson

**Comment by jcnelson** [comment]
Hi @mceoin, thank you for reporting!

I just tried using the following code locally to verify whether or not Blockstack can get the total number of satoshis for your address.  Here's a trace:

```
$ python
>>> import blockstack_client
>>> blockstack_client.backend.blockchain.get_balance('3Bn1DhimaSCUc4MfLoU5Mj2dN4CmNxgfso')
2116534
>>>
```

This is what Blockstack does internally with your address. Can you try the above on your machine?  You can also do it in one line with:

```
$ python -c 'import blockstack_client; print blockstack_client.backend.blockchain.get_balance("3Bn1DhimaSCUc4MfLoU5Mj2dN4CmNxgfso")'
```

This will help me determine if there's a bug is in the UTXO-processing logic itself, in the CLI interface, or in the upstream UTXO service (Blockcypher).

Thanks again!

**Comment by jcnelson** [comment]
I'm guessing this ultimately worked?  Closing the issue here.  If problem persists, please re-open in blockstack-core.
