### ISSUE TITLE
Registration: Pass In Arguments 

### ISSUE THREAD

**Issue by cryptocracy** [stx-labs/stacks.js#182]
When registering a name via cli 
It would be nice if there were a way to include your wallet password and a y for yes for cost confirmation as arguments in the single command.  
example: `blockstack register testname.id WALLETPW y`

**Comment by jcnelson** [comment]
Added in the `rc-0.14.1b` branch of `blockstack-core` (which will incorporate `blockstack-cli` in the next release).  Link: https://github.com/blockstack/blockstack-core/commit/07324a20a93bd4ca51985b8bc457486ffb51ef7c

**Comment by jcnelson** [comment]
Added as `-p/--password` CLI arg.
