### ISSUE TITLE
Blockstack still chokes when using pip3

### ISSUE THREAD

**Issue by cwervo** [stx-labs/stacks.js#188]
This is the error message when I unassumingly used pip with Python3 to download `blockstack`:
```
 File "/Library/Frameworks/Python.framework/Versions/3.4/bin/blockstack", line 94
    print "Would you like to receive an email when there is a new release of this software is available?"

           ^
SyntaxError: Missing parentheses in call to 'print'
```

I don't want to determine the copy, but I'd say being a 2.7 **only** cli is a reasonable thing to put, _prominently_ in the README and on the [set up docs](https://blockstack.org/docs).

**Comment by jcnelson** [comment]
It's not compatible with Python 3.x.  The code now checks and verifies that you're running Python 2.7.x
