### ISSUE TITLE
Add an (approximate) expiry time for names

### ISSUE THREAD

**Issue by vsund** [stx-labs/stacks.js#189]
I did a `blockstack whois vsund.id` to see when I have to renew my name, but there are only blocks for creation and expiry

An (approximate) expire in time would be helpful to have a better understanding for when a renewal is necessary.

---
Related: https://forum.blockstack.org/t/will-you-remove-users-who-are-name-squatting/469/4

**Comment by muneeb-ali** [comment]
@vsund we merged the CLI repo with [blockstack-core](http://github.com/blockstack/blockstack-core) and I moved this issue there. Closing this copy of the issue.
