### ISSUE TITLE
Warn when a name of the wallet is near its expiry

### ISSUE THREAD

**Issue by vsund** [stx-labs/stacks.js#190]
Would be cool to have a warning or reminder when a name in the wallet is near its expiry.
(Configurable with on/off, and a timespan that defines "near")

Auto renewal is also imaginable :)

---
Related: https://forum.blockstack.org/t/will-you-remove-users-who-are-name-squatting/469/4

**Comment by jcnelson** [comment]
I think someone is working on an app for this...
