### ISSUE TITLE
Configuration location improvements

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#191]
I'm working on distributing blockstack with the native macOS app. As part of this, I'd like to make sure that blockstack's configuration gets installed in an appropriate location inside ~/Library (like other macOS apps)

It looks like we can currently set the location of the configuration file using the
`BLOCKSTACK_CLIENT_CONFIG` environment variable. 

Running `BLOCKSTACK_CLIENT_CONFIG=/Users/larry/my-blockstack-config/client.ini` creates that config file and a few other files in that same directory.

1. It seems weird to be able to specific an arbitrary name for `client.ini` but not of the other files.

2. It doesn't seem to be possible to change the location of `BLOCKSTACK_METADATA_DIR` without editing the configuration file after it is created. `BLOCKSTACK_METADATA_DIR` is hardcoded to `~/.blockstack/metadata` even if `BLOCKSTACK_CLIENT_CONFIG` creates another directory.

 I'd expect that metadata would default to being in a subdirectory of the client configuration directory.

Would it make more sense to instead have an environment variable or command line option to specify the a configuration directory and have the layout of files and subdirectories within that folder be consistent? (or am I using this wrong?)

Something like:
`BLOCKSTACK_CLIENT_CONFIG_DIR=~/my-blockstack-config blockstack` 
or 
`blockstack --config=~/my-blockstack-config`

**Comment by muneeb-ali** [comment]
@larrysalibra we're merging CLI into Core. We took care of most earlier Github issues and it's better to start new issues on the Core repo -- thanks!

**Comment by muneeb-ali** [comment]
We've move/migrate any remaining issues from this repo as well. Should be done this week.

**Comment by larrysalibra** [comment]
roger!
