### ISSUE TITLE
Python Version Issue

### ISSUE THREAD

**Issue by mw866** [stx-labs/stacks.js#195]
Received following error running `blockstack` after installation at Ubuntu via pip/pip3:

`
$ blockstack
  File "/usr/local/bin/blockstack", line 58
    print result['result']
               ^
SyntaxError: Missing parentheses in call to 'print'
`

**Comment by mw866** [comment]
Just a follow-up, I suspect it is due to the incorrect shebang: `#!/usr/bin/python3`

However, after changing the shebang to python2.x,  another issue is observed:
`
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
ImportError: No module named blockstack_client.cli
`

**Comment by jcnelson** [comment]
You need to run the code in a directory besides the source directory :)

Also, the code for this project has moved to https://github.com/blockstack/blockstack-core.  If the problem persists, please open an issue there.  Thanks!
