### ISSUE TITLE
circular dependency on blockstore

### ISSUE THREAD

**Issue by muneeb-ali** [stx-labs/stacks.js#20]
We should probably try to remove the circular dependency on blockstore. This will:

a) enable people to install only the client (and not the daemon) 
b) fix the pip install issue where the current hack to get the client is with "pip install blockstore" and "pip install blockstore-client" gives an import error for blockstore

**Comment by jcnelson** [comment]
This can be done, but it will require some code duplication.  In particular, the SNV logic needs to know exactly how to serialize name operations and restore them to different points in time.  This is currently entirely in Blockstore's domain.

**Comment by muneeb-ali** [comment]
Can we avoid code duplication, if we take out the blockstoreDB into a separate repo/package? I'm not sold on this right now and am just throwing it out there. 

One potential benefit can be that if we replace the current DB implementation with say SQLite then the interfaces can stay the same and we can just work on the DB repo for any updates to the underlying DB.

The downside is if blockstore-daemon and blockstoreDB are heavily interdependent then it might not be easy to separate the DB out as a module.

**Comment by jcnelson** [comment]
Actually, I think we can move most of the logic to `virtualchain`.  The only thing the client will still need are some global constants in Blockstore (i.e. opcodes, first block, etc.), but since these won't be changing anytime soon, we can probably get away with duplicating them and not worrying about it.

**Comment by muneeb-ali** [comment]
Yeah duplication values of constant variables should be fine. As you said, they won't be changing much.

Sounds good about moving some of the logic from client to virtualchain. That can resolve the circular dependency stuff.

**Comment by jcnelson** [comment]
should be fixed now
