### ISSUE TITLE
lost btc on registering two domains

### ISSUE THREAD

**Issue by r66ad** [stx-labs/stacks.js#200]
https://blockchain.info/address/3ArkGZmk5oS8i67Wo5s2x2NQyE27JSnNC7

0.06772135 BTC and 0.00398126 BTC
probably lost internet connection.
is it possible to reverse the transactions?

**Comment by larrysalibra** [comment]
Hi @r66ad not sure if you're in the right place. For help with registering Blockstack names, jump on [our slack](http://chat.blockstack.org) or [ask your question in our forum](https://forum.blockstack.org).  

Bitcoin transactions aren't reversible.
