### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by Aranad** [stx-labs/stacks.js#201]
Hello, I have node (4.2.6) and npm (3.5.2) installed, but when I try and do npm install blockstack it installs, gives a big folder tree info and then says this:
npm WARN enoent ENOENT: no such file or directory, open '/var/www/blockstack/package.json'
npm WARN blockstack No description
npm WARN blockstack No repository field.
npm WARN blockstack No README data
npm WARN blockstack No license field.

I thought maybe this means I should be inside the repo dir first, but then it doesn't install, it just immediately gives this:
npm ERR! Linux 4.10.0-20-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "blockstack"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install blockstack as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/blockstack.js/npm-debug.log

This contents of the debug log are:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'blockstack' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData blockstack
8 silly fetchNamedPackageData blockstack
9 silly mapToRegistry name blockstack
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/blockstack
13 verbose request uri https://registry.npmjs.org/blockstack
14 verbose request no auth needed
15 info attempt registry request try #1 at 4:40:07 PM
16 verbose request id badd450f30ede1d4
17 verbose etag W/"58e1ac18-f5ce"
18 verbose lastModified Mon, 03 Apr 2017 01:57:44 GMT
19 http request GET https://registry.npmjs.org/blockstack
20 http 304 https://registry.npmjs.org/blockstack
21 verbose headers { date: 'Fri, 28 Apr 2017 19:40:08 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: 'W/"58e1ac18-f5ce"',
21 verbose headers   age: '123',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-gru7125-GRU',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1493408409.589030,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Fri, 28 Apr 2017 19:40:08 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: 'W/"58e1ac18-f5ce"',
22 silly get     age: '123',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-gru7125-GRU',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1493408409.589030,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/blockstack from cache
24 verbose get saving blockstack to /home/nad/.npm/registry.npmjs.org/blockstack/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install blockstack as a dependency of itself
42 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
42 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
42 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
42 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
42 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
43 verbose cwd /var/www/blockstack.js
44 error Linux 4.10.0-20-generic
45 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "blockstack"
46 error node v4.2.6
47 error npm  v3.5.2
48 error code ENOSELF
49 error Refusing to install blockstack as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by larrysalibra** [comment]
Does this happen on the LTS (v6.10.2) or current (v7.9.0) versions of node?

**Comment by larrysalibra** [comment]
@Aranad Going to close this. Please re-open this issue if you're still having trouble.
