### ISSUE TITLE
Proofs need to check specific html tag

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#204]
See python library for specific tags: 
https://github.com/blockstack/blockstack-proofs-py/blob/master/blockstack_proofs/sites.py
https://github.com/blockstack/blockstack-proofs-py/blob/master/blockstack_proofs/htmlparsing.py#L18

We'll also need to add support for mobile sites:
1. m.facebook.com: class `_5rgt _5nk5`

**Comment by larrysalibra** [comment]
See this for more notes re github proofs: https://github.com/blockstack/blockstack-proofs-py/issues/42#issuecomment-299877977

**Comment by larrysalibra** [comment]
One thing to keep in mind is that facebook serves different sites on different networks in different countries. Here are some screenshots of an example of their free.facebook.com site on a carrier in thailand which is what loads by default when you request `facebook.com`

![img_4886](https://user-images.githubusercontent.com/597182/29836279-c30e20c6-8cc2-11e7-982c-07c16cb40173.PNG)
![img_4887](https://user-images.githubusercontent.com/597182/29836282-c4f63e50-8cc2-11e7-92d1-510d9dbb0daa.PNG)


We'd rather have false negatives instead of false positives.

**Comment by guylepage3** [comment]
@larrysalibra.. we are still a desktop app. we don't have to worry about this until we're on mobile

**Comment by yknl** [comment]
@larrysalibra Would a better approach be to check the meta tags for sites that have it? And fallback to searching in the body and checking the tags for sites that don't.

For Facebook:
`<meta name="description" content="Verifying that +naval is my Bitcoin username. You can send me #bitcoin here: https://onename.io/naval" />`

For Twitter: 
`<meta  property="og:description" content="“Verifying myself: My Bitcoin username is +naval. https://t.co/DdpZv8tMAH #bitcoin”">`

**Comment by shea256** [comment]
> @larrysalibra Would a better approach be to check the meta tags for sites that have it? And fallback to searching in the body and checking the tags for sites that don't.

Ohhh I like this idea. Seems obvious in retrospect.

**Comment by larrysalibra** [comment]
@yknl great!

**Comment by yknl** [comment]
Fixed in 2049e8deaa2416f130ec9e6fe6e804e19acc9875

**Comment by larrysalibra** [comment]
This already shipped.
