### ISSUE TITLE
Protocol handler "web+blockstack:" versus "blockstack:" problems on Linux

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#211]
Blockstack portal registers the `web+blockstack:` protocol handler in `ApiSettingsPage.js:76`

However, `blockstack.js` attempts to use the `blockstack:` protocol handler. This isn't registered in the browser, so it doesn't work, redirecting users to the `https://blockstack.org/auth` page.

If `blockstack.js` switched to using the `web+blockstack` protocol handler, everything works correctly. I'm not sure where to report the issue (here, or in blockstack-portal)?

The issue #205 may be related.

**Comment by larrysalibra** [comment]
The ability to register `web+blockstack:` in browser shouldn't be available anymore.
