### ISSUE TITLE
Multisig Blockstack ID/address support

### ISSUE THREAD

**Issue by ghost** [stx-labs/stacks.js#212]
I am trying to create an auth response following the sample code in documentation using the makeAuthResponse(...) function.

The sample code creates a private key using makeECPrivateKey(...) which I assume needs to be substituted with the real private key of the response sender.

So I figured the next step is to manually fetch such private key from the blockstack wallet by running "blockstack wallet" CLI command in advance mode, however it turns out that my Blockstack wallet is a multisig wallet (all new Blockstack wallets are), so the question is does this library support verification of multisig based address/ID, and if so, can you demonstrate how?

Thanks,
Henry = ]

**Comment by larrysalibra** [comment]
Hey @hentsai we don't yet support multisig addresses in our javascript projects. We will be very soon. You can follow our progress with this issue on the browser: https://github.com/blockstack/blockstack-browser/issues/330#issuecomment-306934409

**Comment by larrysalibra** [comment]
An update to this. We don't have an immediate timeframe for multi address support. It's still something on our radar though. Moving this to backlog.

**Comment by larrysalibra** [comment]
Is there a roadmap for native multisig support for stx? I’m curious and also for the benefit of anyone who happens upon this closed issue.

**Comment by reedrosenbluth** [comment]
@larrysalibra we have multisig support for transactions in this library: https://github.com/blockstack/stacks.js/tree/master/packages/transactions#supporting-multi-signature-transactions

**Comment by larrysalibra** [comment]
Thanks!
