### ISSUE TITLE
doPublicKeysMatchUsername(token) uses the wrong default nameLookupURL format string

### ISSUE THREAD

**Issue by thehenrytsai** [stx-labs/stacks.js#213]
In the case that no name lookup URL is supplied to doPublicKeysMatchUsername(token), the code will use 'https://core.blockstack.org/v1/names/{name}':

  var nameLookupURL = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 'https://core.blockstack.org/v1/names/{name}';

However, later the username supplied in the token will be appended to the format string resulting incorrect URL which will result in lookup error:

'https://core.blockstack.org/v1/names/{name}/somename.id'

**Comment by larrysalibra** [comment]
@thehenrytsai Thank you for reporting this!

**Comment by larrysalibra** [comment]
@thehenrytsai it should be fixed in `v0.3.11`

Thank you again for reporting this!
