### ISSUE TITLE
makeProfileZoneFile makes invalid zone files 

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#215]
`makeProfileZoneFile` removes the protocol (eg. `https://`) and creates a zone file that is invalid according to what blockstack core and our python libraries expect:

The offending line is here: https://github.com/blockstack/blockstack.js/blob/master/src/profiles/profileZoneFiles.js#L23

This is why @pstan26 and others that registered with the portal don't have the profiles appearing properly on the explorer and other places.

This is an example of the type of zonefile this function is currently generating: 
```JSON
{"uri":[{"class":"IN","name":"_http._tcp","priority":10,"target":"www.dropbox.com/s/ffws2zg4silbnip/profile.json?dl=1","weight":1}]}
```

Blockstack Core expects target to be a URI:

```JSON
{"uri":[{"class":"IN","name":"_http._tcp","priority":10,"target":"https://www.dropbox.com/s/ffws2zg4silbnip/profile.json?dl=1","weight":1}]}
```

We have two options:

1. Fix it in blockstack.js and require all users with invalid zone files to issue a `NAME_UPDATE` transaction

2. Fix it in blockstack.js and modify both blockstack.js and blockstack core to prepend `https://` to `target` values if there's not already a protocol specified

I'm leaning towards 2.

Thoughts? @shea256 @jcnelson

**Comment by shea256** [comment]
Yeah option 2 seems like the way to go.

**Comment by jcnelson** [comment]
Option 2.

**Comment by jcnelson** [comment]
I have pushed branch `v0.3.0-core-auth` that always includes the scheme in the URL record (this branch will also include some fixes to core authentication regarding storage and devices, but more on that later).

**Comment by jcnelson** [comment]
Pushed fixes to Core in the `rc-0.14.2-portal` branch.

**Comment by larrysalibra** [comment]
thanks @jcnelson - let me know when you've added tests or if you'd like me to do it!

**Comment by larrysalibra** [comment]
We also need to add support to blockstack.js for resolving profiles missing https.

**Comment by larrysalibra** [comment]
Wait, no, we don't, resolving token files is done in the browser. 

Closing this.
