### ISSUE TITLE
`doPublicKeysMatchUsername` returns CORS error

### ISSUE THREAD

**Issue by scott-martin** [stx-labs/stacks.js#218]
![image](https://user-images.githubusercontent.com/2068545/27399184-f045b082-5689-11e7-8053-5c57f4d77923.png)

I am getting this error when attempting to use the `signUserIn` function. 

From what I can trace, I see a somewhat related bug on line 50 of authApp.js:
```js
if (verifyAuthResponse(authResponseToken)) {
    ...
} else { ... }
```

The function `verifyAuthResponse` defined on line 146 of authVerification.js returns a Promise. A promise is an object, which is truthy, so this line above will always return true. Also the callback function parameter in that function is not being used correctly. The code below would be a correct implementation, converted to use Promises instead of callbacks for consistency with the rest of the library.

```js
export function signUserIn() {
    const authResponseToken = getAuthResponseToken()

    return verifyAuthResponse(authResponseToken)
        .then(isValid => {
            if (isValid) {
                const tokenPayload = decodeToken(authResponseToken).payload
                const userData = {
                    username: tokenPayload.username,
                    profile: tokenPayload.profile,
                    authResponseToken: authResponseToken
                }
                window.localStorage.setItem(
                    BLOCKSTACK_STORAGE_LABEL, JSON.stringify(userData))                
            }

            return isValid;
        });
}
```

I can look through your guidelines and submit this as a pull request if you like. 

The CORS issue when calling `https://core.blockstack.org/v1/names/xxxx` is more likely an issue with the core api, should I make another issue there for that? Thanks in advance for the help!

**Comment by kantai** [comment]
Yes, the CORS issue is indeed an issue with the Core API. I went ahead and added the correct header to the API, so that part should work okay now.

**Comment by scott-martin** [comment]
I still seem to be getting a 404 response back. Although the warning about CORS is gone now.

**Comment by scott-martin** [comment]
Okay so I think the issue is that I am attempting to log in with a user that I have not yet purchased a user id for yet. The client library seems to be using the "address", but I'm guessing the API doesn't actually accept addresses instead of ids. Does that sound right? 

Example: `https://core.blockstack.org/v1/names/15hY9DPZHixmR6SXZLqoemWHyURaMzskHq`

**Comment by larrysalibra** [comment]
@scott-martin great find! A PR would be great!

> Okay so I think the issue is that I am attempting to log in with a user that I have not yet purchased a user id for yet. The client library seems to be using the "address", but I'm guessing the API doesn't actually accept addresses instead of ids. Does that sound right?

The API doesn't accept addresses, that's correct. You've actually found a problem with the Browser! 
We have an error where when logging in without a username on a profile, it sends the address as the username. It should not send a username. I've open an issue here and will fix it in our next release which should ship tomorrow. https://github.com/blockstack/blockstack-browser/issues/548

Thank you @scott-martin so much for reporting this! Sorry about sending you down a rabbit hole.

**Comment by scott-martin** [comment]
Great, glad to help! I will also make a pull request with those JavaScript issues I pointed out above then.

**Comment by larrysalibra** [comment]
Thank you again for your help with this @scott-martin
