### ISSUE TITLE
Where should the private key used to sign authentication requests come from?

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#222]
@jcnelson Where should the private key used to sign the authentication request come from? 

I see in the demo that it is hard coded into the app:
https://github.com/jcnelson/hello-blockstack-nth-time/blob/master/public/app.js#L5

**Comment by shea256** [comment]
### Definitions

- **App signing private key**: A key used by the app to sign data generated by the user while using the app. It is to be generated from the user's keychain and passed by the browser portal to the application.
- **Key decrypting private key**: A private key that is randomly generated by the app that is to be used to decrypt the incoming "app signing private key" passed from core.
- **Key encrypting public key**: A public key derived from the "key encrypting private key" that is to be passed to core and used by core to encrypt the "app signing private key".

### Actions

1. The app randomly generates a "key decrypting private key" behind the scenes.
2. The app passes the "key encrypting public key" to the browser portal.
3. The browser portal / core combo generates the "app signing private key" from the user's keychain.
3. The browser portal encrypts the "app signing private key" with the "key encrypting public key" and then passes it over to the app.
4. The app decrypts the "app signing private key" and then saves it in local storage.

**Comment by larrysalibra** [comment]
My question is answered. Thank you.
