### ISSUE TITLE
Cleaning up api & add documentation

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#223]
We're cleaning up the blockstack.js api so that it has sensible defaults, hides complexity from users and is self documenting.

From [a slack discussion](https://blockstack.slack.com/archives/C074LC7RC/p1498665647554381) this api got positive reviews: 
```
blockstack.redirectToSignIn()
blockstack.isSignInPending()
blockstack.handlePendingSignIn()
```

**Comment by kantai** [comment]
Closing this, as it dealt with older documentation/api issues that were eventually resolved and then supplanted by new documentation issues. Will open a different issue for tracking future blockstack.js documentation plans.
