### ISSUE TITLE
Provide a mechanism to set core node for name to address lookups

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#224]
Right now log in verification defaults to core.blockstack.org

**Comment by larrysalibra** [comment]
Making this high-priority because we need to re-enable name verification ASAP.

**Comment by larrysalibra** [comment]
This is something we should consider during a review of our authentication process and creation of a formal specification.

Apps need to know which core node the user trusts. It is also important for using name functionality in regtest mode.

**Comment by yknl** [comment]
Superseded by https://github.com/blockstack/blockstack.js/pull/668
