### ISSUE TITLE
Interact with raw zone files

### ISSUE THREAD

**Issue by vsund** [stx-labs/stacks.js#228]
For storing [polls](https://github.com/ntzwrk/beacon/issues/9) and [votes](https://github.com/ntzwrk/beacon/issues/10) in Beacon I need to interact with zone files to read/write arbitrary data (also related to https://github.com/blockstack/blockstack.js/issues/229).

I need to:
* read data from zone files
* write data to zone files
* filter / search through zone files

I talked with @jcnelson about the last thing and he meant that Core needs to do the heavy work for this since it needs to hold all zone files for this.

**Comment by shea256** [comment]
@vsund Why does this data need to be included in the zone files? Could it be included in files referenced from the zone file, like token files (which contain profiles)?

**Comment by vsund** [comment]
The problem is availability. Storing poll and vote data on 3rd party servers would (at least theoretically) allow DDoS of certain polls or votes. Using multiple servers would make this more unlikely, but though would not prevent it completely.
I wrote up the requirements for Beacon's storage [here](https://github.com/ntzwrk/beacon/blob/develop/docs/architecture.md).

**Comment by shea256** [comment]
Gotcha ok, thanks for sharing that.

But now I'm thinking that users could self-host their votes and a series of app-specific replica servers could cache the votes and maintain complete copies. It seems like that solves the problem without requiring a bitcoin transaction for every vote.

@jcnelson @muneeb-ali @kantai may have further thoughts on this.

**Comment by jcnelson** [comment]
@shea256 I'm not too worried about using Atlas for this.  Many ballots can be cast in a single Atlas write, so the cost can be amortized.

@vsund is right about vote availability.  In particular, a network adversary can trick the pollster into believing that you either never voted at all (by DDoS'ing your provider).  Also, if the voting protocol allows you to change your mind before the final tally, then hosting the vote in 3rd party servers allows the network adversary to send the pollster stale copies of your vote (by caching your old vote and preventing the pollster from reading your new one).  The only way to stop this latter attack is to ensure every participant sees every vote.

One hybrid approach would be to have the pollster take a snapshot of the votes and write the snapshot to the Atlas network (e.g. the pollster could write the Merkle root of all ballots and store the Merkle tree and ballots in a 3rd party server for auditing purposes).  Voters would have a period of time to refute the pollster's results by showing that their vote was not tallied.  If there are any missing ballots, the pollster would incorporate them and send out a new snapshot.

**Comment by vsund** [comment]
> Many ballots can be cast in a single Atlas write, so the cost can be amortized.

This somehow sounds centralized. Who would write the votes to Atlas? And how would be ensured that he really does (and in time)?

Also, the hybrid approach sounds a bit centralized too. Although voters could check the snapshot, it may be too late when they recognize that their vote didn't count (or do you have a solution for this in mind?). Another thing is, that we probably want polls to be still reproducible after some time maybe even stay completely forever.

**Comment by kantai** [comment]
> Also, the hybrid approach sounds a bit centralized too. Although voters could check the snapshot, it may be too late when they recognize that their vote didn't count (or do you have a solution for this in mind?).

One solution here could be that the aggregator service responds with a certificate that is essentially a signed promise to include your vote in the next published batch. If the aggregator doesn't publish the vote in its next zonefile update (which could be every block during a voting period), the voter would have very fast proof of tampering. This is a somewhat centralized approach, but it would reduce the cost of voting.

I think as a first approach, each vote writing an update to the blockchain and a zonefile to Atlas should work okay. Each vote will be somewhat expensive, though (about USD 2.50 right now).

**Comment by kantai** [comment]
With regards to supporting raw zonefile interactions in blockstack.js, this will require applications to request and receive an `update` permission in their session token. This permission allows the application to queue a transaction (i.e., spend the user's money), which means that we'd want a dialog indicating the request to the user during the login approval.

**Comment by larrysalibra** [comment]
This falls into a broader category of providing a mechanism to ask the browser to generate transactions from the user's browser wallet on its behalf. 

It also falls into a category of examining the functionality and schema of the `blockstack:` custom protocol handler and determining what level of extensibility we want to support for it.

**Comment by vsund** [comment]
@larrysalibra I think we are tackling one additional (separate) issue here: Searching/filtering through zone files. Core can perform better on these than a client-side app could and I think it would also be handy for some apps (i.e. @cryptocracy's Souq).

There's currently an endpoint for searching through profiles. An endpoint for zone file searches would look mostly the same :)

**Comment by cryptocracy** [comment]
Any native (blockstack) searching of zone file contents would be really convenient, especially for Souq's implementation constraints.  
like a `blockstack find_in_zone {{string}}` (where `string` would be the parameter to search for in all known zone files) and the response would be an array of names that contains the given `string` in their zonefile.
Side Note: another good idea would be to also have potentially a limiting parameter to constrain the results returned by what namespace they live on. Ie `blockstack find_in_zone id {{string}}`

**Comment by larrysalibra** [comment]
We still don't provide an easily method for reading zone files in our api - this could be achieved by fetching the core endpoint, but we should provide a convenience method.

**Comment by kantai** [comment]
We actually do kind of have a method for this:

network.getNameInfo -> https://github.com/blockstack/blockstack.js/blob/master/src/network.js#L142

returns a nobject with a `zonefile` key -- of course, our network object isn't the easiest thing to interact with, because it gets called through `blockstack.config.network.getNameInfo()`
