### ISSUE TITLE
Store arbitrary data in zone files

### ISSUE THREAD

**Issue by vsund** [stx-labs/stacks.js#229]
In order to realize https://github.com/blockstack/blockstack.js/issues/228 it's necessary to be able to store arbitrary data in zone files. I think a TXT record would fit very well.

This needs a change in [`profileZoneFiles.js`](https://github.com/blockstack/blockstack.js/blob/master/src/profiles/profileZoneFiles.js) to support additional TXT records.

**Comment by larrysalibra** [comment]
You can do that with this `broadcastZoneFile` method: http://blockstack.github.io/blockstack.js/index.html#broadcastzonefile
