### ISSUE TITLE
Authentication without a username is broken

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#230]
@jcnelson I noticed you changed the authentication code to require a username:

https://github.com/blockstack/blockstack.js/commit/fce4f06ff922b205ab1d84083c7f3445d2621c0b

This makes it so people can no longer log into apps (like hello blockstack and the forum) without having first registered a blockchain id.

Is a blockchain id a requirement of storage?

**Comment by jcnelson** [comment]
Ah, I didn't realize.  I'll revert that.

**Comment by jcnelson** [comment]
Digging through the code more, it will be necessary for the caller to supply a blockchain ID if they want to use storage.  This shouldn't affect login, though.

**Comment by larrysalibra** [comment]
Login without storage isn't really useful for most app use cases. What is preventing us from using storage without a blockstack id in single player mode? 

I think it's really important to minimize user on-boarding pain that they be able to use storage without having to have a blockchain id. Login without ability to use storage isn't terribly useful.

What do you think @jcnelson @shea256?

**Comment by jcnelson** [comment]
Blockchain IDs are needed for multi-player storage, since that's how two people discover each other's public keys.  They are not needed for single-player, however.  I will need to spend some time working on tweaking the implementation so it does not expect a blockchain ID in the single-player case.

**Comment by guylepage3** [comment]
Today I tried to execute the Blockstack To Do List Tutorial and got to the "Log in with Blockstack," clicked the log in button, was taken to the app approval view, clicked "Approve" but nothing happened.

I tried to execute this sequence of events twice. Once without a temporary id created and once with one created but achieved the same results.

**Comment by larrysalibra** [comment]
This is fixed in [v0.8.3](https://github.com/blockstack/blockstack.js/releases/tag/v0.8.3) and works for me against core rc-0.14.3. Please re-open if it occurs in any later versions.
