### ISSUE TITLE
Can't sign in to Blockstack Apps

### ISSUE THREAD

**Issue by jay-ithiel** [stx-labs/stacks.js#231]
I'm not able to sign in to any Blockstack Apps and I can't figure out what the underlying cause is.

I initially had two profiles without usernames and I was able to login to Blockstack Apps. Last week, I bought my first username for one of the profiles. Since purchasing the username, I haven't been able to sign in to any Blockstack Apps. Not even the "Hello Blockstack!" tutorial app. 

I kept getting `auth/components/AuthModal.js: login(): this profile 1HNfZgTFWnnoJauMB7gJBVJbNT7Dj23Nkb has no username`. At this point in time, I had two profiles: 1 with a username and 1 without. So I went ahead and purchased another username for the second profile to clear the error. But I got that same error again which stumped me because I bought usernames for both my profiles. Upon going back to the 'Profiles' page on Blockstack Browser, there was a brand new third profile without a username. Idk how it was created because I didn't create a third profile. It just magically appeared

Larry raised a couple issues about not being able to signin without username
[Can't sign in without username](https://github.com/blockstack/blockstack-browser/issues/601),
[Authentication without a username is broken](https://github.com/blockstack/blockstack.js/issues/230)
so I thought maybe I was having the same issue, but Larry said this was fixed in [v0.8.3](https://github.com/blockstack/blockstack.js/releases/tag/v0.8.3) yet I still can't log in using v0.8.3

This is what gets logged in console when I click 'Sign In with Blockstack':
```
2017-07-10T13:07:31.799-0700 INFO utils/logging-utils.js: Logging system enabled
main.js:153963 2017-07-10T13:07:31.812-0700 INFO utils/logging-utils.js: Log server: http://localhost:8333/
main.js:153963 2017-07-10T13:07:31.815-0700 TRACE index.js: NODE_ENV is not production
main.js:153963 2017-07-10T13:07:31.816-0700 DEBUG index.js: Enabling React devtools
main.js:153963 2017-07-10T13:07:31.842-0700 TRACE App.js: componentWillMount
main.js:153963 2017-07-10T13:07:31.992-0700 TRACE account/store/account/actions.js: refreshCoreWalletBalance: Beginning refresh...
main.js:153963 2017-07-10T13:07:31.994-0700 DEBUG account/store/account/actions.js: refreshCoreWalletBalance: addressBalanceUrl: http://localhost:6270/v1/wallet/balance
main.js:153963 2017-07-10T13:07:32.006-0700 TRACE App.js: performSanityChecks
main.js:153963 2017-07-10T13:07:32.007-0700 DEBUG store/sanity/actions.js: isCoreRunning: http://localhost:6270/v1/node/ping
main.js:153963 2017-07-10T13:07:32.009-0700 DEBUG utils/api-utils.js: isCoreApiRunning: http://localhost:6270/v1/node/ping
main.js:153963 2017-07-10T13:07:32.010-0700 DEBUG store/sanity/actions.js: isCoreApiPasswordValid: http://localhost:6270/v1/wallet/payment_address
main.js:153963 2017-07-10T13:07:32.011-0700 DEBUG utils/api-utils.js: isApiPasswordValid: http://localhost:6270/v1/wallet/payment_address
main.js:153963 2017-07-10T13:07:32.015-0700 DEBUG App.js: Sanity check: Core API endpoint is running!
main.js:153963 2017-07-10T13:07:32.016-0700 ERROR App.js: Sanity check: Error! Core API password is wrong!
main.js:153963 2017-07-10T13:07:32.244-0700 DEBUG App.js: Sanity check: Core API endpoint is running!
main.js:153963 2017-07-10T13:07:32.245-0700 ERROR App.js: Sanity check: Error! Core API password is wrong!
:6270/v1/wallet/balance Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
main.js:153963 2017-07-10T13:07:37.819-0700 ERROR account/store/account/actions.js: refreshCoreWalletBalance: error refreshing balance [TypeError: Failed to fetch]
TypeError: Failed to fetch
:6270/v1/wallet/payment_address Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
main.js:153963 2017-07-10T13:07:37.833-0700 ERROR utils/api-utils.js: isApiPasswordValid: problem checking http://localhost:6270/v1/wallet/payment_address [TypeError: Failed to fetch]
TypeError: Failed to fetch
main.js:153963 2017-07-10T13:07:37.834-0700 DEBUG store/sanity/actions.js: isCoreApiPasswordValid? No!
:6270/v1/node/ping Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
main.js:153963 2017-07-10T13:07:37.847-0700 ERROR utils/api-utils.js: isCoreApiRunning: problem checking http://localhost:6270/v1/node/ping [TypeError: Failed to fetch]
TypeError: Failed to fetch
main.js:153963 2017-07-10T13:07:37.855-0700 DEBUG App.js: Sanity check: Core API endpoint is running!
main.js:153963 2017-07-10T13:07:37.857-0700 ERROR App.js: Sanity check: Error! Core API password is wrong!
console.log('before approving signin request');
VM86:1 before approving signin request
undefined
main.js:153963 2017-07-10T13:09:10.204-0700 DEBUG auth/components/AuthModal.js: login(): this profile 1HNfZgTFWnnoJauMB7gJBVJbNT7Dj23Nkb has no username
main.js:153963 2017-07-10T13:09:10.206-0700 ERROR window.addWindowListener('error'): { isTrusted: [Getter] }
main.js:153963 2017-07-10T13:09:10.209-0700 ERROR window.onerror: Uncaught TypeError: Cannot read property 'length' of undefined [TypeError: Cannot read property 'length' of undefined]
TypeError: Cannot read property 'length' of undefined
    at decodeUnsafe (http://localhost:8888/js/main.js:17086:15)
    at Object.decode (http://localhost:8888/js/main.js:17114:17)
    at Object.decode (http://localhost:8888/js/main.js:43304:22)
    at Function.HDNode.fromBase58 (http://localhost:8888/js/main.js:31651:28)
    at AuthModal.login (http://localhost:8888/js/main.js:2713:72)
    at Object.invokeGuardedCallback (http://localhost:8888/js/main.js:108193:5)
    at executeDispatch (http://localhost:8888/js/main.js:102228:21)
    at Object.executeDispatchesInOrder (http://localhost:8888/js/main.js:102248:7)
    at executeDispatchesAndRelease (http://localhost:8888/js/main.js:101653:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8888/js/main.js:101664:10)
main.js:17086 Uncaught TypeError: Cannot read property 'length' of undefined
    at decodeUnsafe (main.js:17086)
    at Object.decode (main.js:17114)
    at Object.decode (main.js:43304)
    at Function.HDNode.fromBase58 (main.js:31651)
    at AuthModal.login (main.js:2713)
    at Object.invokeGuardedCallback (main.js:108193)
    at executeDispatch (main.js:102228)
    at Object.executeDispatchesInOrder (main.js:102248)
    at executeDispatchesAndRelease (main.js:101653)
    at executeDispatchesAndReleaseTopLevel (main.js:101664)
```

**Comment by shea256** [comment]
@jay-hwang I ran into the same issue.

The redux state tree has changed since the previous version and I think you'll have to delete your account and local storage state and then start over.

You can save your backup phrase and then restore your account from the phrase.

You'll lose any names you registered but you can always manually recover it with help from @larrysalibra.

If you're ok with doing this, here's how you clear your local storage state:

```
localStorage.clear()
```

**Comment by shea256** [comment]
Also the update to allow for sign in without usernames should be pushed to the latest version of Blockstack Core. I'm just not sure if it's been incorporated into the browser package. I'll let @jcnelson @kantai and @larrysalibra comment on this.

**Comment by jay-ithiel** [comment]
@shea256 Great thanks! I'll try this out

**Comment by jay-ithiel** [comment]
I tried to backup my account and delete it, but I couldn't enter the password correctly. I use the same 4/5 passwords for everything (I know this is bad security but it feels so good to never forget your password) so I'm guessing I made a typo when first creating my password. 

I removed Blockstack from my computer, re-installed it and made a brand new account. I can finally sign in now, and Blockstack storage works (hooray!)

I noticed there's only one password input field when creating a new account. I think it would be good to have a second 'password confirmation' input, so if someone makes a typo and the two passwords don't match, it throws an error. I'll raise a separate issue for this.

**Comment by pstan26** [comment]
Just installed @jay-hwang's decentralized blog app "Guild" and could not sign in due to this issue. cc @larrysalibra 

![screen shot 2017-07-13 at 1 49 08 pm](https://user-images.githubusercontent.com/5605552/28180719-fa94d184-67d3-11e7-9a9a-ff750c7ef021.png)


The release notes (which who knows if anyone is reading thoroughly) make it feel like the experience is so prickly that shouldn't even try this developer release out.
<img width="635" alt="screen shot 2017-07-13 at 12 07 25 am" src="https://user-images.githubusercontent.com/5605552/28180854-72e6f090-67d4-11e7-9209-8baa268ab53c.png">

**Comment by larrysalibra** [comment]
This isn't the right repository for problems with Blockstack Browser.  Please open an issue on https://github.com/blockstack/blockstack-browser if you're still having a problem.
