### ISSUE TITLE
Store arbitrary data in user's profile

### ISSUE THREAD

**Issue by scott-martin** [stx-labs/stacks.js#232]
I have some situations where a user might want to elect to make certain data public. It would be nice to be able to store pointers to this public data in their profile so that it is discoverable.

**Comment by larrysalibra** [comment]
This functionality exists now as part of our multi-reader storage feature! Thanks for suggesting this @scott-martin !

Was merged from this pull request: https://github.com/blockstack/blockstack.js/pull/324
