### ISSUE TITLE
Finalize 1.0 of the API

### ISSUE THREAD

**Issue by shea256** [stx-labs/stacks.js#235]

**Comment by shea256** [comment]
# Blockstack API Interface

Petition to move forward with locking these particular API calls:

### Auth

- redirectToSignIn
- isSignInPending
- handlePendingSignIn
- loadUserData
- isUserSignedIn
- signUserOut

### Storage

- putFile
- getFile
- deleteFile

### Profile

*to be determined*

**Comment by shea256** [comment]
We're adding "listFiles" to this as well as per @jcnelson's comment.

**Comment by vsund** [comment]
Seems like this is some kind of API specification for `blockstack.js`. Would be straight forward to release them a bit more process-like and add versions of them to resolve https://github.com/blockstack/blockstack/issues/381 and the problems described there :)

**Comment by larrysalibra** [comment]
Closing this as we're now at version 18 :-)
