### ISSUE TITLE
Blockstack account restoration doesn't work with older accounts

### ISSUE THREAD

**Issue by jay-ithiel** [stx-labs/stacks.js#238]
I deleted and restored my account after updating the Blockstack Browser to the latest release (v12).
It asked me for my Identity Key, whereas in previous versions it asked me for my Backup Phrase. 
Coming from a previous browser version, I had the Backup Phrase and not the Identity Key. I figured it was different names for the same thing, so I entered my Backup Phrase and finished restoring my account with no problems. But then I went to `/profiles`, and my profile was gone. It had a throwaway profile instead of the profile I purchased a username for.

I'm guessing there is a discrepancy from restoring accounts made before Browser v12, since <v12 used a Backup Phrase, instead of an Identity Key. Is there a quick fix I could do on my end to restore my account or is it something the team will have to work on?

Cheers

**Comment by jay-ithiel** [comment]
cc @jcnelson @larrysalibra @kantai

Still having trouble recovering my account. Any ideas?

**Comment by jay-ithiel** [comment]
I know the team is busy and this isn't a pressing issue - just thought I'd share it

Made a quick video on youtube running through the problem.
[blockstack account restoration](https://www.youtube.com/watch?v=narIdbQIHyk&feature=youtu.be)

Maybe an option to restore an account via either backup phrase or identity key would fix this

**Comment by shea256** [comment]
Thanks @jay-hwang sorry for the delay on this. @larrysalibra and I will take a look at this soon and help out.

**Comment by jay-ithiel** [comment]
Closing and moving to blockstack-browser
