### ISSUE TITLE
Get arbitrary profile tokens as required by extractProfile()

### ISSUE THREAD

**Issue by vsund** [stx-labs/stacks.js#240]
I'm trying to fetch profiles (with a given name). There's `extractProfile()` that decodes a profile token. We need a way to get the respective profile token from the Core endpoint to complete getting profiles given only a name.

**Comment by larrysalibra** [comment]
You can use the `lookupProfile` function here: https://github.com/blockstack/blockstack.js/blob/fd8dc3fbfcb8993954f1da7275af00881fd8c0d6/src/profiles/profileLookup.js#L12 which resolves, verifies and decodes a profile token from a name to zonefile lookup core endpoint.
