### ISSUE TITLE
Core session tokens expire

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#241]
Core session tokens are currently good for 1 week when created, but then they expire.  We can push this higher (1 month), but the blockstack.js library should nevertheless determine when this happens and redirect the user to sign in again.

cc @larrysalibra for his thoughts.

**Comment by larrysalibra** [comment]
This seems like a question with a lot more implications than simply redirecting the user to log in again.

I can imagine situations where you would want apps to function indefinitely after first authorization. For example, if I want to give an app permission to write some information automatically on my behalf, having to log in again even once a month would be a huge problem.

To draw parallels to the real world. When I sign in with facebook - say with Tinder - I only have to do it once. The only time I have to do it again is if I revoke the authorization to that app. 

The user "signing in" doesn't necessarily have to correspond to the length of validity of a token. As we discussed at the Decentralized Identity Foundation hackathon, oauth has functionality that allows tokens to expire and be programmatically refreshed.

---

In the short term, handing token expiration would require something like an interface that lets the app add a "signed out" event listener or something along those lines.

**Comment by shea256** [comment]
@larrysalibra Yes that's true. Although if we are to move to a system where tokens don't expire, then we'd need to keep a list of outstanding tokens and have an interface in the browser where you can revoke individual tokens.

That actually seems like a better model in my view and actually makes sense when we move over to S3 api keys (and the like). Essentially we'd be doing away with core tokens and using just S3 api keys. Then we'll allow users to revoke individual keys corresponding to individual apps.

**Comment by larrysalibra** [comment]
With the direct to gaia storage system, we no longer use core session tokens. Closing this as no longer relevant.
