### ISSUE TITLE
Stabilize more file operations

### ISSUE THREAD

**Issue by vsund** [stx-labs/stacks.js#246]
For the coin-operated file viewer I need some more advanced file operations as `mkdir()`, `listdir()`, `deleteFile()`, `rmdir()`.

How's the progress with stabilizing these methods? Alternatively I could use the unstable methods from `blockstack-storage-js`, but it seems that they won't change massively later.

**Comment by jcnelson** [comment]
We are going to be dropping support for directories in Gaia v2.  The supported operations going forward will be `getFile()`, `putFile()`, `deleteFile()`, and `listFiles()`.

**Comment by vsund** [comment]
How's the rough ETA for this? :)

**Comment by shea256** [comment]
@jcnelson That's an awesome set of operations. Love it.

**Comment by jcnelson** [comment]
@vsund I'm aiming for end of next week.  I'm currently working through this issue, which will determine what has to happen for the rest of the implementation: https://github.com/blockstack/blockstack-core/issues/556

**Comment by larrysalibra** [comment]
We've switched to the new storage model that removes directories as mentioned above. Let's move the discussion for any additional storage api methods we need to this thread about finalizing the 1.0 API: https://github.com/blockstack/blockstack.js/issues/235
