### ISSUE TITLE
open pop-up window (instead of tab) for login

### ISSUE THREAD

**Issue by alidcast** [stx-labs/stacks.js#247]
Right now when you use the sign in helpers, e.g. `redirectToSignIn`, a new tab is opened for login and then when you sign in, you're redirected back to the app in the new tab.  The result is that you have two tabs for the same site open.

It seems like this is handled in @larrysalibra's  [custom-protocol-dectecion](https://github.com/edwardstumpf/custom-protocol-detection) fork. Is there a reason you went with this approach?

Another related issue is that if I sign-in to a Blockstack app in a browser that is not my default browser, e.g. safari, then the new tab is opened in my default browser, e.g. Chrome. 

User sign in, as a developer and user, is one of the first points of contact with a Blockstack app, so I'd like to make this as flawless as possible.  Ideally, it works like most external sign-ins. For example, if I sign into Dropbox with Google, a pop-up window is open, I sign in, and then the pop-up self-closes and I'm redirected to the app's page.

**Comment by shea256** [comment]
@alidcastano Thanks for bringing this up. We're actually working to eliminate this problem by moving the dashboard out of the browser and into a separate desktop app.

I'm sure in the short term we can do something with preventing a second window from opening but not sure what the constraints are.

I'll let @larrysalibra comment here. Tagging @jackzampolin as well.
