### ISSUE TITLE
storage documentation / advice

### ISSUE THREAD

**Issue by alidcast** [stx-labs/stacks.js#248]
This is semi-related to #246 about stabilizing more file operations. 

With only `putFile` and `getFile` right now, how should storage be handled when 1) you need to access user specific data and 2) you need to access data for all users?

I've tried to look at other open-source Blockstack apps. [Beacon](https://github.com/ntzwrk/beacon) seems to be in its early development or at least its changes are not public. [Guild](https://github.com/jay-hwang/guild/) seems to be saving all the data in one file and iterating to find that of the correct user data (see [here](https://github.com/jay-hwang/guild/blob/master/src/util/blog_api_util.js) for source), but, unless I'm misunderstanding how storage works, this doesn't seem like an approach that will scale well.

I'll hack together an approach in the meantime but would prefer to know the proper way of handling storage. Thanks!

**Comment by shea256** [comment]
@alidcastano Hey thanks for starting this issue.

Can you explain what you mean by "access user specific data"? Do you mean that you have a central server and you want the locally stored data to be relayed back to your central server? Or do you mean that you have user A's data that needs to be seen by user B?

Regarding "access data for all users", can you elaborate on your use case? For fully decentralized apps this isn't possible because there is no central server or "mothership". That said, you can always include a call where user data is copied and synced to a central server. Highly depends on what you're trying to do.

Our ideal model for applications here is that we can eliminate the need for central servers at all. So apps like marketplaces and social networks need to be rethought. Very different approach and very different way of thinking.

Would love to know what app you're building. Happy to provide further guidance.

**Comment by alidcast** [comment]
@shea256 Thanks for the quick response.

Based on your response, I likely need to rethink my approach which is anchored on a central server way of thinking about storage.

I'm experimenting with a social note-taking app. The closest equivalent would be Quizlet.

So the basic functionality would be: 
- User A can write and access their data (e.g. notebooks and notes).
- User B can see user A's data.

And vice-versa.

What's the recommended way of handling this via only `putFile` and `getFile`? 

Related question: so when you do `puFile`, user A's data is first being stored with all the other users' data in a decentralized fashion, then only user A's data is synced to a central location (e.g. his or hers Dropbox account)?

**Comment by alidcastano** [comment]
To add to the discussion I'll post relevant snippets of how current blockstack apps currently handle storage.

This is how the todos app handles storage (via vue component) : 

```

 watch: {
    todos: {
      handler: function (todos) {
        const blockstack = this.blockstack
        return blockstack.putFile(STORAGE_FILE, JSON.stringify(todos))
      },
      deep: true
    }
  },
....
methods: {
    fetchData () {
      const blockstack = this.blockstack
      blockstack.getFile(STORAGE_FILE)
      .then((todosText) => {
        var todos = JSON.parse(todosText || '[]')
        todos.forEach(function (todo, index) {
          todo.id = index
        })
        this.uidCount = todos.length
        this.todos = todos
      })
    }
}
```

This is how the guild app handles storage: 

```

export const saveBlogs = (blogs, dispatch) => {
  putFile(STORAGE_FILE, JSON.stringify(blogs)).then(isBlogSaved => {
    let user = loadUserData();
    if (isBlogSaved) { window.location = `/blogs/${user.username}`}
  });
}

export const fetchBlogs = dispatch => {
  var blogs = {}, blogIndex = 0;

  getFile(STORAGE_FILE).then(blogItems => { // eslint-disable-line
    blogItems = JSON.parse(blogItems || '[]');

    Object.keys(blogItems).forEach((id, index) => {
      blogItems[id].id = index+1;
      blogs[index+1] = blogItems[id];
      blogIndex = index+1;
    });

    dispatch(receiveBlogs(blogs, blogIndex));
  });


export const fetchUserBlogs = (user, dispatch) => {
  var userBlogs = {};

  getFile(STORAGE_FILE).then(blogItems => {
    blogItems = JSON.parse(blogItems || '[]');

    Object.keys(blogItems).forEach(id => {
      if (isBlogAuthor(blogItems[id], user)) {
        userBlogs[id] = blogItems[id];
      }
    });

    dispatch(receiveUserBlogs(userBlogs));
  });
};
```

They both store the core user content via a single file, e.g. `todos.json` or `blogs.json`. What I don't get is why does `guild` have to filter the user data, while the `todo` app doesn't. In other words,  is all user data being put in a single file or is it just the data of that specific user? 

I'll be testing both approaches out soon but just laying down my thoughts here in the meantime.
