### ISSUE TITLE
Add test for optional redirect feature 

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#249]
We need to add a test for #243

**Comment by abhishek71994** [comment]
Hello, I saw the label and felt that I could contribute. If you point me towards the direction in which I should approach, that would be very helpful. 
Thanks.

**Comment by citizens** [comment]
@larrysalibra I took a stab at writing the test: #344

**Comment by larrysalibra** [comment]
This was fixed by @citizens ! Thank you!
