### ISSUE TITLE
Implement new address based verifications system

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#250]
We're moving from a name-based verification system to an address based verification system that will allow users to verify control over their social media accounts by the same person that controls the private key of the address that owns their avatar.

This is the format of verification message:
`Verifying my avatar on Blockstack is owned by the address 19MoWG8u88L6t766j7Vne21Mg4wHsCQ7vk https://avatar.blockstack.org/address/19MoWG8u88L6t766j7Vne21Mg4wHsCQ7vk`

**Comment by yknl** [comment]
Implemented in 8b4bedcfea95f97089d86a18189637f95ce7f24f

**Comment by larrysalibra** [comment]
@yknl 

We're going to tweak the verification message. See https://github.com/blockstack/blockstack-browser/issues/765 for discussion & reasoning.

New format
```
Verifying my blockchain ID is secured with the address 19MoWG8u88L6t766j7Vne21Mg4wHsCQ7vk

https://id.blockstack.org/address/19MoWG8u88L6t766j7Vne21Mg4wHsCQ7vk
```

**Comment by larrysalibra** [comment]
This has already shipped .

**Comment by shea256** [comment]
@larrysalibra Can we please confirm that the verification message is the following?

```
Verifying my Blockstack ID is secured with the address 19MoWG8u88L6t766j7Vne21Mg4wHsCQ7vk
https://explorer.blockstack.org/address/19MoWG8u88L6t766j7Vne21Mg4wHsCQ7vk
```

**Comment by shea256** [comment]
Actually I see #263 is open. I'll comment on there.
