### ISSUE TITLE
Add additional service verification support

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#251]
Currently we support facebook, twitter and github.

Here's a list of all the service types we want to eventually support:

![29775517-6d7acffa-8bd3-11e7-9fb5-81ba34772014](https://user-images.githubusercontent.com/597182/29836820-5a8f1454-8cc4-11e7-8dd6-c143bfce9c78.png)

We don't have to tackle these all at once. 

Let's add a few high priority ones in this sprint and then open issues for others and mark them with the label `help-wanted`.

**Comment by guylepage3** [comment]
Twitter
Facebook
GitHub
Instagram
LinkedIn
Tumblr
Reddit
Pinterest
YouTube
AngelList
StackOverflow
Hacker News
Snapchat

**Comment by shea256** [comment]
Also considering:

- Yelp
- Foursquare
- SoundCloud
- GoodReads

Let's prioritize the following:

- Instagram
- Hacker News
- LinkedIn

**Comment by larrysalibra** [comment]
We can break these out out into one issue per service: these issues would be great for community members to take stab at. Documenting the interface for services would help as well.

**Comment by larrysalibra** [comment]
If you'd like to add an additional service, please create a new issue for that service and paste a link to the issue into a comment here. We'll happy accept pull requests. Let us know if you have any questions!
