### ISSUE TITLE
Out of sync `loadUserData` documentation

### ISSUE THREAD

**Issue by ootoovak** [stx-labs/stacks.js#255]
Hello, I _think_ I have come across out of sync documentation.

The `loadUserData` example in the [README file (step number 5)](https://github.com/blockstack/blockstack.js/tree/master/src/auth#quickstart) shows it accepting a callback function:
```js
blockstack.loadUserData(function(userData) {
  showProfile(userData.profile)
})
```
But when it wasn't working for me so I looked at [the code](https://github.com/blockstack/blockstack.js/blob/f6f587e458fdae866bfdefd1050cfe2406e170ec/src/auth/authApp.js#L154-L156) and it looks like it doesn't accept any arguments and instead just returns a result:
```js
export function loadUserData() {
  return JSON.parse(window.localStorage.getItem(BLOCKSTACK_STORAGE_LABEL))
}
```

**Comment by jackzampolin** [comment]
@ootoovak This looks like a docs issue! Please feel free to open a PR with a fix!

**Comment by larrysalibra** [comment]
Thanks for pointing this out @ootoovak - I updated the doc.
