### ISSUE TITLE
Story: New verifications UX

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#257]
As a user, I should be able to easily add and verify my social media accounts in the browser using the new address-based verifications system and view the results in both the browser and the explorer.

**Comment by shea256** [comment]
@yknl @larrysalibra Let's cover this in our meeting tomorrow as well. Gotta make sure we have this in tip top shape so users aren't fumbling.

**Comment by shea256** [comment]
We came up with an improvement to the UX of the verifications. We'll provide a link to the discussion below.

**Comment by yknl** [comment]
https://github.com/blockstack/blockstack-browser/issues/805

**Comment by larrysalibra** [comment]
A first version of this has shipped in v0.17.0.

We still don't have the explorer endpoint stuff that lets you view Blockstack IDs for addresses.

We can decide if we want to work on that in the 0.18 sprint.

**Comment by larrysalibra** [comment]
This shipped already.
