### ISSUE TITLE
Plan Payments API details 

### ISSUE THREAD

**Issue by alidcast** [stx-labs/stacks.js#259]
I discussed with @pstan26 about possibly building a "coin-operated file viewer" protocol. But @shea256 mentioned that I'd need Blockstack's JS payments API feature in order to do so.

At a high level, what are the implementation details required to get this done? Would love to start a discussion about it to see if there's any way that I, or other community members, could help.

**Comment by pstan26** [comment]
@larrysalibra any ideas?

**Comment by larrysalibra** [comment]
In my mind, this should be something that is built on top of or that works with bitcoin's lightning network.

**Comment by pstan26** [comment]
Maybe @roasbeef can assist? I think this would be a huge app if done properly and potentially a perfect first app for marriage of Blockstack + Lighting.
