### ISSUE TITLE
Story: Encryption in storage

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#261]

**Comment by xmakina** [comment]
Yes please. There's a lot of reasons against encryption in the browser and being able to encrypt files is going to be critical for several applications

**Comment by kantai** [comment]
Added boolean flags to getFile/putFile to support ECIES using the application private key in PR #262 -- ECIES basically uses ECDH to derive a shared secret, which is used to AES encrypt and HMAC sign.

Apologies for acronyms. Hard to avoid with cryptography standards.

**Comment by larrysalibra** [comment]
This has shipped in blockstack.js and is already implemented in blockstack todos!
