### ISSUE TITLE
Expose identity address in user data object

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#271]
We don't store the identity address in the user data object. It exists in the authentication response token, however apps shouldn't have to decode json web tokens to get it at.

It should be added in this function: https://github.com/blockstack/blockstack.js/blob/b6889ec2a6fe45fe29818cd59089a97030109195/src/auth/authApp.js#L132

We could use the key `identityAddress`.

The identity address is stored in the `iss` key of the authentication response token in the following format:
```
"iss": "did:btc-addr:1GBLCrGLATRcLXS8V81RbzyCQPaSv4ATby"
```

We should only store the address value in that key.

We should also expose the raw `did` in a key `did`.

**Comment by TheSamSmith** [comment]
Can I pick this up?

**Comment by larrysalibra** [comment]
Thanks so much for this @TheSamSmith !

**Comment by larrysalibra** [comment]
We need to make some changes to the PR #273 to get this merged.

**Comment by larrysalibra** [comment]
This was fixed by @bitpshr - Thanks!
