### ISSUE TITLE
What's the situation with HTTPS?

### ISSUE THREAD

**Issue by icidasset** [stx-labs/stacks.js#279]
So I was setting up HTTPS for [my app](http://isotach.io) because Chrome kept complaining about how HTTPS would probably be a good thing to use as soon as a password field came on the screen. Anyhow, I can't log in with Blockstack because Chrome doesn't allow the mixed usage of HTTPS and HTTP.

The HTTP protocol is hardcoded here: https://github.com/blockstack/blockstack-storage-js/blob/master/src/datastore.js#L121
Which I guess is because the local Blockstack endpoint doesn't support HTTPS.
I don't even know how one would set up HTTPS locally 🤔 

So yeah, I'm a bit confused with this HTTPS stuff.
What do you folks think?

Thanks ✌️

**Comment by jackzampolin** [comment]
see issue: https://github.com/blockstack/blockstack-browser/issues/631

**Comment by icidasset** [comment]
Closing in favor of the issue listed above.
