### ISSUE TITLE
Add instagram.com to domain list for proof verification

### ISSUE THREAD

**Issue by yknl** [stx-labs/stacks.js#282]
Instagram verifications only work when you include "www."

https://github.com/blockstack/blockstack-browser/issues/994

**Comment by larrysalibra** [comment]
It looks like something is redirecting my proof that doesn't have "www." to the url with "www." which then doesn't get proxy fetched. Another thing to look at would be normalizing the urls we fetch so that we add www. when the user doesn't include it.

**Comment by larrysalibra** [comment]
Fixed - we've normalized urls so that they are checked with www.
