### ISSUE TITLE
Consider alternatives to redirects for passing authentication response to apps

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#284]
By sending the authentication response with a GET - we're causing the following problems:

* leaking the token in Referrer headers in the app 
* running into limits of URI length (414 error) or header size (520 error)

**Comment by kantai** [comment]
We should note that trying to use POSTs will be very difficult -- client-side Javascript cannot read the POST data, so the data would need to be shuttled back to the client-side application from the application's web server-- this would mean the application would necessarily no longer be _solely_ static Javascript.

**Comment by vsund** [comment]
Also GET requests aren't meant to transmit secret data through its parameters (according to the spec :D). There happen many unexpected/unwanted things like storing the url in browser history, exposing it as referrer (as Larry said), visible on the monitor, etc.

The last point is more important for the core password which gets into the Browser through a GET parameter.

**Comment by timkinnane** [comment]
I was going to make an issue requesting an additional method, like `redirectToSignInWithAuthRequest` that just returns the URI to handle redirection manually. Would that come under this topic?

My objective is to use existing app auth handlers that might open new windows etc in their own way (specifically Rocket.Chat) depending on the environment, be it web or cordova etc. For this I really need greater control over the auth flow, but the existing methods execute most of the process without exposing the URIs they're using.

**Comment by jcnelson** [comment]
This recently bit me on a Blockstack app.  Looking at the `authResponse`, a large chunk of the data is my profile.  Can we consider not passing the profile object in the `authResponse`, and simply having the app look the profile up itself as part of processing the sign-in?

**Comment by hstove** [comment]
> Can we consider not passing the profile object in the authResponse, and simply having the app look the profile up itself as part of processing the sign-in?

I think this is a good decision in the long term. The only gotcha is that we would break apps with an older version of blockstack.js. Do we pass the version of blockstack.js with our authRequest? If so, we could have conditional logic here.

**Comment by jcnelson** [comment]
> I think this is a good decision in the long term. The only gotcha is that we would break apps with an older version of blockstack.js. Do we pass the version of blockstack.js with our authRequest? If so, we could have conditional logic here.

I was afraid of that.  However, I think we can address this in a backwards-compatible way by having `handlePendingSignIn()` automatically fetch the profile and store it into the `userData` structure before storing `userData` to local storage.

The `authResponse` tokens are versioned, so we can definitely add some conditional logic there to only carry out the app-driven lookup for newer versions.

**Comment by kantai** [comment]
I think we already don't pass the profile in auth responses `>=1.1`

**Comment by jcnelson** [comment]
Ah, nm.  The above is already implemented.  I should have read the code closer.

**Comment by larrysalibra** [comment]
Yes. We don't pass profiles in apps using blockstack.js released any time in 2018.

**Comment by kantai** [comment]
The calling structure for this is really confusing though -- it's not immediately obvious that profiles aren't sent over -- basically, for backwards compatibility, we kept the profile key in the auth response object, and so it's left as an argument in the `makeAuthResponse` function. However, if the _browser_ sees the `do_not_include_profile` key in the auth request, it will pass null to that function. This is definitely technical debt, as it embeds the logic for this across two different projects.

**Comment by zone117x** [comment]
Regarding security with the authResponse ending up in browser history and sent to the server - what about using url fragments (anchor tags) `https://testapp.com/login#authResponse=xxxx`

According to spec fragments should not be sent to the server, and I don't think browsers store them in history. 

This also helps with url length issues for the web servers. Maybe also for browser URL bar char limits as well (need to test). 

This also makes cleaning/clearing the authResponse from the URL easier. No need to perform another redirect or abuse the browser `History` API.
