### ISSUE TITLE
Check to see if Blockstack is running

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#287]
Add an API method that checks to see if the Blockstack browser is running.

**Comment by larrysalibra** [comment]
@jcnelson can you expound on this? Is this a method to check if there's a handler installed for `blockstack:`? If there is, calling the handler will start blockstack: why do we need to know if the browser is currently running?

**Comment by jcnelson** [comment]
I opened this so that apps could detect if Core was running or not--for example, if the Core node crashes after the user signs in.  But it looks like this is going to be made irrelevant shortly, since we won't be needing a local Core node any longer :grinning: 

I'll go ahead and close this in favor of not needing a Core node.

**Comment by vsund** [comment]
But though it would be good to test if a given URL is a running Core node (be it a local or a hosted one).

(@jcnelson, I think you meant Core in your first message?)

**Comment by jcnelson** [comment]
You should be able to `GET /v1/ping` as always :)

**Comment by vsund** [comment]
Would be cool to have a method in `blockstack.js` that requests `/v1/ping` and resolves to the version number or rejects with a few errors (couldn't connect to the server, server not a Core node, etc).
