### ISSUE TITLE
putFile should return a public link to the file updated

### ISSUE THREAD

**Issue by xmakina** [stx-labs/stacks.js#288]
Applications need to be able to share user data.

One way to achieve this will be that when a file is updated, a public link is returned. This public link can then be stored, for example, in a file linked to from the Zone File.

**Comment by jcnelson** [comment]
Hey @xmakina, this is a feature that is coming in Gaia v2.  Gaia v2 is already written and available for testing.  If you want to experiment with it, we have instructions here: https://github.com/blockstack/blockstack-browser/pull/739

**Comment by xmakina** [comment]
Thanks, think I'll hold off for this hitting stable as I'm on Windows and there's already a ton of things turned off in there, I don't want to add even more complexity to the system.
