### ISSUE TITLE
Tool for generating name private keys from backup phrase

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#291]
It's possible for a user to both register a name and send a name from Onename to the same address, and end up in a situation where the same address owns two names.  The browser does not know how to handle this.

What is needed is a tool to translate the user's backup phrase into their owner and payment private keys.  Then, the user can use the CLI tool to transfer one of the names to a different identity address.

**Comment by jasonnovack** [comment]
Thanks @jcnelson. I also wonder if there are legitimate use cases for an address to own multiple names.

**Comment by larrysalibra** [comment]
We already have a branch in the browser that starts to do this: https://github.com/blockstack/blockstack-browser/tree/feature/migration-tool

@kantai has also done work on this in https://github.com/blockstack/blockstack-browser/issues/537 as well

**Comment by larrysalibra** [comment]
@jasonnovack tried to answer your question here: https://forum.blockstack.org/t/transfer-username/2479/5?u=larry

**Comment by larrysalibra** [comment]
To enable the creation of such a tool, we should extract the keychain generation code from browser and move it into blockstack.js so that other apps can take advantage of it.

**Comment by jcnelson** [comment]
Addressed here: https://github.com/jcnelson/cli-blockstack

**Comment by hstove** [comment]
I also added a PR for the browser to show your public key on the keychain backup page: https://github.com/blockstack/blockstack-browser/pull/1308
