### ISSUE TITLE
Better Input Sanitation for Social Proofs

### ISSUE THREAD

**Issue by jackzampolin** [stx-labs/stacks.js#292]
Users are running into a number of issues with the social proofs for issues like spaces in inputs, or `https://www.twitter.com` fails while `https://twitter.com` does not. We need to take care of more corner cases.

**Comment by larrysalibra** [comment]
I'm going to close this out since it is a pretty general issue:

If the twitter domain problem is still an issue we can open a specific issue to handle it.

Also, please open an issue other specific examples of where these problems are occurring so that we can address them.
