### ISSUE TITLE
Better Errors for Social Proofs

### ISSUE THREAD

**Issue by jackzampolin** [stx-labs/stacks.js#293]
We need to give users better errors about why social proofs are failing. This will allow us to display them on the front end and give users feedback

**Comment by larrysalibra** [comment]
Totally agree with this. We need better errors across all of our APIs that are programmatically consumable so that developers can either handle the errors or tell users what's going on.

**Comment by yknl** [comment]
Improved error responses have been implemented in this PR https://github.com/blockstack/blockstack.js/pull/720
