### ISSUE TITLE
Ability to check if file exists

### ISSUE THREAD

**Issue by brandonparee** [stx-labs/stacks.js#295]
Currently there is no easy way to check if a file exists in the users storage. 

At the moment the best way to do this is using `getFile`, which will return `null`, but *only* if you aren't decrypting the file. If you have decrypt set to true and you attempt to find it with `getFile` you receive an error -- `Cannot read property 'ephemeralPK' of null`

#### Default Application Data
Most applications will need to store some information for the user when they first authenticate through Blockstack. In my case I have a 'preferences.json' file that I save and rely on to render my application. 
Right now, for the onboarding process of a user I must do the following: 
```
// Attempt to get file and decrypt it.
getFile('preferences.json', true) -> error
// Check if the file exists, since the error 
// might not be related to the file not existing
getFile('preferences.json') -> null
// Put default preferences object
putFile('preferences.json', content, true) 
```

#### Overwriting Existing Files
Some applications might have the ability to upload a file to their Blockstack storage, if the user uploads a file with the same name, the old file will be lost/overwritten. We should be able to check whether or not a file exists before performing a `putFile`

### Suggestion
There should be a new method that receives a file path as a parameter and returns `true` or `false` dependent on whether the file exists or not.

**Comment by brandonparee** [comment]
I just looked through and noticed that there is a `stat` method in `blockstack-storage-js` that does exactly this. Maybe it just needs to be added here since its not recommended to use the other library?

**Comment by larrysalibra** [comment]
We're not using `blockstack-storage-js` anymore, but agree this is something we need.

**Comment by larrysalibra** [comment]
Seems useful to be able to check if a file exists without downloading the whole thing.

@kantai does gaia support something like a `HEAD` http request that will return 200 if the file exists and 404 if it doesn't?

**Comment by kantai** [comment]
Depends on the backend, but the default one does, yes (and so will all the current backends, unless you explicitly configure them not to).

```
$ curl https://gaia.blockstack.org/hub/1BjUfhoU5Pi8QnNzTbkB2BjC9P9pNexQE8/profile.json -I
HTTP/2 200 
accept-ranges: bytes
access-control-allow-origin: *
cache-control: public, max-age=1
content-md5: oqSjS/pBtWoVhuvV6BIKbQ==
content-type: application/json
date: Fri, 27 Jul 2018 12:45:51 GMT
etag: 0x8D5DD05E8950937
last-modified: Thu, 28 Jun 2018 14:46:18 GMT
server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
vary: Origin
x-cache: HIT
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: 3cbebc0a-601e-0036-10a7-251753000000
x-ms-version: 2009-09-19
content-length: 1866

$ curl https://gaia.blockstack.org/hub/1BjUfhoU5Pi8QnNzTbkB2BjC9P9pNexQE8/profile2.json -I
HTTP/2 404 
date: Fri, 27 Jul 2018 12:45:57 GMT
server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
vary: Origin
x-ms-request-id: 84fcc707-e01e-0063-6aa7-25fc24000000
x-ms-version: 2009-09-19
content-length: 0
```

**Comment by njordhov** [comment]
With #720 and release 21, `getFile()` will result in an error when a file does not exist, so checking the promise for `null` no longer work.
