### ISSUE TITLE
Using `putFile` on the same file repeatedly sometimes results in a `TypeError`

### ISSUE THREAD

**Issue by brandonparee** [stx-labs/stacks.js#296]
When using `putFile` with the encrypt parameter set to `true` a `TypeError: Invalid hex string` error is sometimes thrown. The issue does not happen when encrypt is `false`

I've found the bug to be more consistent when writing to the same file multiple times in a row. In my case, I am using `putFile` every time user preferences are changed for it to be auto-saving (rather than edit-save)

### Stack Trace

![stacktrace1](https://user-images.githubusercontent.com/6785558/32744990-93596fba-c86e-11e7-9c46-008790e56d09.png)
![stacktrace2](https://user-images.githubusercontent.com/6785558/32744991-9374d3d6-c86e-11e7-980d-3a2aa473dd1c.png)

**Comment by kantai** [comment]
Thanks for raising this issue. I suspect this is also related to intermittent "invalid hex string" TypeErrors that our test framework sees as well. I'll look into this.

**Comment by larrysalibra** [comment]
This was shipped in v0.13.6. Please let us know if it still appears!

**Comment by brandonparee** [comment]
After upgrading to v0.13.6 my application is no longer able to authenticate users or perform file actions (`getFile`, `putFile`). In all cases it seems to be an issue with encryption. Everything results in a `Assertion Failed` error. 

Here is a stack trace -- 

![screen shot 2017-11-22 at 1 22 44 pm](https://user-images.githubusercontent.com/6785558/33148485-5dd41b98-cf89-11e7-9b6f-6e6befc5453e.png)

Also worth a note -- Reverting to v0.13.15 resolves the issue, so there is no permanent damage associated with this.

**Comment by kantai** [comment]
That's no good. I'll try to fix this today or tomorrow.
