### ISSUE TITLE
Update transaction successfully broadcast but record json wasn't stored

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#30]
`blockstore-cli update` successfully broadcast this transaction:
https://live.blockcypher.com/btc/tx/91cb40ea52ded01b3de02a9fb385231e815f0c955c7735a404b00219005b9792/

But the user data doesn't look like it made it into the dht. I initially suspected the problem with my dht-mirror (https://github.com/blockstack/dht-mirror/issues/4) was at fault.

Looking at the output of the command, however:

```
blockstore-cli update theblockchain.id "$(cat ~/theblockchain.json)" "$(cat ~/theblockchain.key)"
{
    "data": "69642b47b034a6786a53aad537f716420748a1312afaf6f3cd6c45109b3fcccf200ef65b0d17eb",
    "error": "No transaction hash given",
    "success": true
}
```

`blockstore-cli`  appears to have exited before calling `store_name_record` to persist the data in the dht.

The above output seems consistent with exiting here:
https://github.com/blockstack/blockstore-client/blob/master/blockstore_client/client.py#L879

Haven't yet tried to replicate.

**Comment by larrysalibra** [comment]
I tried to run the following to persist the profile data:

```
blockstore-cli update theblockchain.id "$(cat ~/theblockchain.json)" "$(cat ~/theblockchain.key)" 91cb40ea52ded01b3de02a9fb385231e815f0c955c7735a404b00219005b9792
[ERROR] [storage:314] (3484) timed out
Traceback (most recent call last):
  File "/srv/blockstore-venv/local/lib/python2.7/site-packages/blockstore_client/storage.py", line 312, in get_immutable_data
    data = handler.get_immutable_handler( data_key )
  File "/srv/blockstore-venv/local/lib/python2.7/site-packages/blockstore_client/drivers/dht.py", line 151, in get_immutable_handler
    return dht_get_key(key)
  File "/srv/blockstore-venv/local/lib/python2.7/site-packages/blockstore_client/drivers/dht.py", line 101, in dht_get_key
    ret = dht_server.get( data_key )
  File "/srv/blockstore-venv/local/lib/python2.7/site-packages/basicrpc/basicrpc.py", line 46, in default
    return self.request()
  File "/srv/blockstore-venv/local/lib/python2.7/site-packages/basicrpc/basicrpc.py", line 82, in request
    c = self.sock.recv(1)
timeout: timed out
[ERROR] [client:284] (3484) Failed to load user record '312afaf6f3cd6c45109b3fcccf200ef65b0d17eb'
{
    "error": "User data could not be loaded from storage"
}
```

Temporarily commenting out lines 843 to 849
https://github.com/blockstack/blockstore-client/blob/master/blockstore_client/client.py#L843
and running the command again successfully persisted the user data in the dht.

```
blockstore-cli update theblockchain.id "$(cat ~/theblockchain.json)" "$(cat ~/theblockchain.key)" 91cb40ea52ded01b3de02a9fb385231e815f0c955c7735a404b00219005b9792
{
    "status": true,
    "transaction_hash": "91cb40ea52ded01b3de02a9fb385231e815f0c955c7735a404b00219005b9792",
    "value_hash": "312afaf6f3cd6c45109b3fcccf200ef65b0d17eb"
}
```

I started up another dht node on another machine and confirmed the data is accessible.

**Comment by muneeb-ali** [comment]
This has been resolved in latest version. Please checkout the latest version of the client and cli!
