### ISSUE TITLE
Reduce the number of characters in URLs

### ISSUE THREAD

**Issue by vinniejames** [stx-labs/stacks.js#300]
I’ve noticed GitHub pages hosting limits urls to around 8,000 characters, other hosts have similar limits (possibly much lower) 

The authSuccess callback token comes pretty close to this limit.

It may be worth it to reduce the length somehow, or pass the data via another method, POST form, etc

**Comment by kantai** [comment]
This is an important issue for us to keep an eye on and try to find ways to reduce the size of the authResponse.

Fixing issue #321 will go a long way towards reducing the number of characters.

**Comment by larrysalibra** [comment]
We should also consider alternate ways to pass the token #284

**Comment by larrysalibra** [comment]
Using other methods besides redirects would also address this problem: #284

**Comment by yknl** [comment]
Closing this issue and tracking it on https://github.com/blockstack/blockstack.js/issues/284
