### ISSUE TITLE
Expose a wrapper with same methods as localStorage

### ISSUE THREAD

**Issue by vsund** [stx-labs/stacks.js#306]
Gaia is basically a key value store just like localStorage. To make migration (for single user storage) easier, it would be really handy if there would be a wrapper which exposes the same methods as localStorage (see https://developer.mozilla.org/en-US/docs/Web/API/Storage).

Additional methods (i.e. multi user data sharing) could be also exposed to enable next steps with Blockstack easily.

**Comment by larrysalibra** [comment]
That's an interesting idea! Thanks for opening this issue @vsund

**Comment by vsund** [comment]
Nice little side effect: We can benefit from projects like https://github.com/knadh/localStorageDB, that solved the same problems like we currently have with Gaia (providing only a key value store but developers like to have more sophisticated ways to store data).
And that's really only the first result of a really quick search, guess there's much more :)

Edit: Gone through some more results, https://github.com/bebraw/jswiki/wiki/Storage-libraries seems like a good list to start with.
