### ISSUE TITLE
Implement direct-to-hub gaia hub storage client

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#311]
Storage communication will be directly between apps & Gaia Hubs without passing through an intermediary local Blockstock Core daemon.

Related issues:
Bearer token generation code: https://github.com/blockstack/blockstack.js/issues/310
Pass gaia hub root url in authentication response token: https://github.com/blockstack/blockstack.js/issues/309

**Comment by brandonparee** [comment]
Am I correct in assuming this will solve https://github.com/blockstack/blockstack-core/issues/690?

Also if needed, I can help test this out in a live environment once a PR is brought in.

**Comment by kantai** [comment]
This has been merged and released as 0.14.0 on `npm`
