### ISSUE TITLE
Add support for scope add app storage bucket to profile

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#313]

**Comment by yknl** [comment]
Should the API for adding the app index to profile also implement methods to modify the content of this file?

**Comment by larrysalibra** [comment]
My thinking is that the key-value pair in the accounts array should always be replaced by the latest one generated during authentication.

**Comment by larrysalibra** [comment]
The scope is `publish_data` and this functionality shipped in blockstack.js v0.15.0 and browser v0.22.0.
