### ISSUE TITLE
Use production decentralized identifier format

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#316]
This library is currently returning the decentralized identifier in a legacy format. 

We need to update this library and the authentication format to use the current version:

`did:stack:v0:${address}-${name_index}`

**Comment by larrysalibra** [comment]
There's work on this in this branch: 
https://github.com/blockstack/blockstack.js/tree/feature/update-did

Because of our requirement that Blockstack IDs work before names confirm, @kantai @jcnelson and I decided we needed to switch our production did format to the public key.

**Comment by polluterofminds** [comment]
Adding a note to help with prioritization. In an effort to embrace true decentralization, meaning interoperability across different platforms, exposing the updated did that resolves using the DIF's universal resolver, would allow a user better ownership of their identity. Right now, users likely don't even know they have an identity that could, in theory, be used outside of Blockstack apps. But they should know. Each app dev can help in revealing that, which Graphite plans to do, but that did should probably be something available outside of any one app.

**Comment by jcnelson** [comment]
I have an update on this.  The current stable version of Blockstack Core (v19) has a `/v1/dids` endpoint that will let you resolve your DID to your public key and profile.  Also, the `/v1/names` endpoint has been updated to return the name's DID along with the other WHOIS-like information.  I also wrote up the specification for our DID method for the W3C working group [here](https://github.com/blockstack/blockstack-core/blob/master/docs/blockstack-did-spec.md).

The core.blockstack.org node will be updated to v19 shortly.  I also want to make a "blockstack-did.js" library for doing client-side DID resolution at some point.

**Comment by kantai** [comment]
> The core.blockstack.org node will be updated to v19 shortly. I also want to make a "blockstack-did.js" library for doing client-side DID resolution at some point.

I know I'm picking up a tangent here, but I think if we're going to be splitting up our javascript libraries, I think we should do it with a high-level plan like the one discussed here (but actually settle on such a plan):

https://forum.blockstack.org/t/proposal-split-blockstack-js-into-multiple-modules/5749

We should think about splitting up libraries based on who should be responsible for maintaining that particular library. A problem with splitting up libraries _too_ much, is that smaller libraries would increasingly trend towards single-author and same-tester libraries, which leads to a whole slew of other problems --- APIs that don't match their usage, unintended integration dependencies, tests that don't match usage, unclear contribution standards, etc. I'm guilty of this myself, and I think we should be wary of trending in that direction.
