### ISSUE TITLE
0.14.0 Better handling of forward slash in putFile and getFile path arg

### ISSUE THREAD

**Issue by cwackerfuss** [stx-labs/stacks.js#319]
I noticed that as of 0.14.0, a forward slash is added before the filename in the hub url, requiring me to change `'/foo.json'` to: `'foo.json'`. I believe previously the `/` was optional and was removed if you included it.

Here's one of the places where you can see that a leading `/` is added: https://github.com/blockstack/blockstack.js/commit/b9d1bdcf618dcb7265ffd70d2946259f8f91b01a#diff-6737176abc32830ebd1e562c0a17f681R21

I think there are three options here:
1. Leave it how it is, if you pass `/foo.json`, then exactly that will be your filename.
2. Check for a forward slash and remove it
3. Throw an error if the arg doesn't pass a pattern match.

**Comment by larrysalibra** [comment]
Thanks @cwackerfuss - agreed we need to handle this consistently. We should consider this as part of finalizing the 1.0 api #235 so that it's clear what filenames in gaia look like and they don't change.
