### ISSUE TITLE
I got a javascript error when I want to login 'blockstack.redirectToSignIn();'

### ISSUE THREAD

**Issue by jorishermans** [stx-labs/stacks.js#325]
I am building a blockstack application with angular. My angular is been setup with angular-cli. I am also developing my app with typescript. What am I doing wrong?

ERROR TypeError: (0 , _crypto.randomBytes) is not a function
    at getEntropy (keys.js:25)
    at new ECPair.makeRandom (ecpair.js:94)
    at makeECPrivateKey (keys.js:28)
    at generateAndStoreTransitKey (authApp.js:54)
    at Object.redirectToSignIn (authApp.js:141)

**Comment by jorishermans** [comment]
This refers to the fix that webpack will use browserify-crypto.
https://github.com/angular/angular-cli/issues/1548
Angular CLI is skipping and making crypto empty.

Now I get the following issue: 
Sign In Request
Invalid Sign In Request

Do I need to do something special when developing a blockstack app to get this working?

**Comment by jorishermans** [comment]
Make sure you have a manifest.json file in your application. It is now working for me 👍

**Comment by yogesh-randhawa** [comment]
@jorishermans what is the use of a manifest.json file in this case and how can I use it to resolve the error with using blockstack inside an Angular 6 app?

**Comment by jorishermans** [comment]
That is been used to redirect you back to your application ... I am working on an angular library for angular when it is mature enough I will put it on github.
