### ISSUE TITLE
Integration Testing for Blockstack Transaction Generation

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#329]
To test blockstack transaction generation and bitcoin transaction funding in `blockstack.js`, we'll need a way to get an integration testing setup for `blockstack.js` (and support for regtest transactions in `blockstack.js`)

It's not 100% obvious to me how we want to do this. We can definitely support this using the integration test framework for `blockstack-core`, and probably that's what we'll need to do, however, the tests could end up being rather long running, so they probably _shouldn't_ run in `npm test`, but should be added to our CI definition.

**Comment by larrysalibra** [comment]
Not sure if this is the right place for this comment: we'll also need to be able to use blockstack.js generated transactions in regtest mode with the browser.

**Comment by kantai** [comment]
Yeah -- I think that makes more sense as a browser issue.

**Comment by kantai** [comment]
This was shipped a while back
