### ISSUE TITLE
Zonefile Publishing

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#330]
Beyond supporting the `UPDATE` transaction, `blockstack.js` will need to be able to announce a zonefile to the Atlas network.

**Comment by jcnelson** [comment]
How do you want to address this?

* Does this exist already with the transaction broadcaster?
* Do you need a RESTful endpoint in Blockstack Core?  I think there's already one there, but if not, happy to add.

**Comment by kantai** [comment]
Ah -- yeah -- so this is already _sort of_ addressed:

1. As you mentioned, there's a RESTful endpoint in blockstack core:

https://github.com/blockstack/blockstack-core/blob/master/blockstack_client/rpc.py#L1049

and used by `blockstack.js` here:

https://github.com/blockstack/blockstack.js/blob/master/src/network.js#L254

However -- core.blockstack.org blocks all POSTs, so we'd need to reconfigure/change that in the flask app.

2. The transaction broadcaster does support this -- but only when associated with a "watched" transaction -- like, I pass it a `tx_hash` of an UPDATE, and once it has 7 confs, it tries to broadcast it.

3. The transaction broadcaster and the subdomain registrar _both_ have a workaround for (1) not being deployed on core.blockstack.org yet: https://github.com/blockstack/subdomain-registrar/blob/master/src/operations.js#L133

**Comment by jcnelson** [comment]
I'm fine with a solution like (1) or (3), where the client directly pushes a zone file to a Core node.  If this issue (https://github.com/blockstack/blockstack-core/issues/774) goes through, then blockstack.js only needs the URL to an indexer node to do this.

**Comment by larrysalibra** [comment]
This shipped http://blockstack.github.io/blockstack.js/index.html#broadcastzonefile
