### ISSUE TITLE
Add support for passing public keys to encrypt/decrypt

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#332]
The encrypt/decrypt file operations in `blockstack.js` currently only use the logged in user's application keys.

As @yknl brought up, if we want to have applications which share data between users, then we should really add the ability to encrypt and decrypt with a supplied public key.

**Comment by bodymindarts** [comment]
I just tried to implement this myself in the calling code but [encryptECIES](http://blockstack.github.io/blockstack.js/index.html#encryptecies) isn't actually a public method (even though it is documented as such).

**Comment by larrysalibra** [comment]
We have support for this already. pass the public key to the `options.encrypt` field or the private key to `options.decrypt`.
