### ISSUE TITLE
Decide on Node version support policy

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#334]
We've had an informal policy of supporting the most recent Node LTS.

@kantai brings up a good point that we should have a more formal policy.

Whatever policy we came up with, we should apply it consistently across all of our Javascript projects.

I briefly looked into this it seems like something that requires more than a couple minutes to decide. 

This is one of their two charts:

<img width="914" alt="screen shot 2017-12-27 at 5 58 00 pm" src="https://user-images.githubusercontent.com/597182/34378153-8345425a-eb2f-11e7-98ff-c0c6a1b7880a.png">

I'm thinking supporting "Active" LTS releases might make sense. 

What do you think @kantai @yknl and others in the community?

**Comment by larrysalibra** [comment]
Thoughts @kantai @yknl ?

**Comment by kantai** [comment]
Supporting 'active'  sounds like the right policy to me.

**Comment by wackenvoss** [comment]
I'll third that -- "Active" sounds right for us as an ongoing rule.

**Comment by larrysalibra** [comment]
Updated CircleCI to use node v8.11.3 and our readme to indicate this policy.
