### ISSUE TITLE
putFile() in production only returns UnCaught Error (in promise) message: "Expected property "1" of type BigInteger, got r"

### ISSUE THREAD

**Issue by rptrainor** [stx-labs/stacks.js#335]
putFile() in production only ( pq178.herokuapp.com ) returns UnCaught Error (in promise) message: "Expected property "1" of type BigInteger, got r"  When I searched for other issues with this particular error message I kept finding issues with bitcoinjs and bitcoinjs-lib, and so I think the Production Only Error I'm getting with putFile is related to possible Blockstack.js use of Bitcoinjs.  

I tried to add the UglifyEsPlugin to my webpack config, as per the other issues with this uncaught error, but still getting the error in production.

The code for the component is here: https://codeshare.io/GqpVlZ

![screen shot 2017-12-30 at 1 08 40 pm](https://user-images.githubusercontent.com/12374439/34457347-1512ec7a-ed63-11e7-8b1e-ffc7b6b2cbe4.png)

other examples of this error i found : 
- https://github.com/bitcoinjs/bitcoinjs-lib/issues/959
- https://github.com/bitcoinjs/bitcoinjs-lib/issues/864
- https://github.com/bitcoinjs/bip39/issues/60

![screen shot 2017-12-30 at 1 18 34 pm](https://user-images.githubusercontent.com/12374439/34457386-1d08cd0e-ed64-11e7-9a4a-17e9024d5758.png)
![screen shot 2017-12-30 at 1 19 28 pm](https://user-images.githubusercontent.com/12374439/34457387-1d29ad80-ed64-11e7-91f5-50ae5aad23d2.png)

**Comment by polluterofminds** [comment]
This definitely appears to be an issue originating from Blockstack Core. Maybe @larrysalibra can confirm. However, I found a work around. Similar to above, but it actually works in production: 

Rather than the UglifyEsPlugin, install and use the UglifyJsPlugin. Here is how I setup the webpack.config file: 

Require in the plugin: 

`const UglifyJsPlugin = require('uglifyjs-webpack-plugin')`

Then setup the plugin settings like this: 

```
plugins: [
    HtmlWebpackPluginConfig,
    ManifestAssetPlugin,
    IconAssetPlugin,
    new UglifyJsPlugin({
      uglifyOptions: {
        mangle: {
          reserved: [
            'Buffer',
            'BigInteger',
            'Point',
            'ECPubKey',
            'ECKey',
            'sha512_asm',
            'asm',
            'ECPair',
            'HDNode'
        ]
        }
      }
    })
  ]
```
  The final thing I had to do to make sure the production build didn't ignore the Uglify Plugin was change my build script from webpack -p to just webpack.

**Comment by larrysalibra** [comment]
Sorry about the confusion. As you figured out @jehunter5811, our dependency bitcoinjs-lib doesn't work when certain class names are uglified. We need to update our readme: #345

**Comment by JackNeto** [comment]
I'm using an older version of create react app with `uglifyjs-webpack-plugin` `v 0.4.6` and the configuration that worked for me was slightly different (no `uglifyOptions` and use `except` instead of `reserved`)

In `config/webpack.config.prod.js`
```js
plugins: [
    new InterpolateHtmlPlugin(env.raw),
    new HtmlWebpackPlugin({...}),
    new webpack.DefinePlugin(env.stringified),
    // Minify the code.
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
        // Disabled because of an issue with Uglify breaking seemingly valid code:
        // https://github.com/facebookincubator/create-react-app/issues/2376
        // Pending further investigation:
        // https://github.com/mishoo/UglifyJS2/issues/2011
        comparisons: false
      },
      mangle: {
        safari10: false,
        except: [
          'Buffer',
          'BigInteger',
          'Point',
          'ECPubKey',
          'ECKey',
          'sha512_asm',
          'asm',
          'ECPair',
          'HDNode'
        ]
      },
      output: {
        comments: false,
        // Turned on because emoji and regex is not minified properly using default
        // https://github.com/facebookincubator/create-react-app/issues/2488
        ascii_only: true
      },
      sourceMap: shouldUseSourceMap
    }),
    ...
```

**Comment by wbobeirne** [comment]
You'll be pleased to know that blockstack.js no longer requires this configuration as of v18.0.2

**Comment by JackNeto** [comment]
Thanks for the tip @wbobeirne. 
I've updated to `blockstack.js` v18.0.4 but now it's failing to minify

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/bitcoinjs-lib/src/script.js:57 
```

Any ideas?

**Comment by wbobeirne** [comment]
Agh, unfortunately it looks like their library still doesn't play well with CRA's default config, and you'll need to run it through babel: https://github.com/bitcoinjs/bitcoinjs-lib/issues/1159

**Comment by JackNeto** [comment]
So the issue is that most npm modules precompile to es5 (using babel).
**Create react app** by default does not compile any node modules because it assumes this is the case but these bitcoin libs do not do that.  So you want to **include** them when processing with babel.

I eventually got it to work by including 4 modules and it ends up looking like this: 
_(make sure you have at least version `v18.0.2` of `blockstack`)_

In your `webpack.prod.js`
```
          // Process JS with Babel.
          {
            test: /\.(js|jsx|mjs)$/,
            include: [
              paths.appSrc,
              path.resolve(paths.appNodeModules, 'bitcoinjs-lib'),
              path.resolve(paths.appNodeModules, 'tiny-secp256k1'),
              path.resolve(paths.appNodeModules, 'jsontokens'),
              path.resolve(paths.appNodeModules, 'bip32')
            ],
            loader: require.resolve('babel-loader'),
            options: {
              compact: true
            }
          },
```
