### ISSUE TITLE
Hub returns 503s when saving multiple files simultaneously

### ISSUE THREAD

**Issue by daimonia** [stx-labs/stacks.js#337]
If you try to save multiple files at the same time:

```javascript
Promise.all([
  blockstack.putFile('foo.json', '{}', true),
  blockstack.putFile('bar.json', '{}', true),
  blockstack.putFile('bim.json', '{}', true)
])
```

some or all of the requests error out with 503 Service Unavailable

**Comment by kantai** [comment]
I believe that this behavior is related to rate-limiting on the gaia service we provide.

We have a pretty conservative rate limit there at the moment. Do you see this behavior consistently with just putting 2-3 files at a time?

**Comment by larrysalibra** [comment]
This is an issue with our gaia hub production configuration. Closing this issue in favor of: https://github.com/blockstack/gaia/issues/88
