### ISSUE TITLE
Documentation of Public/Private API

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#341]
Currently, we use the `@private` tag to specify that a function shouldn't generate documentation.

This raises an issue when functions are used by, say, `blockstack-browser`, but are irrelevant to most app developers. One potential approach is to categorize the documentation so that you have 'functions which an app developer should use' and 'functions which are only really useful if you're building an alternative browser' and, soon, 'functions which are useful if you want to interact with the blockchain'.

A lot of this discussion started over at PR #340

**Comment by larrysalibra** [comment]
We should figure this out when finalizing the 1.0 api #235

**Comment by yknl** [comment]
Closing as no longer relevant
