### ISSUE TITLE
method wrapper to encrypt for a specific user when writting file

### ISSUE THREAD

**Issue by bodymindarts** [stx-labs/stacks.js#346]
The function [
encryptECIES](http://blockstack.github.io/blockstack.js/index.html#encryptecies) accepts a public key as input so it is possible to encrypt files for other blockstack users, but there is currently no known way of finding out the app public key for a user.

Ideally [putFile](http://blockstack.github.io/blockstack.js/index.html#putfile) would accept a options parameter: `options.encryptFor string` that accepts a blockstack id and encrypts the file for that user.

This would allow us to use multi-player storage in a more private way by storing a copy of the file for each user that should be allowed access instead of making it public.

**Comment by 0xpbj** [comment]
I believe you can find the users public key with: https://core.blockstack.org/#resolver-endpoints-lookup-user

see https://github.com/blockstack/blockstack.js/issues/332

**Comment by bodymindarts** [comment]
closing as duplicate to https://github.com/blockstack/blockstack.js/issues/332

**Comment by bodymindarts** [comment]
@prabhaav thank you for that. It is not the app specific private key, but probably still useful.

**Comment by ntheile** [comment]
any idea on how to get a user's app specific public key? would be really useful for sharing encrypted files
