### ISSUE TITLE
Crypto module being imported, not in package.json

### ISSUE THREAD

**Issue by timkinnane** [stx-labs/stacks.js#352]
https://github.com/blockstack/blockstack.js/blob/1818f2a3270dfd24fd31b729a10365cb40cb0aa4/src/encryption.js#L2

There's a module being imported ('crypto') that is not included in the package.json.

There might be a reason why this works with browserify or other methods, but I'm trying to use this the blockstack package in a meteor app, which does it's own bundling of client side npm packages, and it's throwing a `Cannot find module 'crytpo'` error.

Looking here however, it seems the package is deprecated: https://www.npmjs.com/package/crypto

~~I saw that there's a bower package called 'crypto' as well, but surely that's not the one being intended by this import?~~ edit: my bad, that was just a keyword in the bower.json, not a package.

Thanks for any assistance.

**Comment by timkinnane** [comment]
OK NVM, it seems this is an issue with the Meteor environment (or my usage). I found that crypto is now a core Node feature and thus not required in the manifest. Closing. Enjoy your day.

**Comment by timkinnane** [comment]
For the record, if I'd done more reading first, I would have found #305 and #308

**Comment by x5engine** [comment]
i'm still having issues with this sadly!

**Comment by timkinnane** [comment]
@meteorplus - I'm gonna goo ahead and assume you're running a Meteor client?
I found that Meteor uses a custom build of Node that does not include the crypto module, where the default does. If you `meteor npm install --save meteor-node-stubs` in your project, it will add the required dependencies. This worked for me but still isn't the best solution, because it's quite a big dependency to provide a handful of methods. I think maybe the answer would be updating this and the jstokens-js module to use small third party util for just the _hash_, _cipher_, _random bytes_ and _sha functions_.

**Comment by x5engine** [comment]
@timkinnane I have solved this issues seems I had to use latest version of blockstack :)

Yes Meteor on both client/server.

otherwise I am really struggling wiht gettin CORS on my meteor app to allow blockstack login to access manifest.js on my server!

can you advise me on how did you do this?

thanks bro

**Comment by x5engine** [comment]
ok for CORS I used this and it works on meteor

https://enable-cors.org/server_meteor.html

**Comment by timkinnane** [comment]
@meteorplus Ah yeah, ok. You might want to do that specifically for the manifest route, not all requests. In my app I'm actually generating the manifest on request from settings, by creating a dynamic route handler with Picker, because it might have different details in different instances...

```
  Picker.route('/_blockstack/manifest', (params, req, res) => {
    res.writeHead(200, {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*'
    });
    const name = 'NAME FROM SETTINGS';
    const startUrl = Meteor.absoluteUrl();
    const description = 'DESCRIPTION SETTING;
    const iconUrl = Meteor.absoluteUrl('assets/favicon_192');
    res.end(`{
      "name": "${ name }",
      "start_url": "${ startUrl }",
      "description": "${ description }",
      "icons": [{
        "src": "${ iconUrl }",
        "sizes": "192x192",
        "type": "image/png"
      }]
    }`);
  });
```
