### ISSUE TITLE
`apps` key not populated properly

### ISSUE THREAD

**Issue by bodymindarts** [stx-labs/stacks.js#353]
Having issues with multi-player read. The `apps` key isn’t being populated properly for @kp8383

```
blockstack.lookupProfile("kyle.id").then(profile => console.log(profile.apps));
```

kyle has logged into an app with the `publish_data` permission and has written a file but its not accessible because of ^^^.

Also the error message when this happens isn't very descriptive:
```
> blockstack.getFile("public.json",{username: "kyle.id",app:"http://localhost:3000"}).then(text => console.log(text));
> Promise {<pending>}
> Uncaught (in promise) null
```
Just having `null` as the error makes finding the root cause tricky.

**Comment by larrysalibra** [comment]
Closing this in favor of https://github.com/blockstack/blockstack-browser/issues/1194 since this appears to be a browser problem. Thank you for reporting this @bodymindarts !

**Comment by larrysalibra** [comment]
> Also the error message when this happens isn't very descriptive:

Totally agree with the not-very-helpful error messages - improving them is top on our list of issues to address on blockstack.js!
