### ISSUE TITLE
Github gist proofs should fail if the gist is a fork

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#355]
Gist proofs should _fail_ if the supplied gist is a fork of another user's gist. Github users will frequently fork other users' gists without necessarily reading through the entire gist -- if it contains a verification string, that user can then list this gist as a proof that they are associated with a given Github account.

This can be dealt with using the github gist API -- which is probably a better way of fetching the gists in the first place (i.e., "https://api.github.com/gists/39eab0977b650e2ebbe6fbca409bd8fa").

**Comment by yknl** [comment]
Closing as Github gist proofs have been deprecated.
