### ISSUE TITLE
Clarify return types

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#356]
We should clarify return types in all of our public api methods.

This means making it clear to developers not only the general type of the return value, but the schema of the value when the return value is an object.

@vsund was kind enough to bring this up as part of his creation of typescript definitions for this library #336

**Comment by vsund** [comment]
While resolving this, it may make sense to go through the TypeScript type declarations and correct/improve the wrong ones.

- For the declarations, see all the `.d.ts` files in https://github.com/vsund/blockstack.js/tree/feature/add-typescript-declarations/src
- For the PR (have listed some open types there), see the todo part of https://github.com/blockstack/blockstack.js/pull/336#issue-285799836

**Comment by yknl** [comment]
The entire library has now been converted to Typescript and should provide return types.
