### ISSUE TITLE
lookupProfile should default to https://core.blockstack.org/v1/names

### ISSUE THREAD

**Issue by 0xpbj** [stx-labs/stacks.js#358]
See current code: https://github.com/blockstack/blockstack.js/blob/master/src/profiles/profileLookup.js

This causes issues with production builds that default to https. See (https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content)

**Comment by larrysalibra** [comment]
Thanks @dantrevino for the pull request to fix this!

**Comment by larrysalibra** [comment]
Shipped in v0.15.1.
