### ISSUE TITLE
Implement transaction broadcast api

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#362]
Implement the transaction broadcast javascript api defined here:

https://github.com/blockstack/blockstack-browser/issues/1201

Each API method will make a request to the transaction broadcast service.

Will mock responses until we've confirmed the specific transaction broadcast api.

**Comment by larrysalibra** [comment]
@kantai @yknl i've added function signatures for the transaction broadcast service api here: https://github.com/blockstack/blockstack.js/commit/aec835eafe62d7e9fe2d09cce79cc085719008f7#diff-afe8509c39d4f5df1c2be1db4b65842cR106

Please take a look at these to see if your understanding is the same as mine.

I've also put a comment in each function with a proposed http rest api for the endpoint of transaction broadcast service API. @kantai please let me know if you're planning to or already using something different.

We also need to define the various error conditions along with more specific return values for the 3 functions.

**Comment by kantai** [comment]
@larrysalibra -- this matches my understanding, and when implementing the broadcaster, I'll match that API.

One note --  `broadcastZoneFile` -- there's another function in `network.js` called `publishZoneFile` -- do you think these should be integrated the same way that `broadcastTransaction` is integrated? Or at the very least, they should have more differentiated names?

**Comment by yknl** [comment]
The function signatures make sense to me as well. 

> One note -- broadcastZoneFile -- there's another function in network.js called publishZoneFile

Wouldn't `broadcastZoneFile` replace `publishZoneFile`?

**Comment by kantai** [comment]
Ideally you still allow both behaviors -- broadcasting a zonefile directly to a blockstack core endpoint and using a service to watch for a transaction and then broadcast.

**Comment by larrysalibra** [comment]
> Ideally you still allow both behaviors -- broadcasting a zonefile directly to a blockstack core endpoint and using a service to watch for a transaction and then broadcast

We run into this in two places: both `broadcastZoneFile` and `broadcastTransaction`

The way i've started to handle this with `broadcastTransaction` is if you provide a transaction to watch it is sent to the transaction broadcast service otherwise it is sent to the utxo broadcast endpoint.

We can do the same with `broadcastZoneFile`: if a transaction to watch is provided, send to the service otherwise send to the core endpoint.

If we allow configuration of a network without a broadcast service, we could raise an error in the case that the dev tries to watch a transaction but there's not broadcast service configured.

Thoughts @kantai @yknl ?

**Comment by kantai** [comment]
> We can do the same with broadcastZoneFile: if a transaction to watch is provided, send to the service otherwise send to the core endpoint.
>
>If we allow configuration of a network without a broadcast service, we could raise an error in the case that the dev tries to watch a transaction but there's not broadcast service configured.

That sounds like the right approach to me.

**Comment by yknl** [comment]
Sounds good to me
