### ISSUE TITLE
Clarify Multiplayer Docs

### ISSUE THREAD

**Issue by cwackerfuss** [stx-labs/stacks.js#367]
With multiplayer, you can technically share publicly _and_ privately.

The docs currently focus 100% on how to share data _publicly_, but they never clearly state what's really happening with the data. I think right now its a little confusing that you must have a user's storage path to read from, which makes the process feel like you're sharing data privately between two parties.

I think we should be very clear in the docs that when you're not encrypting data, anyone can find it and read it. If you want to privately share data, you need to do something like store the privileged user's public key, encrypt the file with it, and then save it to your storage so that the other user can read and decrypt with their private key.

**Comment by wackenvoss** [comment]
@larrysalibra @yknl @jcnelson

**Comment by shea256** [comment]
I'd like to propose a former sunsetting of the term "multi-reader storage" in lieu of "multiplayer storage". We shifted over to this in our public blog post communication. Just need to standardize it.

**Comment by wackenvoss** [comment]
Thanks @shea256 -- I've updated the title of this post to say "multiplayer" instead too.
