### ISSUE TITLE
Expand access to the email scope

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#377]
The `email` scope requests the user's email if available. Currently this is only available to a whitelisted group of apps. We should expand this to all apps.

To do this, we need to make sure that users are clearly informed about this request and have the option to opt out.

**Comment by stefanopochet** [comment]
I think this feature would make it easier for developers and product managers to integrate Login with Blockstack in their apps. 
Also, it will definitely help making the login process similar to what popular oAuth connectors offer (like Google and Facebook).

**Comment by pstan26** [comment]
@larrysalibra this would be very helpful for Prism, which Stefano is the engineer for, to have a cleaner onboarding flow. How much engineering effort is there to do this?

**Comment by shea256** [comment]
Yeah this feature would be huge.

**Comment by larrysalibra** [comment]
I've created a pull request to blockstack browser that removes the app whitelist we had previously. https://github.com/blockstack/blockstack-browser/pull/1220

**Comment by ntheile** [comment]
I'm writing a docusign clone app and `email consent` would be huge! right now i have to write my own hack to index each users email address

**Comment by larrysalibra** [comment]
@ntheile sorry for not closing out this issue earlier - we shipped the email scope a couple months ago (see the merged pull request above).
