### ISSUE TITLE
Consistent default regtest port

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#379]
On mac, we use 6270 for regtest - same as production.

blockstack.js uses port `16268`

Can we change this permanently to 6270 or will it break other things? cc @kantai @yknl 

See slack discussion:
```
wrong port?


kenliao [7:48 PM]
```const LOCAL_REGTEST = new LocalRegtest(
   'http://localhost:16268',
   'http://localhost:18332/',
   'http://localhost:16269',
   { username: 'blockstack', password: 'blockstacksystem' })
```
the default setting for local regtest in network.js assumes a core node is running at localhost:16268
if you change it to 6270 it should work
```-  'http://localhost:16268',
+  'http://localhost:6270',
```

larry [7:52 PM]
change it in blockstack.js?

kenliao [7:52 PM]
yes
I think aaron’s operationsTest.js uses port 16268 though

larry [7:53 PM]
how were you getting it to work on your machine?

kenliao [7:53 PM]
I changed the default regtest port to 6270
```

**Comment by kantai** [comment]
Yes, we could have it default in `blockstack.js` to 6270 -- would need to update the port in the operationsTests test cases, but that's not a big issue.

One note -- this can be changed by the client when they include `blockstack.js`:

For example, in the regtest transaction broadcast service, I do the following:
```
      bskConfig.network.blockstackAPIUrl = `http://localhost:${port}`
```
