### ISSUE TITLE
Option to sign but not encrypt files

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#381]
Files written to Gaia are not encrypted or signed by default.  However, blockstack.js already has facilities to sign data, since it already has to do so in order to encrypt it.  We should support an option to sign but not encrypt files, in order to share authentic public data.

We could achieve this in the API by adding a `.sign = true` option in the `options` object passed to `putFile()`.

**Comment by kantai** [comment]
We started a discussion on this in today's engineering meeting:

Reposting here:

>This would be pretty great to have, and not require a ton of effort (we already have all the signing and verification libraries included, and code exists). However, something to think about here is the interaction with multiplayer storage. Namely, should Bob be able to verify Alice’s signed data? The answer is almost certainly yes. This involves two steps:

https://forum.blockstack.org/t/2018-02-22-engineering-meeting/4250/3

>
> 1.   Actual signature verification — that’s easy enough, the data will need to have the signing public key alongside it.
> 2.   Ensure that the public key matches the expected public key
>
>How do we get the expected public key though? The address is the “last part” of the multiplayer storage URL, however, codifying that as a standard is another question.

We circled around the fact that we have basically two options for multiplayer storage:

1. Add pubkeyhash to the app entry in the profile.
Currently `profile.apps[$appDomain]` is the root gaia hub URL. For example:
```javascript
"apps": {
        "https://www.chat.hihermes.co": "https://gaia.blockstack.org/hub/1MEz6wthciFxukEgogNAw4M8vkVMctYoZo/", 
        "https://www.stealthy.im": "https://gaia.blockstack.org/hub/1KFWCWyEubaos7vVC3vPadDwqJzQ9Yowzp/"
      },
```

This would instead be something like:
```javascript
"apps": {
        "https://www.chat.hihermes.co":
          { "userURL": "https://gaia.blockstack.org/hub/1MEz6wthciFxukEgogNAw4M8vkVMctYoZo/",
            "userPubKeyHash": "1MEz6wthciFxukEgogNAw4M8vkVMctYoZo" },
        "https://www.stealthy.im":
          { "userURL":  "https://gaia.blockstack.org/hub/1KFWCWyEubaos7vVC3vPadDwqJzQ9Yowzp/",
            "userPubKeyHash": "1KFWCWyEubaos7vVC3vPadDwqJzQ9Yowzp" }
      }
```

2. As you can see from above, the Gaia URL _already_ has the pubkeyhash. Furthermore, this is _already_ part of the Gaia spec (https://github.com/blockstack/gaia), so we could just read the pubkey hash out of the URL.

The problem with Option 2 is that it binds the multiplayer spec to the Gaia spec. (Honestly, I'm starting to be convinced this is _already_ the case --- the multiplayer spec already expects the `/foo.txt` is always readable from `${gaia-url}/foo.txt`) The problem with Option 1, is that we need a migration story, and it is a generally more verbose format in the profile object.

**Comment by kantai** [comment]
Tagging @yknl @larrysalibra for thoughts here

**Comment by kantai** [comment]
I just came up for a plausible reason (1) might be preferable. Let's say that instead of publishing the public key hash, the application publishes the _public key_. The public key is useful (nearly necessary) for implementing multiplayer encryption.
