### ISSUE TITLE
Wrong profile url returns empty profile object

### ISSUE THREAD

**Issue by x5engine** [stx-labs/stacks.js#383]
You can see that the profile url return from the aut response is wrong and has an index in it and shoul dbe /profile.json not /0/profile.json
![blockstack error](https://user-images.githubusercontent.com/12363020/36651387-a8b81990-1aa0-11e8-96e1-5cd670282f06.jpg)

and because of this I am fetching the profile file a second time after the userLoadData just to get the full name and the profile picture.

also some this assume the user already has a username while many don't and just have an address
https://github.com/blockstack/blockstack.js/blob/30175c820c3e24fa3223a332304b690d7c1b408f/src/auth/authVerification.js

Thank you :)

**Comment by x5engine** [comment]
as @kantai said he thinks the bug is... The profile URL for logins where the user doesn't have an ID is wrong (looks like the old path with an index profile URL)...

**Comment by kantai** [comment]
Thanks for raising this issue @meteorplus --- I moved this over here: https://github.com/blockstack/blockstack-browser/issues/1228, as this is more likely an issue with `blockstack-browser`, as opposed to `blockstack.js`
