### ISSUE TITLE
Expose Apps In Use Through API Endpoint

### ISSUE THREAD

**Issue by polluterofminds** [stx-labs/stacks.js#387]
App devs, and anyone really, could query a Blockstack endpoint just like we can already do with the name query to find all registered IDs that have logged into any given app. Spoke to @jcnelson about this and it should be possible since the appList is already returned in a profile lookup.

**Comment by dhealy05** [comment]
+1. There's no reason you couldn't filter by app on the Blockstack node and it eliminates the necessity/possibility of having to collect and store those names on a separate server.

**Comment by dantrevino** [comment]
Why are apps exposed publicly?  I may not want people to know I'm using a particular app.  For that matter, why would anyone want others to know what apps they are using. A) security hole, B) it is non-censorship resistant.

I see the need, from an app developer standpoint, but implementation should keep the user's privacy in mind.

**Comment by polluterofminds** [comment]
Hey Dan,

Way ahead of you 🙂 Check out this forum post:
https://forum.blockstack.org/t/should-users-be-able-to-hide-the-apps-they-use/4322/6

**Comment by jcnelson** [comment]
Hi @jehunter5811,

Yeah, this is definitely a good feature to have (especially for developers who want to see how many users they have, and measure signup rates).  The Explorer already implements a profile search index, and this could be extended to index app origins by name.  The relevant code is here: https://github.com/blockstack/blockstack-core/tree/master/api/search

Importantly, *anyone* can spin up a search index over the set of profiles.  If you wanted to have your own custom indexes for app data, you could fork this part of the repo and do things like crawl specific fields within a user's public app data (e.g. by curl-ing it from their Gaia hub).
