### ISSUE TITLE
Couple typos/bugs in the storage readme docs

### ISSUE THREAD

**Issue by cwackerfuss** [stx-labs/stacks.js#388]
@yknl mentioned a typo in the https://github.com/blockstack/blockstack.js/tree/master/src/storage docs in the multiplayer read code. The options config should have `username` instead of `user`.

We also need to remove the leading forward slash on all pathname args in these docs. Resolves to `//message.txt`.

**Comment by yknl** [comment]
This was fixed with the new documentation.
