### ISSUE TITLE
Bump auth protocol version to pass gaia hub

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#390]
We need to bump this version to `1.2.0`: 
https://github.com/blockstack/blockstack.js/blob/master/src/auth/authMessages.js#L20

So that this check passes:
https://github.com/blockstack/blockstack.js/blob/master/src/auth/authApp.js#L177

Which enables the passing in of a user-specified gaia hub URL.

**Comment by hstove** [comment]
Happy to help here as well.

**Comment by kantai** [comment]
Thanks @hstove -- this was merged into `develop` in https://github.com/blockstack/blockstack.js/pull/402 -- so whenever we do the next release, this should be resolved.

**Comment by kantai** [comment]
This was merged into master in release 17.2.0
