### ISSUE TITLE
STACKs: include support for pay-with-STACKs wire-format for names

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#394]
Related to https://github.com/blockstack/blockstack-core/issues/776 -- the wire format for paying for names with STACKs will change slightly, and `blockstack.js` will need to be able to generate those transactions.

In particular -- 

`PREORDER` and `RENEW` with STACKs-names will need to include the burn amount on the wire (`OP_RETURN`)

**Comment by jcnelson** [comment]
I'm can take the lead on this.

**Comment by jcnelson** [comment]
Detailing my status:

- [X] namespace preorder with stacks
- [X] namespace reveal
- [X] namespace ready
- [X] preorder with and without stacks
- [X] register with and without stacks
- [X] renew with and without stacks
- [X] revoke
- [x] announce
- [x] name_import

**Comment by jcnelson** [comment]
Submitted PR

**Comment by jcnelson** [comment]
This is implemented in `feature/stacks-transactions`
