### ISSUE TITLE
Potential error with the blockstack register command

### ISSUE THREAD

**Issue by shea256** [stx-labs/stacks.js#40]
Hey @muneeb-ali. I'm pretty confident I downloaded the latest version when you helped me out yesterday (I pasted the exact command you gave me and installed from the develop branch). Unfortunately I'm getting an error with the register command when I provide just the name and nothing more. Has the update command not been separated out from register yet or is there some other issue here? I'm inclined to think the former because of the error message. But in any case, I wanted to report this and provide the response I'm getting. Here it is:

``` bash
$ blockstack register boomboom.id
Registering boomboom.id will cost 0.00041 BTC. Continue? (y/n): y
{
    "error": "Unexpected error, <Fault 1: \"<type 'exceptions.TypeError'>:register() takes exactly 3 arguments (2 given)\">",
    "help": "Try getting latest version of CLI with sudo pip install blockstack --upgrade"
}
```

**Comment by muneeb-ali** [comment]
Thanks for reporting. I'll take a look (probably later in the evening)

**Comment by muneeb-ali** [comment]
It looks like you have an old version of the rpc_daemon running and the new copy of rpc_daemon was not started. A quick (and dirty) way to kill it is:

> pkill -9 python

You can view the two background processes and kill them by PID:

```
(registrar)muneeb@amsterdam:registrar$ ps -A | grep python
74404 ttys003    0:00.00 grep python
70245 ttys004    0:02.80 /Users/muneeb/.virtualenvs/test4/bin/python2.7 -m registrar.rpc_daemon start_daemon
70247 ttys004    0:12.64 /Users/muneeb/.virtualenvs/test4/bin/python2.7 -m registrar.rpc_daemon start_monitor
(registrar)muneeb@amsterdam:registrar$ 
```

**Comment by muneeb-ali** [comment]
Resolved.
