### ISSUE TITLE
Add specification for Programmatic Sign-In

### ISSUE THREAD

**Issue by chris-asl** [stx-labs/stacks.js#406]
As a developer I would like to be able to use programmatic sign in, where the flow does not involve the UI (browser) at all.

To help a bit further, my usecase is an app that when executed like so `node my_app publish a_message`, will write in a `my_file.json` in my storage on Gaia and then terminate. 

As @jackzampolin suggested in Slack, it would be nice to spec a flow for non UI auth.

Possibly related issue: #265.

**Comment by jackzampolin** [comment]
I think this could be solved by specing out a signin flow for CLI applications. This would be useful for:
- Generation of user specific indexes written directly to app storage periodically
- IoT integration
- etc...

**Comment by jackzampolin** [comment]
This is a related issue: https://github.com/blockstack/gaia/issues/96

**Comment by brandonparee** [comment]
Maybe a good solution for this would be to take some of the logic out of Blockstack browser create a new repository called `blockstack-auth` or something similar?

All of the logic from taking in the mnemonic and creating all of your profiles and private keys per app? 

I think it actually might look similar to your repository @jackzampolin :) (https://github.com/jackzampolin/blockstack-pki)

**Comment by adambarthelson** [comment]
+1

**Comment by jackzampolin** [comment]
I think the plan here is to pull the logic out of the browser and move it to `blockstack.js`.

A lot of that code is [here](https://github.com/blockstack/blockstack-browser/blob/master/app/js/utils/account-utils.js) if anyone wants to take a crack at it.

**Comment by bodymindarts** [comment]
Discussing ways to integrate blockstack apps with third parties today with @xdamman we came to the conclusion that this is a critical element.
