### ISSUE TITLE
Interface improvement suggestions

### ISSUE THREAD

**Issue by shea256** [stx-labs/stacks.js#41]
In this issue I'm outlining a list of interface improvement suggestions. It'd be nice to discuss them here and if you'd like, I can separate them out into different issues. Here they are:
#### Blockstack Info

In this command, are we going to have multiple queues like one for registrations and one for transfers? I noticed how you put "queue" at the front in order to keep them together in alphabetical sorting, but I'd like to suggest as an alternative that we have a top level object called "queues" and then have lists in the queues object for "registrations", "transfers", etc. That could look something like this:

``` json
{
  "queues": {
    "registrations": [],
    "transfers": []
  }
}
```

It looks cleaner this way and "queue_register" is a bit of a hard name to read. It took my brain a bit to process it the first time I saw it. Alternatively, if we only plan on having a registration queue, then we can change the name of this list to "registration_queue".
#### Blockstack Lookup

I'm thinking that we might want to change "data_record" to "data", as it looks much cleaner this way.

On the other hand, one could make a good case for being more explicit. If a user would be confused by seeing "data" instead of "data_record" then it probably makes sense to keep it. Otherwise, I'd simplify.
#### Blockstack Names

The labels in this command should be updated to be consistent. This means either "names_owned" should be changed to "names" OR "addresses[0].names" should be changed to "addresses[0].names_owned".

I'm inclined towards the former simply because the command is `blockstack names` but I feel like it could go either way.
#### Blockstack Wallet

As we discussed, we should remove this command from the default set of commands and roll it into the advanced mode. In addition, any command that relies on and interacts with public keys, addresses, and/or balances but not private keys should not require unlocking of the wallet. This can be simply addressed by storing an unencrypted public key alongside the encrypted private key. You might be already doing this (so in that case all you need to do is access it and derive the addresses).
#### Blockstack Config

I'm wondering whether we should update the `blockstack config` command so that it is only a "set" command and not a "get" command. The reason I'm thinking this makes sense is that it's a bit confusing to have certain pieces of information in the "info" command that can be obtained through another command (the "config" command) that returns a subset of that information (just the server info and advanced mode). It also seems to make sense to have the config option as only for "configuring" / setting configs.

This change would mean that if users want to get the configuration details, they would have to run `blockstack info`. The updated `blockstack config` command would then only be valid if options were provided.

**Comment by muneeb-ali** [comment]
1) Switched to using 'queue', thanks for the suggestion.
2) Inclining towards data_record (better to be explicit, people don't understand this new system and we might be using the term "data record" in our tutorials and videos etc)
3) Made it consistent with names_owned
4) This has been included.
5) This has also been included.

**Comment by shea256** [comment]
Great! Sounds good to me.
