### ISSUE TITLE
Error Handling: Automate error reporting

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#413]
We should consider making a unified `Error()` exception that encodes the following:

* A stack trace to the point in the code where it occurred
* A URL that, when clicked, will submit the stack trace anonymously to a bug reporter

The high-level goal is that if a user's app encounters a bug, and they look in the console and see this error, they'll see a helpful message saying something like "click here to report this bug to Blockstack", followed by a URL that encodes the error.

The URL should resolve to a form with a bug report, pre-filled with the data gathered from the stack trace.  The user would have a chance to consent to submit it.

**Comment by kantai** [comment]
Agreed. This can be really great for getting detailed error reports -- the idea being that we'd just prefill values using URL strings on the form: blockstack.org/bugs

A good place to start would be to look at how other frameworks have implemented this (in particular, I think there are tricks to making the console printout highly visible), and then try to emulate.

**Comment by hstove** [comment]
React does a pretty good job with error messages and warnings. I'm pretty sure if you just include a URL in the message, it gets formatted properly.

Here is an example of them creating [an `Error`](https://github.com/facebook/react/blob/94518b068bf52196abea0c83f4c9926bfe2065c6/packages/shared/invokeGuardedCallback.js#L163), and [a warning](https://github.com/facebook/react/blob/27535e7bfcb63e8a4d65f273311e380b4ca12eff/packages/react-dom/src/server/ReactPartialRenderer.js#L522).

I'm happy to help with this one.

**Comment by yknl** [comment]
Errors have been improved in https://github.com/blockstack/blockstack.js/pull/720
Although there isn't an automatically generated error reporting URL.
