### ISSUE TITLE
Multisig support

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#414]
Enable multisig transaction support across the board.

**Comment by kantai** [comment]
I did some preliminary work on adding this in a feature branch:

https://github.com/blockstack/blockstack.js/tree/feature/multisig-keys

There wouldn't need to be that much code to change in blockstack.js to add support for multisig. You can see the start of the code here:

https://github.com/blockstack/blockstack.js/commit/16360ac276b53373017cf4e846def0d51900e61e#diff-0fe27b4f19c9da5406e9a3b01b8c40c7R144

I think maybe the lowest-overhead method would be to add a SingleSigKeySigner class, and a function which takes the `string | { redeemScript, privateKeys }` input and always returns a "signer".

**Comment by kantai** [comment]
Side request: if you're working on this in the process of working on the stacks transaction support, can you make two separate PRs (the first enabling multi-sig and the second stacks transactions)? It's okay if the second depends on the first, but that way it'll be a lot easier to review changes.

**Comment by jcnelson** [comment]
I'm not sure that we need to have multisig support here as a design goal, since the `TransactionBroadcaster` class already provides a way to implement it.  Maybe this is more relevant for the CLI and the Browser?

**Comment by jcnelson** [comment]
Closing this in favor of simply using the `TransactionSigner` class.  Clients should implement multisig using it.
