### ISSUE TITLE
Hacker News username that's not lowercase isn't verifiable

### ISSUE THREAD

**Issue by BrunoBernardino** [stx-labs/stacks.js#415]
Can't take a screenshot now, but the error is due to the fact my username is `BrunoBernardino`, which isn't accepted [here](https://github.com/blockstack/blockstack.js/blob/f7fbfc05bbb1cc242b6fe8a0323941909787f2ab/src/profiles/services/hackerNews.js#L22) because the URL is lowercased [here](https://github.com/blockstack/blockstack.js/blob/f7fbfc05bbb1cc242b6fe8a0323941909787f2ab/src/profiles/services/hackerNews.js#L18).

I get the URL to validate by typing my username lowercase, but then Hacker News doesn't recognise it, thus continuing to fail validation.

The solution should be simply to lowercase the username on the check as well.

I'm currently working on this and will get a PR up.

**Comment by larrysalibra** [comment]
Fixed thanks to @BrunoBernardino 's pull request! The fix will be in the next release.
