### ISSUE TITLE
TypeError: Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by artus** [stx-labs/stacks.js#421]
I can't seem to use the storage functions (`getFile` and `putFile`) but all other functions work corectly.

I created a `required.js` that gets bundled by webpack:
```javascript
window.blockstack = require("blockstack");
```
which I bundle with this command (no config file):
```shell
webpack js/requires.js -o js/bundle.js
```
Logging in works flawlessly, but after login, when I execute this code for instance:
```javascript
blockstack.putFile("test.json", JSON.stringify({ content: "test"}), { encrypt: true });
```
or:
```javascript
blockstack.getFile("test.json", { decrypt: true }).then(response => console.log(response));
```
I always get this message:
```
TypeError: Error.captureStackTrace is not a function
Stack trace:
t.exports.tfSubError@https://artusvranken.github.io/BlockDiary/js/bundle.js:15:124984
e/<@https://artusvranken.github.io/BlockDiary/js/bundle.js:8:100358
e@https://artusvranken.github.io/BlockDiary/js/bundle.js:8:100298
d@https://artusvranken.github.io/BlockDiary/js/bundle.js:8:100729
t.exports.sign@https://artusvranken.github.io/BlockDiary/js/bundle.js:15:122911
p.prototype.sign@https://artusvranken.github.io/BlockDiary/js/bundle.js:8:143799
u/<@https://artusvranken.github.io/BlockDiary/js/bundle.js:37:37626
```
You can inspect the code [here](https://github.com/artusvranken/BlockDiary) and see a working example [here](https://artusvranken.github.io/BlockDiary/).

**Comment by kantai** [comment]
Hi @artusvranken --

This issue is related to function-name-ducktyping used by some of our dependencies: https://github.com/blockstack/blockstack.js#production-usage

Webpack by default will do minification in `production` mode -- those depndencies need to be whitelisted -- an example of a working webpack config is here: https://github.com/yknl/publik/blob/master/webpack.config.js#L10

**Comment by artus** [comment]
Ok, thanks for the quick reply. I'm looking forward to webpack documentation regarding `blockstack.js`.

**Comment by artus** [comment]
So, by using chrome I was able to see what the actual errormessage was:
```javascript
{"message":"Expected property \"1\" of type BigInteger, got n","__property":1,"__type":"BigInteger","__value":{"0":9987566,"1":41884898,"2":28104000,"3":53375808,"4":7989245,"5":12721022,"6":58654670,"7":48516029,"8":53408555,"9":2777307,"t":10,"s":0},"__valueTypeName":"n"}
```

which indeed has something to do with uglifying the javascript as you said above, and is explained [here](https://github.com/blockstack/blockstack.js/issues/335), but I already included the following code in my webpack.config.js:

```
const webpack = require('webpack');

const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const UglifyJsPluginConfig = new UglifyJsPlugin({
    uglifyOptions: {
        mangle: {
            reserved: [
                'Buffer',
                'BigInteger',
                'Point',
                'ECPubKey',
                'ECKey',
                'sha512_asm',
                'asm',
                'ECPair',
                'HDNode'
            ]
        }
    }
});

module.exports = {
    entry: './js/requires.js',
    target: 'web',
    output: {
        filename: './js/bundle.js',
    }, plugins: [
        UglifyJsPluginConfig
    ]
}
```

And still I get the errors?

[EDIT] I tried to use `uglifyjs-webpack-plugin` AND `uglify-es-webpack-plugin` but neither solved the issue.

**Comment by artus** [comment]
For some reason, I didn't update anything to my webpack config but the app started working. No clue why but the above webpack config seems to do the job.
