### ISSUE TITLE
Better instructions for webpacking blockstack.js

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#423]
Our readme does provide a _hint_ that some types need to be whitelisted when uglifying/minifying -- but people get stuck pretty frequently when they use webpack. We should probably have a more detailed warning indicating that users of webpack should read that section, and an example config.

Related to report: https://github.com/blockstack/blockstack.js/issues/421

**Comment by kantai** [comment]
JustinRC also encountered this problem (reported on Slack).

**Comment by yknl** [comment]
The library now uses Webpack, this should no longer be an issue.
