### ISSUE TITLE
Profile URL bug during user authentication

### ISSUE THREAD

**Issue by 0xpbj** [stx-labs/stacks.js#431]
When a user has a new ID-Hash, and they haven't set their profile url, the authentication fails consistently and does not give a proper error message.

<img width="1317" alt="screen shot 2018-04-16 at 8 34 12 am" src="https://user-images.githubusercontent.com/11723563/38820244-34640436-4152-11e8-97d9-0c8c197a4b23.png">

> 2018-04-16T08:33:09.795-0700 DEBUG utils/profile-utils.js: Failed to find profile at https://gaia.blockstack.org/hub/12ELFuCsjCx5zxVDyNxttnYe9VLrRbLuMm/3/profile.json... trying others

> main.js:3779 Uncaught (in promise) TypeError: Cannot read property 'profileUrl' of null
    at main.js:3779

**Comment by kantai** [comment]
This looks related to this PR and issue over here: https://github.com/blockstack/blockstack-browser/pull/1275 -- what version of the browser are you using?

**Comment by 0xpbj** [comment]
I'm using 0.26.2, is it fixed in 0.28?

**Comment by kantai** [comment]
Yes, it should be

**Comment by 0xpbj** [comment]
Great, will test it with 0.28 when it's available.

**Comment by 0xpbj** [comment]
Works in 0.28, closing issue.
