### ISSUE TITLE
Error Handling: Returns null when querying multi-player file for non-configured app.

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#432]
If I query for the app URL for a multi-player file for an app not in my `apps` array, it just returns null. This should probably throw a useful error.

```javascript
 bsk.getUserAppFileUrl("public.json","blankstein.id","https://testy.test.test")
     .then(text => console.log(text))
```

**Comment by kantai** [comment]
@dhealy05's issue #374 and PR #375 are related to this issue. In particular, returning `null` here leads to a `null` in the promise rejection.

**Comment by bodymindarts** [comment]
I ran into this and was not able to figure out the root cause without @kantai's help. Better error messages would certainly have helped.

**Comment by hstove** [comment]
I'm happy to take this on this sprint if no one has started yet.

**Comment by ghost** [comment]
Ran into this as well, caught error was `null` so hard to figure out what was going on. 

Turns out the other user I was trying to pull up logged in via `http` instead of `https`. Turned on forced SSL and was no longer an issue when the user logged in again.

**Comment by yknl** [comment]
Better error handling implemented in https://github.com/blockstack/blockstack.js/pull/720
A proper error will now be thrown instead of returning null.
