### ISSUE TITLE
Error upgrading to 0.17.x

### ISSUE THREAD

**Issue by dantrevino** [stx-labs/stacks.js#434]
I get this error for 0.17.x releases.  Up to 0.16.1 everything works fine.  This is not when building for production, but using 'npm run dev' , using `vue-cli init pwa` template.

```
Uncaught (in promise) TypeError: Cannot read property '-1' of null
    at BN.bitLength (bn.js?81eb:622)
    at Point._hasDoubles (base.js?07a0:331)
    at Point.mul (short.js?c2b3:426)
    at KeyPair.getPublic (key.js?c8c9:62)
    at decryptECIES (encryption.js?fde7:117)
    at eval (index.js?f1aa:118)
```
the last line resolves to:
      `return (0, _encryption.decryptECIES)(privateKey, cipherObject);`

**Comment by dantrevino** [comment]
My code looks like this:  
`blockstack.putFile('index.json', [], {'encrypt': true})`
`blockstack.getFile('index.json', {'decrypt': true}).then...`

**Comment by hstove** [comment]
I think I've seen this when there was an error with login, and the library can't properly get the public key. Since 0.17 is supposed to help with auth issues, maybe try re-logging in? Sorry if you already have, but I think the issue is that `privateKey` is null.

**Comment by dantrevino** [comment]
Turns out I was trying to decrypt an unencrypted file.  Thanks to @jehunter5811 for the suggestion.

This can be closed.

**Comment by vsund** [comment]
Though I think there should be a clearer error message @dantrevino ;)

**Comment by hstove** [comment]
Agreed, I’m working on improving error messages and I’ll include this.
