### ISSUE TITLE
Error handling: improve when decryption fails

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#436]
We need better error handling when decryption fails (e.g., if the file wasn't encrypted in the first place).

This has been experienced more frequently since the upgrade where we switched to encrypt-by-default (see issue #434).

**Comment by hstove** [comment]
Perhaps we could detect that it's not a cipher object, and then just return the un-decrypted file contents, with a warning logged. Usually I might say it'd be better to explicitly fail, but this would help with backwards compatibility since we changed to default encryption.

**Comment by kantai** [comment]
I like that idea, but I'd be a little concerned about the security ramifications -- basically, if the storage host decided they wanted to launch an integrity attack on the user, they would "downgrade" to decrypted data, which would get returned to the user without error. Others may have different opinions, but I think if the error message is clear enough, that a developer who is updating their application will notice the problem, and change the decrypt/encrypt flags to false (we could provide that hint in the error message, maybe?)

**Comment by hstove** [comment]
👍 agreed.
