### ISSUE TITLE
Add formal logging levels

### ISSUE THREAD

**Issue by hstove** [stx-labs/stacks.js#440]
Coming from the conversation around #439, we should have introduce a formal logger with different levels (i.e. error, warn, info, debug). Then, developers can specify what level they'd want to display, with different configuration for development and production.

**Comment by vsund** [comment]
Just to throw this in here, I have a `Logger` class in the TypeScript fork:
https://github.com/ntzwrk/blockstack.ts/blob/develop/src/debug.ts#L10

**Comment by hstove** [comment]
Thanks for the heads up, we'll likely just want to copy that API and use it wherever you use `Logger` in that project.

**Comment by vsund** [comment]
I also added error levels like I thought they would be, would be cool if someone would have a second eye on this.

Also the code probably isn't anymore this close to the original. I refactored the structure in big parts (and [more to come](https://github.com/ntzwrk/blockstack.ts/issues/15) ;)).

**Comment by kantai** [comment]
This was merged into master in release 17.2.0, thanks @hstove
