### ISSUE TITLE
Add support for name search to our API

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#445]
We want to encourage developers to use a javascript search api instead of calling the search endpoint manually.

This will allow us to make search fall back to the name resolver endpoint if a name is not found making it so that newly registered names are immediately discoverable by search.

**Comment by kantai** [comment]
This would also address #456 -- which is a requirement for instantaneously usable name registrations.

**Comment by larrysalibra** [comment]
Yep. I'll take this on my plate to work on in my free time during this event. Thanks @kantai

**Comment by kantai** [comment]
Have a look at:

https://github.com/blockstack/blockstack.js/tree/feature/user-search?files=1
