### ISSUE TITLE
Add social verification for non .id names (.personal.id, .stealthy.id, etc)

### ISSUE THREAD

**Issue by 0xpbj** [stx-labs/stacks.js#446]
I verified prabhaav.stealthy.id with twitter: https://twitter.com/rabhaav/status/989518691476717569

But the browser is not confirming it: 

![image](https://user-images.githubusercontent.com/11723563/39318799-f0e1900e-4933-11e8-9fca-86d69b8cbd6d.png)

**Comment by liphan** [comment]
same here, liphan.stealthy.id cannot be verified with 
twitter: https://twitter.com/liphan_/status/994514853355184128
github: https://gist.github.com/liphan/5d22b0fefbef8a7988b677a88bab1a3d
can someone please advise ?

**Comment by 0xpbj** [comment]
@yknl @kantai

**Comment by yknl** [comment]
The social proof validation library assumes that the format of the username is `name.id` and will throw an error if there are more than 2 parts. e.g. `sponsored.name.id`.

This line needs to be fixed: https://github.com/blockstack/blockstack.js/blob/master/src/profiles/services/serviceUtils.js#L9

**Comment by larrysalibra** [comment]
Thanks @wbobeirne this will be in the next release.

**Comment by blkmrktmatt** [comment]
still having issues here with name.id.blockstack - the error in console is:
`Uncaught (in promise) Error: Please provide the fully qualified Blockstack name.
    at containsValidProofStatement (main.js:66562)`

**Comment by yknl** [comment]
hey @blkmrktmatt can you confirm which version of the Browser you're using?

**Comment by blkmrktmatt** [comment]
I'm using the latest Blockstack-for-macOS-v0.30.1, strange thing though last night on my laptop hackernews and twitter showed both verified, today on my desktop both unverified

**Comment by yknl** [comment]
This should be fixed when the browser upgrades to the latest version of blockstack.js
https://github.com/blockstack/blockstack-browser/issues/1582

**Comment by yknl** [comment]
This should now be working with latest browser and blockstack.js versions.
