### ISSUE TITLE
A better interface for network object

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#449]
Currently, the network object is used through the blockstack.config -- that's awkward and strange. We should wrap that, so that you can call

```
import { network } from 'blockstack'

network.getInfo()
```

And it works.

**Comment by grantlouisherman** [comment]
hey @markmhx could I take this issue?

**Comment by markmhendrickson** [comment]
@grantlouisherman definitely, thanks! 🙏

**Comment by dmaizel** [comment]
Is this still relevant? If so I'd love to take this

**Comment by yknl** [comment]
This is not relevant anymore, a new network library is under development for Stacks 2.0.
