### ISSUE TITLE
Improvements to error messages

### ISSUE THREAD

**Issue by shea256** [stx-labs/stacks.js#45]
I went through a bunch of the commands and noted error messages that are either missing or invalid or could use some improvements to better communicate to the user what is going on.

Here's the list I came up with:
#### Cost, Lookup, Transfer, Update and Whois

With an invalid name is provided to either the cost, lookup, transfer, update, or whois command, this should be reported to the user and the reason the name is invalid should be specified.

As an example, with the commands `blockstack cost a` or `blockstack lookup a` (or the equivalents for transfer, update and whois), the error message should be updated to the following:

```
The name specified is invalid. Names must be included with a valid TLD.
```

With `blockstack cost %` or `blockstack lookup %`, the error message should be updated to the following:

```
The name specified is invalid. Names may only contain alphanumeric characters, dashes, and underscores and must end with a period followed by a valid TLD.
```

With the name `blockstack cost .id` or `blockstack lookup .id`, the error message should be updated to the following:

```
The name specified is invalid. Names must be at least one character long, not including the TLD.
```
#### Cost

In particular, with the cost command, there is currently no error message for the invalid command `blockstack cost .id`. Instead the following is returned:

```
$ blockstack cost .id
{
    "details": {
        "registration_fee": 6.25e-05,
        "transactions_fee": 0.00016
    },
    "total_cost": 0.00022250000000000001
}
```

We should update the error message to the one specified in the previous section.

Next, when a name registration costs more than the balance, the following error message should be returned:

```
The cost of the name you're trying to register exceeds your wallet's balance.
```
#### Transfer

Update the error message shown when an invalid name transfer is attempted:

```
The name you're trying to transfer is not in your possession.
```
#### Update

Update the error message shown when an invalid name update is attempted:

```
The name you're trying to update is not in your possession.
```
#### Register

With the register command, if a name is invalid the error message returned should indicate the name is invalid. Currently this message is returned: "This namespace doesn't exist, try using namespaces like .id". We should use the same error messages specified in the other commands above, depending on whether the name is lacking a TLD or whether the name doesn't have any characters or whether invalid characters are used.

Also, if `blockstack register .id` is entered, the user should not be taken to register the name. Instead, an error should be thrown.

**Comment by muneeb-ali** [comment]
Resolved in 113f5c474ea8e513273ea70274edce3bacd1ae3d

**Comment by shea256** [comment]
Awesome, feels like a breeze!

Just noticed, though, that there still needs to be updates on the error messages for transfers and updates on names you do not own.

Right now when you try to transfer or update a name you don't own, the following message is shown:

``` json
{
    "error": "a.id not owned by 1KBUsvXmSRMUTxp1GhftnbvDeRaEM2D6MX"
}
```

Two things jump out at me:
1. Ownership should be independent of the address, so the address shouldn't be mentioned in the error message.
2. The error message should form a full sentence.

Thus, I'd suggest updating the messages to the following:

```
The name you're trying to transfer is not in your possession.
```

**Comment by muneeb-ali** [comment]
Resolved
