### ISSUE TITLE
Fix scope explanation

### ISSUE THREAD

**Issue by artus** [stx-labs/stacks.js#451]
A scentence in the scope explanation in the README.md is incomplete.

https://github.com/blockstack/blockstack.js/blob/master/src/auth/README.md#scopes

> If no scopes array is provided to the `redirectToSignIn` or `makeAuthRequest` functions.

**Comment by wbobeirne** [comment]
This has been fixed to

> If no scopes array is provided to the redirectToSignIn or makeAuthRequest functions, the default is to request ['store_write'].
