### ISSUE TITLE
Option to pass auth response token to handlePendingSignIn

### ISSUE THREAD

**Issue by muneebm** [stx-labs/stacks.js#464]
Current implementation of `handlePendingSignIn` uses `getAuthResponseToken` to get the auth response token from query string. It would be helpful for users implementing their own authentication flow to have an option to pass the auth response token to `handlePendingSignIn`. 

For example, in an electron app (with custom protocol handler `blockstack-electron` and appDomain  'http://localhost:8080' ), the following would be a possible auth flow:
1. In a BrowserWindow, `makeAuthRequest` with 'http://localhost:8080/redirect' as the redirect URL
2. Call `redirectToSignInWithAuthRequest` with auth request created in step 1
3. On successful authentication, Blockstack browser will call the redirect URL 'http://localhost:8080/redirect',  which in turn will redirect to `blockstack-electron://redirect?authResponse=xxxxxxx`
4. In electron app, handle the redirect `blockstack-electron://redirect?authResponse=xxxxxxx` in the main process and pass the auth response token to the BrowserWindow that called `redirectToSignInWithAuthRequest`
5. In BrowserWindow, pass the auth response token using `handlePendingSignIn` to blockstack.js

**Comment by larrysalibra** [comment]
Thanks for the pull request fixing this @muneebm - will be in the next release!
