### ISSUE TITLE
InvalidDIDError uses "param" instead of "parameter"

### ISSUE THREAD

**Issue by MichaelFedora** [stx-labs/stacks.js#468]
Everything else, including the superclass, uses `parameter`.

https://github.com/blockstack/blockstack.js/blob/e8b0c2afaaa432283b47726a89b6388699b38125/src/errors.js#L57

^ this should be `super({ code: 'invalid_did_error', message, parameter: '' }) `

**Comment by vsund** [comment]
Can second this, occurred (alongside some other flaws like this) while porting to a type-safe language: https://github.com/ntzwrk/blockstack.ts/commit/3116488faf12b10ee9a200c060e1de0ba736511f

**Comment by larrysalibra** [comment]
Fixed in the next release!
