### ISSUE TITLE
won't work with create-react-app

### ISSUE THREAD

**Issue by DanielRHayes** [stx-labs/stacks.js#472]
Whenever I try to build an app I've created with `create-react-app` I get the following error.  I also opened an issue with the `uri-js` library.  I'm also making a quick PR to remove `uri-js` and replace it with `url` from node's api.

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/blockstack/node_modules/uri-js/dist/esnext/uri.js:42

Read more here: http://bit.ly/2tRViJ9
```

**Comment by larrysalibra** [comment]
Thanks for fixing this @DanielRHayes  - it will ship in the next release.
