### ISSUE TITLE
Email confirmation as an identity Proof in the Blockstack Browser and claim in the jwt

### ISSUE THREAD

**Issue by ntheile** [stx-labs/stacks.js#476]
Is it possible to add email as a proof, much like a twitter or facebook account is a proof. You could send a confirmation email for the user to click with a one time code like in most apps on the centralized internet to prove an authentic user email claim.

Many apps would need this feature to know they are dealing with a real user and a real email that they own.

**Comment by yknl** [comment]
Proofs are meant to be verifiable by anyone, emails are only readable by the user themselves. So this wouldn't be possible in the current proof setup.
