### ISSUE TITLE
Reading someone's public file by using identity address

### ISSUE THREAD

**Issue by mehmetkose** [stx-labs/stacks.js#478]
I think we can get someone's file like this. But I want to let users can use my app without any blockstack.id, so is it possible? Or is there any way to do this?

```JavaScript
 let options = {user:'mehmetkose.id',app:'http://fupio.com'}
 blockstack.getFile("/message.txt", options)
 .then((fileContents) => {...});
```

```JavaScript
 let options = {identity:'18h4Xkg9mFhwhLgokzBkggLQ5RD6KAiAvs', app: 'http://fupio.com' }
 blockstack.getFile("/message.txt", options)
 .then((fileContents) => {...});
```

**Comment by jcnelson** [comment]
There is no way to do this, since it's not possible to resolve an arbitrary Bitcoin address to a Gaia hub.  The Blockstack ID (anchored to the Bitcoin blockchain) is what makes this name-to-Gaia-hub resolution possible.

**Comment by mehmetkose** [comment]
I see. was just a question. thanks.
