### ISSUE TITLE
updates to password behavior

### ISSUE THREAD

**Issue by shea256** [stx-labs/stacks.js#48]
The wallet setup process is awesome. Nice flow.

The only issue I noticed was that passwords were displayed in plaintext. I figured we'd get around to updating this at some point and I didn't think this was an urgent issue until @guylepage3 took a screenshot (thankfully he blocked out the password).

After we launch the CLI, we're probably going to be getting a bunch of people providing us with feedback - some will send us screenshots of their terminals and I fear that some will accidentally take screenshots with their passwords. 

The way to fix this would be to treat the input as a masked password input. I've seen some command line input tools have native support for this but I haven't checked in a while.

Is this something we can add in quickly before the release? No worries if not, but if are able to it might save us some grief from the HN crowd.

**Comment by muneeb-ali** [comment]
Resolved in d3bb8a1b3e3ee157774f080a17bffc2275ac91c9
