### ISSUE TITLE
On iOS safari, always redirect to browser.blockstack.org

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#481]
Until we ship our native iOS app, we should always redirect to browser.blockstack.org on mobile Safari. 

This will prevent "unsupported protocol handler" messages on iOS devices.

Thanks to @bodymindarts for raising this issue.

Tagging @shreyasthiagaraj so he's aware of this when working on the future iOS app.

**Comment by ntheile** [comment]
is there a simple temporary workaround for this today? 

or is it possible to sniff out an ios safari agent string and construct the login uri to browser.blockstack.org in my code manually?

**Comment by ericgay** [comment]
This also happens on Safari on OSX. It works fine on OSX Chrome, however (no protocol error/heads to the blockstack site fine).

**Comment by larrysalibra** [comment]
@wbobeirne Thanks for taking this off my plate!

**Comment by wbobeirne** [comment]
@ericgay I cannot replicate it on macOS Safari, it shows a prompt and then works fine. Can you provide any more details about your issue? For the time being, I'll be implementing a fix just for iOS.

<img width="473" alt="screen shot 2018-07-26 at 9 28 46 am" src="https://user-images.githubusercontent.com/649992/43265311-61e112e2-90b6-11e8-92d5-015c8539d9d9.png">

**Comment by larrysalibra** [comment]
This will ship in the next release.
