### ISSUE TITLE
(Mis)use of stale `isomorphic-fetch` package

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#486]
`isomorphic-fetch` is a stale `npm` package, that seems to no longer be maintained.

This is an issue for `node` clients (like @jcnelson 's `node-cli`), because the `node-fetch` version included in that `isomorphic-fetch` is out of date, and doesn't have the necessary features for things like `storage` lookups of non-text data.

Further, we just shouldn't be using unmaintained packages.

@wbobeirne suggested https://github.com/lquixada/cross-fetch
Another viable alternative is to fork `isomorphic-fetch` and just update `node-fetch`.

**Comment by wbobeirne** [comment]
If it's in a purely node environment (e.g. the cli) we should probably just cut out the middleman and not use any isomorphic fetch package, and use node-fetch directly.

**Comment by jcnelson** [comment]
Either way, the node.js environment will have to monkey-patch in a different `fetch` if `isomorphic-fetch` is present.

**Comment by kantai** [comment]
This library is used in both pure node and browser environments, which means that _some_ patching library has to be used for the same `fetch` calling code to work in both environments (unless we want to use some other system of passing the `fetch` function into `blockstack.js` calls, which we shouldn't want to do). I believe simply replacing `isomorphic-fetch` with `cross-fetch` will resolve this issue.

**Comment by kantai** [comment]
This is fixed in `18.0.2`
