### ISSUE TITLE
Pass `nameLookupUrl` into an application on sign-in

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#495]
Applications should not be selecting the Core API endpoint to use to handle sign-ins, and we shouldn't be hard-coding one.  Instead, the Browser (or whatever process is controlling the sign-in flow) needs to be able to tell the application which name lookup URL to use.  This [PR](https://github.com/blockstack/blockstack.js/pull/494) addresses this.

**Comment by yknl** [comment]
Implemented in https://github.com/blockstack/blockstack.js/pull/503
