### ISSUE TITLE
Both fee and fee estimation endpoint should be configurable

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#498]
The `getFee()` method hardcodes the fee estimation endpoint. This should be configurable. We should also allow configuration of a fee-per-byte setting by the developer without relying on the existence of an external service.
 https://github.com/blockstack/blockstack.js/blob/e8b0c2afaaa432283b47726a89b6388699b38125/src/network.js#L405

See this forum post for context: https://forum.blockstack.org/t/how-to-set-custom-tx-fee/5781?u=larry

**Comment by kantai** [comment]
A developer could monkey-patch the `getFeeRate` function in the network option like:

```javascript
function myGetFee() {
   return Promise.resolve(1)
}

boundGetFee = config.network.bind(myGetFee)
config.network.getFeeRate = boundGetFee
```

An alternative is to subclass the Network object and redefine the `getFee` method. I think those options give the developer the most flexibility (as opposed to make this some sort of configurable setting, like a passed in API URL, or something).

**Comment by kantai** [comment]
Indeed, it looks like subclassing is how @jcnelson implemented it in the CLI: https://github.com/jcnelson/cli-blockstack/blob/master/src/network.js#L95

**Comment by markmhendrickson** [comment]
@agraebe Will this remain relevant in a Stacks 2.0 world?

**Comment by agraebe** [comment]
Not sure, what's the reasoning for the request? Our current fee estimate is coming from an endpoint still. It is per byte, so one would need the raw tx byte size as multiplier

**Comment by markmhendrickson** [comment]
I was going through the icebox and noticed this issue, so asking for general housekeeping purposes.

I assume the original context for custom fee estimates here was paid IDs in the deprecated Blockstack Browser, which we're removing for mainnet. So perhaps this functionality can be excised in general from blockstack.js.

**Comment by agraebe** [comment]
makes sense to me. I'd close this and reopen if it comes up again somewhere
