### ISSUE TITLE
Make use of compression before saving to GAIA

### ISSUE THREAD

**Issue by x5engine** [stx-labs/stacks.js#499]
Hello All,

I stumbled upon this library that Facebook uses which compresses data before saving it

https://github.com/zhipeng-jia/snappyjs

and I think this might be a very good thing to have before saving the files offering more space to store data.

Thanks

**Comment by jcnelson** [comment]
Hi @meteorplus ,

The application is more than capable of doing this itself if it wants to compress data.  Compressing data isn't free, nor is there a single "good" compression algorithm, nor is it safe to do things in combination with compression (like compress-then-encrypt, which leaks information about the plaintext).

**Comment by larrysalibra** [comment]
Thanks for the suggestion @meteorplus.

Files written to gaia that are unencrypted are intended to be directly usable by apps and websites that don't use any of the blockstack libraries...think loading an unencrypted file in an image tag.

I agree with @jcnelson that this is something that belongs in the application or a higher level library. Feel free to start a discussion on the forum
https://forum.blockstack.org/ if you'd like some help on different ways to approach this!
