### ISSUE TITLE
Why is this not working ? ( multi storage getFile API )

### ISSUE THREAD

**Issue by karanganesan** [stx-labs/stacks.js#511]
const options = { username: 'ntncodex.id.blockstack', decrypt: true, zoneFileLookupURL: 'https://core.blockstack.org/v1/names/'}

  blockstack.getFile('statuses.json', options)
    .then((file) => {
      console.log(JSON.stringify(file));
    })
    .catch((error) => {
      console.log('could not fetch statuses')
    })
    .finally(() => {
      console.log("finally");
    })

**Comment by larrysalibra** [comment]
Reported from: 
https://twitter.com/karanganesan/status/1023295660106440705

![djn56vixsaajhrw jpg-large](https://user-images.githubusercontent.com/597182/43368105-564b7c84-938a-11e8-9239-3275ee701da8.jpeg)

**Comment by larrysalibra** [comment]
Hi @karanganesan ! I'm so sorry you ran into this problem!

 It looks like you're using an old version of blockstack.js that expects a local core node and doesn't support the type of sponsored username you're using.

Try using the current version 18.0.2.

May I ask which instructions or tutorial you were following? Want to make sure we update anything that is out of date!

**Comment by karanganesan** [comment]
Started with this https://blockstack.org/tutorials/hello-blockstack/ which might be having a outdated version

Followed https://blockstack.org/tutorials/multi-player-storage/ since I am not comfortable with React I took the syntaxs from it and used it in Todo example and tried all the methods from the Multi player storage example using blockstack.method .....

**Comment by karanganesan** [comment]
![screenshot 20](https://user-images.githubusercontent.com/6049925/43467809-3032d480-9500-11e8-948f-2a16a916aea8.png)
![screenshot 21](https://user-images.githubusercontent.com/6049925/43467811-306c20be-9500-11e8-9999-e64dca80270f.png)

why do i get these ?

**Comment by karanganesan** [comment]
These happened when I updated to 18.0.2

**Comment by karanganesan** [comment]
It's working 💫🎉🎉🎉

**Comment by karanganesan** [comment]
Better use this method

https://forum.blockstack.org/t/how-can-i-import-blockstack-js-as-a-script-without-using-a-package-manager/5881
