### ISSUE TITLE
mainnet addresses/private keys even if the blockchain in use is in testset mode

### ISSUE THREAD

**Issue by cyanoboy** [stx-labs/stacks.js#52]
When I run the `wallet`command for the first time it creates addresses of the mainnet type (beginning with 1xxxxx), even if I the blockstack-server node is linked to a bitcoin node in testnet mode. In that case it should initialize blockstack wallet with testnet addresses/private keys (beginning with mxxxx, nxxxx, etc.)

**Comment by muneeb-ali** [comment]
Thanks for reporting this. You're right that the client currently does not have support for testnet addresses and we will work on adding that.

**Comment by muneeb-ali** [comment]
What we need to do is support a testnet mode that:

a) automatically connects you to a server that is running in testnet mode
b) switches you to a wallet with testnet addresses
and c) we need to create testnet namespaces that users can experiment with

**Comment by jcnelson** [comment]
This is now added in the upcoming release (0.0.14).  Had to upgrade the server, virtualchain, and test framework as well, so they could understand testnet addresses.  You can try it out in the `rc-0.0.14.0` branches (`develop` in `blockstack-server`) by setting `BLOCKSTACK_TESTNET=1` as an environment variable.

**Comment by jcnelson** [comment]
This is fixed in 0.14.0 (now merged to `master`).  To use, simply `export BLOCKSTACK_TESTNET=1` before running `blockstack`.  Please re-open this issue if you're still having problems.  Also, please note that you'll need to spin up a testnet Blockstack Core node with `BLOCKSTACK_TESTNET=1` set in its environment variables.
