### ISSUE TITLE
FF Android issues with custom protocol handlers

### ISSUE THREAD

**Issue by stackatron** [stx-labs/stacks.js#521]
> probably something not supported by firefox here: https://github.com/blockstack/blockstack.js/blob/master/src/auth/authApp.js#L71
> probably our custom protocol detection module https://github.com/larrysalibra/custom-protocol-detection
> 
> Will O'Beirne [2:31 PM]
> Yeah, I agree it's probably in there. I just can't get this damn remote debugger working argh.
> 
> Will O'Beirne [2:49 PM]
> @kenliao Looks like Firefox falsely reports that the handler is supported:
> ```blockstack.js: generating v1.1.0 auth request
> openUriUsingFirefox
> protocol handler detected```
> 
> kenliao [2:54 PM]
> ahh
> this makes a great case for not using protocol handlers, but instead go directly to browser.blockstack.org and use web extensions to intercept requests
> 
> Will O'Beirne [2:55 PM]
> Yeah, this is like the third browser I've run into this month that has some jank with protocol detection

**Comment by larrysalibra** [comment]
Thanks for taking care of this @wbobeirne !
