### ISSUE TITLE
getFile not working for non logged in users - Uncaught TypeError: Cannot read property 'hubUrl' of null

### ISSUE THREAD

**Issue by digitalwaveride** [stx-labs/stacks.js#523]
Referring to this conversation in the forum https://forum.blockstack.org/t/sharing-public-data-page-with-not-logged-in-users/5894/3 I have an issue with sharing data/pages publicly to non logged in users.

The following code in the React app works for logged in users without problems (-> The putFile method, as well as getFill have encrypt set to false), for non Blockstack users I get
 `Uncaught TypeError: Cannot read property 'hubUrl' of null`.

```
fetchData() {
    this.setState({ isLoading: true })
    //hardcoded username -> just for this example//
    const username = "digitalwaveriding.id"
    const options = { username: username, decrypt: false, zoneFileLookupURL: 'https://core.blockstack.org/v1/names/' }
    getFile(textsFileName, options)
      .then((file) => {

        var arrTexts = JSON.parse(file || '[]');
        this.setState({
          arrTexts: arrTexts,
        })
      })
      .finally(() => {
        this.setState({ isLoading: false })
      })
    };

```

**Comment by jcnelson** [comment]
Hey @digitalwaveride ,

Can you also try passing `verify: false` as well as `decrypt: false`?  This issue seems to be a side-effect of this other issue here: https://github.com/blockstack/blockstack.js/issues/500

**Comment by digitalwaveride** [comment]
Hey @jcnelson,

thanks so much for looking into this.
Tried to set verify and decrypt to false, unfortunately I still get the same error.
Here is the current code:

```
  fetchData() {
    this.setState({ isLoading: true })
    const username = this.state.curator
    const options = { username: username, verify: false, decrypt: false, zoneFileLookupURL: 'https://core.blockstack.org/v1/names/' }
    getFile(textsFileName, options)
      .then((file) => {
        var arrTexts = JSON.parse(file || '[]');
        var collections = [...new Set([].concat(...arrTexts.map(o => o.tags)))];
        this.setState({
          collections: collections,
          arrTexts: arrTexts,
        })
      })
      .finally(() => {
        this.setState({ isLoading: false })
      })
    };
```

**Comment by polluterofminds** [comment]
@jcnelson I'm able to replicate this. Adding the verify option doesn't resolve the problem. I've resorted to making multiple HTTP requests to get around this, but I'd like to be able to make just the one with getFile.

**Comment by jcnelson** [comment]
> The following code in the React app works for logged in users without problems (-> The putFile method, as well as getFill have encrypt set to false), for non Blockstack users I get

I might be missing something here.  Are you trying to read from a non-Blockstack user's Gaia hub?  The only way you can read from someone else's Gaia hub is if they have a Blockstack ID.

> @jcnelson I'm able to replicate this. Adding the verify option doesn't resolve the problem. I've resorted to making multiple HTTP requests to get around this, but I'd like to be able to make just the one with getFile.

Thanks for confirming!  Can you post the code you're using?  Also, are you doing this in the browser, node, or react native?

Here's what I'm seeing in my (node.js) test:
```
$ node
> bsk = require('blockstack')
...
> global['window'] = { location: { origin: null } }
{ location: { origin: null } }
> bsk.getFile('statuses.json', { username: 'ryan.id', app: 'http://publik.ykliao.com', decrypt: false, verify: false }).then((data) => console.log(data))
[{"id":0,"text":"Hello, Blockstack!","created_at":1515786983492}]
> 
```

**Comment by polluterofminds** [comment]
No problem! Here's one example, but all of them fail for me with the same error documents in the original post for the issue: 

```
const options = { username: userToLoadFrom, zoneFileLookupURL: "https://core.blockstack.org/v1/names", decrypt: false, verify: false}
getFile('publicposts.json', options)
      .then((fileContents) => {
        this.setState({ publicPosts: JSON.parse(fileContents || '{}') });
      })
```

The userToLoadFrom variable I'm testing with is jehunter5811.id.

**Comment by jcnelson** [comment]
Just following up here.  You need to also pass the `app` field in the `options`.  It should match the application origin.

**Comment by polluterofminds** [comment]
@jcnelson Just tried the above suggestion. Can you confirm this is what the options parameter should look like with the app field?

`const options = { username: userToLoadFrom, zoneFileLookupURL: "https://core.blockstack.org/v1/names", decrypt: false, verify: false, app: 'http://localhost:3000'}`

**Comment by jcnelson** [comment]
Yeah, assuming @digitalwaveride's app is hosted at `http://localhost:3000`.

**Comment by polluterofminds** [comment]
I'm not sure about his, but in my testing locally my app origin is definitely `http://localhost:3000`. Still getting the same error, though when passing the app value into the options object.  :(

**Comment by digitalwaveride** [comment]
> I might be missing something here. Are you trying to read from a non-Blockstack user's Gaia hub? The only way you can read from someone else's Gaia hub is if they have a Blockstack ID.

I am trying to read from a Blockstack users Gaia Hub, but with a user who is not logged in to Blockstack. The usecase is basically sharing a page publicly via Twitter etc you name it. Users should have access to the particularly site without being a logged in Blockstack user.

**Comment by digitalwaveride** [comment]
> Yeah, assuming @digitalwaveride's app is hosted at http://localhost:3000.

My app is hosted on http://localhost:8080/

I just tried with
```
const options = { username: username, zoneFileLookupURL: "https://core.blockstack.org/v1/names", decrypt: false, verify: false, app: 'http://localhost:8080'}
getFile(textsFileName, options)
```


and still got this error:
`Uncaught TypeError: Cannot read property 'hubUrl' of null`

**Comment by jcnelson** [comment]
Can you confirm that your profile for `jehunter5811.id` contains an `apps` entry for `http://localhost:3000`?

**Comment by polluterofminds** [comment]
Confirmed: https://gaia.blockstack.org/hub/16KyUebBPPXgQLvA1f51bpsne3gL7Emdrc/0/profile.json

**Comment by jcnelson** [comment]
I'm still having a hard time duplicating this.  Are you able to get the problem to show up when the app is not on `localhost`?

**Comment by polluterofminds** [comment]
Hey Jude, 

Here are all the variations I just tested: 

jehunter5811.id + https://app.graphitedocs.com
jehunter5811.id + http://localhost:3000
graphite.id + https://app.graphitedocs.com
graphite.id + http://localhost:3000

All of them result in the "Cannot read property 'hubUrl' of null" error. If you need something to test in browser rather than from the CLI, I can throw something up on Netlify pretty quickly.

**Comment by jcnelson** [comment]
Hey @jehunter5811, 

Thanks for your examples!  I tried to get `publicposts.json` from your `jehunter5811.id`'s entry for Graphite (`https://app.graphitedocs.com`).  The Gaia hub read prefix for `https://app.graphitedocs.com` in your profile for `jehunter5811.id` is `https://gaia.blockstack.org/hub/1Q5G5kWwDikELELXc54tNdwTg8gbfnLKDU/`, which means that `publicposts.json` should be at https://gaia.blockstack.org/hub/1Q5G5kWwDikELELXc54tNdwTg8gbfnLKDU/publicposts.json.  However, I'm getting a 404 on that file.  This is also true for `graphite.id`.  Do you have another file I can try?

**Comment by polluterofminds** [comment]
@jcnelson Try `/key.json`

**Comment by jcnelson** [comment]
Tried `key.json` and got `03be3120c8e957e50832a4c2de9b039a795a0076d1e1c59044054a519e8dbc3523`.

Here's the code snippit that runs in my test webapp:

```
blockstack.getFile('key.json', { username: 'jehunter5811.id', app: 'https://app.graphitedocs.com', verify: false, decrypt: false })
  .then(function(data) {
    console.log('key.json is ' + data)
  })
```

**Comment by polluterofminds** [comment]
Hmm, wonder if this is a React-specific issue then. @digitalwaveride, is your a React app?

**Comment by digitalwaveride** [comment]
Sorry @jehunter5811 , for what ever reason I missed this last comment.
Yes, it's a React app.

**Comment by seanaye** [comment]
I am getting a similar issue when I provide a username to the options object. If I am logged in as the file owner then I can access the file with
`
{ verify: true, decrypt: false }
`
but when I provide a username 
`
{ verify: true, decrypt: false, username: myusername }
`
then I get could not read property match of null

**Comment by zone117x** [comment]
@seanaye That looks like a different bug -- can you open a new issue for it?
