### ISSUE TITLE
Add an authentication flow that does not depend on `window.location` and `window.localStorage`

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#526]
This is related to https://github.com/blockstack/blockstack.js/issues/500, but the concern is more general than just storage.  In addition to Node.js clients like the CLI, Web clients need to be able to run code from blockstack.js in web workers, which today means transferring this state from the browser into the web worker.

Is there a way the app can initiate a sign-in flow where all this state is passed as arguments and/or stored in a global variable in RAM?  For example, could `handlePendingSignin()` be modified to take an alternative value for `window.location` and be instructed to populate a given object with the Gaia session data and transit keys?  Asking because I'm not sure what the best approach is here (but happy to take a crack at it!)

**Comment by yknl** [comment]
The dependency on a browser environment has been removed since v18.0
