### ISSUE TITLE
Feature request: be able to pass arbitrary private key to decrypt data

### ISSUE THREAD

**Issue by aulneau** [stx-labs/stacks.js#527]
I think there is some confusion (at least on my part) related to multiplayer storage. I've done some research and talked with some people about it, but still generally I am confused. I found [this thread](https://forum.blockstack.org/t/multiplayer-access-sharing-with-the-public-vs-just-trusted-users/4225/8?u=aulneau.id), which has been helpful but I feel like some/all of what was talked about is not yet implemented.

Currently the method `putFile` is able to take a `publicKey` to encrypt the data it's storing with. Generally we use that in the way that we're going to encrypt data for only one other user with their public key they then can decrypt later. 

Let's say I generate my own public/private key pair for a team in an application I am making. I can then store that key for any users who are apart of that team by encrypting it with their public key.

Examples:

Sharing the key with team members:
```jsx
const teamKeys = {
  public: "key",
  private: "key"
};

const teamMembers = ["aulneau.id", "jeff.id", "larry.id"];

const encryptKeysForMembers = () =>
  teamMembers.for(async member => {
    const { publicKey } = await blockstack.lookUpProfile(member);
    const options = {
      encrypt: publicKey
    };
    await putFile(teamKeys, options);
  });
``` 

Any team member could then do :

```jsx
// jeff.id

const teamKeys = await getFile(`/jeff.id/keyEncryptedWithUserPublicKey`, 'owner.id');

const options = {
    decrypt: teamKeys.private,
};

const sharedFile = await getFile(file, options);
``` 

Any team member can write data with these keys

```jsx
const options = {
    encrypt: teamKeys.public,
};

const sharedTeamFile = await putFile(file, options);
``` 

I think being able to encrypt/decrypt data with a private key that can be passed on its own would allow for replicating certain conventions that we expect from applications regarding sharing data with relationships other than 1-1.

Let me know if this makes sense or if I'm missing anything.

cc @larrysalibra @kantai @wbobeirne @yknl

**Comment by yknl** [comment]
Implemented in https://github.com/blockstack/blockstack.js/pull/723
