### ISSUE TITLE
Move profile functions to blockstack.js

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#532]
We want to [make it easy for users to encrypt data for other users.](https://github.com/blockstack/blockstack.js/issues/527) @kantai has [submitted a proposal](https://github.com/blockstack/blockstack.js/issues/458) for how to do that that involves adding additional data to the profile.json file.

Presently some code for manipulating profiles lives in this library while the remainder lives in various places in the browser. This makes it challenging to both reason about and test.

I propose that code for manipulating the profile file belongs in this library including:
* profiles-utils.js: https://github.com/blockstack/blockstack-browser/blob/8d15b3e60d49a3e110d8e39b72324e27fa5c977b/app/js/utils/profile-utils.js#L1
* functions for uploading profile and avatar https://github.com/blockstack/blockstack-browser/blob/master/app/js/account/utils/index.js
* logic for adding `apps` to profile.json https://github.com/blockstack/blockstack-browser/blob/8d15b3e60d49a3e110d8e39b72324e27fa5c977b/app/js/auth/index.js#L260

It makes sense to do this first before moving forward with either #527 or #458.

Tagging @yknl @wbobeirne for their thoughts on this.

**Comment by wbobeirne** [comment]
Very in favor of this. It would be nice to outline what this new API looks like, and if there are any improvements and better forms of encapsulization we can add to make it simpler and easier to use than Browser's implementation.

**Comment by larrysalibra** [comment]
@wbobeirne ❤️ simpler and easier!  I can take some time to go through this tomorrow and propose an API before starting to move anything.

**Comment by yknl** [comment]
Also very in favour of this. It would make it a lot easier to build your own Blockstack browser.

**Comment by larrysalibra** [comment]
I looked into this a bit today - we use lower-level non-public methods to write the profile and avatar photo to Gaia currently in the browser that apps typically wouldn't use.

The blockstack id's identity address private key is used as what in a normal app would be the app private key.  

While moving this functionality, I think we should update it to use the standard `putFile` storage API that all other apps use. 

Right now, use of putFile is dependent on an app private key existing in localStorage. 

It makes sense to tackle #531 and refactor the library so that it no adds and reads data to `window.localStorage` 
https://github.com/blockstack/blockstack.js/issues/531 with telling developers.  This would let us make use the standard `putFile` in the implementation of this functionality without having to do weird hacks like asking the browser to store the identity private key to localStorage before writing a profile.

Going to hold off on moving forward on this issue until that is done.

**Comment by larrysalibra** [comment]
Tagging @kantai to double-check what I'm proposing with gaia above makes sense.

**Comment by kantai** [comment]
Does this seem like a good use case for the forthcoming gaia.js stand alone
client library? Blockstack.js seems to generally make a lot of assumptions
about its environment (in particular, that it is being used within an app),
where a generic putFile to a Gaia hub would be all that’s necessary here.

**Comment by larrysalibra** [comment]
> Blockstack.js seems to generally make a lot of assumptions
about its environment (in particular, that it is being used within an app)

Blockstack.js shouldn't make such strong assumptions about what type of app it's being using in. (The browser is an app after all!)

Handling a pending sign in should return some sort of state data that the developer can choose to store or not store where he chooses. (see proposal and discussion about state from last fall https://forum.blockstack.org/t/duplication-of-code-state-in-blockstack/1539?u=larry)

**Comment by larrysalibra** [comment]
> Does this seem like a good use case for the forthcoming gaia.js stand alone
client library?

This approach would make sense if this functionality was going to stay in browser - if we're moving it to blockstack.js with the idea that people could use it to create an alternate browser, it seems like it should use the same code paths to upload that other apps use.

Having said that, directly using the gaia.js library in blockstack.js to implement upload profile/photo might be the way we go about implementing it.
