### ISSUE TITLE
Recover blockstack wallet from HD private key

### ISSUE THREAD

**Issue by koinster** [stx-labs/stacks.js#54]
Currently I can't recover my blockstack wallet from a private key.  Will this be added so I can recover my wallet on a separate machine?

**Comment by jcnelson** [comment]
This will be possible in certain cases, provided that (1) you didn't set your private keys directly with e.g. `import_wallet`, and (2) you aren't using a multisig ownership or payment address (which requires multiple independent private keys).  The multisig support hasn't been deployed yet, but will be in a few weeks.

In the mean time, you can decrypt the wallet and extract the bare information (multisig or not) with the following script.  I'll add this into the CLI for the next release.

```
#!/usr/bin/python

import blockstack_client
import sys
import json
from getpass import getpass

if len(sys.argv) != 2:
    print >> sys.stderr, "Usage: %s /path/to/wallet.json" % (sys.argv[0])
    sys.exit(1)

wallet_path = sys.argv[1]
password = getpass("Wallet password: ")

with open(wallet_path, "r") as f:
    wallet_data = f.read()

wallet_data = json.loads(wallet_data)

ret = blockstack_client.wallet.decrypt_wallet( wallet_data, password )
print json.dumps(ret, indent=4, sort_keys=True)

sys.exit(0)
```

**Comment by jcnelson** [comment]
In 0.14.0, we've added a `blockstack wallet` command that will print out the base58check key information stored in `~/.blockstack/wallet.json`.
