### ISSUE TITLE
Add gaia hub write url to profile.json

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#540]
Apps need to know which gaia hub write url to use. They can't get this from the user's profile file because read and write urls are different. This information is passed to apps during the browser/authenticator during the authentication process.

The browser/authenticator needs to know the write URL for a given gaia hub. This state should be stored in the user's profile.json encrypted so that only the user's authenticator can read it.

**Comment by shankarganesh-pj** [comment]
Thanks for creating the issue.

**Comment by jcnelson** [comment]
Dup of https://github.com/blockstack/blockstack-browser/issues/1489.  Should I close the one on the Browser?

**Comment by jcnelson** [comment]
I think this is solved now with the `api` field in the profile?

**Comment by yknl** [comment]
This should be resolved with the added `api` field in the profile as mentioned above.
