### ISSUE TITLE
Make sure dependencies are transpiled to ES5

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#541]
A number of our dependencies aren't compiled to ES5 - this is preventing blockstack.js from being used in javascript engines that don't support ES5 such as duktape.

@friedger is going to take a look at this since it's blocking us on Android

**Comment by friedger** [comment]
running dist/blockstack.js again through babel solved the issues I had.

@larrysalibra for duktape, there is still a dependency to the browser in FormData in networks.js (using `window.FormData`)

**Comment by yknl** [comment]
This is now fixed in latest version.
