### ISSUE TITLE
Should accept "Bearer" or "bearer"

### ISSUE THREAD

**Issue by polluterofminds** [stx-labs/stacks.js#544]
Most posts using a bearer token send a header with a capitalized "Bearer". In testing making posts to a gaia hub without Blockstack.js, I kept hitting errors and just got lucky enough to find this line and realize I needed to manually lowercase "bearer".

I could see server side and api implmentations of blockstack storage needing to make their own custom calls to the api, so case sensitivity of "bearer" could be a problem.

https://github.com/blockstack/blockstack.js/blob/77f6ef6e3fd4f9db359bede548c1591937fb49a8/src/storage/hub.js#L30

**Comment by moxiegirl** [comment]
@kantai just putting this on your radar.

**Comment by kantai** [comment]
Got it -- thanks for flagging this @jehunter5811 and @moxiegirl 

This was merged into Gaia 2.2.1 and deployed.

**Comment by moxiegirl** [comment]
Closing as this was fixed @jehunter5811 feel free to reopen if I've closed this in error.
