### ISSUE TITLE
Expose more API methods

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#548]
I'm just starting this issue to keep track of API methods I know that at least one Blockstack app is using that are not yet considered public in blockstack.js.  We can decide what to do with them later.

* getPublicKeyFromPrivate()
* encryptECIES()
* decryptECIES()

**Comment by hstove** [comment]
👍 I use these APIs in Kanstack. Also the signature methods, so:

- `signECDSA()`
- `verifyECDSA()`

Also,

- `makeECPrivateKey()`
- `connectToGaiaHub()` (for scoped auth tokens, not sure if documented)

**Comment by ntheile** [comment]
yep i use all the mentioned api's in my app! it would be awesome to have formal documentation on them! thanks

**Comment by jcnelson** [comment]
I would like to be able to use:

* `getFullReadUrl()`
* `getOrSetLocalGaiaHubConnection()` -- in particular, I want to be able to connect to Gaia hubs without relying on localStorage
* `makeV1GaiaAuthToken()` -- in particular, I want to be able to connect to arbitrary Gaia hubs from an app

In addition, I'll probably want to move the CLI's `makeAssociationToken()` method to blockstack.js in support of `makeV1GaiaAuthToken()`.

**Comment by moxiegirl** [comment]
@kantai Do we need to do anything related to core or think about core before exposing these?

**Comment by kantai** [comment]
@moxiegirl -- I don't think so, these methods being exposed shouldn't affect core.

**Comment by yknl** [comment]
tracking in new issue: https://github.com/blockstack/blockstack.js/issues/768
