### ISSUE TITLE
Support for multiple addresses within the blockstack wallet

### ISSUE THREAD

**Issue by koinster** [stx-labs/stacks.js#55]
Currently my wallet only allows for one address.  For privacy, this should be implemented as multiple accounts will be owned by one address.

**Comment by muneeb-ali** [comment]
The functionality for this is kind of already there since we're using a HD wallet. We've artificially limited the number of addresses to just 1 "payment address" and 1 "owner address" for simplicity. We plan to work on enabling multiple addresses.

**Comment by muneeb-ali** [comment]
@koinster we merged the CLI repo with [blockstack-core](http://github.com/blockstack/blockstack-core) and I moved this issue there. Closing this copy of the issue.
