### ISSUE TITLE
[18.1.0] Structure token related methods

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#555]
Currently, the token related methods are listed under **Storage** in the documentation.

**Comment by friedger** [comment]
@moxiegirl furthermore, some methods like `getNameInfo` are not exported via the `blockstack` object, but `blockstack.config.network`

**Comment by friedger** [comment]
@moxiegirl Where/how is the documentation generated? Could you add some pointers how to fix that?

**Comment by moxiegirl** [comment]
@friedger Just saw this.  I'll fix it today.

**Comment by moxiegirl** [comment]
I'm working on this now...I'll doc how to run this in the readme.

**Comment by moxiegirl** [comment]
@friedger  The left hand navigation is defined with the `documentation.yml` toc file.  That file seems to work ok when the functions are under `src/subdirect/file.js` but it doesn't work under `src/file.js` which is the current situation with `network.js`. I guess when they added the `network.js` file they broke the pattern of how they were adding other functions.

I did not select documentationjs as a tool for documenting this repo. It was something @larrysalibra  had in place. I added the toc to make it more usable but planned to switch the tool.

I've got work related to the wallet, the cli, and Gaia I need to do first before I can get back to this and get it sorted.  I had hoped it would be quick fix but it doesn't seem to be.  The problem isn't critical just annoying.

If you want to take a stab at it see my work in progress commit above. I provide an update to the README. And further pointers.




```
$ npm run build-documentation

> blockstack@18.1.0 build-documentation /Users/manthony/repos/blockstack.js
> documentation build src --config ./documentation.yml --format html --output docs; ./node_modules/.bin/documentation build src --config ./documentation.yml --format json --output docs.json

Failed to read file /Users/manthony/repos/blockstack.js/src/READMETOKEN.mdTable of contents defined sorting of getZonefile but no documentation with that namepath was found
Table of contents defined sorting of getNamePrice but no documentation with that namepath was found
Table of contents defined sorting of getNamespacePrice but no documentation with that namepath was found
Table of contents defined sorting of getGracePeriod but no documentation with that namepath was found
Table of contents defined sorting of getNamesOwned but no documentation with that namepath was found
Table of contents defined sorting of getNamespaceBurnAddress but no documentation with that namepath was found
Table of contents defined sorting of getNameInfo but no documentation with that namepath was found
Table of contents defined sorting of getNamespaceInfo but no documentation with that namepath was found
Table of contents defined sorting of getAccountStatus but no documentation with that namepath was found
Table of contents defined sorting of getAccountHistoryPage but no documentation with that namepath was found
Table of contents defined sorting of getAccountAt but no documentation with that namepath was found
Table of contents defined sorting of getAccountTokens but no documentation with that namepath was found
Table of contents defined sorting of getAccountBalance but no documentation with that namepath was found
Failed to read file /Users/manthony/repos/blockstack.js/src/READMETOKEN.mdTable of contents defined sorting of getZonefile but no documentation with that namepath was found
Table of contents defined sorting of getNamePrice but no documentation with that namepath was found
Table of contents defined sorting of getNamespacePrice but no documentation with that namepath was found
Table of contents 
```

**Comment by yknl** [comment]
Closing as this should be fixed in new version of docs
