### ISSUE TITLE
Add javascript without package manager docs

### ISSUE THREAD

**Issue by moxiegirl** [stx-labs/stacks.js#560]
@markmhx wrote on Slack:

I didn't even realize this was possible through our own documentation, had to google search to find the forum post where someone asked https://forum.blockstack.org/t/how-can-i-import-blockstack-js-as-a-script-without-using-a-package-manager/5881/3

Blockstack Forum
How can I import blockstack.js as a script without using a package manager?
Yes! You can download blockstack.js from the dist folder and use it without npm! https://github.com/blockstack/blockstack.js/tree/master/dist This is how we use it in both our ruby blockstack omniauth strategy and blockstack-android libraries. I added an issue to update our readme and make this more clear! Thank you for the feedback!!! https://github.com/blockstack/blockstack.js/issues/517
Aug 2nd

But my sense is that letting someone play around with blockstack via a web-based code editor like CodePen (already prepopulated with some starter code?) could be very potent

**Comment by moxiegirl** [comment]
@markmhx I've put this up as good first task in case a contributor wants to pick it up.  But it is labeled docs so also on my todo.

**Comment by tpscrpt** [comment]
@moxiegirl @markmhx I've setup a AWS CodeBuild trigger which gets master and compiles a .min.js every hour. The result can be found at https://s3.amazonaws.com/minifyjs/blockstack/blockstack.min.js

**Comment by tpscrpt** [comment]
https://github.com/blockstack/blockstack.js/pull/567#issuecomment-442919635

**Comment by aulneau** [comment]
Hey @JeremiGendron! Thanks for the changes you're suggesting. 

I think a better solution would be that we during our build process we publish a minified version to NPM, and then suggest people use a service like https://unpkg.com/#/ to get access to that. It has the advantage of mirroring npm and also is most likely a service that won't go down.

**Comment by tpscrpt** [comment]
@aulneau Ok, I'll check it out

**Comment by markmhendrickson** [comment]
@JeremiGendron Thanks for taking the initiative here!

**Comment by tpscrpt** [comment]
@markmhx Thank you! I have some questions about the scripts which would be appropriate. Currently, I have it setup so the `build` script now transpiles and uglifies, which yields both `dist/.es5.js` and `dist/.min.js`. Would you like the `prepublishOnly` script to be different from the `build` script? Or is `build` only used when publishing?

**Comment by tpscrpt** [comment]
https://unpkg.com/demo-blockstack-dist is my attempt. I can still customize the package.json scripts if you want something more modular.

**Comment by markmhendrickson** [comment]
@JeremiGendron I'm not familiar with the scripts that have been set up for this repo, but at a glance, it appears that the `prepublishOnly` script is effectively an alias for `build`?

@aulneau Thoughts on @JeremiGendron's unkpg build above?

**Comment by moxiegirl** [comment]
@JeremiGendron Apologies for the slow reply. This slipped through my email. I'll take a look at this and see if we can't move it along. Thank you so much for the PR

**Comment by tpscrpt** [comment]
Same here, no worries!

**Comment by zone117x** [comment]
This is done and live.
