### ISSUE TITLE
Methods are listed in wrong category in Documentation

### ISSUE THREAD

**Issue by shreyasthiagaraj** [stx-labs/stacks.js#562]
http://blockstack.github.io/blockstack.js/index.html

`getGracePeriod`, `getNamePrice`, etc. (the methods added as part of the last release) are all under "Storage". They don't belong there. We probably need categories for "Names" and "Accounts" (this one could also be part of "Profile").

**Comment by friedger** [comment]
Probably same as #555

**Comment by yknl** [comment]
Closing as this should be fixed in new version of docs
