### ISSUE TITLE
Require secure context

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#566]
When an app sends an auth request to the blockstack browser or to gaia the library should check for 
`window.isSecureContext`, shouldn't it?

**Comment by hstove** [comment]
This would require apps to use https, which obviously is a good thing, but isn't something we've required in the past. Even if we added this, developers could work around that pretty easily.

If we truly wanted to force SSL, we'd have to do that on the Browser.

We'd also need to have extra checks for localhost.

Some developers use `.dev` URLs by pointing localhost to a certain domain in their hosts file, so this would break that as well.

**Comment by friedger** [comment]
`localhost` is considered secure.

Indeed, the developer could not use the library. Still, I think the developers  (and finally the end users) should be educated what can go wrong in the context of blockstack if you are not using a secure context.

**Comment by friedger** [comment]
I open a new issue in docs.blockstack.
