### ISSUE TITLE
Update auth request to allow prompting for Gaia hub with an optional default hub

### ISSUE THREAD

**Issue by hstove** [stx-labs/stacks.js#568]
There are two new parameters to set in the auth request:

- `recommendedGaiaHubUrl`: a `String` that is a 'default' URL that the user should be prompted to use
- `solicitGaiaHubUrl`: a `Boolean` to indicate whether the user should be sent through the new Browser flow that prompts for a user-specified Gaia hub.

**Comment by markmhendrickson** [comment]
Is this issue resolved entirely by the above PR?

**Comment by markmhendrickson** [comment]
@hstove *nudge*
