### ISSUE TITLE
Import external private key to blockstack wallet

### ISSUE THREAD

**Issue by koinster** [stx-labs/stacks.js#57]
There doesn't seem to be a way to import an external private key into the blockstack wallet separately.  A user may want to transfer their ID to a different address that they own and outside of the blockstack wallet.  The user can then import the separate key in order to manage it.

**Comment by muneeb-ali** [comment]
Thanks for the suggestion. I'm marking this under feature request and we'll keep you posted on when this gets rolled out.

**Comment by clehner** [comment]
Would importing an external private key allow for maintaining access to a name that was migrated from Namecoin to Blockstack? i.e. if I have a private key for a namecoin address that I used to control a Onename id before the migration, could I import the same private key to use it to control the name now?

**Comment by muneeb-ali** [comment]
@clehner: I think there are two parts to this:

(a) How to get a bitcoin address from a namecoin privatekey
(b) How to import a bitcoin privatekey into the Blockstack CLI

Let's try to push solutions for both of these soon :-)

**Comment by jcnelson** [comment]
The `develop` branch now supports setting the owner private key, the payment private key, and the data private key with the `import_wallet` directive.

**Comment by jcnelson** [comment]
Fixed with `import_wallet` in the new stable release.

**Comment by cloxy** [comment]
Please, give us example how to import name from Namecoin to Blockstack via "import_wallet" command.
1. Exporting u/name private key.
2. Finding the Bitcoin's corresponding address of that private key.
3. Creating wallet in Blockstack.
4. ??? How to import the private key into that wallet?
