### ISSUE TITLE
Feature request: search for users by partial username

### ISSUE THREAD

**Issue by kwingram25** [stx-labs/stacks.js#570]
Currently the only way to access public data for other Blockstack users (as far as I'm aware) is to input their full username and attempt lookupProfile(). There should be an additional function to query for multiple possible user matches based on an input string, which would enable a better user experience for Dapps - i.e. being able to show a live-updating autocomplete for possible user matches while typing.

Perhaps:
```
searchForProfiles(partial: string, zoneFileLookupURL: string): Promise
```
resolving to an array of matching profile objects?

**Comment by polluterofminds** [comment]
@kwingram25 there isn't a blockstack.js method, but there is a public endpoint that offers this functionality: 

https://core.blockstack.org/v1/search?query=

Enter the search term after `query=`

**Comment by kwingram25** [comment]
Ah thank you! I still think there might be value in adding it as a method, even just as a wrapper for that core method - similar to how [lookupProfile](https://github.com/blockstack/blockstack.js/blob/master/src/profiles/profileLookup.js) is implemented
