### ISSUE TITLE
Failed to open uri while redirectAndSignIn

### ISSUE THREAD

**Issue by pshenmic** [stx-labs/stacks.js#571]
Hello. I have issue on my environment (Ubuntu 18.04) when blockstackjs library trying to detect protocol and handle redirection. Earlier, I tried to set up local blockstack browser which seems to messed up my environment and led to the error above.

![image](https://user-images.githubusercontent.com/17009187/49578663-cfa8b080-f97c-11e8-945e-27b1e21398e8.png)

Actually, I don't really need local browser feature, I want all my users to authenticate via browser.blockstack.org. I tried to put this url as second argument, but this does not work.

**Comment by moxiegirl** [comment]
@pshenmic Thanks for logging this issue.  @shreyasthiagaraj or @larrysalibra  any suggestions for what to do.

**Comment by larrysalibra** [comment]
@pshenmic You can use the [`makeAuthRequest`](http://blockstack.github.io/blockstack.js/index.html#makeauthrequest) method to generate an the auth request token string and then redirect the user to by appending the string to `http://browser.blockstack.org/auth?authRequest=` and then redirecting users to the result. 

As to how to uninstall the protocol handler on Ubuntu, @kantai should be able to help you out!

**Comment by markmhendrickson** [comment]
I've assigned this to @zone117x since he's actively working on protocol handling and can incorporate Ubuntu into his considerations per @pshenmic's report.

@pshenmic were you able to use the `makeAuthRequest` method per @larrysalibra's suggestion to direct users to the hosted browser successfully?

@zone117x I've also experienced the same "Failed to open URI" having installed then uninstalled the local browser. Do your protocol handling changes (https://github.com/blockstack/blockstack.js/pull/591) address this case?

**Comment by zone117x** [comment]
Yes it should fix that situation because it will now *always* perform an https redirect unless the local browser is actually opened to notify the web app that it's working.

And I believe the iframe method for opening the protocol prevents these type of popups - although that needs testing.

**Comment by kantai** [comment]
To remove the Ubuntu protocol handler, you should:

1. Remove the entry from your `mimeapps.list` -- edit the file `~/.local/share/applications/mimeapps.list` and remove the `x-scheme-handler/blockstack` entry.
2. Rename the blockstack protocol handler `.desktop` file:
```
mv ~/.local/share/applications/blockstack.desktop ~/.local/share/applications/blockstack.desktop.old 
```

This will remove any protocol association the OS has with `blockstack:` URLs.

**Comment by pshenmic** [comment]
@kantai This instruction did not help me. I don't have anything related to the blockstack in mimeapps.list and blockstack.desktop does not exist in such path.

@larrysalibra But you said it does not work that way on the blockstack forum. https://forum.blockstack.org/t/callback-is-not-fired-with-blockstack-auth/6857/5

**Comment by pshenmic** [comment]
The same happened on different environment (Debian), where I havent even installed blockstack browser any time.

Console reports
```
openUriWithTimeoutHack
[INFO] protocol handler detected
```
