### ISSUE TITLE
`nameLookupURL` set as undefined when testing locally

### ISSUE THREAD

**Issue by medied** [stx-labs/stacks.js#578]
Had to switch between different Blockstack accounts for testing and then started getting this error when attempting to login: 

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined at /Users/medied/internet/blockstack/sovereign/node_modules/blockstack/lib/auth/authVerification.js
```

Some details:

- This error comes up on server console and makes login fail only when testing locally, I can login successfully with the same account on a deployed version of the app. 
- I have tested locally with three different accounts that have a `<username>.id.blockstack` set (for example medied.id.blockstack), and all fail on login with the same error
- I was originally testing with an account that didn't have a username set (an older account created back in the Onename time) and it was working fine locally. I added a username recently to test and now I get the same error
- Have tried clearing `localStorage` and resetting `node_modules`

Talking it over with @hstove we think I'm probably overwriting some arguments somewhere. Any guidance on how I can reset or debug? The code is open source on branch ['bstack2' here](https://github.com/DemocracyEarth/sovereign/tree/bstack2), am curious to know if anyone else can replicate. It seems there's [been similar issues](https://github.com/blockstack/blockstack.js/issues/218#issuecomment-310483080) in the past but this may be specific to my setup

**Comment by medied** [comment]
Creating a brand new Blockstack account results in the same behavior: error locally and successful login on deployed

**Comment by medied** [comment]
When `verifyAuthResponse` is invoked [here](https://github.com/DemocracyEarth/sovereign/blob/bstack2/imports/startup/both/modules/blockstack.js#L101) it's only being provided with first argument `token` but not `nameLookupURL`, hence `nameLookupURL` is undefined. Looks like `nameLookupURL` was added as an argument in [this commit](https://github.com/blockstack/blockstack.js/commit/608905c3d4cf6354d9b44b22387f29b7eb87c8fd) which was after this piece of code was [originally written](https://github.com/DemocracyEarth/sovereign/commit/fc8c708b0a425adaaad0125c8a44c09c7e665284). 

Can someone point me to documentation on `nameLookupURL`? Trying to understand what needs to be provided exactly.

**Comment by yknl** [comment]
@medied the `nameLookupURL` is the URL of the Blockstack core node that you want to use to resolve usernames to profiles. Can you see if it's making any network calls to core nodes in the network logs? For example: `https://core.blockstack.org/v1/names/muneeb.id`. The default is set to `core.blockstack.org`

**Comment by medied** [comment]
Thank you @yknl for the feedback! [Seeing now](https://forum.blockstack.org/t/adding-blockstack-authentication-to-a-centralized-app/6252/8) that `handlePendingSignIn` calls `verifyAuthResponse`, so the call that was failing seems to be redundant and unnecessary. I opted for removing it altogether and the app is working as expected, closing this issue for the time being.
