### ISSUE TITLE
Distribute a browser-ready standalone blockstack.js

### ISSUE THREAD

**Issue by djnicholson** [stx-labs/stacks.js#584]
I don't use npm, browserify, etc. I would like to be able to download a standalone JavaScript file that when referenced from a HTML file makes the methods described in http://blockstack.github.io/blockstack.js/index.html available to the browser.  How do I easily generate this file?

I tried this:
1. create an empty npm project
2. install blockstacks and browserify
3. create a JS file requires.js containing the following:
window.blockstack = require('blockstack')
4. run:
browserify requires.js > dist.js

However, the dist.js file I generated was massive, and still had require(...) calls in it.

**Comment by zone117x** [comment]
Related to https://github.com/blockstack/blockstack.js/issues/582

**Comment by markmhendrickson** [comment]
There's some activity on this at https://github.com/blockstack/blockstack.js/issues/560 as well.

**Comment by zone117x** [comment]
This is done and live.

**Comment by idkjs** [comment]
Since this is deprecated, what is the lib we are supposed to move to?

**Comment by markmhendrickson** [comment]
@idkjs see https://github.com/blockstack/stacks.js#stacksjs-
