### ISSUE TITLE
getNameInfo method is undefined

### ISSUE THREAD

**Issue by markmhendrickson** [stx-labs/stacks.js#587]
I'm unable to find and use the [`getNameInfo` method](https://blockstack.github.io/blockstack.js/#getnameinfo) for some reason.

```
import blockstack from 'npm:blockstack';
let name = 'markmhendrickson.id';

blockstack.getNameInfo(name).then((info) => {
  console.log('info', info);
});
```

This results in the error `Uncaught TypeError: _npmBlockstack.default.getNameInfo is not a function` and when I console log the entire `blockstack` module (loaded with [ember-browserify](https://github.com/ef4/ember-browserify)) for inspection, I don't see it in the list of properties alphabetically:

<img width="684" alt="screen shot 2018-12-24 at 11 20 29" src="https://user-images.githubusercontent.com/28991/50397086-3f38e100-076e-11e9-997a-2c07be75faa6.png">

**Comment by friedger** [comment]
You need to use `blockstack.config.network.getNameInfo` See also 
https://github.com/blockstack/blockstack.js/issues/555#issuecomment-441011884

**Comment by markmhendrickson** [comment]
Much thanks. I see the other issue is intended to update documentation related to this method, but does it make much sense that this method (and others) are under a `config` path? I would expect `blockstack.network.getNameInfo` if it's intended to be organized with other "network" methods. But "config" is confusing to me.

**Comment by kantai** [comment]
Ooh, yeah, we have a feature request for this:

https://github.com/blockstack/blockstack.js/issues/449

**Comment by kantai** [comment]
Closing this in favor of #449
