### ISSUE TITLE
Correct parameter for multi-player getFile calls in documentation

### ISSUE THREAD

**Issue by markmhendrickson** [stx-labs/stacks.js#588]
The blockstack.js documentation indicates that a `username` option ought to be specified to fetch data from a particular user: https://blockstack.github.io/blockstack.js/#getfile

<img width="994" alt="screen shot 2018-12-24 at 18 39 46" src="https://user-images.githubusercontent.com/28991/50404743-d708f000-07ab-11e9-9688-d6f63f69adfc.png">

I found that setting this option would incur the fetching of the indicated user's zone file, but I ran into a zone file parsing error deep in the flatten method of the dependency [zone-file-js](https://github.com/blockstack/zone-file-js) that stumped me for a couple of hours.

I decided to search around to double-check my approach and found that the README for storage indicates this option should actually be named `user`: https://github.com/blockstack/blockstack.js/blob/master/src/storage/README.md#reading-another-users-unencrypted-file

<img width="958" alt="screen shot 2018-12-24 at 18 43 04" src="https://user-images.githubusercontent.com/28991/50404746-da9c7700-07ab-11e9-8e1f-8a4e7ed30f1f.png">

So I changed my code and voila, it works. 💥

**Comment by markmhendrickson** [comment]
Hmm upon further testing, the `username` option name appears to be correct and the README is incorrect.

I'm still running into the same zone file parsing error, but I may file that as a separate issue and leave this one for updating just the README docs.

**Comment by moxiegirl** [comment]
@markmhx can you clarify where you are seeing this in the README? I think this issue might be outdated an no longer a problem.

**Comment by markmhendrickson** [comment]
It appears the README in question is gone now 🤷🏻‍♂️
