### ISSUE TITLE
Handle expired or revoked gaia authentication tokens

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#592]
`blockstack.js` should more seamlessly handle cases where authentication tokens are revoked or expire.

Those authentication tokens are meant to be ephemeral, however, blockstack.js caches them, making expirations (like the last year change) or revocations (these could be used triggered) very disruptive to applications.

**Comment by hstove** [comment]
This is fixed in 18.2.1 for `putFile`.

Good to close?

**Comment by kantai** [comment]
Yep!
