### ISSUE TITLE
ImportError: Twisted requires zope.interface 3.6.0 or later

### ISSUE THREAD

**Issue by Aranad** [stx-labs/stacks.js#60]
I'm getting this error on Linux Mint, I tried the deactivate command as per the troubleshooting section, but there's no such command.

**Comment by Aranad** [comment]
Fixed the problem with
`pip install zope.interface --upgrade`
Might be a good note to add in the troubleshooting section...

**Comment by muneeb-ali** [comment]
Thanks for posting the solution! Just added to the troubleshooting section. Also, feel free to submit a pull request with any changes to code and/or README in the future :-)
