### ISSUE TITLE
getFile not rejecting the Promise

### ISSUE THREAD

**Issue by benoror** [stx-labs/stacks.js#601]
[Blockstack docs (`18.2.0`)](http://blockstack.github.io/blockstack.js/#getfile) states that `getFile` :

> resolves to the raw data in the file or rejects with an error

Nevertheless in practice it does resolve the `Promise` and returns a `null` object instead, thus never getting into the `.catch(` statement.

Even the DEBUG log says it so:
> [DEBUG] getFile my/file.json returned 404, returning null

**Comment by yknl** [comment]
`getFile` now returns a proper error https://github.com/blockstack/blockstack.js/pull/720
