### ISSUE TITLE
Update the release checklist for this project

### ISSUE THREAD

**Issue by moxiegirl** [stx-labs/stacks.js#610]
We need to make sure that when releasing the blockstack.js library, need to make sure:

- The app-generator is updated
- The SDKs are updated
- The browser needs to be XXX?
- Gaia needs to XXX?

cc: @kantai @zone117x @friedger

**Comment by moxiegirl** [comment]
@yknl  I assigned this to you so you can catch anything I didn't actually capture in this ticket.

**Comment by zone117x** [comment]
Capturing the discussion on the dependency cadence workflow:
1. blockstack.js re-release package published
2. PRs opened on all consumer repos using the pre-release version. Tests get ran, make sure everything works.
3. blockstack.js stable release.
4. PRs on consumers repos updated to stable version then merged.

**Comment by yknl** [comment]
Addressed in https://github.com/blockstack/blockstack.js/pull/701
