### ISSUE TITLE
Investigate: Support node.js contexts with `UserSession`

### ISSUE THREAD

**Issue by hstove** [stx-labs/stacks.js#611]
Related to #500, also [a comment](https://github.com/blockstack/blockstack.js/pull/542#issuecomment-465693112) by @origin in the v19 PR.

Now that we have the `UserSession` stuff almost merged with support for different storage strategies, we should build a strategy for using blockstack.js with node.js. This shouldn't be too hard. When defining the `UserSession`, you should be able to pass an `appPrivateKey` during instantiation. This can be done depending on the user's implementation, but most users will likely use an `ENV` variable.

There is also [some code in `authApp.js`](https://github.com/blockstack/blockstack.js/blob/feature/storage-strategies/src/auth/authApp.js#L300) that uses `window` to do protocol handling stuff. This should be wrapped in a check for the presence of `window`. Right now, even importing that file in node.js will cause an error.

**Comment by Origin** [comment]
Is this something that can be worked on in parallel to #542?
