### ISSUE TITLE
Backwards compatibility functions don't work like they used to

### ISSUE THREAD

**Issue by hstove** [stx-labs/stacks.js#612]
This code breaks:

~~~javascript
import { loadUserData } from 'blockstack';

loadUserData();
~~~

Because the code references `this.UserSession()`, and that only works if you do `import * as blockstack`. Why do we need to do `this.UserSession()`, can't we just do `new UserSession()`?

**Comment by freethejazz** [comment]
This issue also affects the ability to pass around backwards compatibility functions for the same reason.

```
/* This no longer works */
let loadData = blockstack.loadUserData;
loadData();

/* Instead you need to bind the function */
let loadData = blockstack.loadUserData.bind(blockstack);
loadData();
```

The above example is trivial but I ran into this issue when integrating `blockstack.js` with `redux-sagas`. Note the required `bind` call in the code below:
```
export function* handlePendingSignIn(blockstack) {
  try {
    const user = yield call(blockstack.handlePendingSignIn.bind(blockstack));
    yield put(actions.setUserProfile(user))
  } catch (e) {
    yield put(actions.userSignInFailed())
  }
}
```

**Comment by freethejazz** [comment]
Should this be marked as fixed now since the necessary code change is in `develop`?

**Comment by moxiegirl** [comment]
@freethejazz should be. Wanna test it? Otherwise, I'll do a run of animal kingdom

**Comment by zone117x** [comment]
Closing since the fixes have been merged and should be in next release.
