### ISSUE TITLE
redirectToSignIn ignores arguments

### ISSUE THREAD

**Issue by freethejazz** [stx-labs/stacks.js#618]
`redirectToSignIn` claims to take several arguments, but promptly ignores them, resulting in broken behavior in backwards compatibility.

```
export function redirectToSignIn(redirectURI: string = `${window.location.origin}/`, 
                                 manifestURI: string = `${window.location.origin}/manifest.json`, 
                                 scopes: Array<string> = DEFAULT_SCOPE) { 
  console.warn('DEPRECATION WARNING: The static redirectToSignIn() function will be deprecated in the '
    + 'next major release of blockstack.js. Create an instance of UserSession and call the '
    + 'instance method redirectToSignIn().')
  const userSession = new this.UserSession()
  userSession.redirectToSignIn()
}
```
https://github.com/blockstack/blockstack.js/blob/master/src/auth/authApp.js#L64-L72

To honor these arguments, I believe we'll need to create an `AppConfig` with the passed arguments and pass it to the `UserSession` constructor.

**Comment by zone117x** [comment]
Thanks for the report @freethejazz, please keep filing issues for any backwards compatibility bugs you run into. We don't yet have tests for all public function signature permutations.

**Comment by zone117x** [comment]
Closing since this has been merged and should be available next release.
