### ISSUE TITLE
get_names_in_namespace returns only one name

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#62]
Using client with local server (version `0.0.10.7`) or server.blockstack.org (version `0.0.10.3`),`get_names_in_namespace` only returns `0.id` for the `id` TLD.

<img width="478" alt="screen shot 2016-03-18 at 4 36 45 pm" src="https://cloud.githubusercontent.com/assets/597182/13872803/e9c14806-ed27-11e5-9293-2a761abf0f8f.png">

**Comment by jcnelson** [comment]
I see it too; investigating...

**Comment by jcnelson** [comment]
Should be fixed now. Please re-open if it's not fixed.
