### ISSUE TITLE
add explicit error message for under funded payment address

### ISSUE THREAD

**Issue by muneeb-ali** [stx-labs/stacks.js#63]

**Comment by deandalianis** [comment]
I am trying to register a new name and I keep getting 
`"error": "Couldn't broadcast transaction. You can try again.".`

The price is: 
`{
   "name_price": 0.00025,
   "total_estimated_cost": 0.00041,
   "transaction_fee": 0.00016
}` 

and my wallet balance: 
`"balance": 0.0016`

Maybe it has something to do with an over-estimation of fees.

**Comment by muneeb-ali** [comment]
Thanks for reporting this. This is likely a combination of two things:

(a) Fee over estimation (https://github.com/blockstack/blockstack-cli/issues/76)
and (b) Not displaying correct/useful messages for this error. 

Can you try keeping at least around a $1 in your wallet and see if you hit the issue again? Thanks,

**Comment by jcnelson** [comment]
This has been fixed in the new release.
