### ISSUE TITLE
Check size on putFile

### ISSUE THREAD

**Issue by markmhendrickson** [stx-labs/stacks.js#636]
In support of https://github.com/blockstack/gaia/issues/161

**Comment by zone117x** [comment]
Tagging https://github.com/blockstack/gaia/pull/256

**Comment by yknl** [comment]
There are some questions to answer here before we can provide a solution. 
e.g. how do we determine content size when streaming a file

**Comment by zone117x** [comment]
Completed with https://github.com/blockstack/blockstack.js/pull/724
