### ISSUE TITLE
Passing custom `localStorage` key to `UserSession` doesn't work as expected.

### ISSUE THREAD

**Issue by hstove** [stx-labs/stacks.js#637]
When creating a `UserSession`, [you are allowed to pass some options to use a different localStorageKey key](https://github.com/blockstack/blockstack.js/blob/952498836cd300557589b9ea14ef3c8f5e50f1e2/src/auth/sessionStore.js#L83) than `blockstack-session`, the default for v19+.

~~~javascript
const userSession = new UserSession({
  appConfig,
  storeOptions: {
    localStorageKey: 'my-custom-key',
  }
})
~~~

However, this doesn't work, because `'my-custom-key' instanceOf String` equals `false`. However, `new String('my-custom-key') instanceOf String === true`, which is odd. We should change this logic to support string literals, or drop support for it (because it is untested).

**Comment by zone117x** [comment]
This is fixed in develop https://github.com/blockstack/blockstack.js/blob/1b4af41d93f7c788772447f49d6ab7d6bdbd8034/src/auth/sessionStore.ts#L82

Typescript picks up dangerous usages of `instanceof` with primitives.

**Comment by zone117x** [comment]
Closing this issue since this is in master branch now, should be fixed.
