### ISSUE TITLE
Ensure all the name methods are exposed

### ISSUE THREAD

**Issue by moxiegirl** [stx-labs/stacks.js#661]
**markmhendrickson** [11:48 AM]
Is `getNamesOwned` in blockstack.js supposed to return both paid and "free" names (i.e. those that end with `.id.blockstack`)? https://github.com/blockstack/blockstack.js/blob/7a21425a7eed0cc6b66f4b4c18bd644ef16cbd21/src/network.ts#L289

I'm not seeing it return the latter, but the docs there say "both on-chain and off-chain" names should be returned

e.g. https://core.blockstack.org/v1/addresses/bitcoin/143vQn8MmACxsfjdTkqwgajN5QZWbxQZpj for `testermctester123.id.blockstack`
And if this method isn't suppose to return both, is there a different method available to query both types of names by address?

**moxiegirl** [12:14 PM]
https://blockstack.github.io/blockstack-android/org.blockstack.android.sdk/-network/get-names-owned.html
also says both

This method tho isn’t exposed in the standard javascript lib so maybe should not be used @kenliao

**kenliao** [1:01 PM]
replied to a thread:
That method should be exposed.

**Comment by zone117x** [comment]
This is an instance method on the `BlockstackNetwork` class. Do we want it exposed like the `getNameInfo` method, which is a wrapper function calling the method on default instance? 
https://github.com/blockstack/blockstack.js/blob/7a21425a7eed0cc6b66f4b4c18bd644ef16cbd21/src/network.ts#L1253

Or we can expose the class instance object itself: https://github.com/blockstack/blockstack.js/blob/7a21425a7eed0cc6b66f4b4c18bd644ef16cbd21/src/network.ts#L1241

**Comment by moxiegirl** [comment]
@zone117x I have no opinion on that.  @yknl Do you have a preference for how this is exposed?

**Comment by moxiegirl** [comment]
@zone117x All the name things should be exposed. Here is the reference conversation from Slack.

moxiegirl 12:17 PM
There are also these, visible seem useful but should they be public in the api:
getGracePeriod
getNameInfo
getNamePrice
getNamesOwned
getNamespaceBurnAddress
getNamespaceInfo
getNamespacePrice

NVM these are public and visible
So they stay
aaron 12:19 PM
I think if we mark them public, we should just be sure to separate them out from the kinds of calls that a developer of an app would usually use
moxiegirl 12:21 PM
so what would be the use case? Should we doc “don’t use these in your app” but “they are ok to use XXXX” --- what is XXXX?
Ken 12:22 PM
they’d be used for special apps like third-party stacks wallets and potentially apps that  let you register names
moxiegirl 12:25 PM
Cool. Thanks Ken. Unless Aaron chimes in with add or counter, I can go with that
aaron 12:26 PM
:thumbsup:

**Comment by yknl** [comment]
This has been completed.
