### ISSUE TITLE
"npm install blockstack --save" failed on Windows

### ISSUE THREAD

**Issue by karanganesan** [stx-labs/stacks.js#667]
attached the log file and error screenshot

[2019-05-17T04_05_29_144Z-debug.log](https://github.com/blockstack/blockstack.js/files/3189846/2019-05-17T04_05_29_144Z-debug.log)

![Screenshot (1)](https://user-images.githubusercontent.com/6049925/57902579-978c8e80-7887-11e9-9bc3-3ea7f60bb5d4.png)

OS : Latest Stable Windows 10 Home
Node and NPM : Latest
Python : Latest

**Comment by yknl** [comment]
@karanganesan this error means that you don't have python installed. However, you will no longer encounter this issue with the latest version of blockstack.js.

**Comment by karanganesan** [comment]
Ok thanks @yknl

**Comment by karanganesan** [comment]
so is Python removed as a dependency @yknl

**Comment by yknl** [comment]
yes
