### ISSUE TITLE
Name with URL ending in `/$address/$number/profile.json` no longer updates

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#669]
It seems like names that end in a `$number` that is not `0` no longer update.  Not sure if this is due to a regression in blockstack.js or the browser.  The reliably-broken username to test this with is `khunter.id`.

**Comment by markmhendrickson** [comment]
This bug will be fixed in the browser: https://github.com/blockstack/blockstack-browser/issues/1926
