### ISSUE TITLE
Unable to use sign in from localhost

### ISSUE THREAD

**Issue by ghost** [stx-labs/stacks.js#672]
Error message :- 
Failed to fetch information about the app requesting authentication. Please contact the app maintainer to resolve the issue.

I am using Ubuntu 19. with npm 5.8.0
![Screenshot from 2019-06-06 10-29-59](https://user-images.githubusercontent.com/51027098/59007903-1d2baa80-8846-11e9-95ad-ba90f027ad58.png)

**Comment by ghost** [comment]
Use 127.0.0.1:5000 instead of localhost:5000

**Comment by jonnydevop** [comment]
https://www.youtube.com/watch?v=KGcHYwjUXMw&list=PLDQHh6RjV5oUJNbtnzV11VVghiJTPJ5Wv&index=5
