### ISSUE TITLE
NoSessionDataError

### ISSUE THREAD

**Issue by poratuk** [stx-labs/stacks.js#673]
Trowed 3 times:
No session data was found in localStorage
https://github.com/blockstack/blockstack.js/blob/master/src/auth/sessionStore.ts#L98

Error occured into UC Browser: 
UC Browser
Version: 12.10.6

Android
Version: 6.0.1

Redmi 4X
Into

**Comment by yknl** [comment]
@poratuk UC browser is not officially supported. It's possible that this is a bug with UC browser and not blockstack.js
