### ISSUE TITLE
Use promises for SessionDataStore

### ISSUE THREAD

**Issue by icidasset** [stx-labs/stacks.js#678]
👋 

Any thoughts on making `SessionDataStore` asynchronous? I'm trying to make a store that uses indexedDB, but failing because currently it is expected that the data store is synchronous.

_Proposed solution:_  
Have the `get`, `set` and `delete` functions return a `Promise`.

_Context_:  
Trying to use Blockstack in a web worker, so no access to local storage.

_Help_:  
Can make a PR if you me want to.

**Comment by zone117x** [comment]
Seems like a good idea. There are several synchronous code paths dependent on the current synchronous `SessionDataStore ` API. Some of the call graphs have async parent invocations so should be easy to update, but looks like at least one or two with a synchronous entry point which are public API functions. So changing these to return Promises would require a major version bump, and no clear way to remain backwards compatible.

**Comment by icidasset** [comment]
Thanks @zone117x ! Might make a fork and a PR for this soon.

**Comment by zone117x** [comment]
@icidasset That would be much appreciated. We already need some of these APIs to be async for future improvements in encryption methods, but don't currently have that prioritized.
