### ISSUE TITLE
Separate local daemon for different users

### ISSUE THREAD

**Issue by muneeb-ali** [stx-labs/stacks.js#68]
Different users on the same machine should not share the same local daemon to broadcast their transactions (this is not a security concern because their wallets are different, but it's causing confusion in reading/displaying the state of local queues).

**Comment by muneeb-ali** [comment]
Thanks @jondale for reporting this. You can follow this issue to track progress.

**Comment by jcnelson** [comment]
This is now fixed simply by configuring your blockstack client to use a separate port.  Simply set the `api_endpoint_port` field under the `[blockstack-client]` heading.

Please re-open if this is still a problem.
