### ISSUE TITLE
LocalStorage Session Conflict

### ISSUE THREAD

**Issue by polluterofminds** [stx-labs/stacks.js#680]
There is a significant issue with the current auth flow that can result in catastrophic data loss for users. 

When a user signs in, a new tab is opened and they are redirected to the Blockstack browser. The original tab for the app still contains the original sign in page. A user can accidentally go back to that tab and sign in again but with a different account. And then if the user returns to the original tab, local storage has the new user session but the app doesn’t know that and writes the existing state to the new account hub.

**Comment by yknl** [comment]
I see how the user can become really confused when they get into that situation. Does the write request not fail if the localStorage session has changed? In that case the app should be able to alert the user to the error before any data loss occurs right? 

In terms of what we can do in blockstack.js to prevent the situation from occurring, the `redirectToSignIn` could return a promise after a successful redirect and the app can use it to disable the sign in button or something else. 

Also, a few ways to potentially mitigate this in the app code:
- Once the sign in button is clicked, poll localStorage for session data and automatically redirect to a signed in state when found. (This could also be something implemented in blockstack.js)
- Warn of an existing user session when processing new auth responses

**Comment by polluterofminds** [comment]
It’s not just confusion, it is data pollution. The write request is successful and takes the application state from the original session and saves it to the Gaia bucket of the new session. 

For example, I had a tab open with a document opened up. I managed to get myself into this weird situation and when I went back to that tab, it looked like I was still signed into one account and that document could be edited. However, in localstorage my usersession data had been updated to the new account. So when I made my changes it saved to the new usersession’s Gaia hub. 

For me that included taking the current document index state and saving it as well. Which overwrote the entire document index for the new account I had signed into with the document index state of previous account.

**Comment by yknl** [comment]
Discussed this in the open engineering call, the proposed solution is to throw an error in `handlePendingSignIn` if there's an existing user session in localStorage.

**Comment by aulneau** [comment]
To chime in here, I do think it is partly the responsibility of the app developer to do a couple things. As Ken said, the application should update itself whenever there is a user session active -- meaning if the application shows the sign in button state without being updated, that is not necessarily the fault/responsibility of blockstack.js -- the application state just isn't being updated correctly. You should probably always be watching for changes to the user session data, such as keeping a copy of it in however you are managing the application state, and it changes/gets removed or anything, the application would update and reflect that state.

**Comment by aulneau** [comment]
An example of how the authentication provider might not matter in this way: if you were to use auth with google/github etc, but the application kept the stale state after a new window/tab opened to auth, it's not the fault of those auth providers. The user ideally would never be presented with a state that is different than what it would be in a different tab etc.

**Comment by polluterofminds** [comment]
>  meaning if the application shows the sign in button state without being updated, that is not necessarily the fault/responsibility of blockstack.js -- the application state just isn't being updated correctly. 

That's not accurate at all. Blockstack forces a new tab to open. You're asking an app developer to change the state on an abandoned tab?

**Comment by polluterofminds** [comment]
If auth happened in one tab, this whole problem is resolved

**Comment by polluterofminds** [comment]
> You should probably always be watching for changes to the user session data, such as keeping a copy of it in however you are managing the application state, and it changes/gets removed or anything, the application would update and reflect that state. 

Yes, I think most apps are already doing this considering all blockstackjs function require it now as part of the userSession object changes in a prior update. So a copy of userSession info is stored in state. But that doesn't help when there is one tab with existing state and another tab with another state. 

What you're saying is that in addition to running putFile function, you want a dev to first check if the userSession state has changed. That's definitely not something other authentication methods ask developers to do.

**Comment by stackatron** [comment]
Thx for spotting @jehunter5811. @zone117x curious to hear from you on this.

**Comment by polluterofminds** [comment]
No problem! I just want to make sure the severity of this is understood. Whether you’re in the camp where you think devs should handle this or not, there’s is an equal urgency to addressing this. 

If devs are to handle it, the core documentation should reference the proper way to handle it because it is absolutely outside the norm. 

If Blockstack is to handle it, it should be a hot fix.

It was lucky that I found this because I could track it down. If a user had ever reported this to me or any other app, it would be next to impossible to debug and understand.

**Comment by friedger** [comment]
Maybe the LocalStorageSessionStore can throw an exception on sign in if the user is already logged in.

**Comment by zone117x** [comment]
This is another case of our code not adhering to a single source of truth principle. 

I think a localStorage usersession should setup an event listener to watch for this situation, and probably a page visibility event listener.

**Comment by polluterofminds** [comment]
What's the priority on this issue? If it's not high, I'd like to start notifying other developers of this potentially happening to their users.

**Comment by yknl** [comment]
If you all support the proposed solution of throwing an error in `handlePendingSignIn` when overwriting an existing user session then there could be a hot fix pretty quickly.

**Comment by jcnelson** [comment]
:+1:

**Comment by joramowuor** [comment]
merge#pr750

**Comment by ruslankonev** [comment]
Hi, I was look this issue moves to Mongo/Collections way, but tell me please, at now possible to read public files, with defined put/get file options and without have an account in blockstack?
I want to add an ability to read files from blockstack without create account.
