### ISSUE TITLE
Use of deprecated crypto functionality in newer versions of Node

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#681]
Moving this from https://github.com/blockstack/cli-blockstack/issues/20 because the cause is in blockstack.js.  Thanks to @john-light for reporting!

> Just a heads up that I am getting this deprecation warning when entering certain commands in the CLI:

```
blockstack-cli balance ADDRESS
(node:14634) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:14634) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:14634) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead
```

**Comment by yknl** [comment]
This experimental PR from @zone117x may potentially address the issue: https://github.com/blockstack/blockstack.js/pull/659
