### ISSUE TITLE
Failed to fetch information about the app

### ISSUE THREAD

**Issue by corbolt** [stx-labs/stacks.js#688]
hey guys, 

i upgraded blockstack.js to 19.2.2 and uploaded the latest version of TimeStack to S3.

Now, i’m no longer able to login due to a “Failed to fetch information about the app requesting authentication. Please contact the app maintainer to resolve the issue.”

Console log states: Access to fetch at ’https://my.timestack.app/manifest.json' from origin ‘http://localhost:8888’ has been blocked by CORS policy: No ‘Access-Control-Allow-Origin’ header is present on the requested resource. If an opaque response serves your needs, set the request’s mode to ‘no-cors’ to fetch the resource with CORS disabled.

CORS is/was already enabled on S3 (& worked before updating) - what else could be the issue here? 

Thanks!

**Comment by stackatron** [comment]
@coboltDE still having this issue? Closing for now and happy to reopen if you still need help.
