### ISSUE TITLE
Add File, Blob, and ReadableStream in `putFile`

### ISSUE THREAD

**Issue by zone117x** [stx-labs/stacks.js#689]
Support common file data types like `File`, `Blob`, and `ReadableStream` in the storage APIs. 

Provides a straightforward way to use common DOM APIs like `<input type=file/>` and `DataTransfer` / `DragEvent`. 

Note: this initial task is a surface API level change, and will not address issues related to encryption size and efficiency. That is, when encryption is enabled, the data streams still be loaded into memory before uploading.

**Comment by stackatron** [comment]
@asopinka @apuyou you both had feedback on the files API. Curious if you feel this would cover your needs or any feedback you might have? Thx

**Comment by apuyou** [comment]
Hi @jeffdomke, I am looking for something like #638, which is about storing documents instead of native files. It doesn't look like this issue is related. Thanks!
