### ISSUE TITLE
Proposal: Implement an `onUserSignOut` event

### ISSUE THREAD

**Issue by zone117x** [stx-labs/stacks.js#694]
Related to https://github.com/blockstack/blockstack.js/issues/680

Quoting from part of @aulneau's [comment](https://github.com/blockstack/blockstack.js/issues/680#issuecomment-512529973)
> You should probably always be watching for changes to the user session data, such as keeping a copy of it in however you are managing the application state, and it changes/gets removed or anything, the application would update and reflect that state.

Related to my [comment](https://github.com/blockstack/blockstack.js/pull/682#pullrequestreview-268372999):
> ... I think there are more situations that would cause similar issues described in #680. Several tabs could be open and logged in for an app. User could logout (clear localStorage) on tab 1, then login with different account, and still remained logged in with original account in tab 2, potentially causing issues depending on how the app is designed. 

---

A `onUserSignOut` event on the `UserSession` class could help devs know when to update their application state. Without them having to figure out sign-in-change polling or other forms for detection. 

### The event API

Could look something like:
```ts
const userSession = new UserSession(...);
userSession.on('userSignOut', function (e) {
  // update app state
});
```

An optional callback for the same event could also be added to something like the `UserSession` constructor or the `UserSession.handlePendingSignIn(...)` function. 

### Implementation

The underlying `SessionDataStore` (localStorage in most cases) would be responsible for setting up their implementation-specific event hooks, and would propagate the updates to the `UserSession` class. 

Additionally, the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) can be leveraged in situations where an old tab's execution has been suspended by the web browser.

**Comment by moxiegirl** [comment]
@zone117x what constitutes a sign out -- a browser reset or simply "logout" of the user on the DApp?

**Comment by zone117x** [comment]
@moxiegirl The referenced issue has the context behind this proposal. I copied & pasted some of the replies, and more elaboration on how this works.

Any communication between apps and the Blockstack Browser is sandboxed and can only be performed via redirects (app -> browser -> app). So this proposal does not have anything to do with the user's state within the Blockstack Browser. 

To recap the referenced issue -- this proposal addresses the discrepancy that can arise between an app's given state vs the user's actual session state data associated with the app domain.

**Comment by moxiegirl** [comment]
@zone117x Thanks for the answer.
