### ISSUE TITLE
UserSession.redirectToSignIn() is not setting userData

### ISSUE THREAD

**Issue by ernestognw** [stx-labs/stacks.js#697]
**Description**
I'm trying to build an SignIn process with blockstack using React.

I followed the docs and the implementation I set up is the following:

```
import { UserSession } from 'blockstack';

class BlockstackButton extends Component {
  constructor(props) {
    super(props);
    this.session = new UserSession();
    this.state = {
      loading: false
    };
  }

  handleSignBlockstack = () => {
    this.setState({ loading: true });
    this.session.redirectToSignIn();
  };

  render() {
    const { loading } = this.state;
    return (
        <button>
          {loading ? (
            <Loader size="15" />
          ) : (
            <Fragment>
              <Icon /> Entra con Blockstack
            </Fragment>
          )}
        </button>
    );
  }
}
```

After the process is finished and I get returned to the application, I'm calling the next script to check if the user is signed in:

```
checkUser = async () => {
    const { session } = this;
    if (session.isUserSignedIn()) {
      const { username, profile, identityAddress } = session.loadUserData();
      // Do something with data
    } else if (session.isSignInPending()) {
      const { username, profile, identityAddress } = await session.handlePendingSignIn();
      // Do something with data
    }
}
```

The problem is that both session.isUserSignedIn() and session.isSignInPending() are returning false, no matter what I do. I've checked another blockstack apps to check what is the expected result saved on localStorage, and it seems that my `blockstack-session` item is setting the transitKey and version, but not saving the userData object. I attach a photo:

<img width="532" alt="Captura de pantalla 2019-08-16 a la(s) 0 27 13" src="https://user-images.githubusercontent.com/33379285/63145366-d92ef180-bfbc-11e9-9ee2-3a1813fe8593.png">

**What i've tried**

- Clean browser cache
- Do the process on localhost in development environment
- Do the process on a server in test environment
- Publishing a production version on with SSL certificated domain
- Changing to another blockstack id account
- Login into another blockstack apps and is working correctly
- Use safari, mozilla and chrome in different environments
- Try on other computers
- Try on my phone

Nothing seems to work.

Any thoughts on this?

**Comment by zone117x** [comment]
Can you show the chrome devtools network log, showing the requests from your app -> the blockstack browser -> back to your app?
As well as the console log output during the same period.

**Comment by ernestognw** [comment]
This is the network log from the whole process:

<img width="1012" alt="Captura de pantalla 2019-08-16 a la(s) 15 07 10" src="https://user-images.githubusercontent.com/33379285/63195198-978f5c80-c037-11e9-917d-9fe100345743.png">
<img width="1011" alt="Captura de pantalla 2019-08-16 a la(s) 15 07 19" src="https://user-images.githubusercontent.com/33379285/63195203-9bbb7a00-c037-11e9-920f-870035dfcc48.png">

And this is the console log output:
<img width="1017" alt="Captura de pantalla 2019-08-16 a la(s) 15 08 58" src="https://user-images.githubusercontent.com/33379285/63195278-ca395500-c037-11e9-8fa2-e6cc1103e892.png">

**Comment by ernestognw** [comment]
I'm still having problems, and can't find a solution.

Somebody can please review this?

**Comment by KNTH01** [comment]
Can you print `userSession.store.getSessionData()` and see what happens?

**Comment by zone117x** [comment]
Do you have this project on GitHub? If so and I can reproduce it then I can debug

**Comment by njordhov** [comment]
Try changing the order of the conditional so `isSignInPending` is called before testing for `isUserSignedIn`. I recall there were an (unintuitive) issue where both returned true at the same time, which in your case will result in `handlePendingSignIn` being shadowed.

**Comment by stackatron** [comment]
@ernestognw let us know if you still have this issue or have more info so we can reproduce. Closing for now happy to reopen.
