### ISSUE TITLE
Fix Gaia concurrency issues [Proposal] 

### ISSUE THREAD

**Issue by stackatron** [stx-labs/stacks.js#707]
- https://forum.blockstack.org/t/blockstack-client-side-orm-and-conflict-resolution/8386/2
- Our docs instruct devs to create index files https://docs.blockstack.org/browser/blockstack_storage.html#understand-gaia-storage-methods which is guaranteed to cause data-loss, corruption and other bugs, unless devs implement complex conflict detection and resolution code. We should do what we can in blockstack.js to help with this. 

Placeholder ticket. @zone117x can replace with a detailed proposal.

**Comment by zone117x** [comment]
This issue is a specific proposal (WIP) to address common concurrency issues https://github.com/blockstack/blockstack.js/issues/702

Going to close this one as a dup
