### ISSUE TITLE
Unable to install development version

### ISSUE THREAD

**Issue by cyanoboy** [stx-labs/stacks.js#71]
When I run

`$ sudo pip install git+https://github.com/blockstack/blockstack-client.git@develop --upgrade`

I get 

`Could not find a version that satisfies the requirement virtualchain>=0.0.9 (from blockstack-client==0.0.13) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.8)`

Then I tried to first install registrar of develop branch.
I also installed virtualchain of develop branch (0.0.9).
Now when I run blockstack-client installation I get:

`Could not find a version that satisfies the requirement registrar>=0.0.4 (from blockstack-client==0.0.13) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.3.1, 0.0.3.2, 0.0.3.3, 0.0.3.4, 0.0.3.7)
No matching distribution found for registrar>=0.0.4 (from blockstack-client==0.0.13)`

But `registrar 0.0.4` does not exists on github.

So it's not possible to use blockstack-client in develop branch.

**Comment by jcnelson** [comment]
We just merged the next release (`rc-0.14.0`) branch to `master`, so `master` is currently the latest codebase.
