### ISSUE TITLE
Collections Demo App + Tutorial

### ISSUE THREAD

**Issue by yknl** [stx-labs/stacks.js#711]
* [Support for multiple identities on collections](https://github.com/blockstack/blockstack-browser/pull/1936)
* [File Rename and Status](https://github.com/blockstack/gaia/pull/217#discussion_r298343312)

**Comment by moxiegirl** [comment]
@yknl As discussed we should be working to add collections functionality to StackIt that @Sahana-Srinivasan wrote.
