### ISSUE TITLE
wallet is locked after manually restarting rpc_daemon

### ISSUE THREAD

**Issue by JFiscella** [stx-labs/stacks.js#72]
after executing `$ kill -9` on rpc_daemon processes, my wallet remains locked upon restarting blockstack-cli with `$ blockstack info`. 

to unlock the wallet again, a workaround was used:

```
$ blockstack register afafdsafsd.id
Enter wallet password: 
Unlocked wallet.
Registering afafdsafsd.id will cost 0.00041 BTC. Continue? (y/n): n
Not registering.
```

by going down a path that _would need_ an unlocked wallet, i was able to unlock the wallet after entering my password.

there should be a command to unlock the wallet outright

**Comment by muneeb-ali** [comment]
Update: @JFiscella's issue was resolved on a retry. We do need a command to unlock wallet.

**Comment by jcnelson** [comment]
This is no longer the case in the `develop` branch.  The back-end RPC daemon can be controlled with the `rpcctl` directive as follows:

```
    $ blockstack rpcctl start  # starts the background daemon
    $ blockstack rpcctl start-foreground  # starts the daemon in the foreground
    $ blockstack rpcctl stop  # stops the background daemon
    $ blockstack rpcctl restart  # restarts the background daemon
```

When starting up the daemon, blockstack will now prompt you for the wallet password and cache your wallet to RAM.  If the user's background daemon gets killed, they can restart it with the above commands.

**Comment by jcnelson** [comment]
Fixed in the new stable release.  Please re-open if this is still causing problems.
