### ISSUE TITLE
Add listFile stat support

### ISSUE THREAD

**Issue by zone117x** [stx-labs/stacks.js#726]
The Gaia feature [option to return fileStat info during listFiles](https://github.com/blockstack/gaia/pull/249) is merged into master and will be available when the PBC hub update is deployed.

**Comment by njordhov** [comment]
Any timeline for when filestats will be available in UserSession.listFiles() or elsewhere in the SDK? I'd be interested in using this in apps. I currently fetch the HEAD of files in Gaia to get size and modification date, but it isn't allowed in stricter browsers. Also, would be useful to get Gaia specific stats like whether the file is encrypted and/or signed.
