### ISSUE TITLE
Define API surface JSON document mutation operations

### ISSUE THREAD

**Issue by zone117x** [stx-labs/stacks.js#728]
Part of [Proposal: JSON Document Storage API with conflict prevention and resolution](https://github.com/blockstack/blockstack.js/issues/702)

This issue is for establishing the public API surface for performing operations on JSON documents in a way that detects and surfaces file conflicts. The implementation is dependent on how [Gaia MVCC](https://github.com/blockstack/gaia/issues/267) is implemented. 

The API is currently intended for two distinct use-cases, but may be split up later on if necessary.

### Use case 1
Apps that already use json files via `getFile` and `putFile` and run into efficiency and corruption related problems. For example, json index files as [described in our main storage tutorial](https://docs.blockstack.org/browser/blockstack_storage.html#understand-gaia-storage-methods).

In this use case, we do not intend to default to any non-generalizable conflict resolution strategies. Conflicts should be surfaced in a way for devs to resolve them in a manner applicable to their app. Documentation and tutorials may provide suggested methods and/or libraries that are useful for many situations. 

### Use case 2
Collection files. These are much more susceptible to file conflicts and perceived data loss due to the new ability for several apps to now be trampling over the same collection file. Additionally, an individual app that is heavily dependent on collections has little or no capability to prevent their app from breaking when other apps, even non-maliciously, overwrite or corrupt user collection files. 

For collections, we have well-defined schemas, and should specify a convergent replicated data type and a default conflict resolution method. 

---

Example API surface and usage:

```ts
const userSession = new UserSession(...);

// The `openDoc` function establishes synchronization-related information as well
// fetching the file content.
const photoIndex = await userSession.openDoc('photos.json', { 
    // If file is being created for the first time, a mutable `doc` 
    // object is provided for the user to perform any initial data 
    // setup. 
    onInstantiate: doc => {
        // Example of setting up initial object structure..
        doc.profilePhotoHistory = [];
    },
    // Callback that is invoked when the in-memory document was stale and updated
    // from merging with the latest document. Could be triggered when attempting
    // to write stale data to Gaia, or perhaps when notified by another browser 
    // context. 
    onExternalChange: doc => {
        // Example of updating the app UI with latest doc state.
        updateProfilePhotoUI(doc);
    }
});

// An example of the how index files are commonly used: upload a file and add
// the file name to an index file. 
async function uploadProfilePhoto(name, fileContent) {
    await userSession.putFile(name, fileContent);
    const latestDoc = await photoIndex.change(doc => {
        doc.profilePhotoHistory.push(name);
        doc.mainProfilePhoto = name;
    }, (doc, conflicts) => {
        // `conflicts` representation is TBD 
    });
    updateProfilePhotoUI(latestDoc);
}
```

**Comment by njordhov** [comment]
The [HTTP Patch](https://tools.ietf.org/html/rfc5789) method could play a role in allowing multiple app instances to make changes to the same file.
