### ISSUE TITLE
GAIA 409 errors when uploading.

### ISSUE THREAD

**Issue by dantrevino** [stx-labs/stacks.js#735]
Blockstack team... I had a user who was importing notes from Google Keep into NoteRiot, but got several `Failed to load <url> resource: the server responded with a status of 409 ()` errors.  These would have been images.  Some images looked like they worked just fine.  Others not.  Why might I be seeing the 409 error?
```
Uncaught (in promise) Error: Error when uploading to Gaia hub
   at Object.<anonymous> (hub.js:34)
   at Generator.next (<anonymous>)
   at fulfilled (hub.js:4)
```

**Comment by yknl** [comment]
Usually 409s are a result of concurrent writes to the same endpoint. Please re-open if you continue to experience this.

**Comment by SomeMoosery** [comment]
@dantrevino - were you every able to resolve this issue? I'm still having trouble with this issue infrequently popping up, and was wondering if you had come up with a working solution.

**Comment by dantrevino** [comment]
@SomeMoosery, @yknl's description of the issue was correct for me. I had multiple puts to the same filename (endpoint). Ebkac.
