### ISSUE TITLE
Insecure default options for unencrypted upload via putFile()

### ISSUE THREAD

**Issue by MarvinJanssen** [stx-labs/stacks.js#738]
As discussed with @friedger on Telegram.

Currently, the default options for unencrypted file upload using putFile() potentially put the users at risk. It is effortless for a malicious Gaia host to tamper with unencrypted files. Many apps put the user's app public key on Gaia in plain text so that other user's may grab it to encrypt data. It is conceivable that a malicious Gaia host could replace such a file with one containing a different public key, which makes a man-in-the-middle attack trivial. Signing files by default mitigates this risk.

putFile() encrypts by default, but it does not sign by default if encryption is turned off. The only reason why this is the case, that @friedger and myself could of, is because of overhead. But we both agreed that we rather have some overhead if we get increased security in return.

One can argue that the onus is on the app developer, but "secure by default" is always preferred in my opinion.

Naturally, it is a minor change in the code: `sign = !encrypt` for `PutFileOptions` and `GetFileOptions`.

**Comment by moxiegirl** [comment]
Maybe we should explain the situation before trying to fix this. Added impacts docs label.
