### ISSUE TITLE
reset browser

### ISSUE THREAD

**Issue by FrankyHo** [stx-labs/stacks.js#742]
except userSession.signUserOut, user id still persist in browser, is there any method redirect to reset browser like "https://browser.blockstack.org/account/delete"?

**Comment by stackatron** [comment]
@FrankyHo can you please provide a little more context on the usecase for this?

**Comment by stackatron** [comment]
Issue moved to [blockstack/blockstack-browser #1999](https://github.com/blockstack/blockstack-browser/issues/1999) via [**ZenHub**](https://www.zenhub.com/)
