### ISSUE TITLE
blockstack.js constantly blocking the thread

### ISSUE THREAD

**Issue by plwalters** [stx-labs/stacks.js#745]
It seems like when integrating blockstack.js that the thread is blocked constantly and it makes Chrome freeze up for a little bit.  Is this expected?  Is it possible to offload the work to a service worker or something to prevent the freezing?

**Comment by zone117x** [comment]
Can you give more context into what blockstack.js usage is causing this problem? 

If this is happening during `putFile`, `getFile`, or the Blockstack ID auth functions -- then it is being addressed by https://github.com/blockstack/blockstack.js/pull/737

**Comment by plwalters** [comment]
Perfect it is happening exactly during those operations :)

I'll close this and track it there.
