### ISSUE TITLE
Double forward slash in avatar url

### ISSUE THREAD

**Issue by njordhov** [stx-labs/stacks.js#755]
The `userData.profile.avatarUrl` may have a double forward slash `//` in the path, as in

    https://gaia.blockstack.org/hub/1KbveCzipEoYGFh3hUMX3cRDYogwNeFDzD//avatar-0

Although `//` actually is valid in the URL path, it is inconsistently handled by libraries and server-side software, introducing ambiguity and potential problems. Case in point, the widely used Express [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) fails to properly proxy a URL with `//` unless it is changed to `/%2F` with the second slash encoded.

Consider eliminating `//` in the avatar url path (and elsewhere if applicable).

**Comment by x5engine** [comment]
well it comes from here https://github.com/blockstack/blockstack.js/blob/1ca24f2e941bba14ac2fac9500d9e32dbfd0f244/src/profiles/profileSchemas/personUtils.ts#L79

maybe checking the double slash might help
