### ISSUE TITLE
Use blockstack-browser on localhost for authentication

### ISSUE THREAD

**Issue by wisdomabioye** [stx-labs/stacks.js#761]
I have blockstack browser installed running at http://localhost:3000 and I have my blockstack powered app running at https://localhost:4000

How do I make the blockstackjs sign-in method direct to localhost?
It always directs me to the https://browser.blockstack.org

**Comment by kyranjamie** [comment]
Hi @wisdomabioye 

Make sure you've got the `redirectURI ` parameter configured https://blockstack.github.io/blockstack.js/classes/usersession.html#redirecttosignin

**Comment by wisdomabioye** [comment]
Thanks @kyranjamie
I have `redirectToSignIn` configured.
`redirectURI`: callback URL on successful authentication
`manifestURI`: I have this configured and 
`scopes`: permissions

This works perfectly with https://browser.blockstack.org/ authentication.

Is there any parameter I'm missing?
I want the `redirectToSignIn` to redirect the blockstack-browser running on localhost

**Comment by friedger** [comment]
@wisdomabioye There is no way to specify a customized url for the location of the blockstack browser. If blockstack.js can't find the blockstack browser at `localhost:8888` then it will use the hosted browser.

Either start your local version on port 8888 or just replace `browser.blockstack.org` with `localhost:3000` in the web browser after you were redirected (in the url like `https://browser.blockstack.org/auth?authRequest=eyJ0eXAiOiJ...`)

**Comment by friedger** [comment]
See also https://github.com/blockstack/blockstack-browser#troubleshooting that explains the difference between dev (port 3000) and production mode (port 8888)

**Comment by wisdomabioye** [comment]
Thanks. 
I ended up replacing `browser.blockstack.org` with `localhost:3000` in the web browser after redirection.
