### ISSUE TITLE
Unknown protocol

### ISSUE THREAD

**Issue by Walterion02** [stx-labs/stacks.js#766]
In the recent testing of apps, when a user does not have Blockstack Browser installed, on Browsers like Opera and Edge, it will show Unknown protocol message. If the user clicks the sign-in button again and follows the process, he will come back with a different transit key than expected so he will fail to sign-in.
![1](https://user-images.githubusercontent.com/58766522/72899620-a17e5f80-3d3b-11ea-90f0-ee0ce3399644.jpg)
![2](https://user-images.githubusercontent.com/58766522/72899621-a216f600-3d3b-11ea-8511-4083642436b1.jpg)

**Comment by zone117x** [comment]
This behavior is unavoidable for Edge and Opera. There is no way to detect or launch a custom protocol URI without triggering those prompts, AFAIK. 

> If the user clicks the sign-in button again and follows the process, he will come back with a different transit key than expected so he will fail to sign-in.

This could be solved by disabling your sign in button after first click.

**Comment by Walterion02** [comment]
> This could be solved by disabling your sign-in button after the first click.

If we do this and user see the error, he will not know what to do anymore,, and it will be a dead-end for him. These two samples are from this month of TMUI, and both users gave the app zero as they think it is flawed.
