### ISSUE TITLE
Use redirectToSignIn to redirect after login

### ISSUE THREAD

**Issue by visualNext** [stx-labs/stacks.js#778]
We hope that our app can be redirected to a new SPA link after login blockstack.
userSession.redirectToSignIn(this.hostLink + ‘/register#/blockstack’, this.hostLink + ‘/manifest.json’)
we found found that the first parameter is not working if we write
this.hostLink + ‘/register#/blockstack’
it will only work when we write this.hostLink + ‘/register/blockstack’
Since we use vuejs SPA in hash mode, we must include “#” sign in our redirect link,
Is there any way, I can use “#” sign in the first parameter of the function redirectToSignIn?
Thank you very much

https://forum.blockstack.org/t/use-redirecttosignin-to-redirect-after-login/10585

**Comment by x5engine** [comment]
hey,

can you try like `this.hostLink + ‘/register/#blockstack’` ?

**Comment by x5engine** [comment]
or even `this.hostLink + ‘/register#blockstack`?
