### ISSUE TITLE
Running `blockstack info` times out

### ISSUE THREAD

**Issue by Ectsang** [stx-labs/stacks.js#78]
I noticed that around 3:40pm (UTC) that I had problems connecting to server.blockstack.org

The error message was:
$ blockstack info
{
    "advanced_mode": "false",
    "cli_version": "0.0.12.7",
    "server_alive": false,
    "server_error": "timeout: timed out",
    "server_host": "server.blockstack.org",
    "server_port": "6264"
}

After waiting several minutes and trying again, I got through:
$ blockstack info
{
    "advanced_mode": "false",
    "cli_version": "0.0.12.7",
    "consensus_hash": "0032dd1376228665819bb557e8f46b2a",
    "last_block_processed": 406951,
    "last_block_seen": 406959,
    "server_alive": true,
    "server_host": "server.blockstack.org",
    "server_port": "6264",
    "server_version": "0.0.10.3"
}

Then immediately after getting the success message, I ran it one more time and this time it failed.
$ blockstack info
{
    "advanced_mode": "false",
    "cli_version": "0.0.12.7",
    "server_alive": false,
    "server_error": "timeout: timed out",
    "server_host": "server.blockstack.org",
    "server_port": "6264"
}

I'm connecting from Hong Kong on a home internet connection. Happy to give more info if needed.

**Comment by muneeb-ali** [comment]
Thanks for reporting! This is either a temporary network/routing issue between your machine and the server running on AWS or the server was under heavy load. We'll look into replicating the problem and increasing capacity of the server as needed.

**Comment by jcnelson** [comment]
This is an old issue, and our infrastructure no longer lives in AWS.  I'm going to go ahead and close this issue.  Please re-open if you're still experiencing problems.  Thanks!
