### ISSUE TITLE
etags, path and its content hash should be removed in deleteFile?

### ISSUE THREAD

**Issue by 0xc22b** [stx-labs/stacks.js#781]
Hi,

I've got an error 412 Precondition Failed when I get a file, delete that file, and put a new file with the same path as the deleted file.

I understand it happened because in getFileContents, getting a file, etags is updated with the file's path and its hash content. But when that file is deleted, etags isn't updated. So when a new file with the same path is created in putFile, the path found in etags and old hash content is used.

I'm not sure it's by design that path should not be reused after deletion? Should I design my app to always generate a new key for a new file or have a random string in the file name?

Thank you.

**Comment by zone117x** [comment]
This looks like a bug. The in-memory `etag` map should be updated after a `deleteFile`.
@reedrosenbluth can you think of any decent work around for this for now? Otherwise, looks like a quick patch?

**Comment by reedrosenbluth** [comment]
Will work on a quick patch for this! @witwitchayakarn thanks for reporting this bug!
