### ISSUE TITLE
Make better use of publicKey in user profile

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#786]
**Is your feature request related to a problem? Please describe.**
Encrypting data for another users requires the exchange of public keys. Currently, there is no official solution. However, Connect authenticator now publishes the user's public key in the public profile (profile().appsMeta.${host}.publicKey)

**Describe the solution you'd like**
userData should contain the public key

**Describe alternatives you've considered**
no

**Additional context**
https://github.com/blockstack/ux/pull/383

**Edit:**
While lookupProfile gives developers access to the publicKey of the user blockstack.js can support this better:
* `EncryptOptions` should include a `username` and `app`. If set the publicKey of the app (or the current app) of the user is looked up and used for encryption.
* `publish_data` permission should mention `appsMeta` next to `apps`.

**Comment by dantrevino** [comment]
From my perspective, the most common use case is finding _other_ user publicKeys. Based on my understanding this will help for the current user.

Currently, the only way to lookup up public keys for other users is querying v1/names/${user}/zonefile ... then parsing zonefile for the profile url ... then getting the profile and finding the key in there ... its easier just to have my app write key.json and then go get it with getFile("key.json", { decrypt: false, username: ${user} })

It is very possible that i'm not aware of some functions that would enable an easy lookup of another user's public key with this update, or maybe its solving a different problem.

Would love to have an easy lookup for *other* users.

**Comment by friedger** [comment]
Actually, `blockstack.lookupProfile` returns already the profile as is.

**Comment by friedger** [comment]
The docs should include this information

**Comment by dantrevino** [comment]
Ah excellent ... i hadnt even thought about using lookupProfile.  Thx @friedger !

**Comment by friedger** [comment]
While `lookupProfile` gives access to the publicKey it can be used better. I updated the origin issue.
