### ISSUE TITLE
error: command 'cc' failed with exit status 1 (OS X El Captian 10.11.4)

### ISSUE THREAD

**Issue by omaritani** [stx-labs/stacks.js#79]
Typed the command line "sudo pip install blockstack" and got the following error message:

_**1 error generated.

error: command 'cc' failed with exit status 1

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/private/tmp/pip_build_root/scrypt/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-W6yXcl-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/scrypt
Storing debug log for failure in /Users/omaritani/Library/Logs/pip.log
Omars-MacBook-Pro-2:~ omaritani$ **
_

Then tried the command line " ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install pycrypto" and got the following message:

**_Omars-MacBook-Pro-2:~ omaritani$  ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install pycrypto
Requirement already satisfied (use --upgrade to upgrade): pycrypto in /Library/Python/2.7/site-packages
Cleaning up...
Omars-MacBook-Pro-2:~ omaritani$ _**

**Comment by muneeb-ali** [comment]
It seems like an installation issue with scrypt which is what

> ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install pycrypto

is supposed to help with.

Can you uninstall pycrypto and install it again?

**Comment by omaritani** [comment]
How do I uninstall pycrypto?

**Comment by muneeb-ali** [comment]
> sudo pip uninstall pycrypto

and then

> ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future sudo pip install pycrypto

**Comment by omaritani** [comment]
**_    1 warning generated.
    cc -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -Wl,-F. build/temp.macosx-10.11-intel-2.7/src/_counter.o -o build/lib.macosx-10.11-intel-2.7/Crypto/Util/_counter.so

Successfully installed pycrypto
Cleaning up..._**

**Comment by muneeb-ali** [comment]
Now try

> sudo pip install blockstack

**Comment by omaritani** [comment]
1 error generated.

error: command 'cc' failed with exit status 1

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/private/tmp/pip_build_root/scrypt/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-cfvbjs-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/scrypt
Storing debug log for failure in /Users/omaritani/Library/Logs/pip.log
Omars-MacBook-Pro-2:~ omaritani$

**Comment by jcnelson** [comment]
This can be fixed with later versions of pip.  If problem persists, please re-open in the blockstack-core repo.
