### ISSUE TITLE
Some IDs registered through Blockstack Browser lacking appsMeta

### ISSUE THREAD

**Issue by jmerestain** [stx-labs/stacks.js#790]
**Describe the bug**
profile.json of users registered using Blockstack Browser do not have "appsMeta" when logging into my app. I made sure that the userSession handling both connect and browser have publish_data scope, though I can getFile, so publish_data doesn't seem to be the problem.

(https://serenity.runkodapps.com)

**What version of Blockstack.js are you using?**
21.1.0

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
profile.json

**Reference IDs (both logged into the same app mentioned above)**
(bathala_id.blockstack) Registered through Connect
https://gaia.blockstack.org/hub/1BtYni3m8nAB7GBT3DnXb77eqBaW3R4unw/profile.json

(jmerestain.id.blockstack) Registered through Browser
https://gaia.blockstack.org/hub/1Gnzj2Hx2oXFdcktxPEpuQiGEM7VHZz2BF/profile.json

**Comment by friedger** [comment]
The relevant PR was never merged nor published : https://github.com/blockstack/blockstack-browser/pull/2000
