### ISSUE TITLE
Docs are missing methods and have broken links

### ISSUE THREAD

**Issue by agraebe** [stx-labs/stacks.js#792]
**Describe the bug**
https://blockstack.github.io/blockstack.js/ is missing two item (`EncryptContentOptions ` & `hexStringToECPair`) and many links seem to be broken.

**Comment by reedrosenbluth** [comment]
The `EncryptContentOptions` link is definitely broken...

The `hexStringToECPair` function is annotated with the `@ignore` and `@private` JSDoc modifiers. Am I correct to assume that this should continue to not be included in the docs? @yknl

**Comment by yknl** [comment]
yes if they're marked as such they should not in the docs
