### ISSUE TITLE
Flawed packaging set up

### ISSUE THREAD

**Issue by kyranjamie** [stx-labs/stacks.js#796]
In relation to the Angular issue, #751, I've taken a look at the bundling set up. Here I'll try to explain the issue, and suggest some potential solutions, for which I'd love feedback on their viability.

I believe the underlying cause of the issue of this ticket is not framework-specific, but an issue with how blockstack.js is packaged.

For context, the current build setup results in two outputs:
1. `build:node`: `tsc` to compile all the individual files into the `lib` directory
2. `build:webpack`: Webpack to output the library as a single bundle, polyfilling all the node specific code etc

Since the `main` property of the `package.json` points to `lib/index`, browser module bundling tools will import the result of the node build, not the web one.

Now, because webpack is probably the most popular bundling tool on the web, a majority of developers can use blockstack.js with its node build without a problem. Webpack handles all the steps required to make it a browser-friendly library.
However, some frameworks, such as Angular, use their own build systems, which don't have the same behaviour (even though it does use webpack internally 🤷 ). The result is a library that just doesn't work. It's rebuilding the library from its compiled source without any of the necessary steps to make it web compatible.

The issue is **fixed immediately** changing the `main` property to point to the webpack bundle in `dist/blockstack.js` instead.

I understand this fix isn't without its flaws, though. There's very little tree shaking that can be done, so you're then required to import the library in its entirety.

Some possible solutions:

##### 1. Deal with it
Make the change above and stomach with the large library size. Encourage developers to import the library dynamically, rather than adding it to their main bundle. We can have a conditional `index.js` that will point to `lib` if it's executed in a node environment.

##### 2. Restructure the library to have multiple entry/exit points
Break the library into conceptual smaller bundles that roughly align to the various use cases one might use the lib for.

##### 3. Remove vendor files from the bundle
Make the large vendor files `peerDependencies` so we remove them from the main bundle.

##### 4. Nothing
Change our documentation to encourage non-webpack users to import the dist bundle directly:
```typescript
import { UserSession } from "blockstack/dist/blockstack";
```

Are there other solutions? The fact that `@blockstack/connect` has `blockstack.js` as a dependency does kind of exasperate the issue. As there are then no direct imports to this lib, it's handled entirely by their module bundling set up. Rendering 3 and 4 not particularly good solutions.

**Comment by zone117x** [comment]
Tempting to go with option 1, at least for now. 

The bummer with option 1 is that I don't think the nodejs `stream` functionality imported by `cipher-base` / `bip39` / `bitcoinjs-lib` is even used in any of our code paths. We'd be giving up on treeshaking/bundle-size to simply work around packaging for an unused downstream dependency. 

I'm curious if typical `blockstack.js` and `@blockstack/connect` usage would still work if:
1. `buffer` was explicitly imported [like this](https://github.com/feross/buffer#usage), rather than depending on it being globally polyfilled.
2. `bitcoinjs-lib` and `bip39` were made peer dependencies.
