### ISSUE TITLE
Refactor into mono repo

### ISSUE THREAD

**Issue by yknl** [stx-labs/stacks.js#799]
→ auth
        All authentication related API
        `userSession`, `signIn`
    → storage
        All Gaia related API 
        `putFile`, `getFile` etc.
    → profile
        Functions used to manipulate user profiles on BNS
    → keychain
        Stacks key generation, manipulation and addresses
        HD wallet derivation for account and wallet
    → transactions
        Transaction building API in `stacks-transactions`
    → network
        API for communicating with Stacks node and sidecar
        Including transaction broadcast, nonce, balance and fee estimation currently part of transactions lib.
    → encryption
        All existing encryption functions in blockstack.js
    → cli
        The stacks CLI, superseding the Blockstack CLI

**Comment by hstove** [comment]
I would recommend also merging:

- `zone-file`
- `jsontokens`

We should also strongly consider merging all of `clarity-js-sdk`.
