### ISSUE TITLE
Backup and restore from Blockstack server CLI 

### ISSUE THREAD

**Issue by cloudzombie** [stx-labs/stacks.js#80]
# Instructions on how to safely backup a Blockstack Server CLI install.
1. Linux/Ubuntu
2. Debian

**Comment by muneeb-ali** [comment]
For backup, you can copy the ~/.blockstack/wallet.json file and keep it in safe place. It has your encrypted HD wallet master key. You will also need to make sure you don't forget your password! 

Good idea about posting these instructions. @cloudzombie Can you start a separate issue for OpenBazaar handle integration? It's easier to follow progress on both issues that way.

**Comment by jcnelson** [comment]
Looks like this is answered.
