### ISSUE TITLE
Is etag missing in response headers?

### ISSUE THREAD

**Issue by 0xc22b** [stx-labs/stacks.js#805]
Hi,

Starting from yesterday, I can't edit my data using userSession.putFile(). I got an error: PreconditionFailedError: Error when uploading to Gaia hub. After debugging, I found that there is no etag in response headers when calling userSession.getFile(). So etags in stroage/index.ts are empty and an edited file is treated as a new file uploaded.

As shown in the image below, I think there should be an etag attribute under response headers.
![Screenshot from 2020-07-24 10-39-44](https://user-images.githubusercontent.com/1229910/88359195-fb6bea80-cd9b-11ea-9e84-c80f07f61715.png)

Can you help check? Thank you very much.

**Comment by dennisosaj** [comment]
Same issue, can't get my file updated when using using userSession.putFile().

Problem noticed today. Worked before without an issue.

<img width="682" alt="Screenshot 2020-07-24 at 15 37 34" src="https://user-images.githubusercontent.com/48364940/88397050-b0fe6400-cdc3-11ea-91c4-afa42cfb27f2.png">

**Comment by kantai** [comment]
To resolve some issues in the public Gaia deployment, the CDN was switched from Azure to Cloudflare. The CDN has switched back to Azure, and so the ETAG headers, etc. for `https://gaia.blockstack.org/...` requests should be the same as before.

If this remains problematic, it would be helpful to figure out which headers are missing if you could provide a sample URL of a `https://gaia.blockstack.org/...` request with the missing header.

**Comment by 0xc22b** [comment]
It works now. Thanks a lot.
