### ISSUE TITLE
Refactor storage to remove circular dependencies with auth

### ISSUE THREAD

**Issue by yknl** [stx-labs/stacks.js#808]
`auth.ts` and `userSession.ts` both have dependencies on storage. Either all storage functions should be accessed through `userSession` or storage functions should be separate and take a `userSession` object as input.

**Comment by kyranjamie** [comment]
https://github.com/blockstack/blockstack.js/issues/795

**Comment by aulneau** [comment]
I'd be open to talking about the pros and cons of the user session in general and if it's still something we want. Anyone else?

**Comment by zone117x** [comment]
I think `userSession` essentially represents the state of an authenticated user, and it makes sense to be defined by the auth lib. If we take that approach, the storage functions should be separated out.
