### ISSUE TITLE
Allowed multiple registration of the same .id 

### ISSUE THREAD

**Issue by unotdog25** [stx-labs/stacks.js#82]
Today I tried using the command line to register a few handles and I was able to register the same handle 4 times with 4 separate payments. Each time I tried 'lookup' the name showed as unregistered. The name has since verified and shows with 'names' command, bit I'm assuming this is not meant to be a feature? 

Had the zope 3.6+ issue when installing, now fixed if this is of any significance. Ubuntu 14.04 64bit

**Comment by jcnelson** [comment]
Hi, thanks for reporting.

> Today I tried using the command line to register a few handles and I was able to register the same handle 4 times with 4 separate payments.

If you used the same keypair to register the names, the tool should have stopped you after the first request went through.  I will investigate this further.  However, if you used a different keypair for each name, then all four registration requests should go through, since as far as the software is concerned, it's the equivalent to four separate people trying to grab the same name (however, only one will be accepted by Blockstack).

> Had the zope 3.6+ issue when installing, now fixed if this is of any significance. Ubuntu 14.04 64bit

I doubt this is related, but will take a look.  Fortunately, the next release will get rid of zope entirely, so you won't see this particular issue again :)

**Comment by unotdog25** [comment]
Thankyou for the reply. I'm not sure what you mean by the same key pair. But all 4 purchases were conpletely on the same instance of blockstack on the same computer so surely it should have stopped me?

Also, despite the first name now appearing when I run the names command, I'm now waiting nearly 48 hours for another name for which I have paid once, yet this name is still showing as available and will allow me to pay for it again. The first were only to test the system, this username I need. Should I still expect it to work after this long?

**Comment by unotdog25** [comment]
I've just tried a third name and now I get a "couldn't broadcast transaction" error. Is there's some documentation you can point to, or any help you can give me regards backup and restore? (using Ubuntu 14.04) do I just need to copy the .blockstack folder in home or even just the encrypted wallet.json?

**Comment by shea256** [comment]
Thanks for submitting this issue @unotdog25. I closed the duplicate issue and we can focus our discussion here.

I'll let @jcnelson and @muneeb-ali respond to this, as they'll know how best to address this.

**Comment by unotdog25** [comment]
To try and resolve my problem I created a complete new instance of blockstack on and live Ubuntu USB. 
This time the name appears in 'info' but over 48 hours later and I can still pay for it again, and it still isn't listed in 'names'. It also remains free to purchase again. Surely this cannot be happening to everyone? Why did two longer domains both register no problem and this 4 letter one is causing so much hassle? Surely I'm not the only person having this issue. I don't care if I have to pay for it a third time but please can someone help me secure this name? My whole branding and cross platform usernames totally rely on it.

**Comment by muneeb-ali** [comment]
@unotdog25 it's likely that your register transaction didn't go through for some reason. The CLI tries to automatically re-try but it can't re-try after the wallet unlock timeout passes. 

This is a known issue that we're fixing in the next release. You can try restarting and then manually unlocking the wallet by following the instructions [here](https://github.com/blockstack/blockstack-cli/issues/72).

Also, pre-orders expire after a while. If the old preorder has more than 130 confirmations, I'd recommend the following steps:
1. Delete the ~/.blockstack/local_state.json
2. Restart the CLI (you can do this by either restarting your Ubuntu or killing the python processes e.g., by pkill -9 python)

Let us know if you need more help. You can also chat with us at http://chat.blockstack.org
