### ISSUE TITLE
Update needed to CLI output for transactions to fix 2 issues

### ISSUE THREAD

**Issue by timstackblock** [stx-labs/stacks.js#820]
**Describe the bug**
Currently we have 2 issues the TXID is missing the first 2 characters 
The link to explorer is not pointing to the current version of the explorer

This is what we get 

{
  txid: 'a5659553e404089f861efba24394268a1bfefbe2d44a1301d45e2505a8ce6c79',
  transaction: 'https://testnet-explorer.now.sh/txid/0xa5659553e404089f861efba24394268a1bfefbe2d44a1301d45e2505a8ce6c79'
}

This is what we should get

{
  txid: '0xa5659553e404089f861efba24394268a1bfefbe2d44a1301d45e2505a8ce6c79',
  transaction: 'https://testnet-explorer.blockstack.org/txid/0xa5659553e404089f861efba24394268a1bfefbe2d44a1301d45e2505a8ce6c79'
}

**To Reproduce**
1. Go to the CLI 
2. Send a a token send transaction
3. look at the output and you will see the 2 issues above

**Expected behavior**
{
  txid: '0xa5659553e404089f861efba24394268a1bfefbe2d44a1301d45e2505a8ce6c79',
  transaction: 'https://testnet-explorer.blockstack.org/txid/0xa5659553e404089f861efba24394268a1bfefbe2d44a1301d45e2505a8ce6c79'
}

**Screenshots**

**Terminal Log**
If applicable, add console log to help explain your problem.
<img width="911" alt="Screen Shot 2020-09-08 at 11 05 47 AM" src="https://user-images.githubusercontent.com/49165468/92494137-524e4780-f1c3-11ea-8c27-350452b9b58d.png">

**Comment by yknl** [comment]
Moving this issue to the stack.js monorepo since the CLI has already been migrated and changes will be made in the new repo.

**Comment by agraebe** [comment]
it looks like what is outstanding here is the URL to the explorer (currently printing: `https://testnet-explorer.now.sh/txid/`). @yknl is that correct? could we pick this issue up and fix in this sprint?
