### ISSUE TITLE
Incorrect text?

### ISSUE THREAD

**Issue by unotdog25** [stx-labs/stacks.js#83]
When attempting to register a name will forbidden characters, eg 'qwert-y' the error message reads:

' The name specified is invalid. Names may only contain alphanumeric characters, **dashes**, and underscores."

Sorry if this doesn't warrant posting here.

**Comment by unotdog25** [comment]
Credit to reddit user huhn_solo

**Comment by muneeb-ali** [comment]
Thanks for submitting! We'll take a look.

**Comment by jcnelson** [comment]
Documentation was wrong.  Dashes are excluded.
