### ISSUE TITLE
Transactions: broadcastTransaction return type is inconsistent

### ISSUE THREAD

**Issue by agraebe** [stx-labs/stacks.js#830]
The `broadcastTransaction` method either returns a string (txid) if successful or a JSON object with error details:

```js
export declare type TxBroadcastResultOk = string;
export declare type TxBroadcastResultRejected = {
    error: string;
    reason: TxRejectedReason;
    reason_data: any;
    txid: string;
};
export declare type TxBroadcastResult = TxBroadcastResultOk | TxBroadcastResultRejected;
```

We should make the response type consistent and always return an object. Developers would use the response and simply check ```if(resp.error)``` for error handling. 

Question: Could we also return null for the txid if a transaction is rejected? From a developer standpoint, what is the value of a rejected txid?

**Comment by friedger** [comment]
See also https://github.com/blockstack/stacks-blockchain/issues/2057

**Comment by kyranjamie** [comment]
Big +1 for always returning an object

**Comment by friedger** [comment]
The argument in blockstack/stacks-blockchain#2057 was that "0x1234" is valid json. Therefore, broadcastTransaction should return `"${txid}"` instead of `txid`.

**Comment by kyranjamie** [comment]
Could it not be the role of this library to provide a more friendly API to consume? 

A string may be valid JSON, but it leaves the consumer of the API the task of checking the type of the response, or face runtime errors. If more metadata needs is added later, 💥  breaking change

I suggest:

```typescript
interface TxBroadcastResultOk {
    txid: string;
}
interface TxBroadcastResultRejected {
    error: string;
    reason: TxRejectedReason;
    reason_data: any;
    txid: string;
}
type TxBroadcastResult = TxBroadcastResultOk | TxBroadcastResultRejected;
```

Imo, best practice is for an API to **always** return objects.
