### ISSUE TITLE
Fix public link in Todos app

### ISSUE THREAD

**Issue by timstackblock** [stx-labs/stacks.js#832]
**Describe the bug**
Create a todo list make the link public copy the link and attempt to open it in another browser and you will see a 404 error
**What version of Blockstack.js are you using?**
stacks.js new releas

**Screenshots**

<img width="1391" alt="Screen Shot 2020-10-15 at 8 16 19 AM" src="https://user-images.githubusercontent.com/49165468/96122327-50ad2900-0ebf-11eb-8031-988dc93a2ded.png">
<img width="1385" alt="Screen Shot 2020-10-15 at 8 16 09 AM" src="https://user-images.githubusercontent.com/49165468/96122330-51de5600-0ebf-11eb-828b-8a87798c0a0d.png">

**Console log**
If applicable, add console log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: Mac OS
 - Browser [safari, chrome]

**Comment by timstackblock** [comment]
This bug exist in prod as well and doesn't seem related to the stack.js change

**Comment by agraebe** [comment]
@markmhx @hstove

**Comment by markmhendrickson** [comment]
I'm closing this out in favor of the issue in the todos app repo itself here https://github.com/blockstack/todos/issues/55
