### ISSUE TITLE
[Transactions] Funky broadcasting logic

### ISSUE THREAD

**Issue by kyranjamie** [stx-labs/stacks.js#837]
_This is an issue with the stacks-transaction library, reporting here due to ongoing mono refactor work_

**Code in question**
https://github.com/blockstack/stacks-transactions-js/blob/ad6ac4fb605c38af6f8d001385e82e0a6c466bfd/src/builders.ts#L188-L201

**Issue**
There's some unusual logic in the broadcast transaction function, added by yours truly, which results in a legitimate network request being made, but **not shown in dev tools** HTTP panel.

This is likely owing to use of the `Request.clone()` method. 

**Resolve**
Avoiding use of `.clone()` with likely result in a more transparent mode of operation

**Comment by yknl** [comment]
Would this resolve the issue you're seeing?

```javascript
const clonedRes = response.clone();
try {
  return (await response.json()) as TxBroadcastResult;
} catch (e) {
  return await clonedRes.text();
}
```

**Comment by kyranjamie** [comment]
I don't believe so.

I think we can just use 👇 . If I recall correctly, I added this so that we never return JSON as a string.

```ts
  const text = await response.text();
  try {
    return JSON.parse(text) as TxBroadcastResult;
  } catch (e) {
    return text;
  }
```
