### ISSUE TITLE
Examples of <data> formatting for update command please

### ISSUE THREAD

**Issue by gordonwcasey** [stx-labs/stacks.js#84]
While the instructions at https://github.com/blockstack/blockstack-cli#update are fairly clear, it would be really helpful if examples could be given with real-world details (like with the rest of the examples using fredwilson.id etc). 

Essentially I would like to update the data behind the names but am not clear on how to format the details so as to achieve that and add various bits of data.

**Comment by muneeb-ali** [comment]
Marked as high-priority.

**Comment by muneeb-ali** [comment]
This is now online! https://github.com/blockstack/blockstack-cli/blob/master/docs/openbazaar.md

**Comment by gordonwcasey** [comment]
Thanks Muneeb. 

If you ever get a chance to do a walk-through on how I could update additional data that would be great.

**Comment by muneeb-ali** [comment]
Which additional data are you looking to update?

**Comment by gordonwcasey** [comment]
I wanted to link up social profiles, websites, that kind of thing.

**Comment by jcnelson** [comment]
A zonefile wizard was merged to 0.14.1.  Profiles can be arbitrary JSON blobs.
