### ISSUE TITLE
Stacks 2.0: Contract deployment to mocknet

### ISSUE THREAD

**Issue by agraebe** [stx-labs/stacks.js#840]
Deploying a contract to mocknet requires the following:

```bash
blockstack deploy_contract ./counter.clar counter 2000 0 cb3df38053d132895220b9ce471f6b676db5b9bf0b4adefb55f2118ece2478df01 -t -T http://localhost:20443
```

Result is:
```bash
{
  txid: '4bc11e1334c52852111142d55e5bbcfadbbb3441c44aa29a4bc507f7d2239377',
  transaction: 'https://testnet-explorer.now.sh/txid/0x4bc11e1334c52852111142d55e5bbcfadbbb3441c44aa29a4bc507f7d2239377'
}
```

Help method for the contract deploy says:

```bash
Command: deploy_contract
Usage:
  deploy_contract SOURCE_FILE CONTRACT_NAME FEE NONCE PAYMENT_KEY 
  deploy_contract --source_file PATH
                  --contract_name STRING
                  --fee INTEGER
                  --nonce INTEGER
                  --payment_key PRIVATE_KEY
                  
  Deploys a Clarity smart contract on the network. 

  If the command succeeds, it prints out a transaction ID. 
  Example: 
    $ export PAYMENT="bfeffdf57f29b0cc1fab9ea197bb1413da2561fe4b83e962c7f02fbbe2b1cd5401"
    $ blockstack-cli deploy_contract ./my_contract.clar my_contract 1 0 "$PAYMENT"
    a9d387a925fb0ba7a725fb1e11f2c3f1647473699dd5a147c312e6453d233456
```

3 things need to be updated:
- [ ] We need to document the -t and -T options
- [ ] We need to update the help content: it prints a JSON object now
- [ ] We need to update the new tx URL that points to the explorer. When -T is set, it should go to a local instance (`localhost:3000`). When it -t is set, it should go to `https://testnet-explorer.blockstack.org/` (not now.sh)

Also, question: is it possible to just set one option instead of two (`-t -T`)?

(this is supporting, but not blocking for https://github.com/blockstack/docs/pull/827)

**Comment by friedger** [comment]
From an API point of view, there is no difference whether I want to deploy to mocknet or testnet. Mocknet can run on a different port, I might have a local explorer or not.
