### ISSUE TITLE
Provider pattern for Clarity JS development

### ISSUE THREAD

**Issue by agraebe** [stx-labs/stacks.js#843]
As per our earlier discussions, let's continue discussions on [this proposal](https://paper.dropbox.com/doc/Proposal-Provider-pattern-for-Clarity-JS-development--A~Ngf~E~C5IPBxYO3W_cJAYwAQ-2bh1pi6voAhxgR36SF6wX). As a next step, @hstove will draft up a more detailed plan.

**Comment by friedger** [comment]
There is an open PR for the JsonRCP provider https://github.com/blockstack/clarity-js-sdk/pull/83

**Comment by agraebe** [comment]
thanks @friedger. Sounds like we simply need to sync a bit on the direction once @hstove can take some time for this, likely post mainnet
