### ISSUE TITLE
Wiki update?

### ISSUE THREAD

**Issue by gordonwcasey** [stx-labs/stacks.js#85]
Just checking if any of the instructions at https://github.com/blockstack/blockstack-cli/wiki are still accurate. It looks to me like these might be out of date (last update on the wiki was September 2015), and therefore a little confusing if someone stumbles across them first.

**Comment by jcnelson** [comment]
Yes, these are out of date.  Please see the docs [here](https://blockstack.org/docs).  Will update the wiki to point there.
