### ISSUE TITLE
Save Single JSON objects at a time

### ISSUE THREAD

**Issue by mattruddy** [stx-labs/stacks.js#851]
**Is your feature request related to a problem? Please describe.**
I was working on storing invoices for an app im working on and found it annoying to have to get all invocies, and then add the new one to the array and resave the entire json file. How come we cant just add a single object and write it to the json file?
**Describe the solution you'd like**
I want to be able to append a new json object into the exisiting json file with out having to fetch the previous

**Describe alternatives you've considered**

**Additional context**

**Comment by friedger** [comment]
Currently, there is no api available at gaia storage that understands json, nor an api that allows for appending bytes to a file.

This could be a good improvement either of the gaia storage (append bytes) or for stacks.js to cache the file content and provide apis to manipulatae json objects.
