### ISSUE TITLE
deserializeCV does not work due to bad SmartBuffer construction

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#853]
**Describe the bug**
When calling `deserializeCV` or `callReadOnlyFunction` the following error occurs:
```
 TypeError: Class constructor SmartBuffer cannot be invoked without 'new'
      at new BufferReader (node_modules/@stacks/transactions/src/bufferReader.ts:52:7)
      at deserializeCV (node_modules/@stacks/transactions/src/clarity/deserialize.ts:24:50)
```

**What version of Blockstack.js are you using?**
@stacks/transactions 1.0.0-beta.9

**Expected behavior**
Just return the correct cv

**Additional context**
https://github.com/friedger/clarity-demo/blob/ecaeb4e61986c8e0386708cf722980d83af93bf9/scripts/deploy.ts#L66

**Comment by friedger** [comment]
Looks like some typescript transpiler issue: https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne

**Comment by yknl** [comment]
Yes, there's a fix for this coming soon. `BufferReader` will no longer extend `SmartBuffer`
