### ISSUE TITLE
Auto-publish packages

### ISSUE THREAD

**Issue by kyranjamie** [stx-labs/stacks.js#858]
Would be great to have all of these packages auto-published to npm when merged into `master`.

Edit per @agraebe's comment:

We'd love to have a CI job that ensures that `master` always represents the most recently published package. Using a tool such as `semantic-release` to publish packages when there's a commit to `master`.

**Comment by agraebe** [comment]
@reedrosenbluth and @kyranjamie - could you share some context in here for Tintash to start working on this soon?

**Comment by kyranjamie** [comment]
Updated description, cc @CharlieC3 as he's familiar with this set up

**Comment by CharlieC3** [comment]
If Tintash is taking this issue, they can ping me on Discord and I'd be happy to explain on a call how I've set it up in other repos using `semantic-release`.

**Comment by CharlieC3** [comment]
After talking to Asim from Tintash and @agraebe, we've decided to let DevOps take this one since we're already familiar with this process. I'll share the changes I've made with Asim in the PR once it's ready.

@agraebe When do you need this completed?
