### ISSUE TITLE
mdhmgoflnkccjhcfbojdagggmklgfloo is blocked

### ISSUE THREAD

**Issue by mijoco-btc** [stx-labs/stacks.js#866]
**Describe the bug**
Calling @stacks/connect (4.2.4) method openContractCall with the browser extension fails in Chroem and Firefox. Behaviour is different in each. Switching the extension off and running with the popup works with Chrome but fails with Firefox.

Chrome Browser:
Calling @stacks/connect (4.2.4) method openContractCall with the browser extension active results in the window opening in error state ERR_BLOCKED_BY_CLIENT

Firefox Browser:
Note: In firefox the extension window does not appear at all. Theres an error in console...
**Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://app.blockstack.org’) does not match the recipient window’s origin (‘https://dcmarket2.risidio.com’).**

All other browser extensions in both browsers are disabled.

The same call in Chrome with browser extension switched off works (i.e. via the popup). In firefox the popup is a blank window.

**What version of Blockstack.js are you using?**
    "@stacks/auth": "^1.0.0-beta.10",
    "@stacks/connect": "^4.2.4",
    "@stacks/encryption": "^1.0.0-beta.10",
    "@stacks/keychain": "^1.0.0-beta.13",
    "@stacks/network": "^1.0.0-beta.10",
    "@stacks/storage": "^1.0.0-beta.13",
    "@stacks/transactions": "^1.0.0-beta.10",

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
Connect

**To Reproduce**
I can reproduce this on two separate domains
https://loopbomb.risidio.com/

**Expected behavior**

**Screenshots**

**Console log**
If applicable, add console log to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Mac Book Pro
 - Browser Chrome, Firefox - behaviour is different in each.
 - Version

**Comment by mijoco-btc** [comment]
Error in browser extension view.

<img width="662" alt="Screenshot 2020-11-30 at 08 46 38" src="https://user-images.githubusercontent.com/4384929/100587607-b2e3b100-32e8-11eb-98af-4e9d8cb86e04.png">

**Comment by markmhendrickson** [comment]
Sorry for the delay here, I appear to have missed this issue earlier. Is it still a problem we should investigate?

**Comment by mijoco-btc** [comment]
Will let you know soon Mark - just coming back to dev work, updating packages etc.

**Comment by mijoco-btc** [comment]
I think this is superseded by other work!
