### ISSUE TITLE
@stacks/encryption does not export hashRipemd160()

### ISSUE THREAD

**Issue by faried** [stx-labs/stacks.js#867]
**Describe the bug**

@stacks/encryption does not export the hashRipemd160 function.

**What version of Blockstack.js are you using?**

@stacks/encryption@1.0.0-beta.13

**To Reproduce**

Try `import { hashRipemd160 } from '@stacks/encryption';`

**Comment by agraebe** [comment]
is this a blocking issue that we should look at with priority?

**Comment by yknl** [comment]
Also, there is a function in the transaction lib that does this:

`import { hash160 } from '@stacks/transactions'`

**Comment by faried** [comment]
I needed to create a salted hash to test the BNS contract a couple of weeks ago, and didn't realize I could use `hash160` directly.  I'll close the issue.
