### ISSUE TITLE
[storage] putFile no longer has the dangerouslyIgnoreEtag option

### ISSUE THREAD

**Issue by aulneau** [stx-labs/stacks.js#876]
These changes:
https://github.com/blockstack/stacks.js/pull/793/files#diff-189df448d4739484d3f18a1acd3d9f4b947564f111c3fb4ef7c14c284ec4c430R86

are no longer in `master` -> https://github.com/blockstack/stacks.js/blob/master/packages/storage/src/storage.ts#L39

Curious to learn how this regression happened. cc @yknl

**Comment by yknl** [comment]
Thanks for catching, I think this might have been left out when we migrated to stacks.js.
