### ISSUE TITLE
[CLI] Sending transactions to specified node URL

### ISSUE THREAD

**Issue by agraebe** [stx-labs/stacks.js#878]
**Describe the bug**
Using the `-H` or the `-T` option should broadcast transactions to a defined node. However, this seems not to work. All transactions are broadcasted to the testnet. It seems the option is ignored.

**What version of Blockstack.js are you using?**
Latest on NPM, fresh install

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
CLI

**To Reproduce**

```
❯ stx deploy_contract ./counter.clar counter 2000 110 cb3df38053d132895220b9ce471f6b676db5b9bf0b4adefb55f2118ece2478df01 -t -H "http://localhost:20443"
{ txid:
   '0x505504afd03dacdddab01912b7cdb7ebe1619f93cbf1ac5868ae7a0a5fa7509a',
  transaction:
   'https://testnet-explorer.now.sh/txid/0x505504afd03dacdddab01912b7cdb7ebe1619f93cbf1ac5868ae7a0a5fa7509a' }

❯ stx deploy_contract ./counter.clar counter 2000 111 cb3df38053d132895220b9ce471f6b676db5b9bf0b4adefb55f2118ece2478df01 -t -T "http://localhost:20443"
{ txid:
   '0x5a7426507190bf96688aecd5a2ed6f1cde4c6d7f41a5c2cde395d7288e46a26d',
  transaction:
   'https://testnet-explorer.now.sh/txid/0x5a7426507190bf96688aecd5a2ed6f1cde4c6d7f41a5c2cde395d7288e46a26d' }
```

(The nonce not starting at `0` is an indicator that the reference account used was on the testnet)

**Expected behavior**
The contract deployment is broadcasted to the local node (mocknet).

**Comment by yknl** [comment]
The correct flag for node URL is actually `-I`. 

try this:
```
stx deploy_contract ./counter.clar counter 2000 110 cb3df38053d132895220b9ce471f6b676db5b9bf0b4adefb55f2118ece2478df01 -t -I "http://localhost:20443"
```

**Comment by agraebe** [comment]
there's an issue with the node right now, but I got this message:
```
FetchError: request to http://localhost:20443/v2/transactions failed, reason: connect ECONNREFUSED 127.0.0.1:20443
```

that suggests the broadcasting attempt went out to the right address. 

We need to update the following:
- https://github.com/blockstack/stacks.js/blob/master/packages/cli/src/argparse.ts
- https://docs.blockstack.org/understand-stacks/command-line-interface#network-selection

Most importantly, we should better describe the `-H`, `-I`, and `-T` options:
- `-T URL              Use an alternative Blockstack transaction broadcaster.`
- `-H URL              Use an alternative Blockstack Core API endpoint.`
- `-I URL              Use an alternative Blockstack Core Indexer endpoint.`

@yknl could you take this on?
