### ISSUE TITLE
Upload image data fails after switch to @stacks/storage api

### ISSUE THREAD

**Issue by mijoco-btc** [stx-labs/stacks.js#880]
**Describe the bug**

I've been uploading image data using the old UserSession object from blockstack.js and recently updated to use the new APIs

The following worked before the switch and fails after the switch with

This worked;
```
import { UserSession } from 'blockstack'
const userSession = new UserSession()
...
userSession.putFile(path, imageData.imageBuffer, options).then(function () {
```

whereas this fails **HTTP Error Code 412 from Gaia hub**

```
import { UserSession } from '@stacks/auth'
import { Storage } from '@stacks/storage'
const userSession = new UserSession()
const storage = new Storage({ userSession })
...
storage.putFile(path, imageData.imageBuffer, options).then(function () {
```

I'm sending the image data, converting the dataUrl to buffer, like this;

```
import dataUriToBuffer from 'data-uri-to-buffer'
...
    const imageBuffer = dataUriToBuffer(dataURL)
```

**What version of Blockstack.js are you using?**
    "@stacks/auth": "^1.0.0-beta.19",
    "@stacks/blockchain-api-client": "^0.34.2",
    "@stacks/connect": "^4.3.1",
    "@stacks/encryption": "^1.0.0-beta.19",
    "@stacks/keychain": "^1.0.0-beta.19",
    "@stacks/network": "^1.0.0-beta.19",
    "@stacks/storage": "^1.0.0-beta.19",
    "@stacks/transactions": "^1.0.0-beta.19",
    "axios": "^0.19.2",
    "blockstack": "^19.3.0",

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**

**To Reproduce**
as above

**Expected behavior**
Image to upload to Gaia hub storage - no http error.

**Comment by reedrosenbluth** [comment]
Are these `putFile` attempts trying to write new data, or overwrite existing data?

Prior to attempting `putFile`, do you do a `getFile`? If the file you are writing isn't a new file (in other words, you are overwriting an existing image) this is required so your client has an up to date `etag`, ensuring that it isn't overwriting new data that it isn't aware of.

**Comment by mijoco-btc** [comment]
Hi - just switched back and tried the 'storage.getFile' before 'storage.putFile'

This worked - thank you!
