### ISSUE TITLE
How To Generate Tx And Sign offline?

### ISSUE THREAD

**Issue by Wangmmx** [stx-labs/stacks.js#884]
Hello, how can I generate a transaction body and sign it offline? I want to complete a simple function of transferring STX. The content in the document is generated on the client side. I want to try the offline method. I see a similar method called `makeUnsignedSTXTokenTransfer`, but it is not very suitable . What I want is to first generate an unsigned transaction body, sign it by the sender, then serialize the signed transaction body, and broadcast the serialized result. Is there such a way? I'm not sure, looking forward to your reply, thanks

**Comment by friedger** [comment]
@Wangmmx Please use the forum.stacks.org or discord for these open questions and close this issue. 

If the documentation at https://docs.blockstack.org/understand-stacks/transactions#serialization is not sufficient you can open an issue on github.com/blockstacks/docs

**Comment by Wangmmx** [comment]
You don't understand what I mean. I need to confirm to the developer instead of the forum. There are many types of transaction bodies in the document. I want to know if there is a way to assemble transaction bodies and sign them offline. It is a simple one-signature account transfer: https://docs.blockstack.org/understand-stacks/transactions#stacks-token-transfer, here is to put the senderKey in the transaction body to build, is there any first to build How about the unsigned transaction body, senderKey to sign separately?

**Comment by yknl** [comment]
@Wangmmx `makeUnsignedSTXTokenTransfer` does exactly what you want, creating a transaction without the private key. What makes it not very suitable?

**Comment by Wangmmx** [comment]
> @Wangmmx `makeUnsignedSTXTokenTransfer` does exactly what you want, creating a transaction without the private key. What makes it not very suitable?

Because this method also uses generator to construct the transaction body, it returns a promise. I want to use a more normal method instead of promise. I have basically solved this problem and constructed a StackTransaction class to complete it. By the way, if you use the way you said, how to put the signature into the transaction body? In other words, what is the signature comes from? thank you for your reply

**Comment by yknl** [comment]
Can you explain why it's not possible to use a promise for your use case? If the nonce and fee are supplied as inputs to the transaction builder, it does not need to be async. Once you have an unsigned transaction, you can sign it using the `TransactionSigner` class.

**Comment by Wangmmx** [comment]
It's my own problem. I try to avoid using asynchronous methods in my projects. If I quote directly, I need  `await` or handle `promise`. 

I have successfully constructed the transaction body and signed it, thank you for your reply, I responded too late. 

I would like to ask how to broadcast transactions? I want to use the rpc interface `/v2/transactions` to broadcast. The rawTx parameter is the serialized transaction body, which looks like `8080000000...`, but it keeps reporting errors: `{Error: "Failed to deserialize posted transaction: Failed to parse transaction authorization : unrecognized auth flags 101"}`, I used the api interface broadcastRawTransaction to be successful, may I ask why?

**Comment by yknl** [comment]
Your request body is probably not formatted correctly. Take a look at `broadcastTransaction` in `@stacks/transactions`

**Comment by Wangmmx** [comment]
Okay, I made it, thank you very much! I forgot to add the url to the request, thanks again!
The successful broadcast transaction was not found on the browser. I found that the last broadcast was successful 10 days ago. Is the testnet unavailable now?

**Comment by yknl** [comment]
There were some issues with Testnet in the last 24 hours. It should be resolved now.
