### ISSUE TITLE
Two different APIs to call a read only function in smartcontractsapi and transactions

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#892]
**Describe the bug**
There are two different APIs to call a read only function:
1. `SmartContractsApi.callReadOnlyFunction(requestParameters: CallReadOnlyFunctionRequest): Promise<ReadOnlyFunctionSuccessResponse>`
2. `function callReadOnlyFunction(readOnlyFunctionOptions: ReadOnlyFunctionOptions): Promise<ClarityValue>`

It is not bad to have both. However, the signatures should be the same. In particular, the result types and the function arguments:
1. `readOnlyFunctionArgs: ReadOnlyFunctionArgs`
1. `functionArgs: ClarityValue[]`

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
@stacks/transaction and @stacks/blockchain-api-client

**Comment by RyanRussell00** [comment]
@agraebe Is this still an open issue?

**Comment by agraebe** [comment]
yes, afaik both options still exist

**Comment by zone117x** [comment]
Note that `@stacks/blockchain-api-client` is not part of this repo. It's a relatively simple API client library auto-generated from OpenAPI spec. It can't (easily) do many useful things like automatically encoding/decoding between js types and Clarity types. 

At first glance, I don't think we should blacklist certain OpenAPI endpoints/functions from the auto-generated `@stacks/blockchain-api-client` lib, and I don't think `@stacks/transaction` should remove the more developer friendly version of the function. 

I'm open to suggestions on how the devx could be improved here.

**Comment by friedger** [comment]
There should be a clear decision making path documented when to use which function.

**Comment by friedger** [comment]
Probably not actionable here. Could be part of documenting stacks.js
