### ISSUE TITLE
Assertion error at toBuffer().

### ISSUE THREAD

**Issue by rac-sri** [stx-labs/stacks.js#898]
**Describe the bug**
Assertion error at toBuffer(). DecodeBtcAddress copied from https://github.com/blockstack/stacks.js/blob/master/packages/stacking/src/utils.ts 
```
const { hashMode, data } = decodeBtcAddress(poxAddr);
  console.log(hashMode, data, poxAddr);
  const hashModeBuffer = bufferCV(new BN(hashMode, 10).toBuffer());
  const hashbytes = bufferCV(data);
  const poxAddressCV = tupleCV({
    hashbytes,
    version: hashModeBuffer,
  });
```
Here Is a video: [video](https://www.loom.com/share/d10c6e6ab4564f4e89734e488e14b7b1)

**What version of Blockstack.js are you using?**

```
    "@stacks/blockchain-api-client": "^0.36.1",
    "@stacks/cli": "^1.0.0-beta.20",
    "@stacks/connect": "^4.3.13",
    "@stacks/network": "^1.0.0-beta.20",
    "@stacks/profile": "^1.0.0-beta.20",
    "@stacks/stacking": "^1.0.0-beta.20",
    "@stacks/transactions": "^1.0.0-beta.20",
```

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
No.

**To Reproduce**
Try converting poxAddr using bn,js, like here:  [ ](https://github.com/blockstack/stacks.js/blob/master/packages/stacking/src/index.ts#L237 )

**Expected behavior**
No assertion error shoul be there.

**Screenshots**
![link](https://cdn.discordapp.com/attachments/796112768486080552/797926467010297926/unknown.png)

**Console log**
If applicable, add console log to help explain your problem.
![image](https://user-images.githubusercontent.com/43861614/104253170-e42fcf00-5499-11eb-98a9-661c3b1aef29.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser Brave
 - Version 1.88

**Comment by hstove** [comment]
Please include the full call stack from your error trace. The error is happening inside `bn.js`, but we have no ability to see where exactly that error is coming from.

If `hashMode === 0`, as it is in your screenshot (and it should be for that address), then I tried running this code:

```
var BN = require("bn.js")

const bn = new BN(0, 10)
console.log(bn)
console.log(bn.toBuffer())
```

And no errors were thrown. Try running just that code snippet and see if it errors. If it does, then I am not sure if we will be able to help - it may be an issue with your environment.

If you're still stuck, you can still use the Stacking library:

```ts
import { StackingClient } from '@stacks/stacking';
import { StacksTestnet } from '@stacks/network';

const client = new StackingClient(address, new StacksTestnet());
const stackingOptions = client.getStackOptions({ ... }); // pass appropriate options
```

From there, you have `stackingOptions.functionArgs`, which you can pass to Connect.

**Comment by rac-sri** [comment]
> Please include the full call stack from your error trace. The error is happening inside `bn.js`, but we have no ability to see where exactly that error is coming from.
> 
> If `hashMode === 0`, as it is in your screenshot (and it should be for that address), then I tried running this code:
> 
> ```
> var BN = require("bn.js")
> 
> const bn = new BN(0, 10)
> console.log(bn)
> console.log(bn.toBuffer())
> ```
> 
> And no errors were thrown. Try running just that code snippet and see if it errors. If it does, then I am not sure if we will be able to help - it may be an issue with your environment.
> 
> If you're still stuck, you can still use the Stacking library:
> 
> ```ts
> import { StackingClient } from '@stacks/stacking';
> import { StacksTestnet } from '@stacks/network';
> 
> const client = new StackingClient(address, new StacksTestnet());
> const stackingOptions = client.getStackOptions({ ... }); // pass appropriate options
> ```
> 
> From there, you have `stackingOptions.functionArgs`, which you can pass to Connect.

Thank you for the reply. I tried both the things you mentioned. In the native nodejs env, scripts are working, but in the create-react-app setup both of them are not working. Please try and resolve this, since create-react-app is probably the most commonly used framework by react developers.

**Comment by zone117x** [comment]
The lib may need changed to use `bn.toArrayLike(Buffer)` instead of `bn.toBuffer()`
From their docs: 
> For compatibility with browserify and similar tools, use this instead: a.toArrayLike(Buffer, endian, length)

**Comment by rac-sri** [comment]
> The lib may need changed to use `bn.toArrayLike(Buffer)` instead of `bn.toBuffer()`
> From their docs:
> 
> > For compatibility with browserify and similar tools, use this instead: a.toArrayLike(Buffer, endian, length)

That worked!!

```
  const { hashMode, data } = decodeBtcAddress(poxAddr);

  const hashModeBuffer = bufferCV(new BN(hashMode, 10).toArrayLike(Buffer));
  const hashbytes = bufferCV(data);
  console.log(hashbytes, hashModeBuffer);
  const poxAddressCV = tupleCV({
    hashbytes,
    version: hashModeBuffer,
  });
  console.log(poxAddressCV.data);

```
Thank you !!
