### ISSUE TITLE
Make network and pox info more accessible

### ISSUE THREAD

**Issue by agraebe** [stx-labs/stacks.js#915]
Right now, only the stacking package exposes `v2/info` and `v2/pox` information. However, that info is important outside of stacking. We should move the methods to another package - maybe `@stacks/network`?

cc @yknl

**Comment by asimm241** [comment]
@alexkeating `/v2/pox` and `v2/info` are already in the `@stacks/network` package. We couldn't find it in the `@stakcs/stacking` package though.  Is it a typo or already taken care of ?
https://github.com/blockstack/stacks.js/blob/9045f5726fd3544fda3f276daa89142158c8da1b/packages/network/src/index.ts#L86

**Comment by diwakergupta** [comment]
Wrong Alex -- you meant @agraebe :)

**Comment by agraebe** [comment]
thanks @diwakergupta 

@asimm241 - you're right, it looks like this was already fixed without being marked. Closing this issue :)
