### ISSUE TITLE
Support custom derivation paths with CLI

### ISSUE THREAD

**Issue by CharlieC3** [stx-labs/stacks.js#918]
Hiro DevOps has two addresses which were created on the V1 network before the V2 mainnet launch using the old `blockstack-cli`, and had some BTC and STX sent to these addresses. Because of this, they were created on the old derivation path which is not supported on the Stacks Wallet.

How can someone access the funds on old addresses created using the old derivation path through any means?

**Comment by markmhendrickson** [comment]
I've transferred this issue to the Stacks.js repo since @kyranjamie has already started adding support there with https://github.com/blockstack/stacks.js/pull/917.

@agraebe I'd suggest you work with @CharlieC3 here on the DevX side in adding support to the CLI given his level of urgency.

**Comment by agraebe** [comment]
Not sure I understand the specific ask- can you elaborate?

**Comment by markmhendrickson** [comment]
The Stacks CLI needs new functionality in which a user can specify the derivation path they want to use when authenticating, since the old `blockstack-cli` generated address with a different derivation path for Stacks 1.0, and now @CharlieC3 can't get to his holdings on Stacks 2.0 since the CLI uses a different path.

**Comment by agraebe** [comment]
@CharlieC3 - mind providing input as to how important that is? We'd need to ask one of @hstove @reedrosenbluth or @kyranjamie I would assume

**Comment by CharlieC3** [comment]
@agraebe Low priority. The funds aren't needed right now, but I wouldn't think we'd want to leave them inaccessible forever.
