### ISSUE TITLE
connect: Send users to Stacks Wallet install page from introductory modal

### ISSUE THREAD

**Issue by markmhendrickson** [stx-labs/stacks.js#919]
Instead of sending them to the hosted authenticator, send them to https://www.hiro.so/wallet/install-web

**Comment by markmhendrickson** [comment]
@hstove Mind linking the relevant PR here?

**Comment by timstackblock** [comment]
> Instead of sending them to the hosted authenticator, send them to https://www.hiro.so/wallet/install-web

What link is sending them to the hosted authenticator?

**Comment by hstove** [comment]
In the previous Connect, when you started auth and saw the Connect modal (before the popup), clicking the button would send you to the hosted authenticator. But the new connect doesn't do that, it redirects you to the install page in the connect modal. Testable at https://pr-761.testnet-demo.stacks.engineering/

**Comment by timstackblock** [comment]
Got it I found the link and this works
