### ISSUE TITLE
Stacking lib: add reward methods

### ISSUE THREAD

**Issue by agraebe** [stx-labs/stacks.js#929]
The API returns burnchain rewards now: https://blockstack.github.io/stacks-blockchain-api/#tag/Burnchain.

The stacking library could provide methods to get the rewards for a set address

**Comment by agraebe** [comment]
@marcosc90 @zone117x what are your thoughts on this? I was thinking this could be a new method inside the stacking lib, eg `getRewardsForBtcAddress()`

**Comment by zone117x** [comment]
Make's sense to me 👍 
@marcosc90 is this something you can take on?

**Comment by ahsan-javaid** [comment]
I have started working on this issue. Assigning it to myself.
