### ISSUE TITLE
Invalid-Json Response

### ISSUE THREAD

**Issue by rac-sri** [stx-labs/stacks.js#936]
**Describe the bug**
A invalid-json response on getCoreInfo() function.

**What version of Blockstack.js are you using?**
Latest from npm

**Expected behavior**
The coreInfo object should be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/43861614/106521760-bcfe7780-6504-11eb-9b8a-b449e195e912.png)

**Console log**
If applicable, add console log to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser NodeJS Scipt
 - Version 12.04

**Additional context**
Client generation code:
```
import { StackingClient } from "@stacks/stacking";

import { StacksTestnet } from "@stacks/network";
import config from "../config.js";

const stxAddress = config.keyInfo.address;
const client = new StackingClient(stxAddress, new StacksTestnet());
// console.log(client);

export default client;
```

Also calling "https://stacks-node-api.testnet.stacks.co/v2/info" in postman gives ```502 bad gateway```

**Comment by friedger** [comment]
This looks like an issue about error handling. What would you expect? (other than stable node)

**Comment by rac-sri** [comment]
> This looks like an issue about error handling. What would you expect? (other than stable node)

Yes. Realised it after testing out the blockchain testnet apis themselves.
