### ISSUE TITLE
StackingClient.getSecondsUntilNextCycle does not output seconds in TestNet

### ISSUE THREAD

**Issue by phuvp** [stx-labs/stacks.js#937]
**Describe the bug**
Running `StackingClient.getSecondsUntilNextCycle` returns a value that the developer would expect to be seconds.
An example output would be `391608000`, which appropximates to 4,500 days.

**What version of Blockstack.js are you using?**

@stacks/network@1.0.0-beta.20
@stacks/stacking@1.0.0-beta.20
@stacks/transactions@1.0.0-beta.20

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
No

**To Reproduce**
Run the following:

```
import { StackingClient } from '@stacks/stacking';
import {
    StacksTestnet,
    StacksMainnet
} from '@stacks/network';

const stxAddress = "SP....";

const client = new StackingClient(stxAddress, new StacksTestnet());
const secondsUntilNextCycle = await client.getSecondsUntilNextCycle();

console.log("SEC TIL NEXT CYCLE")
console.log(secondsUntilNextCycle)
```
**Console log**
```
SEC TIL NEXT CYCLE
390348000
```

**Expected behavior**
I would expect something on the order of 10-15 days, given that the next cycle should be on the 2/15/21. This issue was created in 2/1/21.

**Desktop (please complete the following information):**
 - OS: MacOS and Ubuntu

**Comment by friedger** [comment]
It looks like a factor 50 too much for testnet.
