### ISSUE TITLE
Add WIF format to `make_keychain` in the CLI

### ISSUE THREAD

**Issue by hstove** [stx-labs/stacks.js#938]
When you generate a keychain in the CLI, it uses the standard STX derivation path (which starts with `m/5757'/...`). If you try and use the secret key generated from the CLI in a Bitcoin wallet, you won't be able to access the address generated in the CLI. However, one easy fix is for the CLI to output your `WIF Private Key` (Wallet Import Format), which is supported by many BTC wallets.

To do so:
- Get the WIF key in [keys.ts](https://github.com/blockstack/stacks.js/blob/master/packages/cli/src/keys.ts#L139:L139)
  - `const wif = child.toWIF();`
- Add the WIF key to the result of that function
- Update the typescript return type of that function
- Add a test

**Comment by friedger** [comment]
You can use [stacks-gen](https://github.com/psq/stacks-gen) as a workaround :-)

**Comment by jasnkwcz** [comment]
I'd like to take a crack at this.
