### ISSUE TITLE
Post tutorial on transferring name from the Onename app to the CLI

### ISSUE THREAD

**Issue by muneeb-ali** [stx-labs/stacks.js#94]
A bunch of users have asked for details about transferring the name/ID they registered on the Onename app to the CLI. We need to post a tutorial about this.

**Comment by Gitju** [comment]
I guess a short tutorial on how to register name/ID for OpenBazaar would also be great for new users.

**Comment by muneeb-ali** [comment]
@Gitju Great idea! Can you please start a separate issue for this and we can track progress? Thanks,

**Comment by odinho** [comment]
For the benefit of issue readers, the OpenBazaar issue is #99.

**Comment by claus** [comment]
Any news on this (Onename id import to blockstack CLI)?
Could someone post a quick list of steps here?

**Comment by muneeb-ali** [comment]
Marking this as high priority. Thanks for your patience re this issue.

**Comment by Skorpion7777** [comment]
Hey guys,

here it is step by step:
- open onename account settings ( https://onename.com/settings )
- You'll find "export username" there
- Now enter your Owner Adress there
  
  ```
   - to be found in blockstack cli per: `blockstack set_advanced_mode` => ON
  
   -   and then `blockstack wallet` ==> you'll see your owner Adress there
  ```
- Now everything should be done. Wait a few days. If nothing happens ask in the Slack Forum

@muneeb-ali please check if everything is right and then you can close the topic. Thanks :) !

**Comment by cloxy** [comment]
How to export name/ID from CLI to OneName?

**Comment by jcnelson** [comment]
I'm guessing this is fixed, since we've spent a lot of time getting this to work and I haven't seen any issue tickets open for it.  Closing here; please re-open in blockstack-core if it persists.
