### ISSUE TITLE
Allow more than one argument

### ISSUE THREAD

**Issue by unclemantis** [stx-labs/stacks.js#941]
I currently have this line of code:

    functionArgs: [bufferCVFromString('12345')],

I would like to send more than one argument but I can't figure it out. Little help. Sorry if this is already a feature.

Thank you.

**Comment by kyranjamie** [comment]
It's an array, so you can add more than a single item. See the stacking lib for example

https://github.com/blockstack/stacks.js/blob/a2c0e345eb99daa9d41464eadd4ddb23cb057c4a/packages/stacking/src/index.ts#L296-L309
