### ISSUE TITLE
Problem with contract transactions after the testnet api endpoint upgrade.

### ISSUE THREAD

**Issue by rac-sri** [stx-labs/stacks.js#942]
**Describe the bug**
The official latest version of @stacks/connect, on making contract calls is still trying to connect to the old endpoints.
The canary release : to showconnect popup for signIn confirmation.

**What version of Blockstack.js are you using?**
All modules up-to-date with npm.

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
In package @stacks/connect

**To Reproduce**
1. npm i @stacks/connect
2. Try using making a smart contract call.

*****

1. npm install the canary version
2. Try using showconnect from the api. Nothing will showup.

**Expected behavior**
- Latest release should point to the new testnet api end point.
- Canary releaes: should show a popup after showConnect.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Brave
 - Version Latest

**Comment by friedger** [comment]
For canary, it is important to have the latest extension:
1. go to https://github.com/blockstack/ux/pull/936
2. I go to the last commit and the follow the checks, even if they failed
![Screenshot from 2021-02-06 23-31-21](https://user-images.githubusercontent.com/1449049/107132277-dd9c4800-68dd-11eb-968c-e42d25cd6673.png)

3. There you have an artifact
![Screenshot from 2021-02-06 23-32-19](https://user-images.githubusercontent.com/1449049/107132275-d7a66700-68dd-11eb-8010-00dbfc416f1f.png)

4. Download and unzip it (twice)
5. install manually in a chrome browser

**Comment by agraebe** [comment]
assuming this is resolved. please reopen otherwise
