### ISSUE TITLE
Update READMEs to use @stacks/connect instead of @stacks/auth

### ISSUE THREAD

**Issue by markmhendrickson** [stx-labs/stacks.js#944]
Developers are currently misled into thinking that they should install the auth package instead of connect for most web app purposes.

[The storage README, for example:](https://github.com/blockstack/stacks.js/tree/master/packages/storage#stacksstorage)

![image](https://user-images.githubusercontent.com/28991/107514077-73b7c300-6ba9-11eb-8f63-b641bde70681.png)

**Comment by agraebe** [comment]
@markmhx @kyranjamie is this still relevant? we could ask Tintash to help with this I assume? Any guidance you could provide?

**Comment by markmhendrickson** [comment]
I assume it's still relevant, though it's also just a README / documentation update (in this repository, vs. the docs one) so perhaps @pgray-hiro could take it?

**Comment by agraebe** [comment]
I'd prefer someone from Tintash to take it. This sounds like one should use the code, try to run it, update as necessary (input here would be helpful from an eng like @kyranjamie), and update the README. Probably a good first issue

**Comment by kyranjamie** [comment]
I'm inclined to say this isn't relevant. I wouldn't imagine `@stacks/storage` docs should show connect code examples. Perhaps we can just add a one-liner with a link mentioning connect?

**Comment by agraebe** [comment]
okay, I'm closing this for now. can revisit later if it comes up again.

**Comment by markmhendrickson** [comment]
IIRC the code snippet in the storage README doesn't work – or at least we don't recommend users do this (import `auth` instead of `connect`):

```
import { UserSession } from '@stacks/auth';
import { Storage } from '@stacks/storage';

const appConfig = new AppConfig();
const userSession = new UserSession({ appConfig });
const storage = new Storage({ userSession });
```

Can we just remove this README content in general and link to the storage guide?

https://docs.stacks.co/build-apps/guides/data-storage

![image](https://user-images.githubusercontent.com/28991/125112740-daed8b00-e0e7-11eb-8217-c7c35ca94e59.png)

We also don't recommend what's being shown in the auth package README itself anymore: https://github.com/blockstack/stacks.js/tree/master/packages/auth#generating-an-authentication-request

![image](https://user-images.githubusercontent.com/28991/125112806-f48ed280-e0e7-11eb-9539-955e12beab5b.png)

See the authentication guide here for example: https://docs.stacks.co/build-apps/guides/authentication#initiate-usersession-object

The original idea here was simply to iron out these discrepancies, since they do tend to turn new developers around when getting their feet wet. I'm all for just directing README users to the docs if that simplifies things.

**Comment by agraebe** [comment]
@markmhx thanks for the details! let's keep this one and iron out the discrepancies you describe
