### ISSUE TITLE
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

### ISSUE THREAD

**Issue by OpenGrid** [stx-labs/stacks.js#95]
I get this during installation:

c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```
----------------------------------------
```

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-la78ay0e/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-p2njwk80-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-la78ay0e/cffi/

**Comment by jcnelson** [comment]
Hi @OpenGrid, apologies for the long turn-around time.

You will need to install the `libffi` headers package (i.e. `libffi-dev`).

**Comment by jcnelson** [comment]
Going through and cleaning up issues after the 0.14.0 release.  If this is still a problem for you, please re-open.

**Comment by st0079434** [comment]
You are the BOSS...My Everything worked after applying your resolution 
Guy's Here he means #apt-get install libffi-dev
