### ISSUE TITLE
Delegation: Sample code bug

### ISSUE THREAD

**Issue by agraebe** [stx-labs/stacks.js#956]
This sample code line is not correct:

```
// if you call this method multiple times in the same block, you need to increase the nonce manually
let nonce = getNonce(delegatorAddress, network);
```

`getNonce` needs to be resolve first, so an `await is needed:

```
let nonce = await getNonce(delegatorAddress, network);
```

**Comment by ahsan-javaid** [comment]
@agraebe 
This issue is fixed in [[Stacking] Review and update READMEs](https://github.com/blockstack/stacks.js/pull/1075) pull request which is merged.
Updated change can be seen [here](https://github.com/blockstack/stacks.js/tree/master/packages/stacking)
This issue is ready to close.

**Comment by agraebe** [comment]
great, thanks!
