### ISSUE TITLE
Getting an error `Assertion Failed` with the method `client.delegateStackStx` at "@stacks/network" package

### ISSUE THREAD

**Issue by FhilF** [stx-labs/stacks.js#967]
**Describe the bug**
I am trying to test delegating stacks stx.
But I am getting an error `Assertion Failed` running `client.delegateStackStx` and also `client..stackAggregationCommit` method

**What version of Blockstack.js are you using?**
I am using these verisons
```
"@stacks/network": "^1.2.2",
"@stacks/stacking": "^1.3.0",
"@stacks/transactions": "^1.3.0",
"bn.js": "^4.11.6",`
```

**To reproduce**
Created a keychain using this command:
`stacks make_keychain -t > delegatee.json`
`stacks make_keychain -t > delegator.json`

then replaced the variables:
```
const delegateeAddress = <delegatee.json > keyInfo >  address>
const delegateeBtcAddress = <delegatee.json > keyInfo >  btcAddress>
const delegateePrivateKey = <delegatee.json > keyInfo >  privateKey>

```
![dsdssaaaaa](https://user-images.githubusercontent.com/52390799/110576120-2411ea80-819b-11eb-801f-4aeff0d68bc4.png)

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
In the package `@stacks/stacking`

I found that there was a problem with `poxAddress` object in both methods with function when using the function `toBuffer`
I attached a screenshot of the error so it will be more clearer.

![dsdsa](https://user-images.githubusercontent.com/52390799/110574466-1c9d1200-8198-11eb-9741-e6ca76692425.png)

![dsdsds](https://user-images.githubusercontent.com/52390799/110574470-1e66d580-8198-11eb-87f5-3bf3c640bb7c.png)

I think this is the same problem as https://github.com/blockstack/stacks.js/pull/925.

**Desktop**
OS: Windows 10
Browser Google Chrome
Version Latest

Hope you can resolve this issue. Thank you!

**Comment by zone117x** [comment]
`BN.toBuffer()` strikes again!
https://github.com/blockstack/stacks.js/blob/a6fab4e5c3038cf4eaa7bd997b7d4c5104ca6858/packages/stacking/src/index.ts#L530

Needs updated to:

```ts
const hashModeBuffer = bufferCV(new BN(hashMode, 10).toArrayLike(Buffer)); 
```
