### ISSUE TITLE
"blockstack register" timed out, fee was moved, preorder can't be seen in blockstack but in the blockchain

### ISSUE THREAD

**Issue by Gitju** [stx-labs/stacks.js#97]
I used the `register` command 3 times. 

First registration seems to have worked.

Second time I got this:
`root@server:~/.blockstack# blockstack register <johndoe>.id
Registering <johndoe>.id will cost 0.00041 BTC. Continue? (y/n): y
{
    "error": "timed out"
}
{
    "error": "Error talking to server, try again."
}`

Third registration looked like that it worked.

3x 0.00041 BTC were moved from my balance. I can see 3 transactions in the blockchain. `blockstack info` however shows me just 2 preorders instead of 3. `blockstack names` is empty. 

My second registration seems to be lost. 

**Update 1**
As a quick fix someone can edit `~/.blockstack/local_state.json` and add the missing entries.

**Update 2**
After 12 hours time of waiting and a restart of blockstack with the help of `kill -9 <pid>` for the python processes, `blockstack balance` shows me 0.001665 BTC. I initially deposited 0.0041 BTC. The price of every of my registrations was displayed as 0.00041 BTC including fees.  The difference between my initial deposit and the actual balance is equal to ~ 5.93902439 registrations given those costs. In the bitcoin blockchain I can see 5 transactions. However, `blockstack names` gives me 1 entry, `blockstack info` or `blockstack status` gives me no pending preorder.  If I use `blockstack lookup` or `blockstack whois`  my yesterdays registrations beside the one in my   `blockstack names` are not registered.

**Update 3**
A new try to register one of my desired IDs.
1. `blockstack balance` shows 0.001665 BTC
2. `blockstack whois <johndoe>.id` and`blockstack lookup <johndoe>.id` shows it is not registered
3. `blockstack register <johndoe>.id` is shown to cost 0.00041 BTC, answering with yes results in
     `"error": "Couldn't broadcast transaction. You can try again."` 
     tried it 5-times and always the same response.

**Update 4**
Made a backup of `wallet.json`, `kill -9 <pid>` for blockstack, uninstalled blockstack, removed `~/.blockstack/`,  installed blockstack again, imported the backup of `wallet.json`, same results.

_System_
Server: GNU/Linux Debian 8.3
RAM: 4GB
Cores: 4

**Comment by doodlemania2** [comment]
I've got a similar problem ... on the third attempt I looked at my balance and it was in fact deducted from my wallet. When I tried to do it a fourth time, I get "error": "Address.... has pending transactions. Wait and try later." Couple days now, no dice.

**Comment by muneeb-ali** [comment]
@doodlemania2 and @Gitju we're a couple of days away from the next release of the CLI, I'd highly encourage you to try that out when it comes out instead. These issues are already fixed in the upcoming release and it's a major re-write. 

Also, please DM me in http://chat.blockstack.org and I can transfer some BTC to your CLI wallets for testing. We really appreciate the time (and money!) you're putting into this :-)

**Comment by Gitju** [comment]
@muneeb-ali okay great

**Comment by doodlemania2** [comment]
Cool! Very happy to test and restest. DM coming at you.

**Comment by Gitju** [comment]
Tried @jcnelson 's next release candidate from commit 33e98bf5c95eae56c99b6bae7a30a1e5296c580d

`root@server:~/.blockstack# blockstack balance
{
    "total_balance": 0.004665
}
`

`root@server:~/.blockstack# blockstack register <johndoe>.id
Enter wallet password: 
Unlocked wallet.
Registering <johndoe>.id will cost 0.00041 BTC. Continue? (y/n): y
{
    "error": "timed out"
}
{
    "error": "Error talking to server, try again."
}
`

`root@server:~/.blockstack# blockstack balance
{
    "total_balance": 0.004095
}
`

What follows is
1.  0.004665 BTC - 0.00041 BTC = 0.004255 BTC > 0.004095 BTC = 0.004665 BTC - 0.00057 BTC so the costs were higher than displayed 
2.  `root@server:~/.blockstack# blockstack names` says that nothing was registered and `pending_requests.json` shows that nothing is pending after the "timed out" error message
3. I can see a transaction of my payment address that is located in `wallet.json` directly in the blockchain worth 0.00057 BTC

**Comment by jcnelson** [comment]
Hi @Gitju, I know this is coming a lot later, but we just merged 0.14.0 to master, and it fixes a lot of these underlying problems (it's a ground-up re-write of the CLI's registration logic and has been tested a lot harder).

**Comment by jcnelson** [comment]
I'm going to close this issue due to inactivity.  If the problem still persists, please re-open in blockstack-core.  Thanks!
