### ISSUE TITLE
Stacking lib: Reject native segwit addresses

### ISSUE THREAD

**Issue by agraebe** [stx-labs/stacks.js#973]
**Describe the bug**
Native segwit addresses are not supported on the Stack blockchain. However, the Stacking library currently allows setting these addresses (starting with bc1). The library currently decodes this format into a different one and submits it to the stacking contract calls, resulting in unexpected reward addresses inside contract calls.

The main method in question is [`decodeBtcAddress`](https://github.com/blockstack/stacks.js/blob/48a72fba2eda7e5f0bc7dbd649f274f88d01bd1d/packages/stacking/src/utils.ts#L31).

**Expected behavior**
The library should reject native segwit addresses.

cc @yknl @jcnelson @cuevasm

**Comment by jcnelson** [comment]
The blockchain does not support native segwit addresses (and never has).  It only supports p2pkh and p2sh (including p2wpkh-p2sh and p2wsh-p2sh, not to be confused with native p2wpkh and native p2wsh).  Moreover, there is no way to convert a Bech32 address into a p2sh address that I'm aware of.

**Comment by hstove** [comment]
CC @kyranjamie to double check in the desktop wallet - although I believe I recall explicitly testing with bech32.

**Comment by jcnelson** [comment]
To be clear, if you put a bech32 address into the code here, it _will_ produce a well-formed p2sh address.  However, it won't be spendable.  That's the bug -- the code should be erroring out.

**Comment by kyranjamie** [comment]
Thanks @hstove, yeah the wallet handles this already

<details>
<summary>Desktop wallet screenshot</summary>

![image](https://user-images.githubusercontent.com/1618764/111596736-c77f8280-87cd-11eb-9989-4b1c3a2bc67d.png)

</details>
