### ISSUE TITLE
Update release checklist

### ISSUE THREAD

**Issue by zone117x** [stx-labs/stacks.js#976]
`release-checklist.md` is outdated, and the readme currently doesn't explain which lerna publishing flows are used when updating and releasing a new version.

@reedrosenbluth I think you figured out the correct workflow for this, would you mind adding it to the readme or updating the release-checklist?

**Comment by agraebe** [comment]
@reedrosenbluth would you be able to help?

**Comment by janniks** [comment]
Will remove in https://github.com/hirosystems/stacks.js/pull/1180 and rather codify when addressing  https://github.com/hirosystems/stacks.js/issues/1057
