### ISSUE TITLE
Pip Install Failure OSX 10.11.5

### ISSUE THREAD

**Issue by karim0028** [stx-labs/stacks.js#98]
im trying to install via pip i keep getting this error

**Comment by karim0028** [comment]
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;**file**='/private/var/folders/zk/c72rz9n54cqf61p4gj634nrr0000gn/T/pip-build-FSrGEf/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/zk/c72rz9n54cqf61p4gj634nrr0000gn/T/pip-nWRP1_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/zk/c72rz9n54cqf61p4gj634nrr0000gn/T/pip-build-FSrGEf/pycrypto/

Anybody know how to fix this?

**Comment by songproducer** [comment]
I'm also getting this with this immediately beforehand:

scrypt-1.1.6/lib/crypto/crypto_aesctr.c:38:10: fatal error: 'openssl/aes.h' file not found

**Comment by jcnelson** [comment]
Can you try the following?

`brew install openssl`

This should get you the development headers for OpenSSL.  Our new brew script (in `/pkg/brew`) should also give a way to install `blockstack` via `brew` instead of `pip` (and handle this for you).

**Comment by jcnelson** [comment]
You'll also need the latest version of pip (9.0.1).  Closing this issue here.  Please re-open in blockstack-core if problem persists.
