### ISSUE TITLE
cvToValue throws exception for uint with more than 53 bits

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#983]
**Describe the bug**
`cvToJSON` throws expection for `uint` or `int` with more than 53 bits. `cvToJSON` uses `cvToValue` 

**What version of Blockstack.js are you using?**
transactions 1.3.3

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
no

**To Reproduce**
```
  it("should convert uintCV to hex", async () => {
    const value = cvToJSON(uintCV("1000000000000000"));
    expect(JSON.stringify(value)).equal('{"type":"uint","value":10000000000000000}');
  });
``` 

**Expected behavior**
Not clear how to handle this. For small numbers it makes sense to just return the number, for bigger numbers we need BN values.

**Console log**

```
 should convert uintCV to hex:
     Error: Number can only safely store up to 53 bits
      at assert (node_modules/bn.js/lib/bn.js:6:21)
      at BN.toNumber (node_modules/bn.js/lib/bn.js:519:7)
      at cvToValue (node_modules/@stacks/transactions/src/clarity/clarityValue.ts:108:24)
      at Object.cvToJSON (node_modules/@stacks/transactions/src/clarity/clarityValue.ts:144:51)
      at Context.<anonymous> (test/unit/pool-tool-utils.spec.ts:60:19)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by zone117x** [comment]
Native BigInt would be ideal, but it doesn't support JSON serialization out of the box. String quoted integers seem like the best middle ground behind readability and usability/portability imo.

**Comment by zone117x** [comment]
@friedger what are your thoughts? These could also be encoded a hex string.
