### ISSUE TITLE
fix stx balance help message

### ISSUE THREAD

**Issue by gavinisagi** [stx-labs/stacks.js#987]
**Describe the bug**
stacks-cli ```stx balance <ADDRESS>``` doesn't support bitcoin address query

**To Reproduce**
```stx balance 16pm276FpJYpm7Dv3GEaRqTVvGPTdceoY4```
Will see

``` FetchError: invalid json response body at https://stacks-node-api.stacks.co/v2/accounts/16pm276FpJYpm7Dv3GEaRqTVvGPTdceoY4?proof=0 reason: Unexpected token / in JSON at position 0
    at /root/.nvm/versions/node/v14.15.0/lib/node_modules/@stacks/cli/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
invalid json response body at https://stacks-node-api.stacks.co/v2/accounts/16pm276FpJYpm7Dv3GEaRqTVvGPTdceoY4?proof=0 reason: Unexpected token / in JSON at position 0
```

It seems the https://stacks-node-api.stacks.co/v2/accounts doesn't support bitcoin address.

![截屏2021-03-26 下午3 44 06](https://user-images.githubusercontent.com/37820916/112598861-21c1b880-8e4a-11eb-96eb-43897686345f.png)

**Comment by friedger** [comment]
Bitcoin address does not have a stx balance. What result would you expect?

**Comment by gavinisagi** [comment]
> Bitcoin address does not have a stx balance. What result would you expect?

```
Command: balance
Usage:
  balance ADDRESS
  balance --address ADDRESS

  Query the balance of an account. Returns the balances of each kind of token
  that the account owns. The balances will be in the *smallest possible
  units* of the token (i.e. satoshis for BTC, microStacks for Stacks, etc.).

  Example:

    $ stx balance 16pm276FpJYpm7Dv3GEaRqTVvGPTdceoY4
    {
      "BTC": "123456"
      "STACKS": "123456"
    }
    $ stx balance SPZY1V53Z4TVRHHW9Z7SFG8CZNRAG7BD8WJ6SXD0
    {
      "BTC": "123456"
      "STACKS": "123456"
    }

Use "help" to list all commands.
```

Maybe modify the description.

**Comment by friedger** [comment]
stacks.js and `StacksNetwork` does not have a definition for a bitcoin node url. I'd say this is out of scope.

**Comment by agraebe** [comment]
there seems to be a docs issue here that needs to be resolved
