### ISSUE TITLE
Short tutorial on how to register username/profile for OpenBazaar

### ISSUE THREAD

**Issue by muneeb-ali** [stx-labs/stacks.js#99]

**Comment by muneeb-ali** [comment]
For linking OpenBazaar to Blockstack ID you need the following steps:

1) Download the Blockstack CLI. Instruction are at http://blockstack.org/docs

2) Register the name you're trying to register 

3) After the name appears in the list of names you own, update the profile data. You can check which names you own in the CLI via: 

> $ blockstack names

For updating the profile data, OB needs the GUID data in the following format:

```
"account": [
      {
        "service": "openbazaar", 
        "@type": "Account", 
        "identifier": "5dec6dfa447d64456e8632097c98b593c509bd6e"
      }
    ], 
```

The above data is for ob1.id and can be seen at https://onename.com/ob1.json

We will post more instructions on how to update your profile in the new CLI (which is coming out soon). Along with link to some tool that can help you easily generate a valid JSON profile.

**Comment by Rocks333** [comment]
Please let us know when the CLI is updated so we can finally do this.
Thanks

**Comment by muneeb-ali** [comment]
We're pushing out the [release-candidate](https://github.com/blockstack/blockstack-cli/tree/release-candidate) to live this week.

You can follow the progress of the new CLI release [here](https://github.com/blockstack/blockstack-cli/issues/105).

**Comment by jcnelson** [comment]
Added account-linking [here](https://github.com/blockstack/blockstack-cli/blob/master/docs/openbazaar.md).  Will organize this into an start-to-finish walkthrough.

**Comment by jcnelson** [comment]
This information is now available on our zendesk.
